### ISSUE TITLE
[Feature][ConfigUI/BE] Combine Data Entities and Transformation into Scope Config

### ISSUE THREAD

**Issue by yumengwang03** [apache/devlake#5159]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This feature is both a user need and an internal design request. Currently one Data Connection can only have one set of configuration for Data Entities, which is not flexible for certain use cases. Users may need different Data Entities for different Data Scope in a Data Connection. In addition, because we will move the management of Data Scope to the Data Connection page (https://github.com/apache/incubator-devlake/issues/4760), the configuration of Data Entities also need to be moved.

Thus, Data Entities and Transformation will be combined together for a new concept called Scope Config.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@CamilleTeruel @keon94 Please note that we are working on this issue, the `azure devops` also need to be updated.

**Comment by CamilleTeruel** [comment]
> @CamilleTeruel @keon94 Please note that we are working on this issue, the `azure devops` also need to be updated.

Alright, ping me when the go-side PR is open so that I mirror the change on pydevlake side.
