### ISSUE TITLE
[Question][docker-compose] ERROR: Service 'devlake' failed to build: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument

### ISSUE THREAD

**Issue by hollmanenciso** [apache/devlake#5166]
## Question
Docker-compose up -d on version 0.17.0-beta4 and 0.16 are having an issue, this is related to devlake or anything else?

## Additional context
$ docker-compose up -d
WARNING: The HTTPS_PROXY variable is not set. Defaulting to a blank string.
WARNING: The GOPROXY variable is not set. Defaulting to a blank string.
Building devlake
Step 1/54 : FROM --platform=linux/amd64 debian:bullseye as debian-amd64
 ---> 34b4fa67dc04
Step 2/54 : RUN apt-get update
 ---> Using cache
 ---> a90816749026
Step 3/54 : RUN apt-get install -y libssh2-1-dev libssl-dev zlib1g-dev
 ---> Using cache
 ---> 0a7c21078f2e
Step 4/54 : FROM --platform=linux/arm64 debian:bullseye as debian-arm64
 ---> 34b4fa67dc04
Step 5/54 : RUN apt-get update
 ---> Using cache
 ---> a90816749026
Step 6/54 : RUN apt-get install -y libssh2-1-dev libssl-dev zlib1g-dev
 ---> Using cache
 ---> 0a7c21078f2e
Step 7/54 : FROM --platform=$BUILDPLATFORM golang:1.19-bullseye as builder
**ERROR: Service 'devlake' failed to build: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument**

**Comment by klesh** [comment]
@hollmanenciso Hi, seems like you were using the `docker-compose.yml` file from the repo, it is for `development` purpose, and shouldn't be used on `production`
Please download `docker-compose.yml` from the release page instead
![image](https://github.com/apache/incubator-devlake/assets/61080/4da6df4a-7642-47a0-8d74-fb4bdf55cf59)

**Comment by hollmanenciso** [comment]
thank you @klesh
