### ISSUE TITLE
[Bug][DORA] environment is empty when production regex is left empty

### ISSUE THREAD

**Issue by hezyin** [apache/devlake#5169]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Version: v0.17.0-beta3**

Test repo: https://github.com/hezyin/dora-test-repo1

## First Run

In my first run, I only set the deployment regex and leave the production regex empty. My cicd_tasks are correctly marked as deployments, but all of their environments are empty

<img width="914" alt="Screen Shot 2023-05-11 at 10 41 40 PM" src="https://github.com/apache/incubator-devlake/assets/2908155/8ec30bda-6692-4e76-a832-ae0a90a7f0a1">
<img width="2148" alt="Screen Shot 2023-05-11 at 10 40 57 PM" src="https://github.com/apache/incubator-devlake/assets/2908155/abb36637-98ec-4c59-b917-e20a55f070f9">

## Second Run

So in my 2nd run, I set my production regex to the same value as the deployment regex, this time it works.

<img width="933" alt="Screen Shot 2023-05-11 at 10 41 49 PM" src="https://github.com/apache/incubator-devlake/assets/2908155/d7fd2f88-8241-45a7-8786-7c6914bf28e6">
<img width="2143" alt="Screen Shot 2023-05-11 at 10 43 55 PM" src="https://github.com/apache/incubator-devlake/assets/2908155/41213eab-f5db-4e7a-9906-6f44c7fd2655">

### What do you expect to happen

I'd expect both runs to result in the same data. 

### How to reproduce

See above.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
I see, not sure if it is a bug. @Startrekzky what do you think? should they be marked as `PRODUCTION` when `production regex` is omitted?

**Comment by Startrekzky** [comment]
> I see, not sure if it is a bug. @Startrekzky what do you think? should they be marked as `PRODUCTION` when `production regex` is omitted?

It should be marked as `PRODUCTION` when `production regex` is omitted according to the original design.
