### ISSUE TITLE
[Bug][PluginGenerator] Generator creates defect code

### ISSUE THREAD

**Issue by tim-goto** [apache/devlake#5176]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Run `go run generator/main.go create-plugin test` and then `go run plugins/test/test.go`, some imports are wrong:

```
plugins/test/impl/impl.go:22:2: no required module provides package github.com/apache/incubator-devlake/errors; to add it:
        go get github.com/apache/incubator-devlake/errors
plugins/test/impl/impl.go:23:2: no required module provides package github.com/apache/incubator-devlake/plugins/core; to add it:
        go get github.com/apache/incubator-devlake/plugins/core
plugins/test/test.go:22:2: no required module provides package github.com/apache/incubator-devlake/runner; to add it:
        go get github.com/apache/incubator-devlake/runner
```
It seems like the module names have changed upstream.

### What do you expect to happen

The automatically generated module runs without errors, printing the output given in the developer manual.

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Yup, the plugin generator is broken due to a recent refactor.
I saw you ticked the "Submit a PR" option, would you like to work on it?

**Comment by tim-goto** [comment]
It depends on how difficult/time consuming it would be. I prefer working on the bitbucket server plugin because that is what I actually need but if this helps me get there faster, I could also to that

**Comment by klesh** [comment]
@tim-goto I see, I think we should focus on the Bitbucket Server support at the time being, it doesn't depend on this feature I believe.
