### ISSUE TITLE
[Feature][GitHub plugin] Support transformations from GitHub Environments

### ISSUE THREAD

**Issue by Feggah** [apache/devlake#5178]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I want to classify Deployments and Production Deployments based on the GitHub Environment name that the Job is referring to, instead of only being able to use the Job name

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
What does ` GitHub Environment name` refer to ?

**Comment by Feggah** [comment]
> What does  GitHub Environment name refer to ?

Refer to the name that are highlighed in these printscreens below:

![image](https://github.com/apache/incubator-devlake/assets/11353912/dc985d90-00eb-4733-b475-84b8c11bdc13)

![image](https://github.com/apache/incubator-devlake/assets/11353912/4b63df10-1ad2-40c6-9844-3c8941b6e8f6)

Below is the documentation about the `environment` field in the Actions definition ([ref](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment))
![image](https://github.com/apache/incubator-devlake/assets/11353912/f79bec6a-ab01-4075-8f74-de2b165422d7)

**Comment by klesh** [comment]
Interesting, never notice this before.
@Startrekzky is following up

**Comment by Startrekzky** [comment]
> Interesting, never notice this before. @Startrekzky is following up

It's basically the same as the environment setting in a BitBucket pipeline step. We can reuse this logic if the environment keys and values are collected.

**Comment by Startrekzky** [comment]
This is a valid feature, we need to do it.

**Comment by Startrekzky** [comment]
Hi @Feggah , we are working on collecting GitHub deployments in #5949 . This will also collect the environment of GitHub deployments. 

Although I've read GitHub's doc of how deployments are configured, since we're not using GitHub environments, I'm curious about how you configure them in real life. Do you mind sharing an example of your GitHub workflow or job to conduct deployments? Thank you in advance.
![image](https://github.com/apache/incubator-devlake/assets/14050754/343665f1-8b2d-45d2-9c81-4d1fed4c650f)

**Comment by Feggah** [comment]
Can't help much any longer by giving real-life examples @Startrekzky, I'm not in the same company that I was before.

But our use case was simple: we used environments to apply specific policies to it. For example, for production environments, we had a policy that two people had to approve before the deployment job was executed.

For DevLake specifically, using GitHub Environments would be more reliable than the job name, because we had control over the GitHub Environments and it had a pattern across the company, but for pipeline/job names, each repository had its own different pattern.

**Comment by Startrekzky** [comment]
Hi @Feggah , DevLake is going to support this in the upcoming v0.20. Please see the pic below. Feel free to reopen the issue if it can not meet your needs.
![image](https://github.com/apache/incubator-devlake/assets/14050754/0d8616b6-a3d9-4513-b325-7b6de574a488)
