### ISSUE TITLE
Project Page: Incoming webhook tab: Why is "Incoming Webhooks" tab is disabled?

### ISSUE THREAD

**Issue by surajsud-ril** [apache/devlake#5184]
## Question

I am not able to map project with webhook that I have created. Webhook tab on project page is disabled. Why? 

## Screenshots
<img width="1728" alt="Screenshot 2023-05-15 at 1 28 04 PM" src="https://github.com/apache/incubator-devlake/assets/133637636/37e021b1-62c9-4226-8063-ebfbd0215da1">

## Additional context
I have created the webhook and am able to push data via REST APIs as well. But same is not visible on DORA dashboard because am not able to map the webhook with project as all the documentation seems to suggest. What might be the reason?

**Comment by klesh** [comment]
@surajsud-ril  Hi, you have to create a blueprint first

**Comment by surajsud-ril** [comment]
Actually I don't have any external source (connection) which I can use to create blueprint and without that UI doesn't allow me to connect. I am planning to use webhooks only to push data.

Is there any way?

**Comment by surajsud-ril** [comment]
Got it, Thanks for your help. Have used my GitHub account for the same. But couldn't work out why do I need to create blueprint when webhooks are not mangeable via blueprint. Whats the dependency?

**Comment by klesh** [comment]
If you want to create a standalone `webhook connection`, you may do so on the **Connection** page
If you want to add a `webhook connection` into a project, a blueprint is required to store the relationship between the project and webhook connections.

@Startrekzky @yumengwang03 I think we should create the blueprint automatically to avoid such confusion.

**Comment by Startrekzky** [comment]
@klesh I agree. Actually @yumengwang03 thought of this solution in the first place.
