### ISSUE TITLE
[Bug][jira] collect jira fail in first time.

### ISSUE THREAD

**Issue by likyh** [apache/devlake#5185]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/incubator-devlake/assets/3294100/32fcbc95-f3e9-4056-bbaf-c2e2117ca085)
It seems raise a error when run jira plugin in the first time.

### What do you expect to happen

run success

### How to reproduce

1. deploy delake v0.18
2. create jira connection
3. run jira plugin.

### Version

main

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by likyh** [comment]
There is a name typo. Actually, error trigger in ExtractIssueCommentsMeta. But I have set ExtractIssueCommentsMeta.EnabledByDefault=False. Why it run ?

**Comment by Startrekzky** [comment]
Duplicated with #5223
