### ISSUE TITLE
[Bug][Azure DevOps] Unexpected end of JSON input

### ISSUE THREAD

**Issue by nd-siouxfan** [apache/devlake#5186]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Attempting to retrieve list of repos from AzDo

time="2023-05-15 13:49:30" level=info msg="DEBUG: Starting new HTTPS connection (1): dev.azure.com:443"
time="2023-05-15 13:49:31" level=info msg="DEBUG: https://dev.azure.com:443 "GET /XXXXXXX/xxxxx-platform/_apis/git/repositories?api-version=7.0 HTTP/1.1" 200 None"
time="2023-05-15 13:49:32" level=error msg="HTTP 500 error
	caused by: unexpected end of JSON input
	Wraps: (2) unexpected end of JSON input
	Error types: (1) *hintdetail.withDetail (2) *json.SyntaxError"

Running on V17 Beta 5

### What do you expect to happen

Retrieve list of repos

### How to reproduce

Select projects from Repo

### Anything else

V17 Beta 5

### Version

v0.16.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CamilleTeruel** [comment]
I just tested on  v0.17.0-beta5 and I can get the list of projects and repositories with my PAT.

2023-05-15 19:02:08]  INFO DEBUG: Starting new HTTPS connection (1): dev.azure.com:443
[2023-05-15 19:02:09]  INFO DEBUG: https://dev.azure.com:443 "GET /merico-dev/DevLake/_apis/git/repositories?api-version=7.0 HTTP/1.1" 200 None
[GIN] 2023/05/15 - 19:02:09 | 200 |  1.318242459s |       127.0.0.1 | GET      "/plugins/azuredevops/connections/1/remote-scopes?groupId=merico-dev%2FDevLake"

It's hard to know what is causing your issue without more information. Can you check if the body of "/XXXXXXX/xxxxx-platform/_apis/git/repositories?api-version=7.0" response is valid JSON?
