### ISSUE TITLE
[Bug][GitHub] 401 unauthorized in the middle of a pipeline

### ISSUE THREAD

**Issue by sais8** [apache/devlake#5222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have updated devlake to 0.17.0-beat4 recently and trying to run a pipeline to retrieve issues of type `bug`, '`feature` and few `component types`. Pipeline runs just fine for first few mins and then starts throwing 401 with below error
`time="2023-05-17 14:39:06" level=info msg=" [pipeline service] [pipeline #9] [task #53] [collectApiEvents] finished records: 286"
time="2023-05-17 14:39:10" level=info msg=" [pipeline service] [pipeline #9] [task #53] [collectApiEvents] finished records: 291"
time="2023-05-17 14:39:14" level=info msg=" [pipeline service] [pipeline #9] [task #53] [collectApiEvents] finished records: 296"
[GIN] 2023/05/17 - 14:39:16 | 200 |       1.501µs |       10.1.0.33 | GET      "/ping"
time="2023-05-17 14:39:16" level=warning msg=" [pipeline service] [pipeline #9] [task #53] [api async client] retry #0 calling repos/sed/monorepo/issues/events
        caused by: error running afterRequest for https://api.github.com/repos/sed/monorepo/issues/events?page=304&per_page=100 (401)
        Wraps: (2) authentication failed, please check your AccessToken (401)
        Error types: (1) *hintdetail.withDetail (2) *errors.errorString"
time="2023-05-17 14:39:17" level=info msg=" [pipeline service] [pipeline #9] [task #53] [collectApiEvents] finished records: 300"
time="2023-05-17 14:39:18" level=warning msg=" [pipeline service] [pipeline #9] [task #53] [api async client] retry #0 calling repos/sed/monorepo/issues/events
        caused by: error running afterRequest for https://api.github.com/repos/sed/monorepo/issues/events?page=310&per_page=100 (401)
        Wraps: (2) authentication failed, please check your AccessToken (401)`

The token was working just fine for v0.16.0 release and I believe it is working for 0.17.0-beat4 release as well but for some reason it is throwing 401 in between the pipeline. I can provide more logs for multiple runs if required, please let me know. 

### What do you expect to happen

Expect to see the pipeline run successfully and collect all the issues with the transformation provided.

### How to reproduce

- Create a GitHub connection 
- Add Datascope for the repository
- add transformations and run the pipeline for the time range 

### Anything else

- this occurs every time I run the pipeline

### Version

v0.17.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
Is this happnening when hitting `repos/sed/monorepo/issues/events` each time? Or is it at random stages?

**Comment by klesh** [comment]
Did you set an expiration date when you generated the token on GitHub?

**Comment by sais8** [comment]
> Is this happnening when hitting `repos/sed/monorepo/issues/events` each time? Or is it at random stages?

It is happening every time when I run a pipeline and in stage2 which is `GitHubGraphql`

**Comment by sais8** [comment]
@abeizn @likyh thank you for the quick fix. Which release is this expected to be included in? v0.17.0 stable or any of the beta versions?

**Comment by abeizn** [comment]
@sais8  v0.17.0-beta7
