### ISSUE TITLE
[Bug][Jira] An error occurred during extracting changelog

### ISSUE THREAD

**Issue by mindlesscloud** [apache/devlake#5223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I try to run a blueprint, an error occurred during extracting the changelogs 

![image](https://github.com/apache/incubator-devlake/assets/8455907/5c2f9851-843c-4797-adf1-8c728045a0bc)

### What do you expect to happen

It should go smoothly and no errors like this. 
The bug was caused by the `issue commits collector` being disabled by default. 

### How to reproduce

- create a Jira blueprint
- run the blueprint

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@mindlesscloud Please check if it exists in v0.17, and cherrypick the PR if so.
