### ISSUE TITLE
[Question][DevLake] Configured projects were not kept after upgrading to new version

### ISSUE THREAD

**Issue by 321zxn** [apache/devlake#5226]
## Question
The projects which configured in DevLake were not kept after upgrading to new version.

## Screenshots
1. upgrade DevLake version from V0.16.0-beta11 to V0.17.0-beta4
2. Follow the doc of [upgrade-to-a-newer-version](https://devlake.apache.org/docs/GettingStarted/DockerComposeSetup/#upgrade-to-a-newer-version)
version info and project info, please refer to screenshot:
![image](https://github.com/apache/incubator-devlake/assets/133944526/4d88edef-7437-425d-8009-8f223a3ef869)
![image](https://github.com/apache/incubator-devlake/assets/133944526/3fc44654-bb67-49da-a5f4-12af39c76e41)
@mintsweet @klesh @WillemJiang 

## Additional context
Looking forward to your reply, thanks.

**Comment by mappjzc** [comment]
Did your run the `/proceed-db-migration` ?
Can your show your databases about the projects table ?

**Comment by mappjzc** [comment]
@321zxn

**Comment by 321zxn** [comment]
> @321zxn
> 
> 1. Did your run the `/proceed-db-migration` ?
> 2. Could you please share the content of your `projects` table in the database?

1. run /proceed-db-migration in which step? Is there any documentations?
2. My projects table lists as below screenshot
![image](https://github.com/apache/incubator-devlake/assets/133944526/ff285d83-83ad-44c2-bc3f-f627a5466979)

**Comment by klesh** [comment]
Did you run `docker-compose up -d` command after modifying the `image tags`?
Try `docker-compose ps`  or `docker ps` to see if the `devlake` container is using the correct image.

**Comment by 321zxn** [comment]
Yes, I  run **docker-compose up -d** command after modifying the **image tags**
I have tried **docker-compose ps** and I think the correct image is used, refer to screenshot, thanks.
![image](https://github.com/apache/incubator-devlake/assets/133944526/223fc430-329d-4d70-b698-1bdd16c3184a)

**Comment by mappjzc** [comment]
> > @321zxn
> > 
> > 1. Did your run the `/proceed-db-migration` ?
> > 2. Could you please share the content of your `projects` table in the database?
> 
> 1. run /proceed-db-migration in which step? Is there any documentations?
> 2. My projects table lists as below screenshot
>    ![image](https://user-images.githubusercontent.com/133944526/239407788-ff285d83-83ad-44c2-bc3f-f627a5466979.png)

You can run it by visit the url `[your-devlake-config-ui]/api/proceed-db-migration`

**Comment by 321zxn** [comment]
> 

Thanks.
Below message is displayed when I visit the url **[your-devlake-config-ui]/api/proceed-db-migration**.
{"success":true,"message":"success","causes":null}

**Comment by mappjzc** [comment]
@mintsweet  looks like the db-migration didn't show on config-ui?

**Comment by 321zxn** [comment]
Do you have any ideas for my issue?
I upgrade DevLake to v0.17.0-beta5 today, the same issue exist. Maybe some key steps missing on my side?

Here I list my reproduced steps as below, please help to check:
1. Run **docker-compose down** to stop services;
2. copy the docker folder of old version(V0.16.0-beta11), rename to new version(V0.17.0-beta5), which inclue **.env** and **docker-compose.yml**
![image](https://github.com/apache/incubator-devlake/assets/133944526/816a89b3-da05-446c-b205-19c49d122d92)
3. Open **docker-compose.yml**, modify the image tags of "grafana", "devlake" and "config-ui" to **v0.17.0-beta5**.
![image](https://github.com/apache/incubator-devlake/assets/133944526/4fbc148d-4d39-4a7a-8f82-c6e076ec2254)
4. Under folder of new version(V0.17.0-beta5), run **docker-compose up -d** to start DevLake services

**Comment by klesh** [comment]
Oh, different folders mean different deployments by the design of the docker compose......
you should change only the image tags instead of copying the folder.

**Comment by 321zxn** [comment]
> Oh, different folders mean different deployments by the design of the docker compose...... you should change only the image tags instead of copying the folder.

It's OK now after changing the image tags directly instead of copying one.

Now I have a new confusion, isn't it should be same result when copy the folder? because I have no changes for the copy folder except changing the image tags.
I make a copy in order to prevent the damage for the original environment.

**Comment by klesh** [comment]
> > Oh, different folders mean different deployments by the design of the docker compose...... you should change only the image tags instead of copying the folder.
> 
> It's OK now after changing the image tags directly instead of copying one.
> 
> Now I have a new confusion, isn't it should be same result when copy the folder? because I have no changes for the copy folder except changing the image tags. I make a copy in order to prevent the damage for the original environment.

I'm confused too... It makes perfect sense to me that **projects that were created in one environment NOT showing in another one**, which means they are NOT sharing volumes so damage between different environments is impossible.

Anyway, it is out of the scope of this project, please check docker-compose documentation for detail. https://docs.docker.com/compose/features-uses/#have-multiple-isolated-environments-on-a-single-host

**Comment by 321zxn** [comment]
Many thanks for your kindly reply.
