### ISSUE TITLE
[Bug][PagerDuty] table board_issues is not being populated

### ISSUE THREAD

**Issue by Feggah** [apache/devlake#5233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I configured GitHub DataSource to collect Deployments data and PagerDuty to collect Incidents. My use case is trying to collect DORA metrics.

I selected all GitHub Repositories and PagerDuty Services that I wanted. After the Pipeline was successful, I opened the DORA dashboard to see if it worked.

![image](https://github.com/apache/incubator-devlake/assets/11353912/7455215e-4df8-4c50-b325-b3a8f3b77090)
As you can see above, only Deployment data was successfully collected, and we can see data for DF and LTFC, but the CFR and MTTR are empty.

I thought the collection of PagerDuty Incidents had failed, but by looking at the data in the MySQL database I can see that the table `issues` is populated:
![image](https://github.com/apache/incubator-devlake/assets/11353912/8ee0d0ca-4428-447c-af7d-1f41b4a3ef12)

So I checked how the MTTR query was made, and the tables `issues`, `board_issues`, `boards` and `project_mapping` are used:
![image](https://github.com/apache/incubator-devlake/assets/11353912/720ea43e-9dab-4425-889a-795187169c28)

All tables except `board_issues` have data:
![image](https://github.com/apache/incubator-devlake/assets/11353912/e5656ebc-8b98-4578-98f6-109a38225bc2)

So my hypothesis is that the PagerDuty plugin is not populating correctly the `board_issues` table, thus causing the failure to JOIN tables and extract the values for Incidents data.

### What do you expect to happen

See Incidents data in the DORA dashboard

### How to reproduce

Use GitHub plugin to collect Deployments and PagerDuty to collect Incidents.

The MTTR and CFR isn't going to be populated

### Version

f3f6e9be22cc9eee450ab07d0314c2e3edb95d47

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @Feggah , thanks for reporting. We also found this bug and @keon94 was working on it.
