### ISSUE TITLE
[Feature][Plugin] Snyk Connection

### ISSUE THREAD

**Issue by BrookeKatalon** [apache/devlake#5246]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

[Snyk](www.snyk.io)   is  part of our CICD pipeline, providing security scanning of source code and containers ( Dockerfiles & container images .) 

We'd like to see a plugin to make Synk a connector source to pull in metrics related to security ( CVEs, risk, etc. ) 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for your suggestion. @hezyin @Startrekzky

**Comment by Startrekzky** [comment]
Collecting votes
