### ISSUE TITLE
[Feature][Plugin] AWS CodePipelines Connector ( CodeBuild/CodeDeploy )

### ISSUE THREAD

**Issue by BrookeKatalon** [apache/devlake#5248]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

We'd like to see a plugin to pull build & deploy metrics from AWS CodeBuild/CodeDeploy/CodePipelines, similar to the Azure Devops, Jenkins, Github, Bamboo, etc. plugins. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for the proposal. @hezyin @Startrekzky

**Comment by Startrekzky** [comment]
Collecting votes

**Comment by chandrapratapsingh007** [comment]
Very much needed. I am looking for the same integration.

**Comment by zhoulixiandevlake** [comment]
Our company's agile development project based on AWS cloud-native applications is growing, and we are considering importing DevLake as an efficiency and quality analysis platform for our agile development project. We hope that DevLake can also support AWS data sources.
