### ISSUE TITLE
[Bug][AzureDevops] Missing required value for field merge_commit_sha

### ISSUE THREAD

**Issue by arheys** [apache/devlake#5252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Failed pipeline task: Azure DevOps
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     raise JsonPointerException("member '%!!(MISSING)s(MISSING)' not found in %!!(MISSING)s(MISSING)" %!!(MISSING)((MISSING)part, doc))"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests] jsonpointer.JsonPointerException: member 'lastMergeCommit' not found in {'repository': {'id': 'id', 'name': 'test', 'url': 'url', 'project': {'id': 'id', 'name': 'test', 'state': 'unchanged', 'visibility': 'unchanged', 'lastUpdateTime': '0001-01-01T00:00:00'}}, 'pullRequestId': 111, 'codeReviewId': 111, 'status': 'abandoned', 'createdBy': {'displayName': 'user', 'url': 'url', '_links': {'avatar': {'href': 'url'}}, 'id': 'id', 'uniqueName': 'email', 'imageUrl': 'ur;', 'descriptor': 'aad.'}, 'creationDate': '2023-05-08T10:56:17.630545Z', 'closedDate': '2023-05-21T09:21:11.6762237Z', 'title': 'Update pr tests', 'sourceRefName': 'refs/heads/pr-test', 'targetRefName': 'refs/heads/main', 'isDraft': False, 'mergeId': 'id', 'lastMergeSourceCommit': {'commitId': 'id', 'url': 'url'}, 'lastMergeTargetCommit': {'commitId': 'id', 'url': 'url'}, 'reviewers': [{'reviewerUrl': 'url', 'vote': -10, 'hasDeclined': False, 'isFlagged': False, 'displayName': 'user', 'url': 'url', '_links': {'avatar': {'href': 'url'}}, 'id': 'id', 'uniqueName': 'email', 'imageUrl': 'url'}, {'reviewerUrl': 'url', 'vote': 0, 'hasDeclined': False, 'isRequired': True, 'isFlagged': False, 'displayName': 'Team', 'url': 'url', '_links': {'avatar': {'href': 'url'}}, 'id': 'id', 'uniqueName': 'Team', 'imageUrl': 'url', 'isContainer': True}], 'url': 'url', 'supportsIterations': True}"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests] "
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests] During handling of the above exception, another exception occurred:"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests] "
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests] Traceback (most recent call last):"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/plugins/azuredevops/azuredevops/main.py", line 132, in <module>"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     AzureDevOpsPlugin.start()"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/plugin.py", line 248, in start"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     fire.Fire(PluginCommands(plugin))"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     component_trace = _Fire(component, args, parsed_flag_args, context, name)"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     component, remaining_args = _CallAndUpdateTrace("
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     component = fn(*varargs, **kwargs)"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/ipc.py", line 55, in wrapper"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     for each in ret:"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/ipc.py", line 74, in extract"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     yield from self._plugin.extract(self._mk_context(ctx), stream)"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/plugin.py", line 100, in extract"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     yield from self.get_stream(stream).extractor.run(ctx)"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/subtasks.py", line 82, in run"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     raise e"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/subtasks.py", line 62, in run"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     self.process(data, session, ctx)"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/subtasks.py", line 187, in process"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     tool_model = self.stream.extract(json.loads(raw.data))"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/stream.py", line 90, in extract"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     return autoextract(raw_data, self.tool_model)"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]   File "/app/python/pydevlake/pydevlake/extractor.py", line 53, in autoextract"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests]     raise ValueError(f"Missing required value for field {field.name} at {pointer}")"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] [extractAzuredevopsGitpullrequests] ValueError: Missing required value for field merge_commit_sha at /lastMergeCommit/commitId"
time="2023-05-21 09:35:33" level=error msg=" [pipeline service] [pipeline #14] [task #211] subtask extractAzuredevopsGitpullrequests ended unexpectedly
	Wraps: (2) remote error response:
	  | ERROR: ValueError: Missing required value for field merge_commit_sha at /lastMergeCommit/commitId
	  | Traceback (most recent call last):
	  |   File "/root/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/jsonpointer.py", line 288, in walk
	  |     return doc[part]
	  | KeyError: 'lastMergeCommit'

### What do you expect to happen

Run pipeline without errors.

### How to reproduce

- Create DevLake project, check Enable DORA metrics
- Setup AzureDevops connection
- Transformation use default.
- Run pipeline.

### Version

v0.17.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CamilleTeruel** [comment]
Duplicate of #5108, fix in v0.17.0-beta6
