### ISSUE TITLE
[Feature][BE] When a user removes some data entities, the associated data need to be excluded from metrics calculation

### ISSUE THREAD

**Issue by yumengwang03** [apache/devlake#5263]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a user, if I remove some data entities while editing the Data Config, I would expect that the historical data associated with the removed data entities will not be calculated into the metrics. 

For instance, I have selected Source Code Management, Code Review and Issue Tracking for my-org/my-repo and its data have been collected for several times. Now I want to remove the Code Review entity.

This is probably not a frequent use case, but is important for ensuring the accuracy of metrics.

<img width="850" alt="Screen Shot 2023-05-23 at 4 06 21 PM" src="https://github.com/apache/incubator-devlake/assets/9535430/baa5a03b-3383-4b50-bd6e-38718fa655c6">

### Description

Based on the discussion with @Startrekzky and @klesh, we want to exclude the data of the removed Data Entities from the further calculation of the metrics, but not deleting them. The action of deleting historical data will still remain in one place at the Data Scope level.

However, the relationship between domains (aka Data Entities in Config UI) and the the actual data entities that are used to calculate DORA is not strictly one-to-one. This makes it difficult to identify which data should be excluded from calculating DORA. Thus, we want to make the relationship more straightforward as the following:

repos - Git/Code Hosting (we will combine Source Code Management and Code Review and give it a new name in Config UI)
board - Issue Tracking
cicd_scopes - CI/CD

And when a user removes a domain/Data Entities, the corresponding data entities will be removed from the calculation of DORA.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Tracked in #5920. I need to rethink about the solutions. Editing the data entities in the `scope config` can be tricky.
