### ISSUE TITLE
[Bug][Azure DevOps] subtask extractAzuredevopsGitpullrequests ended unexpectedly

### ISSUE THREAD

**Issue by klemen-df** [apache/devlake#5275]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

At first pipeline run I received an error 'Task failed'

`subtask extractAzuredevopsGitpullrequests ended unexpectedly Wraps: (2) remote error response: | ERROR: DataError (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush bluck if this flush is occuring prematurely) | (MySQLdb.DataError) (1406, "Data too long for column 'description' at row 1) | [SQL: INSERT INTO _tool_azuredevops_gitpullrequests (...)]`

### What do you expect to happen

The pipeline runs without an error.

### How to reproduce

After configure the datasource, define the first blue print and run the pipeline.

### Anything else

Every run.

### Version

v0.17.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CamilleTeruel** [comment]
This is already fixed by #5191 which has been cherry-picked to v0.17.0-beta6.
However this fix works only together with #5081 which is missing v0.17.0-beta6.

**Comment by andremattosferraz** [comment]
@CamilleTeruel the idea is to cherry-pick 5081 to beta6? Or will it enter the next beta version?

**Comment by klesh** [comment]
> @CamilleTeruel the idea is to cherry-pick 5081 to beta6? Or will it enter the next beta version?

Next beta version

**Comment by hezyin** [comment]
@andremattosferraz v0.17.0-beta8 has been released with the required cherry-pick. Let us know if it still doesn't work.

**Comment by KlemenDanfoss** [comment]
> @KlemenDanfoss @andremattosferraz v0.17.0-beta8 has been released with the required cherry-pick. Let us know if it still doesn't work.

`subtask extractAzuredevopsGitpullrequest ... 1048 "Column 'merge_commit_sha' cannot be null"`

:)

**Comment by andremattosferraz** [comment]
#5298 still occurring :(

**Comment by CamilleTeruel** [comment]
Fixed in #5191, the other reported error is tracked by #5298
