### ISSUE TITLE
[Feature][PagerDuty] Support specifying Custom Rate Limit with requests/min instead of requests/hour

### ISSUE THREAD

**Issue by Feggah** [apache/devlake#5279]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Based on the [PagerDuty documentation](https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTUz-rate-limiting) and the [PagerDuty community forum](https://community.pagerduty.com/forum/t/which-rate-limit-of-rest-api-is-correct/3322) the Rate Limit for PagerDuty is 900 requests/min.

We should be able to specify Custom Rate Limit with requests/min instead of requests/hour for PagerDuty.

![image](https://github.com/apache/incubator-devlake/assets/11353912/fed5a612-98ec-46a8-b60e-87eda98aebc1)

Also, the message `PagerDuty does not specify a maximum value of rate limit.` should be changed to `PagerDuty specifies a maximum value of 900 requests/min for rate limit.`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for the suggestion, however, I think we should keep it simple by converting Requests per Minute to Requests per Hour. 
It would be 54000 Requests Per Hours in this case

**Comment by Feggah** [comment]
My only concern here is how this requests/hour are distributed? Because 54000 requested/hour isn't necessarily the same as 900 requests/min.

For example, if I specify 54000 requests/hour, the code distributes it evenly throughout the whole hour (thus, using 900/min) or it tries to go as fast as possible and could, for example, do this 54000 requests in 10 minutes (then waiting 50minutes idle to request again)?

**Comment by klesh** [comment]
@Feggah Good question, it is evenly distributed. So, 900 rpm and 54000 rph are equivalent.

**Comment by Feggah** [comment]
Awesome, I'll close this issue then. Thanks for the clarification!
