### ISSUE TITLE
[Bug][PagerDuty] Plugin isn't pulling all incidents from PagerDuty to _raw_pagerduty_incidents table

### ISSUE THREAD

**Issue by Feggah** [apache/devlake#5311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I created a Blueprint with 1 Data Scope from GitHub and 2 from PagerDuty:
![image](https://github.com/apache/incubator-devlake/assets/11353912/601bb3e8-4bc5-4959-b200-bdbafd98031c)

The Data Entity Issue Tracking is collected only by the PagerDuty Data Scopes.

Both PagerDuty Data Scopes (Services) have, in total, 217 incidents in the last 6 months.
![image](https://github.com/apache/incubator-devlake/assets/11353912/ba054d67-199b-4250-ac8f-b5d8aa62e07f)
![image](https://github.com/apache/incubator-devlake/assets/11353912/2396f87a-1591-481b-b474-8f1cba717466)

But, when I Sync the Project and open the DORA Dashboard Validation, I see that it pulled only 9 incidents instead of 217:
![image](https://github.com/apache/incubator-devlake/assets/11353912/69a314fa-30bf-49fe-98b4-75a1be53ea61)

Probably, this is because the incidents were just collected from the Service with 9 incidents. So I checked the table `board_issues` and can confirm that it has only incidents related to one of the two Services:
![image](https://github.com/apache/incubator-devlake/assets/11353912/7bcbb2be-6bc1-487f-a9c3-0c093a3a478b)

### What do you expect to happen

The PagerDuty plugin should pull all incidents related to the Data Scopes (Services) configured, not just one of them.

### How to reproduce

Create a blueprint with two or more Services and Sync.

The total number of incidents is going to be the number of incidents of one Service instead of all of them added together.

### Version

v0.17.0-beta8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for your report, @keon94 Please take a look

**Comment by keon94** [comment]
@Feggah https://github.com/apache/incubator-devlake/pull/5335 should fix this issue.

**Comment by hezyin** [comment]
The fix has been merged, closing this issue now.

**Comment by keon94** [comment]
@Feggah @sais8, that PR was missing and additional fix. The full fix should be available in beta10. PR: https://github.com/apache/incubator-devlake/pull/5346
cc @hezyin

**Comment by Feggah** [comment]
I noticed that the beta9 wasn't working.

I tried to run a Sync with a fresh installation of DevLake:
![image](https://github.com/apache/incubator-devlake/assets/11353912/2baf77ba-9a91-4088-8a04-cc880ccc603f)

And no `issues` with type INCIDENT were created:
![image](https://github.com/apache/incubator-devlake/assets/11353912/ccc890d8-ed1a-4916-a507-cb1545cfe45c)

![image](https://github.com/apache/incubator-devlake/assets/11353912/2235127a-13ce-4488-975e-1d21c5aa341b)

Then I tried to see the logs, and for each Task, it encountered 0 incidents:
![image](https://github.com/apache/incubator-devlake/assets/11353912/97dc3c7c-ed75-443e-a1a3-85f51c593d7c)

---

I will wait for beta10 and try it out again. Thanks @keon94.

Can we keep this issue open until this works?

**Comment by hezyin** [comment]
@Feggah Hi Gabriel, beta10 is out, could you please give it a try again? Thanks!

**Comment by Feggah** [comment]
Yep, this is working! Thanks people!
