### ISSUE TITLE
[Bug][GitHub] GitHub connection randomly fails with 401

### ISSUE THREAD

**Issue by visortelle** [apache/devlake#5333]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi!

I'm trying to set up a DevLake instance that scrapes [Apache Pulsar repository](https://github.com/apache/pulsar) stats.

It constantly fails at some point with `401` error code.

<img width="1440" alt="Screenshot 2023-05-31 at 3 16 44 PM" src="https://github.com/apache/incubator-devlake/assets/9302460/3daa2f83-5bff-4e66-9cdc-70e3a8d8d8c8">

[**Complete logs of two latest runs**](https://gist.github.com/visortelle/912683ff053222e0f158f2cc1ac6c0e4)

Probably related: https://github.com/apache/incubator-devlake/issues/5222
I tried to set `Custom Rate Limit` to `1500`.

Should I try an even smaller rate limit or use more access tokens? 
I've tried it with 2 tokens (classic) of 2 different GitHub accounts.

Maybe someone has a reference DevLake config that works with large GitHub repos?

### What do you expect to happen

It should work.

### How to reproduce

Try to set up a blueprint with a GitHub connection for https://github.com/apache/pulsar

### Version

v0.17.0-beta8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by visortelle** [comment]
@klesh I would be very appreciated if you could help. 🙏
Do you have any ideas on how to fix the issue?

**Comment by klesh** [comment]
@visortelle , I don't think it is a ratelimit problem, there were 401 errors, did you set up the permissions required according to this doc? https://devlake.apache.org/docs/next/Configuration/GitHub#github-personal-access-tokensrecommended

**Comment by visortelle** [comment]
@klesh

For an experiment, I used another GitHub account and created a token with all permissions.

<img width="408" alt="Screenshot 2023-06-02 at 10 28 48 AM" src="https://github.com/apache/incubator-devlake/assets/9302460/e0078424-141e-46d3-a755-7ef292e9f875">

I failed with same errors:

<img width="1440" alt="Screenshot 2023-06-02 at 10 38 26 AM" src="https://github.com/apache/incubator-devlake/assets/9302460/dda0b1c4-f87b-46c8-bceb-ee3c537f67bc">

Logs: https://gist.github.com/visortelle/cb9f4748e6616669f2357754ab19ca60

**Comment by klesh** [comment]
@visortelle Sorry, I must have missed your reply, will look into it ASAP

**Comment by klesh** [comment]
Unfortunately, I couldn't reproduce your error with the minimal permissions, my TimeFilter was set to 6 months:

![Snipaste_2023-06-12_17-14-55](https://github.com/apache/incubator-devlake/assets/61080/330b2366-2a77-49e9-bfcd-47fddc6eca67)

There have been multiple reports that Github would return 403/500 randomly, I'm suspecting that some of their CDN or Server-Nodes are not very stable from time to time, or place to place. Can you try again at a different time or deploy it to a different region and see if the error gone?

**Comment by klesh** [comment]
Might be related to #5879
