### ISSUE TITLE
[Bug][AzureDevOps] Error extracting running builds 

### ISSUE THREAD

**Issue by CamilleTeruel** [apache/devlake#5336]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We get `(mysqldb.operationalerror) (1048, "Column 'result' cannot be null")` errors when extracting builds that don't have a result yet.

### What do you expect to happen

No error

### How to reproduce

Run azuredevops while a build is running.

### Version

v0.17.0-beta8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KlemenDanfoss** [comment]
@CamilleTeruel , I still get the same error with beta9.

**Comment by hezyin** [comment]
Hi @KlemenDanfoss, we'll add migrations to allow null values in relevant columns in the upcoming v0.17.0-beta10, stay tuned.

**Comment by hezyin** [comment]
@KlemenDanfoss Seems like the last fix didn't cover all the upgrade paths. @CamilleTeruel just added migrations for all relevant columns in https://github.com/apache/incubator-devlake/pull/5420. It will be included in beta11.

**Comment by andremattosferraz** [comment]
Worked guys:

<img width="1190" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/b6a18917-8a0c-45d0-ab7b-bfa4376b86af">
