### ISSUE TITLE
[README][Community] Scanning WeChat code returns "group has reached limit"

### ISSUE THREAD

**Issue by ProjectsOfMLee** [apache/devlake#5340]
Please refer to the title of this issue.

**Comment by Startrekzky** [comment]
I just generated a new one, please try it out. Feel free to reopen this issue if this barcode is invalid.

![img_v2_b8c1b461-c0bd-43ec-95a3-54c7421e597g](https://github.com/apache/incubator-devlake/assets/14050754/4a21660f-c5e1-405b-8535-6d6d83446fdd)
