### ISSUE TITLE
[Bug] panic: listening tcp 8080 missing port in address

### ISSUE THREAD

**Issue by ProjectsOfMLee** [apache/devlake#5359]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I tried running v0.17 & v0.16 locally after cloning the repository and following the installation instructions,

it shows the error as the title states

### What do you expect to happen

I expect it to run properly as I used the docker-compose-dev.yml suggested by a devlake maintainer

### How to reproduce

simply clone the main repo and run `docker-compose -f docker-compose-dev.yml up` 

### Anything else

Using mysql and postgresql both show this error (everything else unchanged)

### Version

v0.17.0-beta

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezyin** [comment]
@ProjectsOfMLee Hi, please follow our docker compose setup doc at https://devlake.apache.org/docs/next/GettingStarted/DockerComposeSetup instead of using the `docker-compose-dev.yml` file.

**Comment by klesh** [comment]
@ProjectsOfMLee Hi, which "installation instructions" did you follow? Can you paste the link here?

**Comment by klesh** [comment]
@spirosoik The guide seems fine to me.
![image](https://github.com/apache/incubator-devlake/assets/61080/595d8e8b-d693-4008-9e1f-9ecfc76fdcec)
![image](https://github.com/apache/incubator-devlake/assets/61080/b602f81f-bebb-41dc-814c-a36a0724a73c)


I'm curious why you would use the `docker-compose-dev.yml` file instead, how do you think we should do to avoid such a misunderstanding?
