### ISSUE TITLE
[Feature][Jira] Transformation based on JQL

### ISSUE THREAD

**Issue by tim-goto** [apache/devlake#5372]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Instead of transformations based on the differnet issue types, we would like to enter [JQL](https://support.atlassian.com/jira-service-management-cloud/docs/use-advanced-search-with-jira-query-language-jql/) queries to select the appropriate tickets since that gives a little more flexibility

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tim-goto** [comment]
Sure: We have a board where multiple components of a single product are tracked, each component has different deployments, code bases and so on.. We would like to track DORA metrics for each component of the product but there is currently no way to distinguish tickets on a board in devlake. For the moment we created individual JIRA boards filtering for the components but it would be nice to have a more granular selection in the devlake transformations.

**Comment by klesh** [comment]
Not sure if I understand you correctly, sounds like you would like the Jira Scope to be like `Board` + `JQL` instead of `Board` alone, so you can group issues from the same `Board` into different DORA projects?

**Comment by tim-goto** [comment]
Yes, either that or Jira ticket selection to be `JQL` + issue type instead of just issue type

**Comment by tim-goto** [comment]
Still important to me
