### ISSUE TITLE
[Feature][Config UI] Improve the ux of the sync frequency setting

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#5382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I wanted to set up a `custom` sync frequency of a blueprint, but I didn't know how to configure it via the cron expression. I had to google it and even after I input a value, I didn't know if it was correct as the UI only showed the next run time.

![image](https://github.com/apache/incubator-devlake/assets/14050754/b5c40398-ec86-4332-8391-4fa1a76ad6f9)

### To Do

- [ ] Provide a link for users to reference, such as https://crontab.cronhub.io/
- [ ] List three future runs for users to preview
- [ ] Allow users to configure daily/weekly/... 0 AM based on their local timezone. For example, if a user is in UTC+2, and the user chooses `daily`, the sync time will be 0 AM in UTC +2 every day, not 2 AM in UTC +2 every day.

### Prototypes
![image](https://github.com/apache/incubator-devlake/assets/14050754/737a21e9-6acf-434c-b2e3-a8122d75d36a)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@mintsweet Can you update the link to cron job setting page to:

```
[Learn how to use cron code](https://crontab.cronhub.io/) or [auto-convert English to cron code](https://cron-ai.vercel.app/)
```

**Comment by mintsweet** [comment]
@Startrekzky Of course. Here's the PR #5732.
