### ISSUE TITLE
[Bug][Azure DevOps] Build not found

### ISSUE THREAD

**Issue by andremattosferraz** [apache/devlake#5383]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Receiving build not found when running AzureDevOps blueprint.
<img width="1440" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/55c80288-688c-4a22-967f-a1ee8666f609">
[task-293-2-1-azuredevops.log](https://github.com/apache/incubator-devlake/files/11665693/task-293-2-1-azuredevops.log)

### What do you expect to happen

Run without error

### How to reproduce

running AzureDevOps blueprint.

### Anything else

Doing a get request to "https://dev.azure.com/shapeDigitalSD/Maintenance%20Product/_apis/build/builds/" dont return any 4863 buildid.

<img width="1336" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/9a800b5c-e544-4335-a590-ad1e59f43950">

### Version

v0.17.0-beta10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by andremattosferraz** [comment]
How does the devlake get those build ids? Is searched from azure dev ops or based on some devlake db table?

**Comment by CamilleTeruel** [comment]
This build id comes from a previous collection. 
I suspect that this is a build that first got marked as deleted, and really got deleted after some time (set in the retention policy of your project settings, minimum 30 days). Asking for the timeline of a build that is just marked deleted returns a 204, but for a build that really got deleted, we apparently get a 404.
