### ISSUE TITLE
[Bug][lake] lake does not handle 404´d Gitlab MR and fails the whole blueprint pipeline

### ISSUE THREAD

**Issue by renflo** [apache/devlake#5385]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have a blueprint which worked earlier and started failing. It integrates with gitlab and started to fail when fetching "Code review" data entities. The UI showed that message:
![Screenshot 2023-06-06 at 21 57 23](https://github.com/apache/incubator-devlake/assets/231459/a1eafd53-663c-4a25-86ae-06639ff52330)

The message is not straightforward but I guessed that maybe the MR was not actually existing anymore and was proven right by simply trying to fetch it in the gitlab GUI:
![Screenshot 2023-06-06 at 21 59 18](https://github.com/apache/incubator-devlake/assets/231459/b94d5a2e-443d-461c-8bd9-271610ffc99a)

That's not good because the whole job just chokes on that missing MR instead of gracefully ignoring it and continuing. As a temporary workaround I've removed the collection of "Code review" data entities and the pipeline now passes, but that also leads to a lot of valuable information not making it to grafana.

I haven't checked the code of lake but I would imagine a relatively simple exception handling block catching and ignoring those errors or a conditional expression would suffice. I really hope you can prioritize fixing this bug.

### What do you expect to happen

The pipeline should just ignore MRs which are 404'd by gitlab and continue its information gathering - instead of completely failing.

### How to reproduce

The steps mentioned in "What happened" are precise enough I believe. 
1. project integrating with gitlab
2. gitlab project with a few MR. you delete one of them.
3. you run the pipeline. 
4. things will likely fail as I describe

Do note that I haven't reproduced myself but this is likely to be what has to be done to be able to.

### Version

v0.16.0
Same behavior in v0.15.1-beta5 and beta6.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for your report, I agree with you we should skip the missing MR, do you know why the MR is gone between collections? is it normal for PR to be deleted from the data source?

@hezyin @Startrekzky  @mindlesscloud @likyh @keon94 @CamilleTeruel I think we should ignore all 404 error for all secondary-data-collections (collectors that rely on other entity, e.g. changelogs , comments, etcs)

**Comment by renflo** [comment]
I would not say it's normal if what you mean is "is it the default". I actually don't know why the team owning this repository deleted it and I've asked them out of curiosity but I guess there could be plenty of reasons. 

Maybe you pushed secrets that should never have been pushed and want them removed. Maybe you for some reason are not happy with what you coded and don't want anyone to stumble upon it. Maybe the MR was so broken there is no reason to keep it for historical reason. Maybe a team wants to delete very old MR from their repos to clean up and only keep the newest ones.

In any case as long as the possibility is there someone will always use it :)

That's great if you can do something. If you orient me a bit in your code base so I get an idea of where to patch I could probably attempt to propose a PR. And if I feel I'm not going to be able to find time I could let you know. Let me know.

**Comment by klesh** [comment]
@CamilleTeruel I agree that it is API-specific. What is your solution then? 
Should we address the issue on the Gitlab plugin? 
How do we report the error without breaking the whole pipeline?

**Comment by CamilleTeruel** [comment]
I don't have a solution and I'm not saying that the framework mustn't ignore those 404s. It's just that we don't yet have a generic way to tell whether those errors happen because the parent resource has been deleted or for another reason.

On the top of my head I see two strategies to tell that, but they are not great:
- Store the API url to get the item in raw rows, not the url used to fetch the whole collection as it is right now. Then the framework can try to refetch the parent item in case of 404. If it fails again we know we can safely ignore the error. The issue is that all plugins have to find or construct that url for each item.
- When we face one of those 404s, rerun collection/extraction/conversion of parent resource from scratch to be sure we are up to date, and then retry the child resource collection. This might slow down collection significantly and might be hard to implement.

Now does it worth it? I don't know how often it can be for another reason in practice, I just have the example of CircleCI API that returned a 404 for getting the jobs of some existing but failed build. But thinking about this one case, the proper handling is also to ignore it, so... maybe we don't care.

BTW, shouldn't we also delete the parent row when we find out it has been deleted from the datasource?

**Comment by renflo** [comment]
I don’t know the codebase at all and not have gotten the following correctly but allow me one comment:
 

> When we face one of those 404s, rerun collection/extraction/conversion of parent resource from scratch to be sure we are up to date, and then retry the child resource collection. This might slow down collection significantly and might be hard to implement.

Retrying is not a good strategy imho. Wastes resources in my case at lease because if it’s gone, it’s gone, it’s not going to help to retry.

In addition the pipelines are running periodically and i would argue that it _is_ a form of retry.


Thanks for discussing this, good to see that the project is alive :)

**Comment by klesh** [comment]
> I don't have a solution and I'm not saying that the framework mustn't ignore those 404s. It's just that we don't yet have a generic way to tell whether those errors happen because the parent resource has been deleted or for another reason.
> 
> On the top of my head I see two strategies to tell that, but they are not great:
> 
> * Store the API url to get the item in raw rows, not the url used to fetch the whole collection as it is right now. Then the framework can try to refetch the parent item in case of 404. If it fails again we know we can safely ignore the error. The issue is that all plugins have to find or construct that url for each item.
> * When we face one of those 404s, rerun collection/extraction/conversion of parent resource from scratch to be sure we are up to date, and then retry the child resource collection. This might slow down collection significantly and might be hard to implement.
> 
> Now does it worth it? I don't know how often it can be for another reason in practice, I just have the example of CircleCI API that returned a 404 for getting the jobs of some existing but failed build. But thinking about this one case, the proper handling is also to ignore it, so... maybe we don't care.
> 
> BTW, shouldn't we also delete the parent row when we find out it has been deleted from the datasource?

I see. Good points. I agree with you that there is no good general solution for this kind of problem. Especially cases like #5464 degrade the collection speed drastically.

Let's deal with them separately unless we come out with a better solution.

**Comment by klesh** [comment]
@renflo We will fix this particular issue ASAP.
