### ISSUE TITLE
[Question][plugin feishu] use feishu only collect meetingdata

### ISSUE THREAD

**Issue by niejian** [apache/devlake#5397]
## Question

**when use feishu plugin like , after run blueprints, only see meeting data. If I want to collect other data, need extend feishu plugin? and the feishu plugin only collect metting data? if not , how can I collect other data, thanks**
```json
[
  [
    {
      "options": {
        "connectionId": 8,
        "numOfDaysToCollect": 80,
        "rateLimitPerSecond": 5
      },
      "plugin": "feishu"
    }
  ]
]
```
## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by klesh** [comment]
Yes, only meeting data is collected for feishu plugin at the moment
