### ISSUE TITLE
[Bug][Connections] Jira Connection in use can be deleted

### ISSUE THREAD

**Issue by byers5** [apache/devlake#5403]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

You are able to delete a Jira Connector that is actually in use in a project so I cause recurrent errors when the Blueprint is running

### What do you expect to happen

An error message saying that the connector is already in use in one or many projects

A way to delete that connection from the project page before deleting it from the connection page

### How to reproduce

Create a Jira connection
Create a projet using that Jira connection
Run the blueprint of the projet until the end
Delete the Jira connection from the connection page
Run the blueprint of the projet

### Version

v0.17.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
Hi @byers5 , thanks for your report, this issue will be fixed in the upcoming version, please stay tuned.

**Comment by Startrekzky** [comment]
Hi @byers5 . This is fixed in v0.18.0. You can check out the [latest release here](https://github.com/apache/incubator-devlake/releases).
