### ISSUE TITLE
[Bug][GitLab] The collected pr commits data is incorrect

### ISSUE THREAD

**Issue by mintsweet** [apache/devlake#5406]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The collected pr commits data is incorrect. missed some data.

This is my project, it has **three** mr, and it includes **four** commits.
![screenshot-20230608-113309](https://github.com/apache/incubator-devlake/assets/37237996/d22999dd-f6af-47f5-aa4a-18f7c69fcfce)
![screenshot-20230608-113329](https://github.com/apache/incubator-devlake/assets/37237996/44be1e11-e841-4e56-b5db-007081461d1a)
![screenshot-20230608-113410](https://github.com/apache/incubator-devlake/assets/37237996/c2b73758-76dc-458c-aea8-69c3fa7fd5a6)
![screenshot-20230608-113427](https://github.com/apache/incubator-devlake/assets/37237996/316fb1b2-0656-4bb2-afbb-47c7149ff62e)

In fact, there are only **two** pr commits collected.
![screenshot-20230608-113515](https://github.com/apache/incubator-devlake/assets/37237996/8ad62d72-a468-44d5-b37f-43ccd3246166)
![screenshot-20230608-113521](https://github.com/apache/incubator-devlake/assets/37237996/0a74fa37-8f82-486a-aadd-8d8527678649)
![screenshot-20230608-113529](https://github.com/apache/incubator-devlake/assets/37237996/4d58022b-f412-4cfa-9976-074a10ff2bd5)
![screenshot-20230608-113554](https://github.com/apache/incubator-devlake/assets/37237996/c9b8b640-4db0-40f7-b503-4ff6b0d54b90)
![screenshot-20230608-113607](https://github.com/apache/incubator-devlake/assets/37237996/c2db2ed8-3973-4423-a9bf-42e1f2414cf3)

### What do you expect to happen

The collected data that it has **four** pr commits.

### How to reproduce

1. Create a new GitLab Project named **Test**.
2. Create a new mr include **one** commit.
3. Create a new mr include **one** commit.
4. Use Devlake to collect Data, and contains two pr commits at this time. ✅
5. Create a new mr include **two** commit.
6. Use Devlake to collect Data. At this time, only two PR commits on the new mr are included, and the old ones are lost. ❌

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezyin** [comment]
@klesh @mappjzc @mintsweet Do we need to fix this for v0.17 as well?

**Comment by klesh** [comment]
@hezyin had been cherry-picked to v0.17 by #5418
