### ISSUE TITLE
[Doc][Plugin] Plugin implementation guide is outdated

### ISSUE THREAD

**Issue by hezyin** [apache/devlake#5429]
https://devlake.apache.org/docs/next/DeveloperManuals/PluginImplementation/ is outdated. However, our Python plugin doc is up-to-date: https://github.com/apache/incubator-devlake/tree/main/backend/python. Shall we simply replace the outdated golang plugin development guide with the latest python doc?

**Comment by keon94** [comment]
Do you intend to deprecate plugin development in Golang in favor of Python?

**Comment by klesh** [comment]
I thought we are going to update the document for golang according to the python one.
@hezyin Can you clarify your intention?
