### ISSUE TITLE
[Bug][dora] wrong identifier in table cicd_deployment_commits

### ISSUE THREAD

**Issue by Marco-De-Stefani** [apache/devlake#5465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

At the moment the Id present in the table "cicd_deployment_commits" is made up in the following way 
gitlab:GitlabPipeline:1:123456789:https://gitlab.com/.../...
but to understand if a deployment caused an incident this query is used:
`select
    cdc.id as deployment_id,
    cdc.finished_date,
    pim.id as incident_id,
    if (pim.id is not null, 'TRUE', 'FALSE') as has_failure
from
    cicd_deployment_commits cdc
    left join project_issue_metrics pim on cdc.id = pim.deployment_id
         left join project_mapping pm on cdc.cicd_scope_id = pm.row_id and pm.table = 'cicd_scopes'
where pm.project_name = 'backstage'
order by 2 desc;`

My problem is that in the table "project_issue_metrics" the field "deployment_id" does not contain the GitLab URL, so the join made between the 2 tables is not working

### What do you expect to happen

I would expect to have incidents connected to deployments in the DORA Validation dashboard. To be more precise, I would expect the table at "Step 4" of the "Check Change Failure Rate & Median Time to Restore Service" to contain incident correlated with deployment

### How to reproduce

This is my current case, but I suppose it could happen also in other ones:

- Have a GitLab project with advanced configuration in DevLake
- Have at least 2 prod deployments
- Add an incoming Webhook with "boards" type, used to register incidents
- Register an incident with date between the 2 deployments
- Have a look at the DORA metrics validation dashboard

### Anything else

I think that the issue is this piece of code in the "deployment_commits_generator.go":
`Id: fmt.Sprintf("%s:%s", pipelineCommit.PipelineId, pipelineCommit.RepoUrl),`

### Version

754135dee02b6b9992da91e17a9de748e00415ba

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Related to #5475
