### ISSUE TITLE
[Bug][Data Deletion] Removing a data scope from a project did not remove the relationship between the data scope and the project in table 'project_mapping''

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#5466]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I deleted a data scope (a Jira board = 'jira:JiraBoard:1:92') on the project's Jira connection page, but the data still existed in the `project mapping` table.

![image](https://github.com/apache/incubator-devlake/assets/14050754/958aab1e-e6b2-43e2-81b7-26dff3f3fed2)

Still in table.project_mapping
![image](https://github.com/apache/incubator-devlake/assets/14050754/03eea60c-7797-4223-90bd-b3e8d75e6c16)

### What do you expect to happen

Removing a data scope from a project will also remove the relationship between the data scope and the project in table.project_mapping. If we don't do this, this project will still use this data scope's data to measure DORA or other metrics.

### How to reproduce

1. Install v0.18.0-alpha3
2. Create a Jira connection and a DevLake project that references this connection
3. Collect two Jira boards
4. Remove a Jira board in the DevLake project, see result

### Version

v0.18.0-alpha3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Sorry, I forgot that `project_mapping` doesn't need to be deleted right away, we just need to prompt users that related projects/bps need to be rerun to update the project_mapping

**Comment by Startrekzky** [comment]
Sorry, it's not a bug.
