### ISSUE TITLE
[Feature][AzureDevops] Select which task type to map to CicdTask

### ISSUE THREAD

**Issue by CamilleTeruel** [apache/devlake#5469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Azure devops plugin currently maps azure "jobs" to CicdTask.
But "jobs" are only one of the different task type in Azure devops model.
It should be possible to configure which task type to map to CicdTask, in particular "stages" that is used by some users.

### Description

Add an option to azure's scope config to select which tasks type to map to CicdTask.
It should support at least "job" and "stage" levels.

### Related issues

#5428

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by andremattosferraz** [comment]
@CamilleTeruel which property do you use to apply the transformation configured regex?

<img width="1012" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/0aace686-389c-4714-9fae-647eed7a342d">
<img width="953" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/c9df0c94-7029-45f3-9536-ebd62ee3e222">


<img width="1286" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/cc3dcba3-df4f-49a6-ade1-8adf0f5213f4">
<img width="1294" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/d84a6281-4d29-4002-9984-1b15ad496340">

**Comment by CamilleTeruel** [comment]
> @CamilleTeruel which property do you use to apply the transformation configured regex?

The `name` property.

**Comment by andremattosferraz** [comment]
@CamilleTeruel looks like is not working properly. Based on the print screen could you figure out what I need to change?

**Comment by alexvaccaro** [comment]
@CamilleTeruel , I see this feature request has been closed but looks like it has not been done yet, does it mean this will not be implemented anymore?

**Comment by alexvaccaro** [comment]
hi, I am still interested in getting this change

**Comment by klesh** [comment]
Hi, @alexvaccaro . I've re-opened the issue. However, no one is working on it at the moment.
