### ISSUE TITLE
[Bug][docker-compose] devlake container keeps restarting

### ISSUE THREAD

**Issue by EliadCohen** [apache/devlake#5474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I used the instructions to install with docker, I used podman-compose instead of docker-compose.
I am unable to access the config ui and when examining the containers, I noticed that devlake_devlake_1 keeps restarting. Upon trying to attach, I saw this message:

`Version:  v0.17.0-beta4@
time="2023-06-13 23:32:39" level=warning msg="Failed to create filestream for logs. Logs will not be piped to files.
        caused by: open /app/logs/devlake.log: permission denied
        Wraps: (2) open /app/logs/devlake.log
        Wraps: (3) permission denied
        Error types: (1) *hintdetail.withDetail (2) *fs.PathError (3) syscall.Errno"
Attempting to write configuration to .env file.
panic: open ./.env: permission denied
Wraps: (2) open ./.env
Wraps: (3) permission denied
Error types: (1) *hintdetail.withDetail (2) *fs.PathError (3) syscall.Errno

goroutine 1 [running]:
main.main()
        /app/server/main.go:36 +0x93
`

In addition, browsing to http://localhost:4000/ I see the following message in the devlake_config-ui_1 console:
`
10.89.0.1 - - [13/Jun/2023:23:36:25 +0000] "GET /assets/index-14ed113a.js HTTP/1.1" 200 1424102 "http://localhost:4000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
2023/06/13 23:36:25 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.89.0.1, server: localhost, request: "GET /api/version HTTP/1.1", upstream: "http://10.89.0.8:8080/version", host: "localhost:4000", referrer: "http://localhost:4000/"

`

### What do you expect to happen

I expect to see the config ui and possibly the devlake container remain running and stable

### How to reproduce

`podman-compose up -d`
Use: https://devlake.apache.org/docs/GettingStarted/DockerComposeSetup
with: https://github.com/apache/incubator-devlake/releases/tag/v0.17.0-beta4 

### Anything else

Also tried docker-compose with sudo
also tried podman-compose with sudo
I'm running on Fedora 37

Thanks :heart: 

### Version

v0.17.0-beta4 

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EliadCohen** [comment]
Issue remains with Beta10

**Comment by EliadCohen** [comment]
An update, commenting out the volume mount in docker-compose stops the constant restart but then other issues pop up. I don't know what should be the handling of this issue

```
  devlake:
    image: apache/devlake:v0.17.0-beta10
    ports:
      - 8080:8080
    restart: always
    volumes:
      # - ./.env:/app/.env   <--------------
      - ./logs:/app/logs
    environment:
      LOGGING_DIR: /app/logs
    depends_on:
      - mysql
```

**Comment by abeizn** [comment]
@EliadCohen You can try to set the parameters in the .env file as: LOGGING_DIR="./logs"

**Comment by klesh** [comment]
please make sure the `./log` if a folder and writable

**Comment by abeizn** [comment]
> 
The .env file should be under incubator-devlake, not under incubator-devlake/backend. Please make sure you modify the .env file under incubator-devlake

**Comment by EliadCohen** [comment]
Seems that the issue is SELinux
modifying the docker compose file to: 
```
52   devlake:
53     image: apache/devlake:v0.17.0-beta11
54     ports:
55       - 8080:8080
56     restart: always
57     volumes:
58       - ./.env:/app/.env:z   <----- Right here
59       - ./logs:/app/logs
60     environment:
61       LOGGING_DIR: /app/logs
```
Also, couldn't run without root. I'm getting errors around the DB migration

**Comment by Startrekzky** [comment]
Problem solved.
