### ISSUE TITLE
[Bug][TAPD]  “invalid syntax” error when running extractStoryChangelog task

### ISSUE THREAD

**Issue by oklmvlns8564** [apache/devlake#5476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

when running tapd task “extractStoryChangelog”，I encounter. the error :
`time="2023-06-13 20:41:17" level=error msg=" [pipeline service] [pipeline #41] [task #49] subtask extractStoryChangelog ended unexpectedly
 Wraps: (2) error calling plugin Extract implementation
 Wraps: (3) invalid syntax
 Wraps: (4) invalid syntax
 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *errors.errorString"`

### What do you expect to happen

Compatible with different interface content returns

### How to reproduce

I found that the problem lies in this function

./backend/plugins/tapd/tasks/shared.go
`// unicodeToZh converts a string containing Unicode escape sequences to a Chinese string.
// It returns the converted string and an error if the conversion fails.
func unicodeToZh(s string) (string, error) {
	str, err := strconv.Unquote(strings.Replace(strconv.Quote(s), `\\u`, `\u`, -1))
	if err != nil {
		return "", err
	}
	return str, nil
}`

using this input:
`&nbsp;current-order接口出现报错报错内容：{"code":-1,"msg":"【message】您没有正在进行中的订单\t【code】-3001\t【file】/data/wwwroot/etc_swoole/app/micro/components/function.php\t【line】26\t【trace】#0 /data/wwwroot/etc_swoole/app/user/controller/ApplyController.php(73): throws('\\xE6\\x82\\xA8\\xE6\\xB2\\xA1\\xE6\\x9C\\x89\\xE6\\xAD\\xA3\\xE5\\x9C\\xA8...', -3001)\n#1 /data/wwwroot/etc_swoole/Ets/server/BaseServer.php(79): app\\user\\controller\\ApplyController-&gt;actionCurrentOrder()\n#2 /data/wwwroot/etc_swoole/Ets/server/HttpServer.php(61): Ets\\server\\BaseServer-&gt;handler(Object(Swoole\\Http\\Request), Array)\n#3 {main}\t","data":null}`

### Version

v0.17.0-beta11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@oklmvlns8564 Thanks for the report.
However, I'm having difficulty reproducing the `panic`, can you write me a UnitTest case based on [this one](https://github.com/apache/incubator-devlake/blob/e8f8d3b824ab4cb79e0bf13d1694e88b73b85730/backend/plugins/tapd/tasks/shared_test.go#L195)? Thanks

**Comment by oklmvlns8564** [comment]
> @oklmvlns8564 Thanks for the report. However, I'm having difficulty reproducing the `panic`, can you write me a UnitTest case based on [this one](https://github.com/apache/incubator-devlake/blob/e8f8d3b824ab4cb79e0bf13d1694e88b73b85730/backend/plugins/tapd/tasks/shared_test.go#L195)? Thanks

@klesh hi, I found that as long as the input string contains' \\u ' but is not Unicode encoded, an error will be reported
`func TestUnicodeToZh(t *testing.T) {
	input := "app\\user\\u4e2d\\u6587"
	expected := "中文"
	output, err := unicodeToZh(input)
	if err != nil {
		t.Errorf("unicodeToZh(%q) returned error %v", input, err)
	}
	if output != expected {
		t.Errorf("unicodeToZh(%q) = %q, want %q", input, output, expected)
	}
}`

**Comment by klesh** [comment]
I finally get to investigate the phenomenon.
Thanks to the unit test case, I figured out what was wrong...
Why would anyone put quoted Unicode string in conjunction with ordinary characters, this is amateur.

It can not be fixed without a tradeoff since the information had been twisted. 😂

**Comment by klesh** [comment]
@oklmvlns8564 Just to make sure, the string "app\\user\\u4e2d\\u6587" appears in you raw data content?
or is it "app\\\\user\\u4e2d\\u6587"

**Comment by Startrekzky** [comment]
Hi @oklmvlns8564 , can you answer the above question?
