### ISSUE TITLE
[Bug][gitlab] Not fetching correctly squashed commits from merge requests

### ISSUE THREAD

**Issue by Marco-De-Stefani** [apache/devlake#5486]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The fetching of the merge request information from GitLab APIs is not completely correct because the option "squash on merge" of GitLab is not managed correctly.
To be more specific when a MR is squashed the related commit sha is not reported inside the field "merge_commit_sha" that we are fetching from GitLab APIs but is instead inside the "squash_commit_sha" field. The information about the squashing option enabled or disabled is inside the "squash" field.

Gitlab docs: https://docs.gitlab.com/ee/api/merge_requests.html#response

### What do you expect to happen

I would have expected to have the "merge_commit_sha" field in the "pull_requests" table be populated to proceed with the DORA metrics validation.

### How to reproduce

- Have a working version of DevLake
- Integrate it with a GitLab project
- In the integrated Gitlab project set as "Required" the squash option (under Settings -> Merge Request ->  Squash commits when merging)
- Create a Merge request in the project and merge it 

### Version

v0.17.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
I see, what is the solution in your mind? Should we add a new column or convert the squash_commit_sha instead of merge_commit_sha?

**Comment by Marco-De-Stefani** [comment]
I've tried to convert the squash_commit_sha inside the merge_commit_sha field and it looks like it's working fine.
Just to avoid the creation of other bugs, let me test something more regarding that and I'll provide a PR

(I realized this morning that in some strange cases, GitLab is returning null to both of the fields, so maybe it's a GitLab bug)

**Comment by klesh** [comment]
@Marco-De-Stefani I talked to @liangjingyang and he contributed some very valuable information:
Accord to the [comment from the gitlab official repo](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/app/models/merge_request.rb#L556), not only `merge_commit_sha` might be `null`, but also `squash_commit_sha` when using `fast-forward` without squash.
So, we may need to do another fallback to the `diff_head_sha` to fully address the problem.

**Comment by Marco-De-Stefani** [comment]
@klesh I opened a PR, if you think that something is not right, feel free to contact me on Slack
