### ISSUE TITLE
[Bug][Connections] JIRA connection information is partially lost in the form.

### ISSUE THREAD

**Issue by MarcViola** [apache/devlake#5489]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When a JIRA connection is created with a JIRA Server and an API token, and later the connection is edited, the form goes back to JIRA Cloud and the token field is empty.  Causing some confusion as to what kind of configuration is used.  The configuration is not lost per se as we can still test it successfully but it should show the right configuration.

### What do you expect to happen

I expect the form to show the actual configuration because a user looking at the form cannot tell how the JIRA connection is configured.

### How to reproduce

Create a JIRA connection and use JIRA Server with API token.
Test connection and save connection.
Edit the same JIRA connection - the JIRA Cloud is selected and the API field is empty (meaning the dots are not visible because it's a token and it shouldn't be visible).

### Version

v0.17.0-beta11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
I can't reproduce this bug. Do you have this problem? Can you take a screenshot in Gif to give us more information?
