### ISSUE TITLE
[Bug][Gitlab] GitLab pipeline jobs collection takes a long time

### ISSUE THREAD

**Issue by kyleliu1008** [apache/devlake#5493]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In version v0.16.0, when collecting job data of GitLab pipeline, each execution will repeatedly collect all job data within the specified range, resulting in a long collection time.

### What do you expect to happen

If the job status is completed and has not been updated, the job information will not be collected again.

### How to reproduce

Run GitLab pipeline collection twice.

### Version

v0.16.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@kyleliu1008 Hi, thanks for the report. However, I am unable to reproduce the problem. The incremental collection seems to be working fine on v0.16.0

![image](https://github.com/apache/incubator-devlake/assets/61080/c813221b-0eff-46d8-a06f-0d1b801a6d93)


Please provide more detailed information

**Comment by kyleliu1008** [comment]
> 
![image](https://github.com/apache/incubator-devlake/assets/29494039/b1e2e505-1dc5-41dc-b3dd-801e1c0f49ae)

![image](https://github.com/apache/incubator-devlake/assets/29494039/a1823cd6-f3d6-4b21-9d53-81544836c591)

The above screenshots are logs from two executions, both of which show full data collection was performed.

**Comment by klesh** [comment]
@kyleliu1008 Interesting, I believe the problem is caused by the `status=created`, collector would re-fetch those unfinished jobs by design and yes, it is totally normal for "duplicated" records in the raw table.

Are they all with pending status? Neither `success` nor `failed`? Is that normal for your `jobs` to be in the queue for days?

**Comment by kyleliu1008** [comment]
Indeed, there are many jobs in status=created among the projects I have collected, and this should be a problem with the CI settings. However, there are already a large number of these types of jobs, and I hope not to repeat collecting them. Is there a better solution to identify whether a job needs to be updated, such as the ”last update time“?

**Comment by Startrekzky** [comment]
@klesh What will happen if we do not re-fetch the 'created' status GitLab job?

**Comment by klesh** [comment]
> Indeed, there are many jobs in status=created among the projects I have collected, and this should be a problem with the CI settings. However, there are already a large number of these types of jobs, and I hope not to repeat collecting them. Is there a better solution to identify whether a job needs to be updated, such as the ”last update time“?

No, not really since the API doesn't support such a filtering option.



> @klesh What will happen if we do not re-fetch the 'created' status GitLab job?

That is a good idea, I think it makes sense to fetch only the finished job only.

**Comment by kyleliu1008** [comment]
In fact, there is another phenomenon related to the data in the "_raw_gitlab_api_job" table: when the pipeline is in a non-completed state, devlake will repeatedly collect all jobs under the pipeline, causing the jobs data corresponding to the pipeline in the "_raw_gitlab_api_job" table to double each time it is collected, leading to the increasing size of the table. This problem becomes more prominent when there are a large number of blocked pipelines or when pipelines have long lifecycles (of course, these issues should be improved in CI practices).

Of course, the raw table is meant to record the originally collected data, but the data volume of the devlake table I deployed quickly reached millions. This is related to the fact that our project generates a lot of invalid pipelines (which we are also working on resolving). If devlake could recognize that the pipeline and its corresponding job have not changed and not collect them again, it would be perfect.

**Comment by klesh** [comment]
> In fact, there is another phenomenon related to the data in the "_raw_gitlab_api_job" table: when the pipeline is in a non-completed state, devlake will repeatedly collect all jobs under the pipeline, causing the jobs data corresponding to the pipeline in the "_raw_gitlab_api_job" table to double each time it is collected, leading to the increasing size of the table. This problem becomes more prominent when there are a large number of blocked pipelines or when pipelines have long lifecycles (of course, these issues should be improved in CI practices).
> 
> Of course, the raw table is meant to record the originally collected data, but the data volume of the devlake table I deployed quickly reached millions. This is related to the fact that our project generates a lot of invalid pipelines (which we are also working on resolving). If devlake could recognize that the pipeline and its corresponding job have not changed and not collect them again, it would be perfect.

@kyleliu1008 Yes, I understand your point perfectly. However our hands are tied when Gitlab API doesn't support filtering records by `updated` field, the idea of "devlake could recognize that the pipeline and its corresponding job have not changed and not collect them again" is logically impossible, we are simply unable to predict whether or not a `pipeline/job` has been updated without fetching them from the API.  In case you may wonder if we could compare the fetched record against the database before writing to the `_raw_table`, the answer is NO since it would create a cyclic dependency between subtasks which would create problems for #5411 

Anyway, it won't be a problem if we collect only those FINISHED records, which are supported by the Gitlab API by the `scope` parameter. Do you think it is ok for your case?

**Comment by kyleliu1008** [comment]
This would be great as it can prevent repeatedly collecting Jobs that have not been completed (with the status of "created", "manual", "skipped"). Will it also have no impact on metrics?

I found that archived jobs are also being collected.
![image](https://github.com/apache/incubator-devlake/assets/29494039/f020adcb-a792-4c6f-8be5-8358f213acc4)
![image](https://github.com/apache/incubator-devlake/assets/29494039/e689335c-70f5-422f-a39d-9529249729f8)
The details returned by the archived job include the artifacts_file information.

**Comment by klesh** [comment]
interesting, what does "archived" mean? why shouldn't they be collected?
cc @Startrekzky
