### ISSUE TITLE
[Bug][devlake] devlake cannot connect to the database after upgrading

### ISSUE THREAD

**Issue by DOITMY** [apache/devlake#5494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Initial version
![5ffe2770f5d6bd44c9fa31f15f4c8d4](https://github.com/apache/incubator-devlake/assets/30098615/f385a229-ee04-49cf-bb34-99b86eb0ea65)

DevLake quited automatically very often. I updated to v0.17.0-beta11 based on the suggestions from the community.
![image](https://github.com/apache/incubator-devlake/assets/30098615/edf28a0f-e01c-485c-b816-316b7fab80d9)

Now it can not start or connect to the database. See the errors below:
![image](https://github.com/apache/incubator-devlake/assets/30098615/988e3fcd-f316-4706-a040-9e1b0c8fb528)

### What do you expect to happen

Please help debug this problem.

### How to reproduce
N/A

### Anything else

1

### Version

v0.17.0-beta11

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Please check if your `mysql` instance can be connected first.
