### ISSUE TITLE
[Feature][framework] Check deletable before deleting connection/scope

### ISSUE THREAD

**Issue by mindlesscloud** [apache/devlake#5503]
### Definition:
> A scope is considered "deletable" if it is not referenced by any blueprint. Similarly, a connection is "deletable" if all scopes associated with it are deletable.

To ensure data integrity, we need to perform a deletable check before deleting scopes or connections. However, if the user simply wants to clear the data, we won't perform this check.

### Delete Scope
When attempting to delete a scope, the following steps should be followed:

If the scope is not deletable, we should not delete it. Instead, return a status code 409 (conflict) along with the following JSON body:
```json
{
  "projects": [
    "projectName1",
    "projectName2"
  ],
  "blueprints": [
    "blueprintName1",
    "blueprintName2"
  ]
}
```
### Delete Connection
When attempting to delete a connection, the process should be as follows:

If the connection is deletable, remove all scopes associated with it and then delete the connection itself.
If the connection is not deletable, we should not delete it. Instead, return a status code 409 (conflict) along with the following JSON body:
```json
{
  "projects": [
    "projectName1",
    "projectName2"
  ],
  "blueprints": [
    "blueprintName1",
    "blueprintName2"
  ]
}
```
By following these guidelines, we can ensure that only deletable scopes and connections are removed, and conflicts are properly handled by returning the appropriate status codes and JSON bodies.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
The criteria for whether a data scope or connection is deletable is:
- when a data scope/connection is not referenced by any project or blueprint, it's deletable.
- when a data scope/connection is referenced by one or more projects or blueprints, it's not deletable.

A special case: 
- `connection_1` has `scope-1` and `scope-2`. 
- `connection_1` is added to `project-1`, but only with `scope-1`. 
- `project-1` has been run to collect data from `scope-1`.

Question 1 - Can we delete `scope-1` in `connection-1`'s detail page?
No.

Question 2 - Can we delete `scope-2` in `connection-1`'s detail page?
Yes.

Question 3 - Can we delete `connection-1`?
No.

Question 4 - How can I delete the data of `scope-1`
Remove `scope-1` from `project-1` or delete `project-1` first. Then go to `connection-1` and delete `scope-1`.

**Comment by Startrekzky** [comment]
The related prototypes.
![image](https://github.com/apache/incubator-devlake/assets/14050754/e595974b-b774-4740-9ba7-a31e5b8bfe45)

**Comment by Startrekzky** [comment]
> Is this for v0.19?

No, it's for v0.18. This has caused a bug for v0.18, if a user visited a project that referenced a deleted connection or data scope, the page throws an error. Do you have time to work on this?

![image](https://github.com/apache/incubator-devlake/assets/14050754/750050ec-0b3e-4b6b-918e-12f90cfb06ef)

**Comment by keon94** [comment]
Yes, I might need a couple of days for this one.

**Comment by keon94** [comment]
@Startrekzky I am not exactly clear on "if a connection is deletable, remove all of its scopes, then the connection". If you mean, the UI should do that, then yes it's doable because the UI will have access to the list of scopes in the connections page already. But we can't automate that in the backend without massive code changes.
