### ISSUE TITLE
[Feature][AzureDevops] Support Issue tracking Data Model

### ISSUE THREAD

**Issue by alexvaccaro** [apache/devlake#5505]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Users of Azure DevOps are likely to use Azure Boards which comes as part of Azure DevOps to track work and therefore issues/stories/etc. that are used for DORA metrics

### Description

Support the Issue tracking Data Model on Azure DevOps

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Thanks for the feature request, can @Startrekzky  @CamilleTeruel  take a look at it?

**Comment by Startrekzky** [comment]
Collecting votes for this feature.
