### ISSUE TITLE
[Feature][Jira] Add Resolution Field to Domain Layer Issues Entity for Jira Source Type

### ISSUE THREAD

**Issue by narrowizard** [apache/devlake#5507]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a user of DevLake, I want to have the resolution field available in the domain layer issues entity when the source type is Jira, so that I can analyze and visualize the resolution status of issues in my engineering analytics.

### Description

Currently, the domain layer issues entity does not include the resolution field, which is an important piece of information for understanding the status of issues in Jira. This feature request aims to add the resolution field to the domain layer issues entity and populate it when the source type is Jira.

To implement this feature, the following steps should be taken:

1. Update the domain layer schema to include a new field called "resolution" in the issues entity. This field should be a string type to accommodate the various resolution statuses that can be present in Jira (e.g., Fixed, Won't Fix, Duplicate, etc.).

2. Modify the data transformation process to map the resolution field from the Jira tool layer schema to the domain layer schema when the source type is Jira. This may involve updating the ETL (Extract, Transform, Load) process or any other data transformation logic used in DevLake.

3. Ensure that the resolution field is populated correctly in the domain layer issues entity when the source type is Jira. This may require testing with different Jira projects and issue types to verify that the resolution field is accurately captured and transformed.

4. Update any relevant documentation and user guides to reflect the addition of the resolution field in the domain layer issues entity.

By adding the resolution field to the domain layer issues entity and populating it when the source type is Jira, users of DevLake will be able to gain more insights into their engineering processes and make data-driven decisions for improving their development workflows.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
- [ ] Add a `resolution_reason` field to table.issues
- [ ] Add a `resolution_reason` field to _tool_jira_issues
- [ ] For jira plugin, the value of resolution_reason should be extracted and transformed from `fields.resolution.name` in table _raw_jira_api_issues.
![image](https://github.com/apache/incubator-devlake/assets/14050754/1833f636-95c1-4419-ab0e-f1afaa1ad490)

[TBD] I'm still investigating if there's resolution_date for Zentao and TAPD
