### ISSUE TITLE
[Refactor][Framework] Unify Helpers into a single one

### ISSUE THREAD

**Issue by keon94** [apache/devlake#5519]
## What and why to refactor
What are you trying to refactor? Why should it be refactored now?
Unify ConnectionHelper, ScopeConfigHelper and ScopeHelper into a single Helper. Have the plugin interface expose a getHelper() function that returns an instance of this helper. This will make life easy. We will have access a plugin's helper from anywhere in the code given its name.

## Describe the solution you'd like
How to refactor?
Mentioned above

## Related issues
Please link any other

**Comment by klesh** [comment]
Nice, I would prefer the new helper to be called `DataSourceHelper`.

**Comment by keon94** [comment]
@klesh looks like this is done? Can we close it?

**Comment by klesh** [comment]
@keon94 Thanks for asking. There are a couple of plugins left to be updated, I will close it when done.
