### ISSUE TITLE
[Bug][Data Deletion] Not all associated entities are deleted after deleting a data scope

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#5534]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When deleting a Jira board, the data in the following entities are not deleted:
- [x] `boards` @keon94 
- [x] `issue_assignees`. Fixed in PR #5537 
- [x] `_tool_jira_boards` This is caused by the _raw_data_params value in this entity
![image](https://github.com/apache/incubator-devlake/assets/14050754/b58f3cbf-302b-4516-85ef-44a3bf1cdc66)
- [x] `_tool_jira_issue_comments`
- [x] ...

When deleting a TAPD board, the data in the following entities are not deleted:
- [x] `boards` @keon94 
- [x] `_tool_tapd_story_statuses`
- [x] `_raw_tapd_api_bug_statuses`
- [x] and more 

When deleting a Jenkins board, the data in the following entities are not deleted:
- [x] `cicd_scopes` @keon94 

### What do you expect to happen

Delete all associated entities after the data deletion

### How to reproduce

N/A

### Version

v0.18.0-alpha7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
All scope entities should be checked since they were created by `config-ui` so they don't have `_raw_data_params` field.

**Comment by keon94** [comment]
@klesh @Startrekzky All the associated PRs with this issue have been merged, so you can restart/resume testing.

**Comment by Startrekzky** [comment]
@keon94  I'll do. Thanks

**Comment by Startrekzky** [comment]
Test passed
