### ISSUE TITLE
[Bug][pluginhelper] Data Deletion may cause collateral damage

### ISSUE THREAD

**Issue by klesh** [apache/devlake#5535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

During investigation of #5534 , I notice the following logic
https://github.com/apache/incubator-devlake/blob/8f8edfc2a02b114160470fe68fad6f1dee3490fb/backend/helpers/pluginhelper/api/scope_generic_helper.go#L627

Seems like we are deleting records from all tables by examining the `raw_data_params` only with the `LIKE` clause.

1. `raw_data_params` itself doesn't contain the **plugin name** and **connection id**, which means it may delete records that belongs to other plugins or even connection id
2. `LIKE` clause is fuzzy, it is likely to match records belongs to another scope

### What do you expect to happen

connectionId and pluginName should be included in the SQL, and we should use the exact match `=` instead of `LIKE`

### How to reproduce

...

### Version

b40efa574abbe0530d3cf623cbddb5a3e34bcc7f

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
(1) is a problem, agreed. For (2), LIKE would be needed if we ever have to match on a subset of the JSON, or for backward compatibility purposes if we ever add fields to it in the future. Nevertheless, I can change it to match on exact `=` for now.

**Comment by keon94** [comment]
Here's what it's going to look like now
![image](https://github.com/apache/incubator-devlake/assets/25063936/6c77878b-b619-405b-bd23-a937331ae125)

**Comment by klesh** [comment]
@keon94 we should use exact match "=" for now
If the `plugin` field is to be added, I would prefer to add it as a new column. 
I'm thinking maybe we can add a new field `_plugin`, and fill it  with the `_raw_data_table` field
![image](https://github.com/apache/incubator-devlake/assets/61080/60dd530b-0b02-421f-b124-6d58bb9bbfb3)

But, it is a big migration, we can discuss it later.
Can we utilize the `_raw_data_table` to determine which `plugin` it belongs to ? for now

**Comment by keon94** [comment]
@klesh Well, The way I did it was to add it as a field in _raw_data_params
