### ISSUE TITLE
[Bug][Blueprint] Jenkins connection does not display details - infinite spinner

### ISSUE THREAD

**Issue by pakfur** [apache/devlake#5556]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Added a connection that has a bunch of jobs

![image](https://github.com/apache/incubator-devlake/assets/1521847/9cf0b8f1-cbb3-44dc-bdd0-3fbc4e9e51aa)

There are errors when running the connection.
![image](https://github.com/apache/incubator-devlake/assets/1521847/85524c0c-dc5c-44c0-8386-4228d0607768)

View details infinite spinner, and there are 404 errors for missing Jenkins jobs

![image](https://github.com/apache/incubator-devlake/assets/1521847/4baaee77-4346-40a7-aa2c-dc1cd6197e59)

Logs attached:
[logging.tar.gz](https://github.com/apache/incubator-devlake/files/11850118/logging.tar.gz)

### What do you expect to happen

Expected the Blueprint connection to succeed and the details to be displayed.

### How to reproduce

This connection uses 125 scopes. Another Jenkins connection uses one connection scope and displays the detail OK. 

### Version

0.17-beta12

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Needs to cherrypick to v0.17

**Comment by mintsweet** [comment]
hi, @pakfur.
I need to check which of the 125 scopes caused the issue, so Could you please provide the return value of these APIs?

**Comment by Startrekzky** [comment]
According to the feedback from a user, this problem disappeared in v0.18. Please upgrade to the latest v0.18 version and test it out. Thanks.
