### ISSUE TITLE
[Feature][Dashboards] Coding speed and project sizes dashboard

### ISSUE THREAD

**Issue by rusinikita** [apache/devlake#5567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

- As a technical leader, I want to find bottlenecks, visually explore code quality problems, and prioritize technical debt.
- As a developer, I want to find areas for code quality improvement and prioritize technical debt.
- As an organizational leader, I want to see detailed aspects of development and compare teams' efforts.

## Motivation

1. DevLake already has entities for tracking changes in code lines and a [demo dashboard](https://devlake.apache.org/livedemo/EngineeringLeads/GitextractorMetricsDashboard) that utilizes them.
2. There are closed-source tools that provide various visualizations of code metrics for prioritizing technical debt. For example, [codescene](https://codescene.com/for-architects-and-technical-leaders).

I think we should try to provide ready-to-use powerfull dashboards for gathering code insights and provide instructions.

I created a [dashboard prototype with SQLite and ECharts](https://github.com/rusinikita/devex). I believe that some of the graphics can be recreated in Grafana.

## Value

The team's goal is to plan and deliver features and improvements. In this case, the best solution is changes without coding.

The team can identify problems and set goals to decrease the codebase and automate repetitive work, and then track progress measured in code lines or code lines per month.

## Main metrics

- Package/file change speed (code lines per month) for insights on hot software parts.
- Package/file changes per author for insights on bus factor and knowledge keepers.
- Project file sizes.

## Goal

- The ability to compare different repositories/projects is critical for architects and technical leaders.
- The ability to easily filter out unimportant content (generated files, tests, not code).

## Changes

- Add a new "out of the box" dashboard named "Code Insights."
- Add a live demo similar to [this](https://devlake.apache.org/livedemo/EngineeringLeads/GitextractorMetricsDashboard).
- Add documentation for the new metrics [here](https://devlake.apache.org/docs/Metrics).
- Add a dashboard link to the existing metric documentation ([1](https://devlake.apache.org/docs/Metrics/AddedLinesOfCode), [2](https://devlake.apache.org/docs/Metrics/DeletedLinesOfCode)).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@rusinikita Nice, the dashboard you created looks greate, I like it
@hezyin @Startrekzky Looks interesting, would you take a look and comment.

**Comment by Startrekzky** [comment]
Looks good. I'm particularly interested in quality and tech debt metrics. In contrast, we should be careful about performance metrics as they might discourage developers.

**Comment by rusinikita** [comment]
@Startrekzky Yes, the documentation must include warnings that it is not a team performance or efficiency metric. It is only for coding problem insights.

Could you give me advice on how to provide this feature? Where should I look to change the documentation and dashboards?

**Comment by Startrekzky** [comment]
@rusinikita 
1. You need to start from your team's own use cases and think about what coding problems you and your colleagues might have. 
2. After you have figured out the problems you have in mind. You can start thinking about what `metrics` can be used to quantify the problem. DevLake already supports a list of [engineering metrics](https://devlake.apache.org/docs/Metrics).
3. You can refer to the [domain data model](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema) to measure your own metrics.
4. Add dashboard(s) to visualize the metrics following [this Grafana guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide).
