### ISSUE TITLE
[Bug][framework] subtasks seem to get stuck forever

### ISSUE THREAD

**Issue by mindlesscloud** [apache/devlake#5569]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

subtasks seem to get stuck forever
![image](https://github.com/apache/incubator-devlake/assets/8455907/7dd21a99-4064-43de-bdca-bad4d82d8db0)

### What do you expect to happen

Task execution should succeed or fail and should not get stuck

### How to reproduce

- setup DevLake@v0.18.0-alpha10
- create a blueprint to collect data from Jira
- run the blueprint

### Version

v0.18.0-alpha10

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@vaidik The bug of the issue was found in a `dev` version which means it is unlikely to be related to your problem.
It would be better for you to file another issue and describe the plugin and task that are having the problem, thanks.
