### ISSUE TITLE
[Bug][TAPD] The tapd scope in blueprint cannot be selected normally

### ISSUE THREAD

**Issue by mintsweet** [apache/devlake#5571]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The tapd scope in blueprint cannot be selected normally.

![screenshot-20230626-172614](https://github.com/apache/incubator-devlake/assets/37237996/8680e4fc-b56f-4894-88d3-956e5404dd5c)
![screenshot-20230626-172621](https://github.com/apache/incubator-devlake/assets/37237996/b434f09d-969e-4fea-96b5-2530303ca430)

### What do you expect to happen

The tapd in blueprint can be selected normally.

### How to reproduce

1. create a tapd connection.
2. add some remote scope in that connection.
3. create a project or a blueprint.
4. add that connection in blueprint

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@klesh Is this issue already fixed by #5576 ?
