### ISSUE TITLE
[Feature][Linear] Support Linear.app as a data source

### ISSUE THREAD

**Issue by arnaudlimbourg** [apache/devlake#5579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I would love to see support added for linear.app as a data source.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Collecting votes. It'll be great if you can also tell us more about your use cases of Linear and the metrics you want to measure.

We'll consider doing it if more users with specific metric needs want this feature.

**Comment by brunoferreira** [comment]
Would love integration with Linear.
