### ISSUE TITLE
[Bug][Dashboard] The value of 'Percentage of Coding Days Each Month' is 100% for months without coding

### ISSUE THREAD

**Issue by zhoulixiandevlake** [apache/devlake#5588]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

This project finished in March 2023, but the value of 'Percentage of Coding Days Each Month‘ is 100% for the months of April, May, and June in 2023."　
![image](https://github.com/apache/incubator-devlake/assets/136300268/2ebb48a3-ead8-4737-87e1-e306ea70fe57)

### What do you expect to happen

This project finished in March 2023, so the value of 'Percentage of Coding Days Each Month' should be 0% for the months of April, May, and June in 2023."　

### How to reproduce

As recorded in 'What happened’

### Version

v0.17.0-beta11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@zhoulixiandevlake  Is this panel in the dashboard 'Engineering Overview'? You can click `edit` to see the SQL to get the data, which looks like below:
```
with _commits_groupby_name_and_date as (
  select
    author_name,
    date(authored_date) as _day,
    count(*)
  from
    lake.commits c
    join lake.repo_commits rc on c.sha = rc.commit_sha
    join project_mapping pm on rc.repo_id = pm.row_id
  where
    pm.project_name in ($project) and
    (WEEKDAY(authored_date) between 0 and 4)
    and $__timeFilter(authored_date)
    and authored_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)
  group by 1,2
)

select
  DATE_ADD(_day, INTERVAL -DAY(_day)+1 DAY) as time,
  100*count(*)/(count(distinct author_name) * count(distinct _day)) as working_days_percentatages_per_month
from _commits_groupby_name_and_date
group by time
```

Please check if there're commits in the repo(s) configured in this DevLake project that are authored after March.
