### ISSUE TITLE
[Bug][Dashboard] The count of 'PRs Opened/Merged' and 'PRs Merged over Month' are different.

### ISSUE THREAD

**Issue by zhoulixiandevlake** [apache/devlake#5590]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The count of 'PRs Opened/Merged' and 'PRs Merged over Month' are different.
The count of 'PRs Opened/Merged' appears to be closer to the correct value, but it is still not accurate.
![image](https://github.com/apache/incubator-devlake/assets/136300268/178ab866-c690-484e-be9a-9dabc151dc19)
![image](https://github.com/apache/incubator-devlake/assets/136300268/620fde79-dfdd-4bb0-8a9f-21bf901c53f8)

### What do you expect to happen

I hope to obtain the accurate count for the statistics.

### How to reproduce

It seems to be happening consistently

### Version

v0.17.0-beta11

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoulixiandevlake** [comment]
The values for these two views are also not consistent
![image](https://github.com/apache/incubator-devlake/assets/136300268/93f1c154-eabb-43c6-af97-367684d5fbea)
![image](https://github.com/apache/incubator-devlake/assets/136300268/e737ceba-894e-4014-8647-90d1920f92c1)

**Comment by Startrekzky** [comment]
Hi @zhoulixiandevlake ,

1. The 'PRs Opened/Merged' in the dashboard 'Engineering Throughput and Cycle Time' measures the `The number of merged PRs of all PRs created within the timeframes`
![image](https://github.com/apache/incubator-devlake/assets/14050754/24cc89b3-b8fa-4459-beaa-3bb28538f7dc)

While the 'PRs Merged over Month' in the dashboard 'Engineering Overview' measures the `The PRs get merged within the timeframes`
![image](https://github.com/apache/incubator-devlake/assets/14050754/b6606e64-411e-4e98-8d48-d86889f25648)

2. 'PRs Merged w/o Review' shares the same logic with 'PRs Opened/Merged' as these two panels are in the same dashboard.
![image](https://github.com/apache/incubator-devlake/assets/14050754/d38f9419-575a-4a99-b9f9-13e8f5457507)
