### ISSUE TITLE
[Bug][Config-UI] The tab state cannot be maintained when jumping to the page

### ISSUE THREAD

**Issue by mintsweet** [apache/devlake#5599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

the tab state cannot be maintained when jumping to the page.

![image](https://github.com/apache/incubator-devlake/assets/37237996/9447f7ed-14b7-430f-9644-1a8c06f91036)

### What do you expect to happen

the tab state can be maintained when jumping to the page.

### How to reproduce

1. create a project/blueprint.
2. add a connection to it.
3. click the button `collect data`.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Here are some scenarios that come to mind.

1. from projects/list go.
2. collect data.
3. update blueprint name.
4. update sync policy.
5. add a connection.
6. re-transform data.
7. collect all data.

**Comment by Startrekzky** [comment]
@mintsweet I edited the above cases and the target tab in BP. Overall, the tab to jump depends on what users have done and will do next step. 

For instance, if a user clicks `collect data`, he/she would like to see the progress of the pipeline. If a user enters a project after creation, he would like to `add connections`.
