### ISSUE TITLE
[Feature][PagerDuty] Add data source dashboard for PagerDuty

### ISSUE THREAD

**Issue by hezyin** [apache/devlake#5605]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

PagerDuty support is added in v0.17. We should add a data source dashboard for PagerDuty so users can browse PagerDuty data after collection. Since most PagerDuty data lives in `issues` table in the domain layer as of now, the dashboard can re-use panels from other data source dashboards in the issue management domain.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
What additional metrics do they want other than those from other dashboards?
