### ISSUE TITLE
[Feature][blueprint] Add blueprint execution notification

### ISSUE THREAD

**Issue by robgutsopedra** [apache/devlake#5636]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

After _months_ of blueprint executions working flawlessly, they started "partially failing" for reasons which are not important for this issue, arriving to this: 
![image](https://github.com/apache/incubator-devlake/assets/101654801/1682ec71-0be4-4a76-89f0-bfecacffa61e)
At first glance, everything is more or less green, but:
Almost everything failed: 
![image](https://github.com/apache/incubator-devlake/assets/101654801/63ff7598-5411-4d7c-9899-d7d5ddbe2bcb)

vs
Almost everything worked
![image](https://github.com/apache/incubator-devlake/assets/101654801/b77f3778-75a9-45c2-a63b-00b4246d8f67)

I just realized something was wrong because I was missing some data in Grafana - but blueprint execution provides little to no info regarding the _actual_ execution. 

Bigger projects require more detailed info. 

### Description

I'd love to:
1. Have more visual direct information of what "partially" means after a blueprint execution
2. Be able to define what "partial success" means on each project. Maybe on a project with 100 repos I can tolerate 5 failures on a random execution, but not 99. 
3. Receive a notification - slack would be perfect - with some basic information on the run. 

With any of these three, my life would get much better. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@robgutsopedra Thanks for reporting the issue. I'll think about it.

**Comment by klesh** [comment]
Maybe we can let Grafana do the work since it has notification and it can access the `_devlake_tasks` for failed tasks.
