### ISSUE TITLE
[Feature][Config UI] Add transform-box-styled UI to "Select Data Scope"

### ISSUE THREAD

**Issue by yumengwang03** [apache/devlake#5640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For improved user experience, we would like to do an adjustment for the UI of selecting data scope as shown in the following screenshot:
<img width="1506" alt="Screen Shot 2023-07-06 at 5 22 01 PM" src="https://github.com/apache/incubator-devlake/assets/9535430/6b200113-48a1-4b0f-a453-445a5956a303">
<img width="829" alt="Screen Shot 2023-07-06 at 5 22 22 PM" src="https://github.com/apache/incubator-devlake/assets/9535430/0cf65cda-9e90-48b8-ad45-4082146b1be2">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
There're three types of plugins in terms of data scope selection:
1. GitHub - support the keyword search and the adjustment of the scope
![image](https://github.com/apache/incubator-devlake/assets/14050754/0c635bd6-487e-4b88-a8c5-51073a583810)

2. GitLab/Azure DevOps/BitBucket/Bamboo/Jira/TAPD - support the keyword search, but doesn't support the adjustment of the scope
![image](https://github.com/apache/incubator-devlake/assets/14050754/f0aef874-5852-457b-8d2f-2047f3a34783)


3. Jenkins - doesn't support the keyword search or the adjustment of the scope
![image](https://github.com/apache/incubator-devlake/assets/14050754/9811bc54-e1e4-472d-aade-d003e2e5c391)

**Comment by mintsweet** [comment]
TAPD is not supported yet.

**Comment by abeizn** [comment]
@keon94 Could you assist with implementing support for the Azure DevOps API's search-remote-scopes feature?

**Comment by keon94** [comment]
@abeizn I believe we investigated this when we implemented Azure and they didn't have a search API for repos. You can only get the list of all of them for a given project. cc @CamilleTeruel
