### ISSUE TITLE
[Refactor][Auth] Not returning the tokens or passwords on APIs

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#5643]
## What and why to refactor
What are you trying to refactor? Why should it be refactored now?

On the Connections Admin form, we can add tokens to access the tools, but those Tokens are returning in the API openly with no necessity and compromising the security of it.

The reason is in the companies where DevLake will be used, not all DevLake Admin are able to have full read-only access to those tools, but as we return it from the API side, it is available for them.

## Describe the solution you'd like
How to refactor?

Not returning the tokens or passwords on APIs, it should be treated as one way only, as soon it is saved on the DB just going to be updated if required by the interface.

## Related issues
Please link any other

**Comment by Startrekzky** [comment]
We need to support this before DevLake v1.0 as it's a major security risk.
