### ISSUE TITLE
[Feature][Migrations] Migrations of _raw_data_params to support scopes (pre v0.15)

### ISSUE THREAD

**Issue by keon94** [apache/devlake#5644]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Older versions of Devlake (prior to v0.15) only wrote the ConnectionId to _raw_data_params. Identify the plugins that have been supported prior to the introduction of scopes and write migrations that populate their raw, tool and relevant domain tables. This may be quite a lot of work, and we should evaluate whether it is worth doing.

Edit: After discussions, the scope of this effort will be limited to just performaing this migration for scope and domain-scope tables, and leaving the other tables out.

### Description

PR: #5606 

### Related issues

#5598 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
In these old versions, Connections and Scopes had a 1:1 relation. Plan of attack should be like this: For each plugin's data record, use the ConnectionId to look up that plugin's tool-scope table by that ID. That should give us the Scope we're looking for. Go back to that data record, and write this Scope's Id to its _raw_data_params field.
For domain tables, use the domain-ID's ConnectionId+PluginName to determine the appropriate records, and adjust their _raw_data_params with the ScopeId.

**Comment by keon94** [comment]
After internal discussions, it'll be sufficient to just cover the scope and domain-scope tables.

**Comment by klesh** [comment]
According to the discussion, I think we can close this issue, right?

**Comment by keon94** [comment]
Let's just close it with the PR. I've linked it there.
