### ISSUE TITLE
[Feature][Schema] Pluggable Metrics Exporter

### ISSUE THREAD

**Issue by saada** [apache/devlake#5654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a devops engineer, I would like to support other metrics storage solutions such as Datadog or Prometheus or Mimir. 

### Description

Currently it looks like the design of DevLake revolves around the [DomainLayerSchema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#schema-diagram).

Being able to consolidate various visualization from Datadog along with DORA metrics would be a powerful enabler for software teams.

Thanks DevLake team!

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Do you want to:
1. get the data from Datadog or Prometheus
2. OR design more engineering metrics based on your own SDLC practices?

**Comment by Startrekzky** [comment]
Hi @saada , may I ask what specific Datadog metrics do you want to measure?

**Comment by saada** [comment]
The list of metrics is shown in the [official docs](https://devlake.apache.org/docs/Metrics).
If someone wants to use an alternative to Grafana like Datadog, they need to store these metrics in Datadog.

**Comment by Startrekzky** [comment]
@saada Got it. Any updates about this?

**Comment by saada** [comment]
No updates. Still hoping we can support Datadog as an external metrics provider for DevLake
