### ISSUE TITLE
[Bug][Gitlab Blueprint] Sync gitlab data subtask fail

### ISSUE THREAD

**Issue by EvanChen1989** [apache/devlake#5657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

During syncing gitlab data, many subtask(about 15%) failed. And even I try to rerun failed tasks, there's always some failed subtasks so the total status is always "partial success". It would cause data missing during analysis.

<img width="1489" alt="image" src="https://github.com/apache/incubator-devlake/assets/29242240/25749024-4387-477d-8a9d-aa4f2af13b41">

### What do you expect to happen

sync successful for all project.

### How to reproduce

select multiple projects (more than 20, in our case it's about 200+) in gitlab blueprint and trigger the sync.

### Version

v0.17.0-beta4@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@EvanChen1989 Thanks for the report, can you attach the log for investigation?

**Comment by EvanChen1989** [comment]
[logging-20230717.tar.gz](https://github.com/apache/incubator-devlake/files/12195464/logging-20230717.tar.gz)

@klesh Didn't see much error here... we're still suffering from this behavior, need to check these sync jobs from time to time and click the 'retry failed tasks'...

**Comment by klesh** [comment]
@EvanChen1989 Sorry for the late reply, I checked the log and it was empty... so, no way can tell what was wrong...
Can you try updating to the latest version `v0.19.0-beta2` and see if it was fixed?

**Comment by EvanChen1989** [comment]
@klesh Sorry didn't visit github very often. I've figured out the problem -- memory issue. The process was terminated so quick so RDS monitor didn't  even show memory usage increase and the job get killed. After increase the memory to 16G the situation becomes better.

-- but I'm still getting unstable failure during the sync job. Will attach new logs if there is any.

**Comment by klesh** [comment]
@EvanChen1989 No problem, any time.
