### ISSUE TITLE
[Bug][Dashboard] Some panels in `Component and file-level metrics` dashboard show no data

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#5675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/incubator-devlake/assets/14050754/8c8a6317-7dad-49fb-b4e3-c3aab8990b54)

It seems to be caused by this piece of SQL
![image](https://github.com/apache/incubator-devlake/assets/14050754/b96388b8-f373-4be0-9ff0-8dd135e65720)

### What do you expect to happen

Show data

### How to reproduce

-

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
repo_snapsuhot exists, but no data

**Comment by abeizn** [comment]
@Startrekzky Not a bug, the subtask collectDiffLine EnabledByDefault = false. The users need run it in advanced mode. Or we update EnabledByDefault from false to true. 
![image](https://github.com/apache/incubator-devlake/assets/101256042/df824e9d-594c-423f-86c5-859d4f2a9ba5)

**Comment by Startrekzky** [comment]
Thanks @abeizn , I'll close it for now.
