### ISSUE TITLE
[Bug][Dashboard] `Engineering Throughput and Cycle Time - Team View` shows no data

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#5676]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/incubator-devlake/assets/14050754/4d862ff1-9646-48bf-a351-4cd5c5eb6925)

It seems to be cause by this:
![image](https://github.com/apache/incubator-devlake/assets/14050754/c142e949-5f47-491b-9c0c-bc63052d88bc)

### What do you expect to happen

Show data

### How to reproduce

Install v0.18.0-beta1 and configure teams

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
This is not a bug caused by data collection, I have turned it off.
