### ISSUE TITLE
[Feature][Jira Transformation] Support to incident tickets using status transition

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#5679]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

In my process, we use one Jira ticket to control the incidents, and we have some status to control it.
When an incident is happening we have a status called "In Progress", and when the incident is mitigated from production we still use the same ticket to aggregate all the improvements related to it, and for it, we keep the ticket as "Investigating/Implementing Solutions", then we finish this incident just when we have all the propose improvements in place.

We want to use DevLake to measure the incident time based on open status changes from one ticket and not just based on if that status is closed or open like supports now.

### Description

I believe we could have the option to select from what status to what status we want to determine if that incident was closed.

### Related issues

No.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @msarzijr , thanks for the proposal. I'll think about it.
