### ISSUE TITLE
[Bug][Blueprints] Config-UI’s failure in handling large GitHub org

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#5680]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I tried to select many repos the UI gave me this error: 
![image](https://github.com/apache/incubator-devlake/assets/17132893/c38d6f60-5483-4b10-9ded-90ccb1e3117b)

### What do you expect to happen

Be able to select as many repos as I need.

### How to reproduce

I believe we need to increase the limits, or make a interface where we can easily set increase them.

### Version

v0.16.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
hi, @msarzijr. Thanks for your report.
Could you please provide this data to help me to reproduce this issue?
Or you can also try upgrading to a newer version.

**Comment by msarzijr** [comment]
I am sorry for the long time, and I am using the v0.19 beta 1 and I will try again.

**Comment by klesh** [comment]
Would you mind sharing a screen-recording video for further investigation if the problem persists? Thanks
