### ISSUE TITLE
[Bug][Webhook] 0.18-beta1 Can't Delete Webhook

### ISSUE THREAD

**Issue by awickham10** [apache/devlake#5682]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When deleting a webhook I get an error saying the plug doesn't implement PluginSource. There is a 500 in the logs, but no other valuable information, even when setting log level to debug.

```
[GIN] 2023/07/17 - 19:03:11 | 500 | 5.129992ms | 10.138.35.36 | DELETE "/plugins/webhook/connections/2"
```

### What do you expect to happen

Delete the webhook.

### How to reproduce

Delete the webhook through the UI.

![image](https://github.com/apache/incubator-devlake/assets/7840633/857be61e-3a05-45f8-89e4-05b09964fe4d)

### Version

v0.18-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
Thanks for your feedback. I will take a look and try to fix it.
