### ISSUE TITLE
[Bug][Azure DevOps] Cannot Associate Scope Config

### ISSUE THREAD

**Issue by awickham10** [apache/devlake#5698]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When trying to associate a scope config to a connection, I get an error.

![image](https://github.com/apache/incubator-devlake/assets/7840633/b36ca2f5-08ad-4965-8355-d5c6177114a3)

```
time="2023-07-18 17:02:51" level=error msg="HTTP 404 error
caused by: error retrieving scope with scope ID undefined (404)
Wraps: (2) could not get scope (404)
Wraps: (3) record not found (404)
Wraps: (4) record not found
Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *errors.errorString"
```

### What do you expect to happen

The scope to be able to associated.

### How to reproduce

Try to associate a scope config to a connection.

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
hi @awickham10, thanks for your report.
@CamilleTeruel Can you check this issue?
