### ISSUE TITLE
[Bug][GitHub] Fail to add public repos to a GitHub connection

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#5721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

It threw a 500 error.

![563b41ee-c555-4886-860a-5f6e3aed96e0](https://github.com/apache/incubator-devlake/assets/14050754/f7c5ab1e-8280-45d5-b9d7-5fe1fc73583a)

![image](https://github.com/apache/incubator-devlake/assets/14050754/6a94a54b-8855-492a-83f8-7f6a5e06a461)

### What do you expect to happen

1. Successfully added the public repos. 
2. Plus, it's better to show the repos with the namespace. Otherwise, it's hard to tell whether I have added the right repos.
![image](https://github.com/apache/incubator-devlake/assets/14050754/2f4c0637-1b35-40d5-9e77-15d0dc285368)

### How to reproduce

1. Install DevLake v0.18.0-beta1
2. Create a GitHub connection
3. Add public repos and save

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Seems like the database is using the wrong collation setting
![image](https://github.com/apache/incubator-devlake/assets/61080/03fe5574-c9ae-446f-aa81-be95f9727c5d)

**Comment by ZhangNing10** [comment]
hi @Startrekzky are you using an external mysql db? kindly take care of the charset and colllation of the db, should be utf8mb4 and utf8mb4_bin.
you can create the db like below:
CREATE DATABASE IF NOT EXISTS lake DEFAULT CHARSET utf8mb4 DEFAULT COLLATE utf8mb4_bin

**Comment by Startrekzky** [comment]
@ZhangNing10 Thanks. I'll close it.
