### ISSUE TITLE
[Doc][Github] Settings for Github App configuration

### ISSUE THREAD

**Issue by jluque0101** [apache/devlake#5723]
## Documentation Scope
https://github.com/apache/incubator-devlake-website/blob/main/docs/Configuration/GitHub.md

## Describe the Change
Improve GitHub configuration when using GitHub App.

## Additional context
I am trying to configure GitHub integration by using GithubApp but I am finding some difficulties, Devlake version is **v0.18.0-beta1**.

I inferred configuration from comments in [PR #5077](https://github.com/apache/incubator-devlake/pull/5077).

Connection seems to be working but when trying to add Data scope it is not able to fetch Organizations/Owners, wheel keeps rolling. from logs I see:
```
devlake-lake-8f8fd59cf-f8j7z lake 	caused by: error decoding response from https://api.github.com/user/orgs?page=1&per_page=100: raw response: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/orgs/orgs#list-organizations-for-the-authenticated-user"}"
```

I am able to see in UI `installationId` once I add `appId` and `Private key` therefore test connection button also works.
My Github app is installed at org level with the following permissions:

- Actions: Read only
- Contents: Read only
- Issues: Read only
- Metadata: Read only
- Pull requests: Read only

May you know if I am missing something else or if there is any documentation around this? I couldn't find it so far. Thanks a lot!

**Comment by klesh** [comment]
@jluque0101 Seems like the `org` permission is missing... Can you see any related permission from the permissions page?
BTW, would you like to polish the document afterward?

**Comment by jluque0101** [comment]
Hi @klesh , from `org` permissions I see the following items. I believe it refers to organizational settings however I don't see anything related to access the organization information itself.

- Administration: Manage access to an organization.
- Blocking users: View and manage users blocked by the organization.
- Custom repository roles: Create, edit, delete and list custom repository roles.
- Events: View events triggered by an activity in an organization.
- GitHub Copilot for Business: Manage Copilot for Business seats and settings.
- Members: Organization members and teams.
- Organization announcement banners: View and modify announcement banners for an organization.
- Organization codespaces: Manage Codespaces for an organization.
- Organization codespaces secrets: Manage Codespaces Secrets for an organization.
- Organization codespaces settings: Manage Codespaces settings for an organization.
- Organization dependabot secrets: Manage Dependabot organization secrets.
- Personal access token requests: Manage personal access token requests from organization members.
- Personal access tokens: View and revoke personal access tokens that have been granted access to an organization.
- Plan: View an organization's plan.
- Projects: Manage projects for an organization.
- Secrets: Manage Actions organization secrets.
- Self-hosted runners: View and manage Actions self-hosted runners available to an organization.
- Team discussions: Manage team discussions and related comments.
- Variables: Manage Actions organization variables.
- Webhooks: Manage the post-receive hooks for an organization.

Regarding the outcome, I'll be happy to contribute if needed, sure!

**Comment by klesh** [comment]
@jluque0101 I couldn't figure out which permission to grant from the given information.
the API `https://api.github.com/user/orgs` is for fetching the organizations that the token belongs to, so devlake could list all repos for those `orgs` for the user to select from.
Sorry, I'm not familiar with the Github App. Would you like to contact Github and ask them which one to grant?

**Comment by klesh** [comment]
@Feggah Sorry for replying so late, I missed your comment.😂😂
Thanks for the information, will fix it ASAP

**Comment by gespi1** [comment]
when using Github app as the auth, the orgs and owners do not load. Any word when the endpoint update will happen for github apps? 

Luckily found that you can search for them, after hours of troubleshooting lol
