### ISSUE TITLE
[Bug][GitHub] CICD Deployment count does not use job names

### ISSUE THREAD

**Issue by raihle** [apache/devlake#5743]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When viewing DORA metrics (e.g. deployment frequency) for a GitHub repository, it seems only workflow run names that match the deployment/production regex are being treated as deployments, while matching job names are not detected.

After some further experimentation, it seems workflow names are also being detected.

### What do you expect to happen

According to docs / UI both workflow run names and job names should be matched against the regexes, while workflow names are ignored.

### How to reproduce

Set up a GitHub repository with two workflows with one job each:

1. One workflow should set the run-name property to "Deploy to Production"
2. The other workflow should set the job name to "Deploy to Production"

Run the first workflow once, and the second workflow twice.

Import the repository in devlake with DORA metrics enabled, using "Deploy to Production" as the deployment regex (leaving production regex empty).

The Grafana graph for monthly deployments will show 1 (the number of workflow runs matching the regex) instead of 2 (the number of workflow runs with matching jobs) or 3 (the union)

### Anything else

With automatically triggered workflows, the run names are by default based on the message/name of the commit/PR/etc. that triggered them, which is quite nice - but does not reliably identify the environment being deployed to, if any.

Meanwhile, job names are set in the workflow definition, and can be fixed since they do not need to differentiate the workflow run from other runs of the same workflow.

I'm willing to invest some time in this, but I barely understand Go well enough to read it (and in fact haven't found what needs fixing yet).

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for the report, will investigate later

**Comment by klesh** [comment]
Hi, @raihle , I'm investigating the problem, I would like to know what `workflow names`, `workflow run names`, and `job names` you are referring to. Can you take some screenshots and highlight them so we can be on the same page?
Thanks.

**Comment by raihle** [comment]
@klesh I'm using the terms as described here: https://devlake.apache.org/docs/Configuration/GitHub/#cicd

**Workflow name**: The name given to a workflow in the workflow definition file (the top-level `name` property), defaulting to the file path. These are shown in the left-hand list of all workflows when viewing the "Actions" tab of a repository. For this repository (https://github.com/apache/incubator-devlake/actions), that would be for example "Auto Cherry Pick", "Build-BuilderImage-Push-Docker", etc.
<img width="319" alt="image" src="https://github.com/apache/incubator-devlake/assets/985768/029acdc6-af5a-4e68-9d51-2500f93422b4">

**Workflow Run Name**: The name given to a specific workflow run in the workflow definition file (the top-level `run-name` property), defaulting to various different values depending on what triggered the run (can be the workflow name, a truncated commit message, etc.). These are shown in the right-hand list of workflow runs when viewing the "Actions" tab. 
<img width="531" alt="image" src="https://github.com/apache/incubator-devlake/assets/985768/2abb6a46-e498-430f-a901-c703a0735a63">

**Job Name**: The name given to a job inside a workflow definition file (the job-level `name` property), defaulting to the id of the job. These are shown in the left-hand side list and in the right-hand side graph when viewing a specific workflow run (e.g. "Build lake-builder image"): https://github.com/apache/incubator-devlake/actions/runs/3010479662
<img width="330" alt="image" src="https://github.com/apache/incubator-devlake/assets/985768/e980044c-da35-4fd1-96b7-a37ee5ae1aff">
<img width="324" alt="image" src="https://github.com/apache/incubator-devlake/assets/985768/d5f319d7-0c9d-4db0-a00f-65c9378d8b70">

**Comment by abeizn** [comment]
@raihle  
![image](https://github.com/apache/incubator-devlake/assets/101256042/750d9505-8863-40b4-a0ae-919e29bd702a)
"The name of the GitHub workflow run or one of its jobs matches" like this:
![image](https://github.com/apache/incubator-devlake/assets/101256042/5a375e87-c165-402e-9e4c-c8140d04aef1)

It may be that our understanding is different, or our sentence descriptions are inaccurate, leading you to think that some data do not match.

1. GitHub workflow run is executed once and counts as one deployment.
2. As long as one of the job names matches, this run will be considered a deployment.

Finally, group by pipeline_id+commit_sha is used to calculate the number of deployments. 
In the above example, that is ``` Build and Push devlake builder ｜ Build and Push devlake base ｜ Build and Push devlake image```  belongs to one deployment, not 3 times

**Comment by raihle** [comment]
@abeizn In that image, "github workflow run name" is pointing at the workflow name. The workflow _run_ name is "feat(config-ui): support full sync mode (#6200)".

We agree on what job names are, but in my testing they were not matched. There have been a few versions since then so I will try again.

**Comment by abeizn** [comment]
@raihle Sorry for the late reply, I took a few days off. 
Can you look at the data in the cicd_tasks table? When type=DEPLOYMENT, you can observe what is the value of the name field.
I set deployment and production regex to  `Build and Push devlake` (job name)  https://github.com/apache/incubator-devlake/actions/runs/6120227585/workflow
![image](https://github.com/apache/incubator-devlake/assets/101256042/fa8f43c6-496a-45fd-9cea-5a8a6105fd7b)



![image](https://github.com/apache/incubator-devlake/assets/101256042/f61b957c-cf82-4b6a-9703-30aaea59da69)

**Comment by raihle** [comment]
The cicd_tasks table is always empty, even when I can see the deployments in Grafana.

**Comment by abeizn** [comment]
@raihle Thank you. I am also very confused. Could you please collect the _apache/incubator-devlake_ repo and set deployment and production regex to _Build and Push devlake_ (job name)? I'd like to rule out whether it's due to different workflow settings in our repos.

**Comment by raihle** [comment]
Good call, the incubator-devlake project does work as expected! So perhaps this is down to permissions for the access token.

I am using a GitHub app with the following permissions (all read-only):

* Repository
  * Actions
  * Administration
  * Commit statuses
  * Contents
  * Deployments
  * Issues
  * Metadata
  * Pull requests
* Organization
  * Members

As far as I can tell, the access requirements for apps are not documented, and we added everything that seemed relevant. Fine-grained PATs are the closest, and we have all of the permissions listed except for Discussions (a feature we do not use). But I will request access to Checks, Discussions, and Environments, and we'll see if that helps.

**Comment by d4x1** [comment]
@raihle  Thanks for your testing.

I think devlake's document should only list all the neccessary permissions.  + 1

**Comment by abeizn** [comment]
Looking forward to your test reply.

**Comment by abeizn** [comment]
And I also have some conjectures. You can also help me see if this is possible.

For GitHub Actions, the job name can be either the name in the left-hand side jobs list or the name used in the actual running job. It depends on how you define the job in your workflow file.

When you use job_id: or jobs.<job_id>.name: to define a job in the workflow file, that name will be displayed in the left-hand side jobs list.

Example:

jobs:
   build:
     name: My Build Job
In the example above, My Build Job will be displayed as the name in the left-hand side jobs list.

When you use name: to define a step or action within a job, that name will be displayed in the actual running job.

Example:

jobs:
   build:
     steps:
       - name: My Build Step
         run: echo "Building..."
In the example above, My Build Step will be displayed as the name of a step in the actual running job.

The job names can be different for different repositories because each repository has its own workflow file, and you can customize the job names according to your requirements.  

Finally, attach the workflow settings of devlake: https://github.com/apache/incubator-devlake/blob/main/.github/workflows/build.yml

**Comment by raihle** [comment]
Adding the new permissions seems to have worked. Presumably it is "Checks" that made the difference. I will re-run the tests with only that permission added, but it takes some time because our GitHub org admins are quite busy.

**Comment by abeizn** [comment]
@raihle Great, looking forward to your reply.

**Comment by abeizn** [comment]
Hi @raihle, any updates? Please feel free to contact us if you need any help.

**Comment by raihle** [comment]
Sorry for the delay, I can finally confirm that this was resolved by adding "Checks" to the app permissions.

**Comment by abeizn** [comment]
@raihle Thank you very much for your reply, it will be of great help to us.
