### ISSUE TITLE
[Bug][Azure DevOps] Failed to edit the scope config

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#5763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

it threw an error when I edited the scope config of a Azure DevOps connection
![20230727193120_rec_](https://github.com/apache/incubator-devlake/assets/14050754/9b0f7705-e301-4330-8193-c17d32468134)

### What do you expect to happen

Edit the scope config successfully.

### How to reproduce

-

### Version

v0.18.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
This is an issue caused by dirty data, please do not create a scope config without entities.
