### ISSUE TITLE
[Bug][UI] Cannot create Project with slash (/) in name

### ISSUE THREAD

**Issue by Feggah** [apache/devlake#5765]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Before upgrading to 0.18, I was able to create Projects with `/` normally:
![image](https://github.com/apache/incubator-devlake/assets/11353912/d419bd56-dbaf-4960-be3b-62eac4e9d2f7)

After upgrading, I got the following error when trying to create a Project:
![image](https://github.com/apache/incubator-devlake/assets/11353912/e57b5fe7-fbc5-41cd-827d-4e7594c4070c)

Even with this error, the Project appears in the Project list with the name formatted incorrectly:
![image](https://github.com/apache/incubator-devlake/assets/11353912/4912ef10-6cc6-4b32-8054-f0f74c741c84)

If I try to open this created Project, it keeps loading forever:
![image](https://github.com/apache/incubator-devlake/assets/11353912/776e6a1b-118a-4c9f-8510-6ed2adf2ac76)

### What do you expect to happen

Being able to create Project with slashes in the name, because the documentation is:
![image](https://github.com/apache/incubator-devlake/assets/11353912/7b85ff3b-fc5b-455c-9e2c-c678a59399dc)

### How to reproduce

Try to create a Project with slash `/` in name

### Version

v0.18.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks for reporting.
