### ISSUE TITLE
[Bug][UI] Documentation link returned 404 error

### ISSUE THREAD

**Issue by diegotony** [apache/devlake#5766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I have click in documentation button return 404 error
![Captura de Pantalla 2023-07-27 a la(s) 14 58 29](https://github.com/apache/incubator-devlake/assets/11952580/ed7f046b-64e1-4040-8d6d-60d06fd76455)

![Captura de Pantalla 2023-07-27 a la(s) 14 57 54](https://github.com/apache/incubator-devlake/assets/11952580/ad032895-ac86-4986-80db-43e455ffdccd)

### What do you expect to happen

Go to documentation page

### How to reproduce

click in documentation icon

### Version

v0.16.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Another pr to fix it the issue with broken links in config-ui.
