### ISSUE TITLE
[Bug][Azure Devops] Unknown column 'start_time'

### ISSUE THREAD

**Issue by klemen-df** [apache/devlake#5780]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I run 'Collect all data' I get the following error :

Unknown column '_tool_azuredevops_jobs.start_time' in 'field list'

### What do you expect to happen

When I run 'Collect all data' the process should end successfully.

### How to reproduce

Install version 0.17, upgrade to 0.18 and run 'Gather All Data' on Azure Devops.

### Version

v0.18.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
It appears that the fields in the database are not underscored.
![image](https://github.com/apache/incubator-devlake/assets/61080/2eb00aef-9bfe-429e-9925-3b5693af9e59)

**Comment by klesh** [comment]
@keon94 @CamilleTeruel 
I think we need to migrate these fields for v0.17 users:
![image](https://github.com/apache/incubator-devlake/assets/61080/91507196-4b39-42ce-b52d-693023d3a5a1)

**Comment by keon94** [comment]
Let's first port #5785 and #5746 back to both v0.18 and v0.17.

**Comment by klesh** [comment]
@keon94 Will it fix the fields that have already been created? I don't think so, because I was seeing `startTime` and `finishTime`  with the latest code.
