### ISSUE TITLE
[Feature][Azure DevOps] Include Azure DevOps Custom Dashboard

### ISSUE THREAD

**Issue by hollmanenciso** [apache/devlake#5781]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As part of release v0.18 Azure DevOps was included but Custo Dashboard in Grafana is not available.

![image](https://github.com/apache/incubator-devlake/assets/11529240/04153c42-0f3e-4ace-858f-d5b23c3d5e78)

I made some adjustments described by @Startrekzky in Slack and that works perfectly.

1*  Copy GitHub/BitBucket dashboard and save to a new dashboard
2* Go to the dashboard setting - variables, change the SQL of getting the options of Azure's repo_id

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
I'll take it.
