### ISSUE TITLE
[Bug][gitlab]  gitlab connection syncs indefinitely

### ISSUE THREAD

**Issue by MarcViola** [apache/devlake#5783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

A gitlab connection never finishes to collect data.  When the job is successful, it takes about 12 min. to complete.  Every now and then the job runs continuously for days without completing.  The cancel button doesn't cancel the job.  I restart the devlake containers to end it.
Other gitlab jobs run just fine, there seems to be something special with this one.
I thought it was a one-time event but it's been happening a few times now.

### What do you expect to happen

Scan to complete in about 12 min.

### How to reproduce

Create project with a gitlab connection.  Select a number of repositories.  Create a daily schedule.  Monitor job for status.

### Version

v0.17.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MarcViola** [comment]
wrongly closed the issue.

**Comment by klesh** [comment]
@MarcViola Thanks for your report, there were so many tasks, can you point out which task failed/stucked?

**Comment by klesh** [comment]
Seems like the connection to the database had failed. Maybe the mysql container crash for some reason? How about the storage and memeory usage? Can you set up some monitoring mechanism for it?

**Comment by MarcViola** [comment]
The container itself is ok.  Storage is ok.  But I'll setup some monitoring and see what happens to CPU and memory.

**Comment by MarcViola** [comment]
CPU idle and Free mem during the night when data collection is happening. I have disabled the collection of unused projects and will monitor again tonight and see if it makes a difference.  It does look like resources may be a problem at some point.

![image](https://github.com/apache/incubator-devlake/assets/31352762/0c571f18-9b3e-4b5a-9892-3c40275d34db)

**Comment by MarcViola** [comment]
I will add more memory to the VM.  I'll close the ticket for now and re-open if it's still an issue.  Thanks.
