### ISSUE TITLE
[Bug][Azure devops] Can't associate scope config

### ISSUE THREAD

**Issue by klemen-df** [apache/devlake#5802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Using v0.18.0-beta3 (upgraded from 0.17)

I have a connection to Azure devops, test say 'Connected'.

In this project I also have a 'Data scope' associated with this project.

But 'Scope config' for this 'Data scope' says 'N/A'.

When I want to associate a scope config (an existing one) I just get a red square on the top saying 'Operation failed.'.

When I want to edit that scope config (the pencil icon) I get 'TypeError: Cannot read properties of null (reading 'map')'

Any thoughts?

### What do you expect to happen

Scope config should be attached to data scope.

### How to reproduce

Install 0.17, create connection, data scope, scope config, upgrade to 0.18

### Anything else

Sadly nothing in development console or in pod logs

### Version

v0.18.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KlemenDanfoss** [comment]
Hi,

any feedback on this?

**Comment by klesh** [comment]
@CamilleTeruel Can you take a look at the problem? thanks
