### ISSUE TITLE
[Feature][Azure DevOps] Sort Repositories List

### ISSUE THREAD

**Issue by awickham10** [apache/devlake#5821]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As an administrator of the DevLake product, I would like to be able to quickly add a repository to the data scopes. Currently, the list of projects is unsorted making it difficult to locate the repository. It would be nice if the list of projects was sorted alphabetically.

### Description

![image](https://github.com/apache/incubator-devlake/assets/7840633/ecedb4e2-c747-483d-bdfd-f696ee49957b)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mindlesscloud** [comment]
Hi @awickham10 Thanks for your suggestion. It's a good idea to sort the projects list. It can be easily implemented if the response is only one page. But there is a technical difficulty with the list that needs to be paginated. If the API does not support sorting first and then paging, we cannot achieve this only on the front end.

**Comment by neraath** [comment]
This is a challenge for me as well.
