### ISSUE TITLE
[Doc][README] README broken links

### ISSUE THREAD

**Issue by hollmanenciso** [apache/devlake#5842]
## Documentation Scope

The main README has some broken links
[Create an Issue](https://devlake.apache.org/community/make-contribution/fix-or-create-issues):
[Submit a PR](https://devlake.apache.org/community/make-contribution/development-workflow)
[Write a Blog](https://devlake.apache.org/community/make-contribution/BlogSubmission)
[Develop a Plugin](https://github.com/apache/incubator-devlake/blob/main/backend/DevelopmentSetup.md)

## Describe the Change

Update links to the right ones

[Create an Issue](https://devlake.apache.org/community/MakingContributions/fix-or-create-issues):
[Submit a PR](https://devlake.apache.org/community/MakingContributions/development-workflow)
[Write a Blog](https://devlake.apache.org/community/MakingContributions/BlogSubmission/)
[Develop a Plugin](https://github.com/apache/incubator-devlake/blob/main/backend/DevelopmentManual.md)

**Comment by mintsweet** [comment]
Closed by #5836
