### ISSUE TITLE
[Feature][config-ui] Support deletion of projects

### ISSUE THREAD

**Issue by renflo** [apache/devlake#5850]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

1. I want to be able to delete projects

### Description

To my knowledge it's not possible to delete projects today. In my installation i've ended up having 3 that I would like to remove but can't.

![Screenshot 2023-08-10 at 12 30 41](https://github.com/apache/incubator-devlake/assets/231459/415e23cb-9ac7-46ea-a19b-089ae7fb99c3)

Adding support for deletion would be welcome. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Projects can be deleted in the future version. It's on the way.

**Comment by mintsweet** [comment]
Hi @renflo, We don't think deleting a project is a good option, but we still provide this option, you can do it in project settings.

![image](https://github.com/apache/incubator-devlake/assets/37237996/2db43d69-10a6-47e4-9bdd-4a0b3885d676)

**Comment by renflo** [comment]
Oh, good to know, did not notice this option.

**Comment by renflo** [comment]
I guess you can close - i think perhaps the button should be elsewhere because it's not really easy to find, but this can wait for later releases.

**Comment by mintsweet** [comment]
Thank you for your suggestion, we will consider it.
