### ISSUE TITLE
[Feature][config-ui] Offer a screen showing all pipeline executions, regardless of project/blueprint

### ISSUE THREAD

**Issue by renflo** [apache/devlake#5851]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I want to have access to information relative to all pipeline execution, regardless of project/blueprint so I can easily spot which pipelines are failing.

This overview should ideally both allow to navigate to the project itself but even better also have a "re-run" button.

Context here is that I have created 10s of projects in devlake and the number will keep growing. Having to manually navigate to each of them to see if their pipeline is running as it should is very cumbersome.

As an illustrative example the jobs view in gitlab could be a nice "target" in terms of GUI and features.
![Screenshot 2023-08-10 at 12 39 28](https://github.com/apache/incubator-devlake/assets/231459/6dd0a1e0-92ae-4078-9a44-20ab042cf18e)

### Related issues

I'm having a few issues with devlake and see pipelines regularly failing. This feature request would not solve the issues but it would really simplify my work getting an overview over what works and what does not.
1. https://github.com/apache/incubator-devlake/issues/5847
2. https://github.com/apache/incubator-devlake/issues/5849

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Startrekzky seems like we need the pipelines listing page with ability to filter records by Status

**Comment by Startrekzky** [comment]
Hi @renflo , this is duplicated with #3673 , and will be implemented soon.

**Comment by renflo** [comment]
Oh sorry, i must have overseeing it when searching. Great news!
