### ISSUE TITLE
[Bug][lake] Pipelines running concurrently regularly fail

### ISSUE THREAD

**Issue by renflo** [apache/devlake#5852]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

As mentioned in https://github.com/apache/incubator-devlake/issues/5849 I have a few issues and periodical pipelines failing. My periodical jobs tend to happen at the same time and when it happens they more or less all fail. 

I've seen errors about database connection not being available and the 429 bug mentioned over will of course also be very likely to occur. I can't recall if I've also had out of memory errors but it's possible. Anyways: in many case a pipeline triggered manually when no other pipeline runs succeeds, but if I look at the nightly run this exact same pipeline, running at the same time as the others, will have failed. That means that I end up having to trigger all pipelines manually at regular interval to get fresh data. That's not sustainable.

### What do you expect to happen

Making sure devlake never fails because of concurrency is of course ideal, and https://github.com/apache/incubator-devlake/issues/5849 which I just filed is falling in this category of requests. 

But I would really like you to add a configurable `MAX_CONCURRENT_PIPELINES`variable to the system which would lead to it never running more pipeline than configured in parallel. 

An env var, like the many other env vars supported by lake, would be perfect.

### How to reproduce

Create many concurrent pipeline and run them all together.

### Version

v0.18.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
There is a setting when creating a connection.
Is it helpful?

![image](https://github.com/apache/incubator-devlake/assets/5844806/4b0cb4f6-efa5-43bb-bb0a-0dac163dbbc2)

**Comment by renflo** [comment]
I saw that the jira connection, which i don't use but may start using, had a rate limiting feature after filing this. 

I'll see if i can set this up on my existing gitlab connection.

**Comment by renflo** [comment]
@d4x1 So I've checked my connection but I see no feature allowing me to reach the screen you mention over for an *existing connection*. Is it not implemented or am I missing something, in which case you could perhaps tell me how to access it?

I see a button to delete the connection - but will all the associated data scope disappear then? I need them and would like to not have to recreate them (over 50 of them)

**Comment by klesh** [comment]
@renflo 
![image](https://github.com/apache/incubator-devlake/assets/61080/76345364-7217-4f09-a6a6-05c4466c3982)

@Startrekzky I think this button is not very obviously as well.

**Comment by renflo** [comment]
@klesh thx.

If i can allow myself
1. Putting edit close to the delete feature would make sense
1. I think "edit" in text on a button is better that this edit icon.

Now i'll setup custom rate limit :)

**Comment by d4x1** [comment]
> @klesh thx.
> 
> If i can allow myself
> 
> 1. Putting edit close to the delete feature would make sense (big red button on top)
> 2. I think "edit" in text on a button is better that this edit icon.
> 3. You should uniformize the ux choice a bit. I got told that projects were deletable under settings, in a button at the bottom at the page that i did not see. This button would be easier not to miss if it was in the same location as the "delete connection" is. There probably are other examples of possible uniformization that would improve ux.
> 
> Now i'll setup custom rate limit :)

+1

**Comment by Startrekzky** [comment]
Yes, the UX here needs to tweak a little bit. Thanks for the feedback.

**Comment by Startrekzky** [comment]
Let's do a quick fix like this 
![image](https://github.com/apache/incubator-devlake/assets/14050754/06e28b25-6d51-4501-bd79-23a76119fbbd)
