### ISSUE TITLE
[Feature][config uid] Search zentao projects

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#5860]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I want to choose a zentao project, but there are two many projects, I want to filter them by keyword.

![image](https://github.com/apache/incubator-devlake/assets/5844806/e0ae775d-ebf9-46a7-bf28-26b1f56bbde8)

### Description

As above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Duplicated with the subtask in #5640 .
