### ISSUE TITLE
[Bug][GitHub]During sync of the github repository which has workflow names longer than 255 characters we getting an error

### ISSUE THREAD

**Issue by ech018** [apache/devlake#5867]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

During sync of the github repository which has workflow names longer than 255 characters we getting an error.

`time="2023-05-09 08:37:03" level=error msg=" [pipeline service] [pipeline #3] [task #25] subtask convertRuns ended unexpectedly
	Wraps: (2) error adding result to batch
	Wraps: (3) Error 1406: Data too long for column 'name' at row 17
	Wraps: (4) Error 1406: Data too long for column 'name' at row 17
	Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError"`

### What do you expect to happen

Successful sync without an error.

### How to reproduce

Sync github repository which has workflow name longer than 255 characters.

### Anything else

This issue is related to changes in this [pull request](https://github.com/apache/incubator-devlake/pull/5208).

This is the [name field](https://github.com/apache/incubator-devlake/blob/cd37555f7424c68c5e0cf8f8469f2cef9423da43/backend/core/models/domainlayer/devops/cicd_pipeline.go#L28) with limited length which needs to be increased.

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Can you manually change the `name` field in the table pull_requests of DevLake MySQL and restart collecting data?
