### ISSUE TITLE
[Feature][Gerrit] Create gerrit plugin

### ISSUE THREAD

**Issue by fhubik** [apache/devlake#5871]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a user, I'd like to use gerrit as input source.

### Description

Gerrit is often essential part of complex, decentralized and also upstream projects. It would be very useful to have a plugin integrating it as code-review data source, compared to traditional all-in-solutions like github or gitlab (where the PR/MR workflows are different and might not be suitable for some teams).

Also it's mentioned in the roadmap as "pending" https://devlake.apache.org/docs/Overview/Roadmap/ - yet the status is unclear to this point.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Howell-Zhang** [comment]
Collecting data for Gerrit doesn't seem to be that straightforward.
