### ISSUE TITLE
[Question][MySQL] Missed data in "project_mapping" table

### ISSUE THREAD

**Issue by ambrisolla** [apache/devlake#5872]
## Question
The "project_mapping" table is not getting populated after changing devlake to 0.18 ( beta ). Has anyone noticed this behavior?

**Comment by klesh** [comment]
Hi, @ambrisolla , it is indeed changed from populating on "Blueprint Save" to "Pipeline Run" so that users could populate the table as they see fit when they are using only the Pipelines, e.g. to create a pipeline directly by calling the API

**Comment by ambrisolla** [comment]
@klesh thank you! I have many queries using the "project_mapping" table to join project and repository data.  I'm try to find out how to realize this join without the project_mapping table, but nothing yet. Thank you for explain to me!

**Comment by ambrisolla** [comment]
Hi @klesh, I wasn't configuring scope-config... my bad! Tks
