### ISSUE TITLE
[Bug][Zentao] Incorrect URL and Original_Project Field Values in DevLake Zentao Data Source

### ISSUE THREAD

**Issue by narrowizard** [apache/devlake#5874]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After collecting data from the Zentao data source, the 'url' field in the 'issues' table does not meet expectations. It appears to be an API link, whereas it should be a web issue redirect link. Additionally, the 'original_project' field does not meet expectations either. It seems to be collecting the value of the project, but there are issues from other projects as well.

### What do you expect to happen

The 'url' field in the 'issues' table should contain the web issue redirect link from Zentao. The 'original_project' field should accurately reflect the project from which the issue originates, even if it is different from the project currently being collected.

### How to reproduce

Set up DevLake to collect data from a Zentao data source.
After data collection, check the 'url' field in the 'issues' table. It currently shows an API link instead of a web issue redirect link.
Check the 'original_project' field. It currently shows the value of the project being collected, even when there are issues from other projects.

### Version

release-v0.18

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@Startrekzky  I have watched all the url fields in raw table, they are all APIs, is it by design or just a bug?
