### ISSUE TITLE
[Bug][Jira] jira status not updated

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#5876]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

EE found that the status of an issue (id: 26260 key: EE-14544) was not updated to the latest, but changelog collected the latest status changes.

### What do you expect to happen

Hope jira  issue status is updated in a timely manner

### How to reproduce

For the detailed analysis process of the problem, you can refer to the doc：
https://merico.feishu.cn/docx/WKSmdRtRNomsJixO5xJcdN1tnZg

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
For the time being, use the full refresh solution first: https://github.com/apache/incubator-devlake/issues/5841

**Comment by abeizn** [comment]
resovled by #5841

**Comment by xiaomingzhang12** [comment]
Resolved by  https://github.com/apache/incubator-devlake/issues/5841
