### ISSUE TITLE
[Feature][Config UI] Update bamboo plan list

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#5882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I create some bamboo plans whose name like "xxx-xxx", and when I config them, the style  confuses me.

![WX20230815-154310@2x](https://github.com/apache/incubator-devlake/assets/5844806/59227b62-6f9e-4ad9-8409-5d03dede1764)

### Description

I want a more clear list.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
The UI of this dialogue will be updated in issue #5640 . You can check if it solves your problem then.
