### ISSUE TITLE
[Question][GitHub] How to avoid skipped jobs counting as successful production deployment?

### ISSUE THREAD

**Issue by vinicius-batista** [apache/devlake#5885]
## Question
Our CI/CD is based on `release-please` and for every PR merged we deploy to our staging environment but for production we only deploy when a release pr was merged, otherwise we skip this job, as screen shots bellow.

We have setup our Data Transformation to identify all deploys matching `deploy(.*)` and deploys matching `deploy-prod` as production deployments.

But when we made only staging deployment, devlake mark the workflow as a production deployment in our metrics. 

There is a way we can setup devlake to avoid this skipped jobs or the best approach is to divide our deployments in different workflows?

Thanks.
## Screenshots
Case when deploy-prod was skipped and shouldn't be counted as a production deployment
![image](https://github.com/apache/incubator-devlake/assets/30128450/1821789a-0e92-41eb-8f52-791e88a177aa)

Case when deploy-prod runs and should be counted as a production deployment
![image](https://github.com/apache/incubator-devlake/assets/30128450/b30c72c0-88d9-4d15-9904-1b52da0725fd)

## Additional context
Add any other context here.

**Comment by mintsweet** [comment]
hi @klesh, could you please answer this question?

**Comment by klesh** [comment]
hi, @vinicius-batista , very good question. i think u r right,this is a bug. Skipped run should be skipped in dora as well. Can u file an issue for it and i will see to it

**Comment by klesh** [comment]
oh, sorry, I thought this is a discussion.

**Comment by vinicius-batista** [comment]
Hi, this fix was introduced on 0.18.0? I made the same test again and still counting as deployment done to production

**Comment by klesh** [comment]
@vinicius-batista 
What is the exact version, can you post a screenshot showing the information?
Can post the related data and describe the problem? I need the detail to figure what went wrong.

**Comment by vinicius-batista** [comment]
Sorry for the late response. I'm running on docker image v0.18.0 with same repositories from previous post.

Run 6266720731 on GitHub, as you can see deploy-prod job was skipped because the commit wasn't a release commit.
![image](https://github.com/apache/incubator-devlake/assets/30128450/df8d13e5-f5b2-4345-bef8-48ce06c7cd32)

The screenshot above show table _tool_github_job, job deploy-prod shown as `NEUTRAL` but also shown as `COMPLETED`
![image](https://github.com/apache/incubator-devlake/assets/30128450/d4cabc84-2300-46a0-8ad6-bbcfa541fff6)

On table cicd_deployment_commits shown as `SUCCESS, DONE AND PRODUCTION`.
![image](https://github.com/apache/incubator-devlake/assets/30128450/a2c74c30-b95d-4de5-aec4-f0efc498f049)

table cicd_tasks
![image](https://github.com/apache/incubator-devlake/assets/30128450/e47f2b80-b4a3-4fba-b713-113e51383249)
 
I think for the code submitted to fix this issue, in cicd_tasks the job `deploy-prod` should have result `SKIPPED` but still blank, maybe for this reason this deploy is counting as successfull to production.

**Comment by klesh** [comment]
@vinicius-batista I see, thanks for the detailed description. Seems like the `github_graphql` needs to be fixed as well, will look into it ASAP
