### ISSUE TITLE
[Bug][DORA] A MTTR case summary does not appear

### ISSUE THREAD

**Issue by skucherenko-voxel** [apache/devlake#5887]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When Time to Restore Service is `Less than one day`, it does not appear in the "Overall DORA Metrics" dashboard.
This is caused for a letter case error. The message in the SQL behind states "Less than one Day". with a capital 'D' in the "Day" word.
![image](https://github.com/apache/incubator-devlake/assets/100363292/3654c5c2-b1a0-4215-9b58-9ed86c43e4eb)

### What do you expect to happen

It should appear. To make it so, change the capital 'D' by a small 'd'.
![image](https://github.com/apache/incubator-devlake/assets/100363292/872608ac-89a8-4bf6-8dbf-4bf12fa140de)

### How to reproduce

Any project with the `MTTR DORA` metric set as `Less than one day` serves. 
Go to DORA dashboards and see the `Overall DORA Metrics` dashboard as its `Time to restore service` row stays blank in that case.

### Version

v0.18.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@skucherenko-voxel I noticed that you have checked “Yes I am willing to submit a PR!”. Are you planning to submit a pull request?
