### ISSUE TITLE
[Bug][Config UI] Unexpected style on buttons

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#5891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I find some buttons have a blue rectangular box and obviously they are unexpeceted.

![WX20230816-145840@2x](https://github.com/apache/incubator-devlake/assets/5844806/ffc37ec5-a05d-4457-ab5b-30d266006b27)
![WX20230816-145321@2x](https://github.com/apache/incubator-devlake/assets/5844806/cfcd886c-1558-4403-96ee-3bbb6830dfd9)

### What do you expect to happen

Remove the blue box.

### How to reproduce

Just open config ui and go to `/blueprints` and you will find it.

### Anything else

This is my web browser version:
<img width="710" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/87653fda-f95e-4665-ba42-ed7ee09ea207">

### Version

a85b9faee

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
replace new ui resolved this issue.

https://github.com/apache/incubator-devlake/pull/6632
