### ISSUE TITLE
[Bug][Jira] Jira connection failed 

### ISSUE THREAD

**Issue by PanajotisMaroungas** [apache/devlake#5894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Jira (Jira Cloud) test connection failed with error message, inspite of valid authentication credentials:

"Connection test FAILED. Key: 'JiraConn.MultiAuth.AuthMethod' Error:Field validation for 'AuthMethod' failed on the 'required' tag Wraps: (2) Key: 'JiraConn.MultiAuth.AuthMethod' Error:Field validation for 'AuthMethod' failed on the 'required' tag Error types: (1) *hintdetail.withDetail (2) validator.ValidationErrors"

![Screenshot_devlake](https://github.com/apache/incubator-devlake/assets/15141651/9cf615a9-6f47-43b3-bfb6-d83a57377251)

### What do you expect to happen

Test connection succeeded

### How to reproduce

Create a jira connection for a jira cloud server.

### Anything else

I copy the request and I add the parameter "authMethod": "BasicAuth" and the response was successful.

IMO there are two possible fixes

- reactivate the UI with the option Basic Auth or Using Personal Access Token

or

- add an exception to the validator (Backend) for the jira plugin, to avoid this error 

### Version

<v0.17.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@PanajotisMaroungas Thank you for your feedback. I recommend upgrading to version v0.17.0 or v0.18.0-beta5. The subsequent versions have made changes to the Jira connection, which are likely to address your issue.

**Comment by PanajotisMaroungas** [comment]
Thank you very much, the update worked
