### ISSUE TITLE
[Feature][Object Storage] Allow Domain Data to be written in object storage 

### ISSUE THREAD

**Issue by artofcomputing** [apache/devlake#5930]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a Data Engineer, I want the flexibility to:
- Save Domain-Data in Object Storage to be consumed by other systems;
- Choose the data format to be written in Object Storage (e.g CSV, PARQUET, TSV);
- Simplify DB management (by only keeping system tables in a OLTP system);

Currently, Apache DevLake doesn't have these features natively.

### Description

By having these, any team can easily integrate Apache DevLake in their current ETL stack, and it will let teams choose the best way to persist Domain Data within their systems.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ZhangNing10** [comment]
@artofcomputing thanks for reporting! @klesh @Startrekzky could you kindly have a look?

**Comment by Startrekzky** [comment]
Hi @artofcomputing , I'm open to this. Can you tell me a specific use case of how you'll use DevLake with another data format?

**Comment by artofcomputing** [comment]
Thanks @Startrekzky!

My current use-case would be:
- Output Domain Layer Data to CSV/Parquet in a S3 bucket
- Consume S3 CSV/Parquet files with a Apache Airflow DAG
- Load data into Google Big Query within the same Airflow DAG

However, by allowing Domain Layer Data to be exported to object storage (AWS S3, GCS, ABS) the possibilities are endless (I can choose X number of ETL tools to extract this data and load it into Y numbers of OLAP systems).

**Comment by Startrekzky** [comment]
Hi @artofcomputing. Thank you for the feedback. I'll consider it. Just to clarify that it might not be supported in the short term as it requires a lot of work. The community has higher priorities which you can find in the [roadmap](https://devlake.apache.org/docs/Overview/Roadmap)

**Comment by artofcomputing** [comment]
No worries @Startrekzky, it'll be a great addition to DevLake in a long term, for now I'll extract the data from the OLTP DB.
