### ISSUE TITLE
[Bug][Zentao] Calculations of issues.time_remaining_minutes were wrong

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#5935]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

As expected, the expected  remaining working hours of a Zentao task should be taken directly from the value of the left field of the Zen task, not through "expected-consumption".
![image](https://github.com/apache/incubator-devlake/assets/142298906/0778f00f-f4b5-4952-8194-9eab107085da)

### What do you expect to happen

 Remaining working hours of a Zentao task should be taken directly from the value of the left field of the Zen task.

### How to reproduce

In the collected issues, when the estimated working hours are less than the actual working hours consumed, check whether the data in the issues table is correct.

### Version

v0.19

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by narrowizard** [comment]
Also, the value of time_remaining_minutes is not supposed to be negative, according to actual scenario.
