### ISSUE TITLE
[Bug] DevLake tooltip text cannot be copied

### ISSUE THREAD

**Issue by KucherenkoSerhiy** [apache/devlake#5958]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The tooltips in DevLake disappear on the mouse leaving the help (?) icon, which is too fast. Some of these tooltips have links inside them and cannot be copied. The following image shows an example of such a case.

![image](https://github.com/apache/incubator-devlake/assets/13918875/a4db6e33-25c9-4f45-9d4b-63e28cfedf63)

### What do you expect to happen

To be able to copy the text inside the tooltip

### How to reproduce

Look for any help icon, hover over it, and see its tooltip appear. Try to copy the tooltip's content, and see that you cannot.

### Version

v0.18.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for reporting, @mintsweet please take a look
