### ISSUE TITLE
[Bug][config-ui?] Issue with Incorrect URL Path Conversion in DevLake

### ISSUE THREAD

**Issue by KelvinVenancio** [apache/devlake#5976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have identified an issue within DevLake's URL handling where the character "/" for Project name is not being properly converted to "%2F" as it should be. This problem is causing DevLake to interpret a path that doesn't actually exist, leading to incorrect behavior and unexpected results.

When attempting to use a URL containing the "/" character, DevLake fails to encode it correctly as "%2F", which is the standard URL-encoded representation for a forward slash. Consequently, the application is unable to correctly interpret and route requests that involve this character in the URL path.

### What do you expect to happen

I expect that when using the DevLake application Projects with "/" on the name, any occurrence of the "/" character in the URL path should be correctly encoded as "%2F" according to standard URL encoding rules. This proper encoding will enable DevLake to accurately interpret and route requests involving URLs containing the "/" character.

### How to reproduce

To reproduce the issue, follow these steps:

1. Create a new project with a "/" character in its name.
2. Add a "Data Connections" component to the project.
3. Click on "Edit Data Scope and Scope Config" for the added component.

The error occurs in step 3, as illustrated by the images below:

![Screen Shot 2023-08-29 at 08-58-31](https://github.com/apache/incubator-devlake/assets/5761755/4609a065-7edc-4b2a-80b4-e44fd1314637)
![Screen Shot 2023-08-29 at 08-59-22](https://github.com/apache/incubator-devlake/assets/5761755/05b55b65-7428-4428-8910-022d47405137)
![Screen Shot 2023-08-29 at 09-00-41](https://github.com/apache/incubator-devlake/assets/5761755/955afd0b-bf42-478a-b6d5-15eff244f534)

Upon performing these steps, you should observe the incorrect behavior where the DevLake application fails to properly handle the "/" character in the URL, leading to an error or unexpected result. This reproduction will help demonstrate the problem and assist in identifying the root cause of the issue.

### Anything else

Note that in image 3 above, the access worked correctly after I corrected the URL manually by adding the code for the character "/".

### Version

v0.18.0-beta7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
I think this is a bug.

**Comment by mintsweet** [comment]
Hi, @KelvinVenancio. Thank you for your report.
But I didn't catch the error from your screenshot. Can you provide the error screenshot?

**Comment by mintsweet** [comment]
Hi, @KelvinVenancio, sorry for missing the error image. I will fix it today.
