### ISSUE TITLE
[Bug][tapd] error on extract namespace from repository url

### ISSUE THREAD

**Issue by leric** [apache/devlake#5991]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Failed to extract namespace part of a repo url like : https://gitlab.com/merico-dev/ee/tapd-test.git 

Namespace should be "merico-dev/ee", it only extracted first segment in url path "merico-dev".

![image](https://github.com/apache/incubator-devlake/assets/863493/68d362c4-a4e4-43bc-aa1f-7369cd03b2b6)

### What do you expect to happen

Use url path without the last segment as namespace

### How to reproduce

repository url path has more than 2 segments, e.g. https://gitlab.com/merico-dev/ee/tapd-test.git  has 3 segments "merico-dev", "ee", "tapd-test.git"

### Version

v0.18

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
I think this procedure will work when you want to extract issue's relation commits info when you using jira. 
Is it right ? @leric (If yes, please update the description, and make it clear and understable.)

As to the question you have mentioned, the namespace field is  extract by a regexp, and  it's configurated in blueprint or scope's config. Please paste your config  content, so we have dive into it.

cc @narrowizard

**Comment by leric** [comment]
Not in this case, it just split out the first segment of url path:

https://github.com/apache/incubator-devlake/pull/5994/files#diff-d28cea07c6ce6ec7e3a62264712c15c4f156bf04abc53c362353039b512bc830

**Comment by narrowizard** [comment]
I don't think there are configuration like jira's `remotelinkRepoPattern` in tapd plugin. @d4x1

**Comment by d4x1** [comment]
> remotelinkRepoPattern

You are right.  I only find `remotelinkRepoPattern` in Jira plugin.
