### ISSUE TITLE
[Bug][ZenTao] date filed does not take into account the time zone where zentao is located 

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6009]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Take the 6115 bug as an example, 2023-09-04 closed the issue at 11:57:14, collected the data, and view issue_changelogs the table, the corresponding create_date is 2023-09-04 19:57:14 + 08
![image](https://github.com/apache/incubator-devlake/assets/142298906/d81b8891-bb4f-4bfd-a936-011d76902bf9)
![image](https://github.com/apache/incubator-devlake/assets/142298906/b1a9a99e-3806-4f34-9183-7e02feda0435)
The zentao time zone of the testing environment is Beijing UTC + 8

### What do you expect to happen

The corresponding create_date is 2023-09-04 11:57:14 + 08
From linwei:   The standard process should be to combine this string (or datetime type) + the time zone where zentao is located, and then convert these two information into the time in the UTC time zone.

### How to reproduce

See “What happened”

### Version

v0.18

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
I think it is related with the db url config. please provide some additional information.

**Comment by xiaomingzhang12** [comment]
Devlake doesn't need to be changed. When filling in zentao dburl on ee side, just add loc = Asia/Shanghai.
