### ISSUE TITLE
[Feature][Teams] Simplify Team Creation and Onboarding Process

### ISSUE THREAD

**Issue by surevs** [apache/devlake#6026]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

The current documentation serves as the primary resource for adding teams within DevLake. However, navigating this documentation can be somewhat intricate. To streamline the team creation and project onboarding process, we propose the following enhancement:

### Description

Implement a feature similar to the existing tool connections, which would automatically generate teams based on project commits from git and the individuals associated with Jira tickets. Additionally, integrating a user-friendly UI for further team additions would significantly expedite the project onboarding process.

Key Features of the Enhancement request:

Automatic Team Generation: DevLake should automatically generate teams by analyzing project commits and associating individuals with corresponding Jira tickets. This automation will reduce manual efforts and enhance accuracy in team setup.

User-Friendly UI: DevLake should introduce an intuitive and user-friendly interface for adding and managing teams. This interface should allow users to easily customize and adjust team settings, making the onboarding process smoother and more efficient.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @surevs , thanks for the feedback.

**Comment by jay-linumlabs** [comment]
What is the status of this?
