### ISSUE TITLE
[Bug][gitlab] raw data of gitlab pipeline detail is not collected

### ISSUE THREAD

**Issue by leric** [apache/devlake#6027]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The "collectApiPipelineDetails" subtask doesn't collect data into _raw_gitlab_api_pipeline_details table, so the "started_at" and "finished_at" field in _tool_gitlab_pipelines are empty, then the duration in cicd_pipeline is not correctly calculated.

The CollectApiPipelineDetails task used _tool_gitlab_pipelines.gitlab_updated_at field for incremental update, but that table is already updated by ExtractApiPipelines.

### What do you expect to happen

"started_at" and "finished_at"  fields in _tool_gitlab_pipelines and gitlab api result is the same, cicd_pipelines.duration_sec and pipeline duration on gitlab page is the same.

### How to reproduce

Gitlab sync task with CICD domain enabled, _raw_gitlab_api_pipeline_details table is empty after sync.

### Version

v0.18

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
This issue is solved.
