### ISSUE TITLE
GitHub repo's not loading 

### ISSUE THREAD

**Issue by pramodh-b** [apache/devlake#6038]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After adding the GitHub connection, it keeps on loading the data scopes. repositories won't show up to select for data scopes.
![image](https://github.com/apache/incubator-devlake/assets/116708310/14ee2bcd-666c-42af-ad73-9a70e3438557)

### What do you expect to happen

After adding the GitHub connection it should show up the repositories present in the GitHub for adding in data scopes

### How to reproduce

As of now can be reproduced anytime 

### Anything else

It's happening every time now

FYI I've used the helm chart to deploy

### Version

Apache 2.0 License v0.18.0-beta9@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Hi @pramodh-b thank you for your report.
Could you please provide the network response to this request?

**Comment by pramodh-b** [comment]
Hope this helps
![image](https://github.com/apache/incubator-devlake/assets/116708310/24427fe5-aca8-4d1f-8d82-4233f18dce75)

**Comment by klesh** [comment]
@pramodh-b Thanks, seems like it was a BE problem, can you share the `devlake` container log as well?

**Comment by d4x1** [comment]
hi @pramodh-b   I am following this  issue. Could please tell me the connection info you are using to help me reproduce this issue? 
<img width="795" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/9b611e45-1fb2-48ff-8184-16317341e9db">

Do not paste your personal information here. I just want to reproduce this issue.

**Comment by pramodh-b** [comment]
Hi @d4x1 , please find the below details
1. Github version: **GitHub cloud**
2. Authentication type: GitHub access token ➡️ Classic token
3. Proxy URL: Do not use any proxy URL
4. Use GraphQL APIs: Disabled.

When I used a Fine-grained token, the required repo wasn't showing even though proper permission and other required permissions were provided.

**Comment by d4x1** [comment]
> Hi @d4x1 , please find the below details
> 
> 1. Github version: **GitHub cloud**
> 2. Authentication type: GitHub access token ➡️ Classic token
> 3. Proxy URL: Do not use any proxy URL
> 4. Use GraphQL APIs: Disabled.
> 
> When I used a Fine-grained token, the required repo wasn't showing even though proper permission and other required approvals were provided.

Thank you @pramodh-b , Let me test it and find what's going wrong.

**Comment by pramodh-b** [comment]
> @pramodh-b Thanks, seems like it was a BE problem, can you share the `devlake` container log as well?

Hi @klesh please find the below logs of container

[GIN] 2023/09/13 - 07:31:27 | 200 |     753.707µs |     10.244.5.60 | GET      "/plugins/github/connections"
[GIN] 2023/09/13 - 07:31:27 | 200 |    2.323422ms |     10.244.5.60 | GET      "/plugins/gitlab/connections"
[GIN] 2023/09/13 - 07:31:27 | 200 |     2.15022ms |     10.244.5.60 | GET      "/plugins/sonarqube/connections"
[GIN] 2023/09/13 - 07:31:27 | 200 |     564.806µs |     10.244.5.60 | GET      "/plugins/pagerduty/connections"
[GIN] 2023/09/13 - 07:31:28 | 200 |     607.806µs |     10.244.5.60 | GET      "/plugins/jira/connections"
[GIN] 2023/09/13 - 07:31:28 | 200 |     464.605µs |     10.244.5.60 | GET      "/plugins/tapd/connections"
[GIN] 2023/09/13 - 07:31:28 | 200 |     515.305µs |     10.244.5.60 | GET      "/plugins/zentao/connections"
[GIN] 2023/09/13 - 07:31:28 | 200 |    3.219831ms |     10.244.5.60 | GET      "/plugins/bitbucket/connections"
[GIN] 2023/09/13 - 07:31:28 | 200 |     519.105µs |     10.244.5.60 | GET      "/plugins/jenkins/connections"
[GIN] 2023/09/13 - 07:31:28 | 200 |     803.407µs |     10.244.5.60 | GET      "/plugins/azuredevops/connections"
[GIN] 2023/09/13 - 07:31:28 | 200 |     697.507µs |     10.244.5.60 | GET      "/plugins/webhook/connections"
[GIN] 2023/09/13 - 07:31:28 | 200 |      47.601µs |     10.244.5.60 | GET      "/userinfo"
[GIN] 2023/09/13 - 07:31:32 | 200 |     1.04841ms |     10.244.5.60 | GET      "/plugins/github/connections/5/scopes?blueprints=true"
[GIN] 2023/09/13 - 07:31:32 | 200 |  269.621344ms |     10.244.5.60 | POST     "/plugins/github/test"
[GIN] 2023/09/13 - 07:31:33 | 200 |         1.4µs |      10.244.5.1 | GET      "/ping"
[GIN] 2023/09/13 - 07:31:35 | 200 |  286.364789ms |     10.244.5.60 | GET      "/plugins/github/connections/5/remote-scopes"
time="2023-09-13 07:31:37" level=error msg="HTTP 500 error
        caused by: error decoding response from https://api.github.com/orgs/10290767/repos?page=1&per_page=100: raw response: {"message":"Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.","documentation_url":"https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"}"
[GIN] 2023/09/13 - 07:31:37 | 500 |  226.567028ms |     10.244.5.60 | GET      "/plugins/github/connections/5/remote-scopes?groupId=10290767"
[GIN] 2023/09/13 - 07:31:43 | 200 |         1.1µs |      10.244.5.1 | GET      "/ping"

**Comment by d4x1** [comment]
> > @pramodh-b Thanks, seems like it was a BE problem, can you share the `devlake` container log as well?
> 
> Hi @klesh please find the below logs of container
> 
> [GIN] 2023/09/13 - 07:31:27 | 200 | 753.707µs | 10.244.5.60 | GET "/plugins/github/connections" [GIN] 2023/09/13 - 07:31:27 | 200 | 2.323422ms | 10.244.5.60 | GET "/plugins/gitlab/connections" [GIN] 2023/09/13 - 07:31:27 | 200 | 2.15022ms | 10.244.5.60 | GET "/plugins/sonarqube/connections" [GIN] 2023/09/13 - 07:31:27 | 200 | 564.806µs | 10.244.5.60 | GET "/plugins/pagerduty/connections" [GIN] 2023/09/13 - 07:31:28 | 200 | 607.806µs | 10.244.5.60 | GET "/plugins/jira/connections" [GIN] 2023/09/13 - 07:31:28 | 200 | 464.605µs | 10.244.5.60 | GET "/plugins/tapd/connections" [GIN] 2023/09/13 - 07:31:28 | 200 | 515.305µs | 10.244.5.60 | GET "/plugins/zentao/connections" [GIN] 2023/09/13 - 07:31:28 | 200 | 3.219831ms | 10.244.5.60 | GET "/plugins/bitbucket/connections" [GIN] 2023/09/13 - 07:31:28 | 200 | 519.105µs | 10.244.5.60 | GET "/plugins/jenkins/connections" [GIN] 2023/09/13 - 07:31:28 | 200 | 803.407µs | 10.244.5.60 | GET "/plugins/azuredevops/connections" [GIN] 2023/09/13 - 07:31:28 | 200 | 697.507µs | 10.244.5.60 | GET "/plugins/webhook/connections" [GIN] 2023/09/13 - 07:31:28 | 200 | 47.601µs | 10.244.5.60 | GET "/userinfo" [GIN] 2023/09/13 - 07:31:32 | 200 | 1.04841ms | 10.244.5.60 | GET "/plugins/github/connections/5/scopes?blueprints=true" [GIN] 2023/09/13 - 07:31:32 | 200 | 269.621344ms | 10.244.5.60 | POST "/plugins/github/test" [GIN] 2023/09/13 - 07:31:33 | 200 | 1.4µs | 10.244.5.1 | GET "/ping" [GIN] 2023/09/13 - 07:31:35 | 200 | 286.364789ms | 10.244.5.60 | GET "/plugins/github/connections/5/remote-scopes" time="2023-09-13 07:31:37" level=error msg="HTTP 500 error caused by: error decoding response from https://api.github.com/orgs/10290767/repos?page=1&per_page=100: raw response: {"message":"Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.","documentation_url":"[https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"}](https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/%22%7D)" [GIN] 2023/09/13 - 07:31:37 | 500 | 226.567028ms | 10.244.5.60 | GET "/plugins/github/connections/5/remote-scopes?groupId=10290767" [GIN] 2023/09/13 - 07:31:43 | 200 | 1.1µs | 10.244.5.1 | GET "/ping"

You can follow `{"message":"Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.","documentation_url":"[https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"}](https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/%22%7D)"` to solve your problem.

As to the long term,  we will dive into the SAML and see what we can do to find it in the early stage.

**Comment by pramodh-b** [comment]
HI @klesh 

 Issue resolved. Thank you all for the help.

**Comment by klesh** [comment]
Nice to know, @d4x1 I think we should forward the error message instead of throwing 500 error for this particular case, what do you think?

**Comment by WuJiahu** [comment]
> @pramodh-b Thanks, seems like it was a BE problem, can you share the `devlake` container log as well?

Hi,how to find the devlake container logs?

**Comment by klesh** [comment]
@WuJiahu run command `docker-compose logs -f devlake` in the folder of `docker-compose.yml`

**Comment by d4x1** [comment]
> @WuJiahu run command `docker-compose logs -f devlake` in the folder of `docker-compose.yml`

@WuJiahu  Any updation?

**Comment by WuJiahu** [comment]
> > @WuJiahu run command `docker-compose logs -f devlake` in the folder of `docker-compose.yml`
> 
> @WuJiahu Any updation?

yes, i have fixed it
