### ISSUE TITLE
[Bug][Bamboo] In cicd_scopes table created_date updated_date empty

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6080]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/incubator-devlake/assets/142298906/f492c867-210f-41d9-a850-a1c9b1e742e7)

### What do you expect to happen

created_date updated_date should have a value, the value logic is the plan creation time and the most recent update time

### How to reproduce

See above

### Version

v0.19

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
I think it is table `cicd_scopes`.

**Comment by d4x1** [comment]
In bamboo's `created_date` and `updated_date `  are bamboo plan's properties.  I cound not find any API to fetch this, and its web page have no such info too.

@xiaomingzhang12 @Startrekzky

**Comment by xiaomingzhang12** [comment]
Confirm with the product Zheng Yi, these two fields do not need to be processed for the time being.
