### ISSUE TITLE
[Bug][Bamboo] In cicd_tasks table, the value duration_sec field is empty

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6082]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the testing environment, collect the plan p1 under project xm-1. After the collection is completed, check the data in the cicd_scopes table
![image](https://github.com/apache/incubator-devlake/assets/142298906/339a653e-1735-4d1f-8646-c04833d49b33)

### What do you expect to happen

For an executed plan-build, that is, cicd_pipeline, the execution time (seconds) of the build needs to be stored. If the API does not return directly, it needs to be finished_date - started_date
![image](https://github.com/apache/incubator-devlake/assets/142298906/0ccb7e53-6fe2-40f8-8d8b-56fcbed2df4b)

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Does this issue talk about  cicd_tasks or cicd_pipelines ?

cicd_pipelines.duration_sec has value now.

**Comment by xiaomingzhang12** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.
> 
> ### What happened
> In the testing environment, collect the plan p1 under project xm-1. After the collection is completed, check the data in the cicd_scopes table ![image](https://user-images.githubusercontent.com/142298906/267847099-339a653e-1735-4d1f-8646-c04833d49b33.png)
> 
> ### What do you expect to happen
> For an executed plan-build, that is, cicd_pipeline, the execution time (seconds) of the build needs to be stored. If the API does not return directly, it needs to be finished_date - started_date ![image](https://user-images.githubusercontent.com/142298906/267846140-0ccb7e53-6fe2-40f8-8d8b-56fcbed2df4b.png)
> 
> ### How to reproduce
> See above
> 
> ### Anything else
> _No response_
> 
> ### Version
> main
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)



> Does this issue talk about cicd_tasks or cicd_pipelines ?
> Yes  ,cicd_tasks.duration_sec is empty
> cicd_pipelines.duration_sec has value now.
> 
> @xiaomingzhang12

**Comment by d4x1** [comment]
cicd_tasks.duration_sec is empty now. Need to be fixed.
