### ISSUE TITLE
[Bug][Config UI] Errors when update project conection's scopes

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#6097]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/incubator-devlake/assets/5844806/d8bb65f1-9167-4140-a71f-d67d37268ecf

Look at this video.
1. When I choose "ALL",  some iterms are not included.
2. When I update scopes, an error occured.

### What do you expect to happen

1. I choose "ALL", and all scopes are included.
2. I can update scopes successfully.

### How to reproduce

Create a project and add a bamboo connection to it.  Do the operations like me in the video.

### Anything else

None

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Hi @d4x1, question 1 is in line with expectations. When you click 'ALL', the data scope is not loaded all, so it only selects the loaded data scope.

I will check question 2.

**Comment by mintsweet** [comment]
hi @d4x1, I checked question 2 and found it is a backend error, please check it.
