### ISSUE TITLE
[Bug][zentao] Collect data error with zentao v18.5 

### ISSUE THREAD

**Issue by mickey50** [apache/devlake#6098]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When collect bug data  , the task failed:
time="2023-09-15 17:13:22" level=warning msg=" [pipeline service] [pipeline #2] [task #7] [api async client] retry #0 calling /projects/575/bugs\n\tcaused by: Http DoAsync error calling [GET /projects/575/bugs]. Response: {\"status\":\"success\",\"data\":\"{\\\"locate\\\":\\\"http:\\\\\\/\\\\\\/58.247.92.122:8765http:\\\\\\/\\\\\\/111.111.111.111:8765\\\\\\/user-deny-project-bug.json\\\"}\",\"md5\":\"a833d1a5f58b294fbcd5c623d39eb433\"}<html><head><meta http-equiv='Content-Type' content='text/html; charset=utf-8' /></head><body><br />\n\t17:13:22 Uncaught Error: Call to undefined method helper::end() in module/common/model.php:413<br />\n\tStack trace:<br />\n\t#0 module/project/model.php(2867): commonModel->deny('project', 'bug', false)<br />\n\t#1 module/project/control.php(1174): projectModel->setMenu('575')<br />\n\t#2 api/v1/entries/projectbugs.php(27): project->bug('575', 0, 0, 'status,id_desc', 0, 'all', 0, 0, '100', '1')<br />\n\t#3 framework/api/router.class.php(216): projectBugsEntry->get('575')<br />\n\t#4 www/api.php(49): api->loadModule()<br />\n\t#5 {main}<br />\n\t  thrown in <strong>module/common/model.php</strong> on line <strong>413</strong> when visiting <strong></strong><br />\n\t</body></html> (403)"

### What do you expect to happen

collect bug data into lake

### How to reproduce

collect data from zentao v18.5

### Anything else

where test the " /projects/575/bugs " with postman ,it have same error ,ant I can't find this api in zentao's apidoc

### Version

release_v0.19

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Devlake is tested in zentao open source version 18.3. We need some time to upgrade to 18.5.
@mickey50
