### ISSUE TITLE
[Feature][GitHub] CICD grafana stats

### ISSUE THREAD

**Issue by hollmanenciso** [apache/devlake#6101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a manager, I want to have CICD metrics on GitHub dashboard in grafana

### Description

include all CICD metrics in the current GitHub dashboard in grafana

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Looking forward to your PR 💪
