### ISSUE TITLE
[Feature][webhook] Support #5909 and #5269 by allowing creating Change(PR) via webhook plugin

### ISSUE THREAD

**Issue by klesh** [apache/devlake#6103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

- #5909
- #5269

### Description

Currently, Change Lead Time calculation relies on the `PRs`, `Commits`, and `DeploymentCommits`. However, some of them might not be available in some use cases:

- #5269 trunk-based development doesn't have any PR at all, every developer would push his/her Changes to the branch directly. In this case, each push might contain multiple `commits` and be considered a **PR**
- #5909 deployment on **PR Merge** would produce required entities(`PRs`, `Commits`, and `DeploymentCommits`) just fine, but the catch is that the `DeploymentCommits.commit_sha`s come from `PR.head_commit_sha`s which are **NOT**  included in the `main`(release) branch when using **Squash and Merge** method, so it is impossible to connect `PR`s to their correct `Deployments`.

**Note that in the above cases, the information we need is only available during the CI/CD runtime and then lost forever, in other words, it can't be recovered afterward when collecting.**

In general, the data we need for CLT calculation might not be available or correct in some cases, we need a universal solution to support them.

###  Assuming that we offer an API that Support creating `PullRequest` via the `webhook` plugin:
```
curl http://localhost:8080/plugins/webhook/1/pull-requests -X 'POST' -d '{
    "head_commit_sha": "015e3d3b480e417aede5a1293bd61de9b0fd051d",
    "base_commit_sha": "83c2256d5cf089b63e04ddd39517a464ff3108d2",
    "merge_commit_sha": "<THE CORRECT MERGE COMMIT SHA>",
    "head_repo_id": "github:GithubRepo:1:123",
    "base_repo_id": "github:GithubRepo:1:123",
    "url":"https://github.com/apache/incubator-devlake/pulls/1111",
    "status": "merged",
    "commits": [
        { "commit_sha": "...", "message": "...", "author_name": "...", "author_email": "...", "authored_date": "..." }
    ]
  }'
```

#### For the use case of Trunk-Based development #5269 

We can use the API to create virtual PR whenever the `main` branch is updated/pushed:

`.github/workflows/create-virtual-pr.yml`
```
on:
  push:
    branches:
      - main
jobs:
  create-virtual-pr:
    name: Create Virtual PR on Apache DevLake
    steps:
        - name: Post PR to Webhook
          run: |
            curl http://<devlake domain>/plugins/webhook/1/pull-requests -X 'POST' -d '{
                "head_commit_sha": "015e3d3b480e417aede5a1293bd61de9b0fd051d",
                "base_commit_sha": "83c2256d5cf089b63e04ddd39517a464ff3108d2",
                "merge_commit_sha": "<HEAD_COMMIT_SHA>", 
                "head_repo_id": "github:GithubRepo:1:123",
                "base_repo_id": "github:GithubRepo:1:123",
                "url":"https://github.com/apache/incubator-devlake/pulls/1111",
                "status": "merged",
                "commits": [
                    { "commit_sha": "...", "message": "...", "author_name": "...", "author_email": "...", "authored_date": "..." }
                ]
              }'

```

#### For the use case of Deploy on PR Squash and Merge #5909 

`.github/workflows/deploy-on-pr-merge.yml`
```
​on:
    pull_request:
        branches: [master]
        types: [closed]
jobs:
    deploy:
        environment:
            name: ${{ needs.init.outputs.environment }}
        steps:
          - uses: actions/checkout@v3
             with:
               ref: 'master'
          - name: Post PR to Webhook
            run: |
              curl http://<devlake domain>/plugins/webhook/1/pull-requests -X 'POST' -d '{
                  "head_commit_sha": "015e3d3b480e417aede5a1293bd61de9b0fd051d",
                  "base_commit_sha": "83c2256d5cf089b63e04ddd39517a464ff3108d2",
                  "merge_commit_sha": "<MASTER_COMMIT_SHA>", 
                  "head_repo_id": "github:GithubRepo:1:123",
                  "base_repo_id": "github:GithubRepo:1:123",
                  "url":"https://github.com/apache/incubator-devlake/pulls/1111",
                  "status": "merged",
                  "commits": [
                      { "commit_sha": "...", "message": "...", "author_name": "...", "author_email": "...", "authored_date": "..." }
                  ]
                }'

```

#### How it works

The common problem of the above use cases is either there is **No PR at all** or it comes with the **WRONG** `merge_commit_sha`. By allowing users to create PR via the `webhook` plugin, we can solve the problem so that DORA can be calculated correctly.

### Related issues

See [Use Case](#use-case)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @klesh , I have a few thoughts:
1. To do it or not?  -----  I agree that we should support measuring DORA for a trunk-based development model in general. 
2. When should we do it, before v1.0 or after v1.0? ------ Is it a must-do for DevLake v1.0? From my understanding, the trunk-based model is normally practiced by small businesses. I'm not sure if they're the primary target users for DevLake.
3. How should we do it?  ------ The above solution (using the incoming webhook to mock PRs) relies on the event mechanism on the target VCS tool. I would like to know the user flow to get this configured for evaluation.

**Comment by klesh** [comment]
> Hi @klesh , I have a few thoughts:
> 
> 1. To do it or not?  -----  I agree that we should support measuring DORA for a trunk-based development model in general.
> 2. When should we do it, before v1.0 or after v1.0? ------ I don't think it's a must-do for DevLake v1.0. From my understanding, the trunk-based model is normally practiced by small businesses. I'm not sure if they're the primary target users for DevLake. We should follow up on the feature requesters to gather their team sizes. [I asked the requesters in #5269](https://github.com/apache/incubator-devlake/issues/5269#issuecomment-1729472106).
> 3. How should we do it?  ------ The above solution (using the incoming webhook to mock PRs) relies on the event mechanism on the target VCS tool. I would like to know the user flow of this solution for evaluation.

3. I thought #5269 described the user flow already. Do you mean more or it was not what you needed?

**Comment by nlespiaucq** [comment]
Hi @klesh,
I have read comments about supporting the trunk-based development on #5269 and in this current ticket.
Is there any plan to go forward? Wasn't the virtual PR a valid solution?

**Comment by klesh** [comment]
@nlespiaucq I think virtual PR is a viable solution as far as I understand the problem. Unfortunately, I don't have experience practicing trunk-based development, so I am not working on the subject at the moment.
However, I am open to anyone willing to contribute, I am also willing to support the development in terms of sharing knowledge, thoughts, and reviews.
