### ISSUE TITLE
[Bug][Bamboo] Change the splicing of cicd_scopes.name and cicd_pipelines.name

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6106]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Now cicd_scopes.name is spliced in the way of project + "space ” +“ -” + "space ”+ plan.
![image](https://github.com/apache/incubator-devlake/assets/142298906/f3e06b29-8779-4878-bc0b-746ecd8e4206)

### What do you expect to happen

cicd_scopes.name needs to be changed to project + "/" + plan, this kind of splicing logic.
Take the above screenshot as an example
The value of xm-1 - p1 needs to be changed to xm-1/p1.
The name in the table cicd_pipelines also needs to be changed to this splicing logic.

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
hi @mintsweet 
cicd_scopes.name comes from _tool_bamboo_plans.name, and _tool_bamboo_plans.name is set when uses choose bamboo plans inConfig UI via API `HTTP PUT /connections/:connectionId/scopes`, so I need your help to fix cicd_scopes.name.

cc @xiaomingzhang12 

cicd_pipelines.name should be fixed in backend. @d4x1

**Comment by d4x1** [comment]
@Startrekzky @xiaomingzhang12 
 I found that plan's name form  `hlw-h3 - h2` is returned from bamboo's API, for example:
```
{
    "shortName": "h2",
    "shortKey": "H2",
    "type": "chain",
    "enabled": true,
    "link":
    {
        "href": "http://18.232.129.138:8085/rest/api/latest/plan/HLWH3-H2",
        "rel": "self"
    },
    "key": "HLWH3-H2",
    "name": "hlw-h3 - h2",
    "planKey":
    {
        "key": "HLWH3-H2"
    }
}
```
`"name": "hlw-h3 - h2"` is the plan's official name.

Shall we update it with our custom splicing logic?

**Comment by xiaomingzhang12** [comment]
> @Startrekzky @xiaomingzhang12 I found that plan's name form `hlw-h3 - h2` is returned from bamboo's API, for example:
> 
> ```
> {
>     "shortName": "h2",
>     "shortKey": "H2",
>     "type": "chain",
>     "enabled": true,
>     "link":
>     {
>         "href": "http://18.232.129.138:8085/rest/api/latest/plan/HLWH3-H2",
>         "rel": "self"
>     },
>     "key": "HLWH3-H2",
>     "name": "hlw-h3 - h2",
>     "planKey":
>     {
>         "key": "HLWH3-H2"
>     }
> }
> ```
> 
> `"name": "hlw-h3 - h2"` is the plan's official name.
> 
> Shall we update it with our custom splicing logic?

In that case, I think it's better to use the format returned by the bamboo api itself.
