### ISSUE TITLE
[Bug][Bamboo] cicd_pipelines.result is missing a state

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6107]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The result of Plan build, taken as _tool_bamboo_plan_builds build_state, will be standardized as'SUCCESS ',' FAILURE 'in the domain layer.
![image](https://github.com/apache/incubator-devlake/assets/142298906/3e81b328-ce4c-49a7-997f-766984bcf3b6)

### What do you expect to happen

From the _tool_bamboo_deploy_build table, there is a NOT_BUILT status that needs to be added.
![image](https://github.com/apache/incubator-devlake/assets/142298906/63060d1e-b3dd-42be-b97a-62b9e13e0013)

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
According to this [doc](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/package-tree.html) , I find there three kindso of  state in bamboo 6.8.1, and the following two we need to handle:
1. [BuildState](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/BuildState.html)    
[FAILED](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/BuildState.html#FAILED)
[SUCCESS](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/BuildState.html#SUCCESS)
[UNKNOWN](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/BuildState.html#UNKNOWN)
2. [LifeCycleState](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/LifeCycleState.html)
[FINISHED](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/LifeCycleState.html#FINISHED)
[IN_PROGRESS](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/LifeCycleState.html#IN_PROGRESS)
[NOT_BUILT](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/LifeCycleState.html#NOT_BUILT)
[PENDING](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/LifeCycleState.html#PENDING)
[QUEUED](https://docs.atlassian.com/atlassian-bamboo/6.8.1/com/atlassian/bamboo/builder/LifeCycleState.html#QUEUED)

1. Shall we add a new state called "UNKNOWN"?  If not, how to mapping "UNKNOWN" state? 
2. Are IN_PROGRESS\NOT_BUILT\PENDING\QUEUED regarded as devlake's "IN_PROGRESS"?

@Startrekzky @xiaomingzhang12

**Comment by d4x1** [comment]
> @d4x1 I think we only transform the ones that match our rules to `SUCCESS/FAILED` or `DONE/IN_PROGRESS`, and
> 
> 1. don't transform all other values
> 2. transform all other values to 'OTHER'

@Startrekzky 
There are many state you can find them here: https://github.com/apache/incubator-devlake/blob/main/backend/core/models/domainlayer/devops/cicd_pipeline.go#L44

**Comment by d4x1** [comment]
Return to the original issue, I think "NOT_BUILT" and "UNKNOWN" states are all legal in tool layer which is simply transormed from ray layer, "NOT_BUILT" and "UNKNOWN"  will be ""(empty string) and `STATUS_IN_PROGRESS` in the domain layer.

@xiaomingzhang12 

I don't know what to fix……

**Comment by d4x1** [comment]
FINISHED -> DONE
IN_PROGRESS -> IN_PROGRESS
NOT_BUILT -> NOT_STARTED
PENDING -> NOT_STARTED(if it has starttime, then it is IN_PROGRESS, otherwise it is NOT_STARTED)
QUEUED ->   NOT_STARTED(if it has starttime, then it is IN_PROGRESS, otherwise it is NOT_STARTED)
