### ISSUE TITLE
[Bug][Teams] Validation of teams csv allows invalid formats

### ISSUE THREAD

**Issue by a-grealish** [apache/devlake#6117]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I manually created a users.csv file with each user's teams separated with a `,` after misreading the example file. The correct separator is `;`, which makes sense as the file is a csv.

The file was uploaded as accepted by the API. However, the filtering by team on the grafana dashboards was not working as I expected.

On inspecting the database, I noticed that the `team_users` table listed the values in the `team_id` as the comma separated values, rather than splitting them out into individual rows. 

### What do you expect to happen

I would expect the upload to be validated, and rejected. And I would not expect the comma separated values to end up in the key of the database table. 

### How to reproduce

Modify the example csv to be comma sepearted, and upload

[users_broken.csv](https://github.com/apache/incubator-devlake/files/12661908/users_broken.csv)

### Anything else

I agree with https://github.com/apache/incubator-devlake/issues/6026 that it would be much nicer to move to a better UI for team creation. But regardless of that, I believe we should improve validation at both the API and DB layer. This example shows one issue, but I would assume there are other validation issues that might cause problems.

### Version

v0.17.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
I agree. Adding more validations would help with the UX. Thanks for reporting.
