### ISSUE TITLE
[Bug][Bamboo] The description field in table cicd_scopes is empty

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6124]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. In the bamboo page, fill in the description information of the plan
![image](https://github.com/apache/incubator-devlake/assets/142298906/d138cfe3-e0ae-4a0a-8e5a-52ce5c58c027)

3. Collect data for this plan
4. Check the cicd_scopes table and find that the description field is null
![image](https://github.com/apache/incubator-devlake/assets/142298906/08bf20ae-83b2-4431-9ef8-2968140fad77)

### What do you expect to happen

1. The value of the expected description field is consistent with the description on the bamboo page, that is, This is a test plan.
2. I feel that this is not a high priority

### How to reproduce

See above

### Version

v0.19

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
I think `description` field is not necessary in devlake, I have checked the Bamboo API's response, there is no description info in `plan.json` API,  it costs some time to fulfill `description` field with another way.  

So  just leave it, I won't fix it at now.  @xiaomingzhang12  cc @klesh @abeizn 


![image](https://github.com/apache/incubator-devlake/assets/5844806/ec35dee9-f85a-46df-a2ae-34290eec1187)
