### ISSUE TITLE
[Bug][Schema] cicd_pipelines lacks `started_date`, `queued_date` and cicd_tasks lacks `created_date`, `queued_date`

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#6132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When investigating into the CI/CD schema, I found that
- table cicd_pipelines lacks the field `started_date`
- table cicd_tasks lacks the field `created_date`

These two fields are different in CI/CD workflows. For instance, if a GitLab job is queued after it's created, its `created_date` and `started_date` will be different.

![image](https://github.com/apache/incubator-devlake/assets/14050754/929c7dcb-8d5f-43a7-b491-70f18e58c055)

### What do you expect to happen
In v0.20:
- [x] Add the field `started_date` and `queued_date` to table cicd_pipelines
- [x] Add the field `created_date`and `queued_date` to table cicd_tasks
- [x] Add the field `queued_date` to table cicd_deployment_commits
- [x] Check and fix the value assignment logic of Bamboo's `created_date`, `queued_date` and `started_date`
- [x] Check and fix the value assignment logic of GitLab's `created_date`, `queued_date` and `started_date`
- [x] Update the schema doc and diagram: https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#cicd_pipelines

In v0.21:
- [x] Check the values of `created_date` and `started_date` in cicd_pipelines
   - [x] GitHub 
   - [x] Jenkins
   - [x] BitBucket
   - [x] Azure
- [x] Check the values of `created_date` and `started_date` in cicd_tasks
   - [x] GitHub 
   - [x] Jenkins
   - [x] BitBucket
   - [x] Azure
- [x] Check the values of `created_date`, `queued_date` and `started_date` in cicd_deployment_commits
   - [x] GitHub 
   - [x] Jenkins
   - [x] BitBucket
   - [ ] Azure

### How to reproduce

Collect a GitLab job that has been queued.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Got it, it's a tedious change. I'll do it later.

**Comment by d4x1** [comment]
<img width="734" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/2302d43d-aa3a-4c67-92a8-1ce1e594758a">

AzureDevops plugins has no cicd_deployment_commits data so far. So it's not checked.
