### ISSUE TITLE
[Feature][Gitlab] Parsing CI/CD trigger jobs

### ISSUE THREAD

**Issue by Marco-De-Stefani** [apache/devlake#6135]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I would like to have the possibility to fetch the trigger jobs from GitLab CI/CD pipelines
https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-trigger-jobs

### Description

In my company, we have a setup where basically a main pipeline is triggering a child pipeline, which is responsible for the actual deployment (and from it I can have the actual environment where I'm deploying)
I know that GitLab doesn't offer an API to fetch those like we're fetching the pipelines, but the jobs need to be fetched for every single pipeline with the endpoint
`projects/{{ ProjectId }}/pipelines/{{ PipelineId }}/bridges`

I think it would be cool if we could have a setting for enable/disable this on the UI

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@d4x1 @abeizn  Since it has to be collected by each pipeline. I think one logical solution to this is:
1. Add a collector for this `GitLab bridge` entity but make it optional
2. Support #5920 . Allow users to enable it in the Config UI

So I think it relies on the implementation of #5920
