### ISSUE TITLE
[Bug][Module Name] Bug title Secondary rate limit

### ISSUE THREAD

**Issue by pramodh-b** [apache/devlake#6137]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The GitHub repo was huge in size, so it threw up the below error whenever the pipeline ran.

![image](https://github.com/apache/incubator-devlake/assets/116708310/3cf4186d-fb61-4d4a-8f86-3b3479ae9611)

### What do you expect to happen

Expected that pipeline run successfully 

### How to reproduce

just by triggering the pipeline

### Anything else

This issue occurs every time the pipeline runs.

### Version

v0.18.0-beta9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pramodh-b** [comment]
The issue was resolved after enabling the "Use GraphQL API" option in the GitHub connection.
@klesh

**Comment by klesh** [comment]
@pramodh-b Thanks for reporting the issue.

**Comment by abeizn** [comment]
sloved
