### ISSUE TITLE
[Bug][Module Name] Bug title Gitextractor plugin takes long time.

### ISSUE THREAD

**Issue by pramodh-b** [apache/devlake#6138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The gitextractor plugin in the pipeline takes 13+ hours to complete. and the scheduled pipeline will fail because the gitextractor task and GitHub repo task will fail, If I run it manually then it will be successful by taking 13+ hours. 

it says "the process terminated unexpectedly" on both tasks.

### What do you expect to happen

Expected the scheduled pipeline should be completed without errors and not take so much time

### How to reproduce

This happens every day

### Version

v0.18.0-beta9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@pramodh-b 
How big and how many repos are you trying to clone?

**Comment by pramodh-b** [comment]
> @pramodh-b How big and how many repos are you trying to clone?

Hi @d4x1 It's only 1 private repo and its size is 1.34GB

**Comment by pramodh-b** [comment]
with the v0.19.0-beta1 version, when I run manually also the pipeline is getting failed.

**Comment by abeizn** [comment]
@pramodh-b 
If you don't need some data, such as commit_files, you can skip it, which will save you a lot of time. In subsequent versions, we will continue to optimize the gitextractor module to reduce its time consumption as much as possible.

how to skip commit_files collector: 
you should set SKIP_COMMIT_FILES=true in .env file or enviroment variable.

**Comment by Startrekzky** [comment]
This will be tracked and solved in https://github.com/apache/incubator-devlake/issues/6853.
