### ISSUE TITLE
[Bug][Sonarqube] Task failure with 'data too long' error message

### ISSUE THREAD

**Issue by aubertaa** [apache/devlake#6150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Extraction task from sonarqube server is failing with this message:

![image](https://github.com/apache/incubator-devlake/assets/14087776/a2dfeffb-135c-4cb8-8c80-4aadbfaeae1c)

"subtask ExtractAdditionalFileMetrics ended unexpectedly Wraps: (2) error adding result to batch (500) Wraps: (3) Error 1406 (22001): Data too long for column 'file_metrics_key' at row 365 (500) Wraps: (4) Error 1406 (22001): Data too long for column 'file_metrics_key' at row 365 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError"

Feel free to ask if i can give more details, that's the only information i have in logs for now.

### What do you expect to happen

Task should be successful.

### How to reproduce

I wonder where this file_metrics_key comes from, i can't find it in published models : https://devlake.apache.org/docs/v0.19/DataModels/DevLakeDomainLayerSchema/#cq_file_metrics

### Anything else

devlake used is :  0.19.0-beta1
sonarqube server is : Version 9.9.1 (build 69595)

### Version

0.19.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for reporting the bug, will look into it ASAP

**Comment by abeizn** [comment]
@aubertaa The problem has been fixed and will be released in v0.19.0-beta3.

**Comment by integraci-co804** [comment]
i have the same issue like that, i am using devlake version v0.21.0@ac4f7fe
![Uploading image.png…]()
