### ISSUE TITLE
[Bug][Lake] Lock wait time exceeded

### ISSUE THREAD

**Issue by leobonfimm** [apache/devlake#6152]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Facing some problems during the pipeline process and some queries on database devlake that built the Grafana dashboard.

The image below is the error on the pipe
![image](https://github.com/apache/incubator-devlake/assets/39925352/2faf7dc5-b34e-41bd-8cb9-e07bf692f9f6)

When execute this query sometimes takes 90 seconds to execute
```SQL
SELECT
  original_project
  ,COUNT(*)
FROM
  issues
GROUP BY
  original_project
```

I think this happened because there are some locks on the devlake table.

### What do you expect to happen

The task should be successful and the query executes more quickly.

### How to reproduce

This happens every day

### Version

v0.18.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, @leobonfimm Thanks for reporting the issue. Could you try the latest `v0.19.0-beta2` and see if the problem fixed?

**Comment by leobonfimm** [comment]
Hei @klesh, the problem persists, in my case when there is more than one project running on the same schedule it starts the pipeline for all of them instead of starting one and putting the others on pending.

**Comment by klesh** [comment]
To clarify, there are two problems:

1. Executing queries on Grafana is slow when there is a pipeline ( or is it multiple ) running.
2. Pipelines triggered by different Blueprints should be queued.

**Comment by leobonfimm** [comment]
Exactly, we have some deadlock problems that occur as well.

Like the image below:
![image](https://github.com/apache/incubator-devlake/assets/39925352/dc3ef0d9-b86b-4bfa-a34a-0bb4a1f72b5f)

**Comment by klesh** [comment]
Alright, let's divide and conquer.

> To clarify, there are two problems:
> 
> 1. Executing queries on Grafana is slow when there is a pipeline ( or is it multiple ) running.

You may try to optimize the `mysql`, e.g. to use a Cloud-based database instead. Slow queries are out of the scope of our project because it happens between `grafana` and `mysql`, unless the slowness is caused by the lack of necessary indexes.

> 2. Pipelines triggered by different Blueprints should be queued.

Did you set the environment variable `PIPELINE_MAX_PARALLEL` ?

**Comment by leobonfimm** [comment]
@klesh, update the version of Devlake and set the value of this env `PIPELINE_MAX_PARALLEL ` to 1, solve the problems about lock table and deadlocks. Thanks a lot for the help...
