### ISSUE TITLE
[Bug][Teambition] in v0.19.0-beta2 verson，cant  find  teambition Connections

### ISSUE THREAD

**Issue by TinyNing** [apache/devlake#6155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I deploy devlake with docker-compose in ubuntu22.04，and my version is v0.19.0-beta2 verson
bu in localhosts:4000/connections , I can't find the teambition  data connection
![image](https://github.com/apache/incubator-devlake/assets/79590928/4f38a69b-6d15-49c8-8b62-b12ed92f9848)

### What do you expect to happen

It can  configure teambition  Connections

### How to reproduce

This is a problem that will definitely arise

### Version

v0.19.0-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@ningjunwei Teambition support on the `config-ui` was removed.
@mintsweet I think we can add it back and start to support more backend-only plugins

**Comment by ningjunwei** [comment]
@klesh Hi I try to config teambition with Advanced Mode ,but  failed.  there is my steps
1.  add Blueprint with  Advanced Mode
2.  set the teambition config, come from https://devlake.apache.org/docs/v0.19/Configuration/AdvancedMode/#11-teambition, but i have dont know what connectionId is, because i cant config the teanbition with ui, so i write connectionId 1,  and i change my projectid
3. i create a project ,then i change the default blueprint name to   Advanced Mode Blueprint ,but i cant collect

**Comment by coldgust** [comment]
@ningjunwei You can try to create a connection using api
```text
curl --location 'http://{devlake-backend-host}:{port}/plugins/teambition/connections' \
--header 'Content-Type: application/json' \
--data '{
    "name": "teambition-test",
    "endpoint": "https://open.teambition.com/api/",
    "rateLimitPerHour": 20000,
    "appId": "",
    "secretKey": "",
    "tenantId": "",
    "tenantType": "organization"
}'
```
And you will get the `connection id` from response.

BTW, you can also start the pipeline using api
```text
curl --location 'http://{devlake-backend-host}:{port}/pipelines' \
--header 'Content-Type: application/json' \
--data '{
    "name":"MY PIPELINE",
    "plan":[
        [
            {
                "plugin":"teambition",
                "options":{
                    "connectionId":1,
                    "projectId": "",
                    "pageSize": 10
                }
            }
        ]
    ]
}'
```
