### ISSUE TITLE
[Bug][GitExtractor] cloneGitRepo ended unexpectedly: reference delta not found

### ISSUE THREAD

**Issue by richard-fletcher** [apache/devlake#6159]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When importing one git repo I get the following error

`cloneGitRepo ended unexpectedly: reference delta not found`

### What do you expect to happen

The repo would import correctly.

### How to reproduce

Reproduction is challenging as it seems to be caused by something specific to this repository.

### Anything else

I believe that this issue is caused by this bug in `go-git` https://github.com/go-git/go-git/issues/495.

Likely updating the the `go-git` module to the latest version will resolve the issue. I am willing to open a PR with the change but as I am not a go developer I am unable to test it locally.

### Version

v0.19.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Thanks for reporting the issue. I noticed that you checked the box to submit PR yourself. I'm looking forward to your PR.
