### ISSUE TITLE
[Bug][Nginx] Trying to add an webhook to a blueprint with large scope fails with nginx error 413

### ISSUE THREAD

**Issue by aubertaa** [apache/devlake#6160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

- i do have a large scope project (all projects from several dataconnections gitlab, sonarqube, jenkins)
- i try to add an existing incoming webhook to the project configuration
- the PATCH call made from the interface to the backend directly fails with en 413 error from nginx

![image](https://github.com/apache/incubator-devlake/assets/14087776/1a566016-26b3-49bd-a4e5-34098f20274c)

![image](https://github.com/apache/incubator-devlake/assets/14087776/e28d0377-1c6c-4384-a0b8-746a01cf1ff0)

We may notice also the wrong wording on the button ("Confirm")

### What do you expect to happen

project update should be ok

### How to reproduce

- have a large scope project
- have an incoming webhook configured
- try to add incoming webhook to the project configuration (in 'projects > edit > incoming webhooks tab')

### Version

v0.19.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@mintsweet Can you help me take a look at this first?

**Comment by mintsweet** [comment]
Hi @aubertaa thank you for your report.
This looks like an Nginx limitation issue, you can modify the Nginx configuration to bypass it.

```
client_max_body_size  20m; // change to a size that you need
```

**Comment by mintsweet** [comment]
HI @aubertaa, we adjusted our nginx config and you don't need to do anything.
