### ISSUE TITLE
[Bug][Upgrade] Bugs upgrading from 0.16.0-RC9 to v0.18

### ISSUE THREAD

**Issue by robgutsopedra** [apache/devlake#6179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I upgraded from 0.16-RC9 to 0.18 and I’m getting some… Weird scenarios.
First:
I added the encryption secret at:

```
lake:
  image:
  ...
  encryptionSecret:
    secret: {obtained from the previous pod as per the error message/docs}
```

Then:

```
time="2023-10-02 15:43:43" level=info msg="/app/impls/dalgorm/dalgorm.go:230 Error 1054 (42S22): Unknown column 'id' in 'where clause'
[0.491ms] [rows:0] UPDATE `_tool_jira_boards` SET `connection_id`=1 WHERE id = 1"
time="2023-10-02 15:43:43" level=error msg="HTTP 500 error
        caused by: error executing migration (500)
        Wraps: (2) Error 1054 (42S22): Unknown column 'id' in 'where clause' (500)
        Wraps: (3) Error 1054 (42S22): Unknown column 'id' in 'where clause'
        Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError"
Which I “solved” by adding ID field *manually* to _tool_jira_boards
Then I got some “info” logs which seemed problematic, but are at info level.
time="2023-10-02 15:51:10" level=info msg="/app/impls/dalgorm/dalgorm.go:174 invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret; invalid encryptionSecret
```

Now I have devLake, supposedly, up and running, but after creating the token (And successfully testing the notification) I’m stuck at GitHub connection - no repositories appear, no organizations/owners, nothing. I’m using the same token (refreshed, but same) I was using before.
![image](https://github.com/apache/incubator-devlake/assets/101654801/36dfff37-c8d0-4547-8a32-468df3e4b37f)

I’m slightly surprised it is able to connect to the DB (hosted in gcloud), but it’s not able to retrieve any data from it! That’s partially okay, I can re-do that work, but I’m wondering what’s wrong now with the installation.
This is the only thing I see in the pod logs, but maybe I can look somewhere else:

```
GIN] 2023/10/02 - 16:02:28 | 200 |        1.13µs |    10.21.19.218 | GET      "/ping"
time="2023-10-02 16:02:29" level=error msg="HTTP 500 error
        caused by: Key: 'GithubConn.MultiAuth.AuthMethod' Error:Field validation for 'AuthMethod' failed on the 'required' tag
        Wraps: (2) Key: 'GithubConn.MultiAuth.AuthMethod' Error:Field validation for 'AuthMethod' failed on the 'required' tag
        Error types: (1) *hintdetail.withDetail (2) validator.ValidationErrors"
[GIN] 2023/10/02 - 16:02:29 | 500 |      245.23µs |    10.21.19.245 | POST     "/plugins/github/test"
time="2023-10-02 16:02:33" level=error msg="HTTP 404 error
        caused by: record not found (404)
        Wraps: (2) record not found
        Error types: (1) *hintdetail.withDetail (2) *errors.errorString"
[GIN] 2023/10/02 - 16:02:33 | 404 |     3.50676ms |    10.21.19.245 | GET      "/plugins/github/connections/1/remote-scopes"
[GIN] 2023/10/02 - 16:02:38 | 200 |        1.14µs |    10.21.19.218 | GET      "/ping"
[GIN] 2023/10/02 - 16:02:48 | 200 |        1.09µs |    10.21.19.218 | GET      "/ping"
[GIN] 2023/10/02 - 16:02:55 | 404 |        2.57µs |    172.16.70.14 | GET      "/"
[GIN] 2023/10/02 - 16:02:58 | 200 |        1.12µs |    10.21.19.218 | GET      "/ping"
[GIN] 2023/10/02 - 16:03:08 | 200 |         1.4µs |    10.21.19.218 | GET      "/ping"
[GIN] 2023/10/02 - 16:03:18 | 200 |        1.21µs |    10.21.19.218 | GET      "/ping"
[GIN] 2023/10/02 - 16:03:25 | 404 |        2.74µs |    172.16.70.14 | GET      "/"
```

Any ideas or suggestions are greatly appreciated!

### What do you expect to happen

Upgraded version should work!

### How to reproduce

Upgrade from 0.16-RC9 to v0.18 
* With PVs
* With gcloud sql DB
(Try to have some contents on the DB)

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ZhangNing10** [comment]
hi @robgutsopedra, thanks for the report! I am trying to reproduce the issue, but i didn't find the helm chart with version 0.16-RC9, did you mean chart version 0.16.0-beta9 ?

**Comment by ZhangNing10** [comment]
hi @robgutsopedra , unfortunately I can't reproduce the issue, my upgrade finished successfully. Maybe you can   install a new devlake, instead of upgrading the old one

**Comment by khanh96le** [comment]
I encountered the sane error @ZhangNing10

**Comment by ZhangNing10** [comment]
@khanh96le  is it an upgrade? from which version to which version? and how did you do the upgrade?

**Comment by khanh96le** [comment]
> is it an upgrade?
Yes, it is an upgrade.

> from which version to which version?
I upgraded from v0.15.0 to v0.18.0 (got the error), then to v0.19.0-beta1 (still got the error)

> and how did you do the upgrade?
I click to the button in the config-ui
![Screenshot 2023-11-07 at 14 31 46](https://github.com/apache/incubator-devlake/assets/19431276/776d7740-bab4-4c6e-ba78-6d37f21d10d6)

**Comment by ZhangNing10** [comment]
did you get the value for ENCRYPTION_SECRET from old pod before upgrading?

**Comment by khanh96le** [comment]
Yes I did @ZhangNing10, they are exactly the same value
