### ISSUE TITLE
[Bug][Lake] Import inconsistency

### ISSUE THREAD

**Issue by leobonfimm** [apache/devlake#6182]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We are constantly having inconsistencies when importing data from Jira, we run it manually monitoring the pipe and when it runs successfully it brings all the data, but when we put this import into a routine (e.g. daily), the data comes with divergent amounts, we had situations that at different times we had a different amount too.

### What do you expect to happen

Import data correctly.

### How to reproduce

This happens every day.

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, @leobonfimm , Jira supports incremental collection which means it can download new data since the last collection, so it doesn't sound like a problem.
Please provide more detailed information if you believe it is a problem.

**Comment by leobonfimm** [comment]
Hi @klesh, exactly!

**Comment by klesh** [comment]
@leobonfimm ok, thanks for the clarification. will look into it ASAP.

**Comment by leobonfimm** [comment]
Hi @klesh, this is our results during the last days. All the import is the range data set from the beginning of the year.
![image](https://github.com/apache/incubator-devlake/assets/39925352/10f1f4c7-fd5c-4aa3-96af-e3a20b8d73cb)

**Comment by klesh** [comment]
Interesting...
@leobonfimm , Are you having your 2 bps scheduled daily?

**Comment by leobonfimm** [comment]
We have 4 bps running daily schedules at different times.

**Comment by klesh** [comment]
@leobonfimm Seems like they are collecting the same scope with different time ranges which causes the total number of issues to fluctuate depending on which one gets executed first.

**Comment by klesh** [comment]
@leobonfimm No, it should not be a problem for multiple repos belonging to the same connection and used by multiple projects.

I don't have any clue at this point, Do you know what might be the cause of it?

Can you try the latest [v0.19.0-beta5](https://github.com/apache/incubator-devlake/releases/tag/v0.19.0-beta5) and see if the problem persists?

We could arrange an online debugging session if the problem persists, you may contact me on Slack.

**Comment by leobonfimm** [comment]
Hi @klesh, I did what you recommended, we didn't have any errors during the bps pipeline, but we still had problems with the number of issues.

![image](https://github.com/apache/incubator-devlake/assets/39925352/63e64f18-6c11-4438-ba54-ed0026713a17)

**Comment by klesh** [comment]
@leobonfimm It is hard to tell what is wrong without the details of the projects/bps.. I can only hope that you can come up with some theories then I can confirm or help analyze the cause of the problem...

**Comment by leobonfimm** [comment]
Hi @klesh, I understand, do you know when I started to investigate this problem?

And what kind of information do you need that I can share with you?

**Comment by klesh** [comment]
@leobonfimm How about a debugging session on Zoom? Please contact me on Slack if it is ok for you.

**Comment by klesh** [comment]
Seems like the phenomenon came from the `issue_extractor` by looking at the logs of the pipeline from Sunday:
![image](https://github.com/apache/incubator-devlake/assets/61080/7f0a3723-2d8c-4bb8-8877-92f0e3874532)
We were expecting 780 records but the subtask ended at around 452 which is problematic.

With that being said, the cause of the problem is still a mist, I suggest that we deploy a new Apache DevLake onto a new infrastructure and try to collect one of the problematic board to see if we could reproduce the phenonmenon.

**Comment by d4x1** [comment]
It seems a serious problem.  Can you help test it with only two repos in a differnent connection ans see what it happens? @leobonfimm

**Comment by leobonfimm** [comment]
Hi @d4x1, we increased our instance in Google Cloud and stabilized the imports, but with 4 teams, now we start to increase the number of teams to see if it's stable with more teams.

```
db-n1-standard-1	vCPUs: 1 | Memory(MBs):3840
db-f1-micro             vCPUs: 0.2(But in google doc is specify that is a shared cpu) | Memory: 0.6 GB
```

**Comment by d4x1** [comment]
> Hi @d4x1, we increased our instance in Google Cloud and stabilized the imports, but with 4 teams, now we start to increase the number of teams to see if it's stable with more teams.
> 
> ```
> db-n1-standard-1	vCPUs: 1 | Memory(MBs):3840
> db-f1-micro             vCPUs: 0.2(But in google doc is specify that is a shared cpu) | Memory: 0.6 GB
> ```


Thanks for your work. I'll keep an eye on this issue.
