### ISSUE TITLE
[Bug][Jira Blueprint][Urgent] Data sync interrupted by special encoding character

### ISSUE THREAD

**Issue by EvanChen1989** [apache/devlake#6205]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

During syncing jira data through our daily job, it fails with below log:

time="2023-10-09 21:37:46" level=error msg=" [pipeline service] [pipeline #2956] [task #64500] subtask extractIssues ended unexpectedly\n\tWraps: (2) error adding result to batch (500)\n\tWraps: (3) Error 1366 (HY000): Incorrect string value: '\\xF0\\x9F\\x88\\xB4\\xEF\\xB8...' for column 'body' at row 248 (500)\n\tWraps: (4) Error 1366 (HY000): Incorrect string value: '\\xF0\\x9F\\x88\\xB4\\xEF\\xB8...' for column 'body' at row 248\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError"

**It block the whole usage for this part of data, since all the data for recent 6 months are not synced due to this exception, and we're using this board for jira in daily work, please help fix ASAP** 

### What do you expect to happen

1. sync success
2. if the sync fails, I expect to see which raw data processing fails and we can try to update it from jira. Now we can do nothing...

### How to reproduce

no idea, since there's no clue how I can produce such data

### Version

v0.19.0-beta2@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Can you run this command:
```
SELECT character_set_name, collation_name FROM information_schema.columns WHERE table_schema = 'lake' AND table_name = '_tool_jira_issue_comments' AND column_name = 'body';
```
![image](https://github.com/apache/incubator-devlake/assets/101256042/fc295215-c900-4e81-a7f7-cfed355350c7)

**Comment by abeizn** [comment]
![image](https://github.com/apache/incubator-devlake/assets/101256042/3ef48162-51cc-40b1-b2c5-cfd376473faa)

@EvanChen1989  And I didn't reproduce it. This character can be collected normally.

**Comment by abeizn** [comment]
please set CHARACTER_SET_NAME="utf8mb4" and COLLATION_NAME="utf8mb4_bin".
