### ISSUE TITLE
[Bug][Dashboard] No Grafana variables

### ISSUE THREAD

**Issue by MikeAtJulaya** [apache/devlake#6212]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

No variables inside Grafana
![Screenshot 2023-10-10 at 09 20 55](https://github.com/apache/incubator-devlake/assets/127132677/f3235798-713d-4404-978b-d9b82c62260c)
![Screenshot 2023-10-10 at 09 23 12](https://github.com/apache/incubator-devlake/assets/127132677/322dc463-ce8f-4b65-b649-fb3af7dc1a3b)
<img width="1365" alt="Screenshot 2023-10-10 at 15 49 12" src="https://github.com/apache/incubator-devlake/assets/127132677/802096e9-6088-4544-a98c-150b3f13945d">

### What do you expect to happen

To have variables like my Github repositories (actually 9 in the lake database) into Grafana to have metrics. Without metrics nothing are working. 

### How to reproduce

I have just created a new environment (docker) added Jira and Github repos, created a project and run a collect.

### Version

v0.19.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MikeAtJulaya** [comment]
[Slack thread](https://devlake-io.slack.com/archives/C03APJ20VM4/p1696922678102279)

**Comment by Startrekzky** [comment]
I'm looking at it.

**Comment by MikeAtJulaya** [comment]
In Grafana logs when I `run query` on variable `repo_id`:
```
logger=tsdb.mysql t=2023-10-11T08:08:12.965792251Z level=error msg="Query error" error="Error 1045: Access denied for user 'devlake_reader'@'10.0.60.126' (using password: YES)"
```

**Comment by Startrekzky** [comment]
I think this issue has been solved. The root reason was a 'devlake_reader' user was created and this user had no permission to the DB. Feel free to reopen the issue if it still exists.
```
logger=tsdb.mysql t=2023-10-11T08:08:12.965792251Z level=error msg="Query error" error="Error 1045: Access denied for user 'devlake_reader'@'10.0.60.126' (using password: YES)"
```
