### ISSUE TITLE
[Bug][Azure Devops] Invalid Personal Access Token

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#6221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I want to set up an Azure Devops connection, and I have encountered these questions:

1.  I don't know to generate a PAT. After clicking the link,
<img width="823" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/ab71fc16-08e0-4b74-aa28-dd022a9031c0">
go to https://devlake.apache.org/docs/v0.19/Configuration/AzureDevOps/#auth-tokens , there is no efficent guide, only some text like this:
<img width="1186" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/27a3577f-c845-4e9b-98e0-89d0acb671b7">

2. I generate a PAT following https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows, my token is like this: 
<img width="623" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/c506eddb-b27a-4be4-b528-e691c74ab67d">

and I paste it to devlake connection page, it turns out something wrong.
<img width="835" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/9599ef82-4381-4fad-8d7e-7cf02e2cb956">

I have noticed that "Please select ALL ACCESSIBLE ORGANIZATIONS for the Organization field when you create the PAT.", but  my personal access token cannot change this field. I don't know why.

### What do you expect to happen

1. An clear way to help me to generate PAT.
2. My token works well.

### How to reproduce

Just try to use Azure Devops connection, and you will reproduce it.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@keon94  @CamilleTeruel  Can you help me?

**Comment by klesh** [comment]
@CamilleTeruel Thanks, it helps.
