### ISSUE TITLE
[Bug][DB migration] db migration unexpected end of JSON input from v0.19.0-alpha5 to main_231013_0844_62f71ad

### ISSUE THREAD

**Issue by ZhangNing10** [apache/devlake#6248]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After upgrading from v0.19.0-alpha5 to main_231013_0844_62f71ad, db migration failed with unexpected end of JSON input.

2023/10/16 04:02:03 [Recovery] 2023/10/16 - 04:02:03 panic recovered:
GET /proceed-db-migration HTTP/1.1
..............................
unexpected end of JSON input
/app/core/errors/util.go:34 (0x12e2499)
/app/core/models/migrationscripts/20230829_normalize_bp_settings.go:86 (0x12e1fed)
/app/core/migration/migrator.go:95 (0x15696ea)
/app/server/services/init.go:114 (0x15778ab)
/app/server/api/api.go:84 (0x158ff84)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x11f7861)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x11f784c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x11f6986)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x11f6969)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x11f580a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x11f5491)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x11f4fbc)
/usr/local/go/src/net/http/server.go:2936 (0xcb1575)
/usr/local/go/src/net/http/server.go:1995 (0xcac711)
/usr/local/go/src/runtime/asm_amd64.s:1598 (0x99ca80)

### What do you expect to happen

db migration succeed

### How to reproduce

upgrading from v0.19.0-alpha5 to main_231013_0844_62f71ad

### Version

v0.19.0-alpha5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@klesh  Please have a look at it.
