### ISSUE TITLE
[Bug][GitHub] Task error 3988 when collecting data from GitHub Enterprise

### ISSUE THREAD

**Issue by gabytal** [apache/devlake#6259]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dear Devlake developers,
We got this error for a Github task when tried to run a pipeline.

`subtask extractApiPullRequests ended unexpectedly Wraps: (2) Error 3988 (HY000): Conversion from collation utf8mb4 0900 ai ci into utf8mb3 general ci impossible for parameter (500) Wraps: (3) Error 3988 (HY000): Conversion from collation utf8mb4 0900 ai ci into utf&mb3 general ci impossible tor parameter Error tvpes: (1) *hintdetail.withDetail (2) *hintdetail.withDetail(3) *mysql. MvSQLError`

![image](https://github.com/apache/incubator-devlake/assets/45428645/99cc5564-1634-4fd9-9efe-759debd8a232)

![image](https://github.com/apache/incubator-devlake/assets/45428645/7c1dec53-2e28-4422-89bd-8844c450b57b)

Couldn't find anything helpful from logs.

devlake:[v0.18.0](https://github.com/apache/incubator-devlake/releases/tag/v0.18.0)
database: mysql

Thanks. 
Appreciate any kind of help.

### What do you expect to happen

Expect for the task to be completed successfully

### How to reproduce

1. Browse to https://devlake/projects/testproj?tab=status
2. Press "Collect All Data"

### Anything else

it happens only for some Github repos, some other Github tasks are OK

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mkaufmaner** [comment]
This error is intermittent for some repositories in GitHub enterprise.

<img width="652" alt="Screen Shot 2023-10-16 at 1 25 25 PM" src="https://github.com/apache/incubator-devlake/assets/2073135/8f718761-3bc3-4248-ba36-4f1ec38fb548">

**Comment by d4x1** [comment]
@gabytal  What's your MySQL version  and have you upgrade it from a lower version?

**Comment by abeizn** [comment]
Can you check the character set? 
SELECT character_set_name, collation_name FROM information_schema.columns WHERE table_schema = 'lake';

And please set CHARACTER_SET_NAME="utf8mb4" and COLLATION_NAME="utf8mb4_bin".
related to https://github.com/apache/incubator-devlake/issues/6205

**Comment by klesh** [comment]
@cicdguy I agree, just need to figure out a solution for MySQL while not affecting Pg

**Comment by mkaufmaner** [comment]
> Can you check the character set? SELECT character_set_name, collation_name FROM information_schema.columns WHERE table_schema = 'lake';
> 
> And please set CHARACTER_SET_NAME="utf8mb4" and COLLATION_NAME="utf8mb4_bin". related to #6205

@abeizn This worked. Also had to run a script to change the existing charset and collation for all tables.

```
-- To get the SQL to run for all devlake tables
SELECT CONCAT('ALTER TABLE ', tbl.TABLE_SCHEMA, '.', tbl.TABLE_NAME, ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;') FROM information_schema.TABLES
 tbl WHERE tbl.TABLE_SCHEMA = 'devlake'
```

**Comment by michaelawarren** [comment]
I'm seeing this issue too. Will try the work around. would be nice if the DB setup/migration did this automatically.
