### ISSUE TITLE
[DORA Metrics][Median Lead time for changes] configurable statuses for start and end time

### ISSUE THREAD

**Issue by dwaghulade** [apache/devlake#6263]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Our report is showing very high number and when reviewed query and results, found that it is considering time between JIRA ticket created and when ticket is resolved/closed.
In our case, we are looking for time between status changed to In Dev  and changed to In QA/IN UAT.

### Description

Need below considerations for "Median Lead time for changes" Dora metrics

- the start time of Change lead time should be: the time a ticket changed to In Dev status?
- while the end time of Change lead time is: the time a ticket changed to QA/IN UAT status?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @dwaghulade , the change lead time defined in DORA is between
- start time: PR's first commit's authored date
- end time: commit gets deployed to the production environment

Please refer to this doc: https://devlake.apache.org/docs/Metrics/LeadTimeForChanges#how-is-it-calculated

The example you wrote is the definition of another metric in DevLake, which is [Issue Lead Time](https://devlake.apache.org/docs/Metrics/RequirementLeadTime).

My understanding is that you want a metric that measures the duration between `the time a ticket changed to In Dev status` and `the time a ticket changed to QA/IN UAT status`. I think it's doable if you have the data collected. 

May I ask how can we get the two time? Through issue changelogs, or do you have two fields to log these?

**Comment by Startrekzky** [comment]
@dwaghulade If you already have Jira issues collected. Can you query:

```
select * from issue_changelogs where issue_id = 'An id in table issues'
```

to check if a Jira issue's entire status transition logs are collected?

**Comment by dwaghulade** [comment]
Yes, Jira issues are collected which can be confirmed on the dashboard. Please refer to below screenshot. However "select * from issue_changelogs where issue_id = 'An id in table issues'" query is returning empty result.

***@***.***

***@***.***


Regards,
Dhiraj Waghulade| Project Manager, LTIMindtree-EA | Desk +1 512 687 9758 | Cell +1 512-665-9513 | email: ***@***.******@***.***>

**Comment by Startrekzky** [comment]
@dwaghulade It should be collected, did you replace the 'An id in table issues' with the real value of the issue id?

**Comment by dwaghulade** [comment]
Thanks; my mistake, I didn't notice query require replacing value with actual id.

Yes, issue logs are getting collected. In below example, we would like to consider time between when original_to_value changed to In Dev and changed to In QA. Current report is referring time between ticket created and to_value changed to DONE. When we refer status it is just considering TODO, IN_PROGRESS & DONE.

***@***.***

Regards,
Dhiraj Waghulade| Project Manager, LTIMindtree-EA | Desk +1 512 687 9758 | Cell +1 512-665-9513 | email: ***@***.******@***.***>

**Comment by dwaghulade** [comment]
Any updates on above request please?

**Comment by Startrekzky** [comment]
> Yes, issue logs are getting collected. In below example, we would like to consider time between when original_to_value changed to In Dev and changed to In QA. Current report is referring time between ticket created and to_value changed to DONE. When we refer status it is just considering TODO, IN_PROGRESS & DONE.


Hi @dwaghulade . In your case, you have to write your own query to get the result. The logical steps are:
1. Join table [issues](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#issues) with table [issue_changelogs](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#issue_changelogs) to get all issues' time of transitioning to 'In Dev' and time of transitioning to 'In QA'. 
2. Diff the two time-fields to get the lead time of every issue
3. Calculate the median lead time of all issues

It's a complicated SQL so you can follow the [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#issue_changelogs) and [metric examples](https://devlake.apache.org/docs/Metrics/RequirementLeadTime#how-is-it-calculated) to figure it out.
