### ISSUE TITLE
[Bug][Teams] Cant link a user to multiple teams 

### ISSUE THREAD

**Issue by rogeriospinaintelipost** [apache/devlake#6264]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I create a team user linked to multiple teams, their DORA deployments appears for every team he belongs.

### What do you expect to happen

I expect to see DORA metrics by team, and devlake to understand for which team that deployment is.

### How to reproduce

- Create Team A and Team B, and Project X
- Create a user and link it to both teams (A,B)
- Send webhook deployment for Project X
- See DORA (by Team), both teams will show the same deployment in "Monthly deployments" panel

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Startrekzky please take a look at the problem, thanks.

**Comment by Startrekzky** [comment]
Can you tell us how you organize your projects and teams in your organization, and how each project/team manages repos/issues/deployments? Please refer to the use cases in this doc https://devlake.apache.org/docs/GettingStarted/HowToOrganizeDevlakeProjects#4-use-cases

**Comment by rogeriospinaintelipost** [comment]
@Startrekzky, it also leads to another problem. When a user switches to another team, their authored deployments go with them. I expected that those deployments would remain tied to the team
