### ISSUE TITLE
[Bug][Lake] LOGGING_DIR is not writable by default

### ISSUE THREAD

**Issue by cicdguy** [apache/devlake#6265]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

`LOGGING_DIR` is not writable on the apache/devlake Docker images. This results in an unhandled exception and crash of the lake container when logs aren't able to write to the devlake.log file on `/app/logs`. 

### What do you expect to happen

App should not crash if logs are unwritable.

### How to reproduce

Run it on a k8s cluster where the default user is _not_ root and the `seucrityContext` has non-root settings.

### Anything else

Override of `LOGGING_DIR` works, but it's a hacky workaround to overcome a simple solution (which is a directory permissions fix).

### Version

v0.18.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@cicdguy Looks good to me, thanks for volunteering, and happy coding. 😊
