### ISSUE TITLE
[Bug][Connections] Pages in the Data Scope breaks if you add too many items

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#6278]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have added more than 500 Data Scope and the page is not displaying all the pages.

### What do you expect to happen

The page could be paged as well in blocks of 10 pages for large volumes.

### How to reproduce

Add more Data Scope that your screen can display.

Here is a print of the problem:

![Screenshot 2023-10-18 at 2 20 12 PM](https://github.com/apache/incubator-devlake/assets/17132893/677b043d-8d0f-4efb-8a42-2f03a076e2df)

### Version

v0.19.0-beta4@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@mintsweet can you take a look?
