### ISSUE TITLE
[Bug][Projects] Jenkins connection Data Scope does not display all selected ones

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#6279]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After selecting some Jenkins Data Scope, the table with the selected ones does not display all the selected ones.

Check the screenshots:
![Screenshot 2023-10-18 at 4 17 51 PM](https://github.com/apache/incubator-devlake/assets/17132893/a301ed30-13f3-4fd3-ab64-a617b37f85ca)
![Screenshot 2023-10-18 at 4 20 25 PM](https://github.com/apache/incubator-devlake/assets/17132893/5961d17b-6fe6-4dcb-8edb-ff1b1bce07bd)

### What do you expect to happen

I expect to see all the selected ones in the table.

### How to reproduce

I tried to add the items again, and it still not displaying in the list even if the count still shows them all.

### Version

v0.19.0-beta4@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, @msarzijr Thanks for reporting the issue, However, I couldn't reproduce the phenomenal on my local machine.
Do you mind sharing the API response of the `/api/blueprints/<bp_id>`, you should be able to find them on the Developer Toolbar.
Or could you identify the pattern between the showing and hidden ones? I suspect it is the names of the scopes that causing the problem, but don't know exactly how without the actual data.

**Comment by msarzijr** [comment]
@klesh, here is the API data; the exciting part is that it is returning the 6 lines (I changed) and displaying only 4.
![Screenshot 2023-10-19 at 9 47 58 AM](https://github.com/apache/incubator-devlake/assets/17132893/7cc45160-0cd5-4318-b42b-ac3a288d6864)

**Comment by msarzijr** [comment]
By the way, the same happens with GitLab repos.

**Comment by klesh** [comment]
I suspect that the missing scopes on the project page do not actually exist on the Connection Detail page, can you verify that?
If that is true, I would like to know why it happened, did you delete them on the Connection Detail page, or in the database, or the project is actually created by calling the  API with scope_ids that don't exist in the database?

**Comment by micheleangioni** [comment]
Unfortunately the same happens for GitHub. Example:

1. Initially 2 repos are selected, I add other 2 repos to have 4
![image](https://github.com/apache/incubator-devlake/assets/7933034/7906027a-5c4e-4ebf-a76a-bd0bd2b757d9)

2. I get the confirmation message "Update data scope successful." but it keeps showing only 2 repos
![image](https://github.com/apache/incubator-devlake/assets/7933034/b9dbee65-af48-4bd8-aa0f-60bbda7cc11c)

**Comment by msarzijr** [comment]
@klesh I tried to add some without the scope, and it worked. 
![Screenshot 2023-10-20 at 10 16 42 AM](https://github.com/apache/incubator-devlake/assets/17132893/5102d958-0efb-44a1-b87b-1d787eec2cc2)

And we both are using the Config UI only to maintain the configuration.

**Comment by msarzijr** [comment]
@klesh what looks like is, that as we have lots of pipelines (1000+), it looks like when we select pipelines from the bottom of the list that need to be paged loaded, those are not shown in the table after added.

**Comment by klesh** [comment]
@msarzijr Can you activate the Developer Toolbar by pressing C-S-i and then enter the page and see if any requests to path like `/plugins/xxx/scopes/yyy` with 404 status code?
