### ISSUE TITLE
[Feature][Config UI] Add search option on all Data Scope selection

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#6290]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Add a filter for Data Scope on all available connections.

![Screenshot 2023-10-19 at 11 44 13 AM](https://github.com/apache/incubator-devlake/assets/17132893/cfc8c770-84f1-4554-99ab-9b380ac8b36c)

### Description

When you have thousands of repositories, and pipelines it becomes complex to use the UI to set the Data Scope.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Collecting votes

**Comment by d4x1** [comment]
@msarzijr  Jenkins scopes can be searched by keyword. 
Do you mean devlake add more search options(filters)?  In fact, it depends on the thrid-party's API.  We can do something on it, but it's  hard to make an easy to use filter.

**Comment by klesh** [comment]
I think @d4x1 is right, I thought it was about the Project page and I was wrong.

For the connection detail page, the scopes are returned by the Remote Data Source  API, some of them do not support searching at all, and Jenkins is unfortunately one of them.

Sorry, this is undoable.

**Comment by micheleangioni** [comment]
Hey @klesh ,
what about GitHub and Jira?

The problem is that DevLake becomes quickly unusable when there are many repositories (or Jira boards). 
If making a good-for-all search is not feasible, at least an ad-hoc for GitHub should be considered.

As said, the problem is that it makes DevLake unusable, which defeats the purpose of the whole project.

For Jenkins some workarounds could be used, like showing a loading gif while fetching the all the repos and having the search on the Frontend. What do you think?

**Comment by msarzijr** [comment]
@d4x1, we also have the option to filter what is in the list to start. I do prefer to have it from the API when available. I know the management of paging and filter makes it more complicated, but it would be best to have API search and Paging management all together.

**Comment by msarzijr** [comment]
@klesh it is doable, just a little harder. Even for the ones without search options from the api, we always can load all the data and do the search in the browser.

**Comment by MarcViola** [comment]
Hi, came here to request a similar feature.  Is it possible to just have a filter field at the top of every pages (projects, connections, scope, etc.) to filter the list on the page?  For example, I have projects over several pages, I would like to see only projects with a certain name.  It's basically a filter on the UI which has all the information already.  Thanks.

**Comment by klesh** [comment]
@msarzijr Well, in this case, yes, it is doable... However, there will be usability issues, for example, it may take a long time to load and process all pages, and that is a good idea. Loading all pages is NOT a good practice, or don't need pagination in the first place.

@micheleangioni I believe Github and Gitlab are searchable under the Connection detail page.
![image](https://github.com/apache/incubator-devlake/assets/61080/18e4a320-f256-46a8-9760-db1afa7fd78c)a

@MarcViola Do you mean the same thing to @msarzijr ? filtering on the front end?

**Comment by MarcViola** [comment]
Hi, yes.  But also on other screens as well.  Thanks.

**Comment by Startrekzky** [comment]
This is supported in v0.20 beta versions. Please check it out.
