### ISSUE TITLE
[Feature][Config UI] Add search option and order by in all selected Data Scope selection

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#6291]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Here is the idea:
![Screenshot 2023-10-19 at 11 47 52 AM](https://github.com/apache/incubator-devlake/assets/17132893/21d54995-60de-4170-b693-b6fe7833afa7)

### Description

When we have thousands of repositories and pipelines to maintain it becomes essential to search and order the selected data. Related to the issue #6290 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for reporting the issue, will look into it later,

**Comment by msarzijr** [comment]
@klesh they are on different pages, and it will be nice to have both. When you have 1000+ items both are super important.

**Comment by klesh** [comment]
@msarzijr I see, thanks for the clarification. the search option is doable on this page because records come from the local database, I think they are both reasonable and the search option is more important than sorting.
