### ISSUE TITLE
[Bug][Azure MySQL] Error at Azure Mysql Database Flexible on Migration Step Devlake

### ISSUE THREAD

**Issue by osanam-giordane** [apache/devlake#6292]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I try run firt time Apache Devlake and start "Proceed to Migration" I receive this information on lake pod:

**error executing migration (500) Wraps: (2) Error 1235 (42000): This version of MySQL doesn't yet support 'existing primary key drop without adding a new primary key. 

In @@sql_generate_invisible_primary_key=ON mode table should have a primary key. Please add a new primary key to be able to drop existing primary key.' (500) Wraps: (3) Error 1235 (42000): This version of MySQL doesn't yet support 'existing primary key drop without adding a new primary key.**

![image](https://github.com/apache/incubator-devlake/assets/22400043/2edc4a27-bb79-467a-816d-8f6f24d7cd45)

![image](https://github.com/apache/incubator-devlake/assets/22400043/1143ea8e-4b5c-4f42-9a80-9304d751419b)

I´m using Azure Mysql Flexible and tried disable sql_generate_invisible_primary_key and remove PK´s and not resolved. 
Mysql version 8.0 and not have another available version at Azure MySQL.

References:

https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-limitations#generated-invisible-primary-keys
https://dev.mysql.com/doc/refman/8.0/en/create-table-gipks.html
https://github.com/prisma/prisma/issues/20944

### What do you expect to happen

Expected Apache DevLake run correctly migration and allow access at tool.

### How to reproduce

I´m using Azure Kubernetes Service (AKS) and Azure MySQL Flexible version 8.0.
Apache Devlake v0.18.0 latest installed with Helm Chart.

### Version

latest version and v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@keon94 @CamilleTeruel Please help take a look when you find time, thanks.

**Comment by d4x1** [comment]
@osanam-giordane  
Have you tried to disable GIPK following [this guide](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-limitations#steps-to-disable-gipk) ?
If you disable it, it won's return errors theoretically.

And if you want to dive into it, after disabling it, you can create a test table and run command `ALTER TABLE {test_table_name} DROP PRIMARY KEY` and  see what will happe.


And if you build devlake from source code, I think you can remove this line https://github.com/apache/incubator-devlake/blob/main/backend/python/plugins/azuredevops/azuredevops/migrations.py#L148   (@keon94 please help to confirm it.)

**Comment by osanam-giordane** [comment]
Hi @d4x1 I tried disabke GIPK and wasn´t resolved.

For build source code for me it´s impossible because I use pipelines for deploy this and when another release will created I need to change this line again and is it not help me.

The problem is with Azure Mysql, I tried last weekend on AWS and GCP and ran properly.

I´ll open a ticket at Microsoft for understand how I can resolve this.

Thanks for help folks!

**Comment by d4x1** [comment]
> Hi @d4x1 I tried disabke GIPK and wasn´t resolved.
> 
> For build source code for me it´s impossible because I use pipelines for deploy this and when another release will created I need to change this line again and is it not help me.
> 
> The problem is with Azure Mysql, I tried last weekend on AWS and GCP and ran properly.
> 
> I´ll open a ticket at Microsoft for understand how I can resolve this.
> 
> Thanks for help folks!

@osanam-giordane  Looking forward to receiving a response from Microsoft

**Comment by rahulbhadja** [comment]
@osanam-giordane, hey did you receive anything from Microsoft?

**Comment by GuillermoGarciaF** [comment]
I confirm I get the same error when using Azure MySQL Flexible Server
MySQL version: 8.0

**Comment by michal-partyka-knauf** [comment]
@osanam-giordane, were you able to solve it? I'm having the same problem, also tried disabling GIPK.
