### ISSUE TITLE
[Bug][Database] Support with MariaDB

### ISSUE THREAD

**Issue by daviddsp** [apache/devlake#6305]
## Question
Hello Devlake Team,

I am currently using Devlake version 18 and have encountered issues while trying to calculate the 75th and 90th percentiles using the `percentile_disc` and `percentile_cont` functions in MySQL. I have searched through various forums and learned that MariaDB supports these functions.

Could you please confirm if Apache Devlake is compatible with MariaDB, or if there is any workaround available to calculate percentiles in MySQL for the current version of Devlake? 

Your guidance and support would be highly appreciated.

Best regards,

**Comment by klesh** [comment]
Hi, @daviddsp We haven't tested it yet, but MariaDB is folked from Mysql, they are most likely compatible.
It will be great if you would like to test it and let us know the result.

**Comment by klesh** [comment]
Glad it worked, I'm closing the issue, free feel to reopen or file new ones if needed.
