### ISSUE TITLE
[Feature][Module Name] OpsGenie Plugin

### ISSUE THREAD

**Issue by hmilkovi** [apache/devlake#6347]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

View alerts and incident from opsgenie in relation to deployments or code changes.
Same as PagerDuty.

### Description

Pool alerts, teams, priority same as PagerDuty

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
We have covered it via #6154 which will be merged in the next milestone.
Closing the issue for now, feel free to reopen if needed.
