### ISSUE TITLE
[Bug][GitLab] The accounts table contains only empty values for created_date field

### ISSUE THREAD

**Issue by antoniomuso** [apache/devlake#6362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The accounts table contains only empty values for `created_date` field. see:
```sql
SELECT  *
FROM lake.accounts
```
![image](https://github.com/apache/incubator-devlake/assets/16511436/dccbdb32-9bfa-491d-b33a-d8534cd8941c)

### What do you expect to happen

`created_date` should be not empty.

### How to reproduce

```sql
SELECT  *
FROM lake.accounts
```

### Anything else

Current Gitlab Version: [v16.4.1-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.4.1-ee)

### Version

v0.18.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @antoniomuso , I saw you marked

**Comment by d4x1** [comment]
@antoniomuso It's reasonal, because we don't fetch account's created_data in GitLab.

**Comment by antoniomuso** [comment]
Yes, I can. I want to estimate the onboarding time for my company, from the time when the user account is created to the time it does the first commit. 
For this reason, I need `created_data` field.

**Comment by Startrekzky** [comment]
@antoniomuso Got it. That makes sense.

**Comment by antoniomuso** [comment]
Hi @Startrekzky, I started working on the PR but am currently blocked. Can you give me some tips on PR?

**Comment by Startrekzky** [comment]
Hi @keon94 , can you help him with the issue, please?
