### ISSUE TITLE
[Bug][GitHub] DevLake does not display list of repos for larger organizations when trying to create a data scope for a GitHub connection

### ISSUE THREAD

**Issue by bobwilkinson20** [apache/devlake#6364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have successfully configured a GitHub connection (classic PAT, GraphQL on). From that connection, I have repos directly owned in my account along with access to two organizations that are part of our corporate infrastructure.

When trying to create data scopes using that connection, DevLake is able to list my directly owned repos (there are only 3) along with repos from the smaller of the two organizations (there are 233 repos). It hangs, however, trying to list repos from the larger organization (there are 438 repos).

Working organization:
![Screenshot 2023-10-30 at 9 37 03 AM](https://github.com/apache/incubator-devlake/assets/53875715/57e5634b-b22d-4433-b161-96314ca92cd5)

Non-working organization:
![Screenshot 2023-10-30 at 9 39 09 AM](https://github.com/apache/incubator-devlake/assets/53875715/4855c1ba-36cc-46ca-97ed-b01da653f3b3)

### What do you expect to happen

Should see the repo list, regardless of the number of repos.

### How to reproduce

1. Create an GitHub connection using classic PAT, GraphQL on
2. Create enough repos to trigger the issue (233 works, 438 does not, unsure where the exact breakpoint is) .
3. Try to Add a new Data Scope for the GitHub connection, then select the large organization 
4. Observe that the repositories list on the right side of the pane does not complete loading.

### Anything else

Reproduces 100% of the time

### Version

Apache 2.0 License v0.18.1-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bobwilkinson20** [comment]
I discovered what the issue was - turns out not to be related to the number of repos at all.

The problem was that the problematic organization require explicit authorization on the PAT. Once I authorized for the organization, the list worked normally.

I will close out this issue and instead create a new one to display an error message of some sort rather than spin forever.

**Comment by d4x1** [comment]
Agreed!

**Comment by Startrekzky** [comment]
This is caused by another problem tracked in #6365
