### ISSUE TITLE
[Bug][Bitbucket]The Bit Bucket PR metrics values show a discrepancy: the Pickup time and review time are not matching when compared, and they appear to be too high.

### ISSUE THREAD

**Issue by naveenreddymanukonda** [apache/devlake#6367]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We are using Bitbucket as our code repository, and we've noticed that the pull request (PR) pickup time and PR review time do not match when we cross-check them with the values from the PRs.

The first comment was added within 24 hours of the PR being opened, on 2023-10-19, but the PR pickup time is currently indicating 331 hours.

![image](https://github.com/apache/incubator-devlake/assets/40488776/b9fe3c00-7933-45af-9f71-d1280e680805)

![image](https://github.com/apache/incubator-devlake/assets/40488776/70c5fdb7-27d8-4231-8431-1c738ec682ce)

### What do you expect to happen

In this scenario, the PR cycle time should align with the time the first comment was provided on the PR, which should be approximately 13 hours.

### How to reproduce

To collect data on the PR cycle time and PR review time for a Bitbucket project where you send a PR, merge it on the same day with a few comments, and then analyze the times, follow these steps:

Create a Bitbucket Project:

Log in to your Bitbucket account.
Create a new Bitbucket project if you haven't already.
Create a Repository:

Within your Bitbucket project, create a new repository.
Fork the Repository:

Fork the repository to your account.
Clone the Repository:

Clone the forked repository to your local machine.
Make Changes and Commit:

Make some code changes.
Commit the changes and push them to the forked repository.
Create a Pull Request (PR):

Create a new pull request from your forked repository to the original repository.
Add a few comments to the PR for review.
Merge the PR:

Once the PR is reviewed and approved, merge it on the same day.
Collect Data:

Make note of the date and time when you opened the PR and when it was merged.
Calculate PR Pickup Time and PR Review Time:

Compare the calculated PR pickup Time and PR Review Time to understand how long it took for the entire PR process and how long the initial review took.

### Version

v0.19.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @naveenreddymanukonda , I reproduced it on my local environment. It seems there's a bug about the pr_comments' `created_date`. Please check it out @d4x1 

![image](https://github.com/apache/incubator-devlake/assets/14050754/3c45dd42-a1fb-4664-b8a7-edfc101ebaa4)

![image](https://github.com/apache/incubator-devlake/assets/14050754/b1bc5cf7-6370-4b41-829a-d2ac60d34065)

![image](https://github.com/apache/incubator-devlake/assets/14050754/3dd2ed0e-7763-4499-acfa-38d6a9d16e57)

**Comment by naveenreddymanukonda** [comment]
Can you please let me know when this is going to be released? @d4x1 @Startrekzky

**Comment by d4x1** [comment]
I think we can cherry pick this to v0.19 if necessary. @Startrekzky

**Comment by Startrekzky** [comment]
Hi @naveenreddymanukonda , this fix will be included in v0.20.0-beta1, estimated to be released within this week.
