### ISSUE TITLE
[Bug][GitHub dashboard] Typo Merged PRs instead of NON-Merged in two metrics 

### ISSUE THREAD

**Issue by lana-holmen** [apache/devlake#6407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Metric 4.1. name is "Ratio of Non-merging PRs to All Closed PRs"
but a query is based on "Merged PRs" to "Closed PRs" (and this looks right based on data).

### What do you expect to happen

Metric 4.1. re-name as "Ratio of Merged PRs to All Closed PRs"

### How to reproduce

I can see it in dashboards for all our teams onboarded.
It's a current status. No need to reproduce.

### Version

v.0.19.0.beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks @lana-holmen , are you interested in putting up a PR to fix it?

**Comment by lana-holmen** [comment]
Hi @Startrekzky , yes:)
as it's not urgent, let me to do it - it takes some time as I have not done it before here.

**Comment by Startrekzky** [comment]
@lana-holmen Perfect. I've assigned it to you. Take your time.

**Comment by klesh** [comment]
Hi, @lana-holmen You may removing the "Stale" label if you are working on the issue, thanks.
