### ISSUE TITLE
[Bug][Config UI] Blueprint detail page shows TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by felipesbs** [apache/devlake#6411]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When i try to view details of blueprint, the system show error

![image](https://github.com/apache/incubator-devlake/assets/23387404/a1ba641d-85ec-46b1-9be4-5888c499f1d6)

### What do you expect to happen

View Details of the blueprint 

### How to reproduce

Go to Advance option in the left side-bar and select details on the blueprint.

### Anything else

The problem occur when i try to enter a blueprint details in advance option.

### Version

v.0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@felipesbs Thanks for reporting the issue, would you like to upgrade to latest v0.19-rc2 and see if the problem persists?

**Comment by felipesbs** [comment]
@klesh Hi! I Apply the upgrade to v.0.19-rc2 but the problem persists.
![Recording 2023-11-13 at 10 29 38 (2)](https://github.com/apache/incubator-devlake/assets/23387404/2bc0b41d-e955-483d-8d93-417edab48a20)

**Comment by klesh** [comment]
@mintsweet Please help.

**Comment by mintsweet** [comment]
Hi @felipesbs, can you provide a response about this API?

![image](https://github.com/apache/incubator-devlake/assets/37237996/1301951e-d90f-465b-b49c-becd9fd5ace9)

**Comment by felipesbs** [comment]
@mintsweet Hi!...sure this is response
![image](https://github.com/apache/incubator-devlake/assets/23387404/c4ae7502-de9a-4898-9433-08dba34b069f)

**Comment by mintsweet** [comment]
@felipesbs Hi, can you expand the settings item?

**Comment by felipesbs** [comment]
@mintsweet sure!
![image](https://github.com/apache/incubator-devlake/assets/23387404/47c0bc00-9016-4bd6-bd8b-d47245aa253b)

**Comment by mintsweet** [comment]
@felipesbs Hi, I only want to check the connections, can you show all connections?

**Comment by felipesbs** [comment]
@mintsweet 

![image](https://github.com/apache/incubator-devlake/assets/23387404/c4cefa0e-b84c-47f7-b0f6-0746d5ded396)

Details.
![image](https://github.com/apache/incubator-devlake/assets/23387404/605a300e-1f8a-4151-b947-9e6fc62783ad)
![image](https://github.com/apache/incubator-devlake/assets/23387404/18a6de9d-e630-47b3-9138-3e3b7f3ad4a9)
![image](https://github.com/apache/incubator-devlake/assets/23387404/247a6b4c-b1be-467b-8c8f-b1d3fb26d4d9)

**Comment by mintsweet** [comment]
@felipesbs, Can you check whether the GitLab connection with id 1 exists in the GitLab connection list?

**Comment by mintsweet** [comment]
@felipesbs What is your current version?

**Comment by felipesbs** [comment]
v.0.18.0

**Comment by mintsweet** [comment]
@felipesbs Sorry, I don't have any ideas about this issue at the moment. I may need to debug it online. I'll see when you have time.

**Comment by felipesbs** [comment]
@mintsweet that is bad for me :( , where are you locate and what is the timezone?

**Comment by mintsweet** [comment]
@felipesbs utf8

**Comment by felipesbs** [comment]
Hello any can help me with this problem?  Right now this bug block me for advance in migration to the new version of Devlake from v.0.14.6 to  v.0.19.0
