### ISSUE TITLE
[Feature][GitLab Issue Tracking] Include Data Transformation for GitLab Issue tracker

### ISSUE THREAD

**Issue by en-henciso** [apache/devlake#6435]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

GitLab Issue tracker is currently supported by devlake but Data Transformation for it is not implemented

If I go to the Scope COnfig I select all of them including Issue Tracker 
![image](https://github.com/apache/incubator-devlake/assets/142229524/ec6976d9-269a-4baa-9a90-b1896076b1dd)

but next in Data Transformation, it's just available the CICD
![image](https://github.com/apache/incubator-devlake/assets/142229524/9dfd0817-29a7-47d7-86a2-ecdf74b58114)

If I compare it with GitHub Data Transformation I notice we can edit CICD and others like Issue Tracking, cross domain and code review
![image](https://github.com/apache/incubator-devlake/assets/142229524/67968a6f-7669-40fd-95c1-46fba513d3f9)

In this case, Issue Tracking is required to measure my DORA metrics

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@clement-igonet  I think @en-henciso  wants to normalise mussy GitLab issues into `Requirement` `Bug` or `Incident`.
@Startrekzky Please follow up this issue.

**Comment by Startrekzky** [comment]
Hi @en-henciso , may I know what exactly you want to achieve with the issue tracking or code review configurations?
