### ISSUE TITLE
Launch DevLake

### ISSUE THREAD

**Issue by Dionusia** [apache/devlake#6440]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I followed the steps to launch devlake and i also saw DevLake Quick Setup Guide in Youtube and when i finish the steps and open the browser to connect to localhost:4000, i get New Migration Scripts Detected, i select the option proceed to database migration and i get error executing migration (500) Wraps, so i can't continue

### What do you expect to happen

I should be able to visit the localhost:4000 after following the steps

### How to reproduce

I tried everything i found but nothing works

### Version

v0.19.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Was it a brand new installation or upgrade from an older version?

**Comment by Dionusia** [comment]
It was a brand new installation following the exact steps.

Στις Δευ 13 Νοε 2023 στις 12:27 ο χρήστης Klesh Wong <
***@***.***> έγραψε:

**Comment by klesh** [comment]
@Dionusia That is not right, you should not be seeing "New Migration Scripts Detected" for a new installation.
Please make sure the database you are using is Empty.

**Comment by Dionusia** [comment]
I did again the installation from scratch and now when i visit
localhost:4000 i get:
DevLake APIOffline

DEVLAKE_ENDPOINT: /api

Please wait for the Lake API to start before accessing the Configuration
Interface.

Στις Τρί 14 Νοε 2023 στις 5:07 π.μ., ο/η Klesh Wong <
***@***.***> έγραψε:

**Comment by Dionusia** [comment]
sorry i found the solution for this, now everything is running fine!

Στις Σάβ 18 Νοε 2023 στις 6:26 μ.μ., ο/η Dionusia Psiri <
***@***.***> έγραψε:

**Comment by klesh** [comment]
Glad to know, closing issue now
