### ISSUE TITLE
[Bug][Azure DevOps] Git Extractor task failing with status code: 400

### ISSUE THREAD

**Issue by en-henciso** [apache/devlake#6441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

On DevLake v0.19.0-beta6 AzureDevOps git extractor task is failing with status code: 400

PAT it's fine and the project configuration is as well.
I recreated the same scenario using the same PAT with the same AzureDevOps project and it worked fine
![image](https://github.com/apache/incubator-devlake/assets/142229524/544fdbbf-a2f9-4748-a43d-b5bcdb1f3fae)

### What do you expect to happen

get project data

### How to reproduce

create azure connection -> data scope -> project and asociate connection to the project -> collect data

### Version

v0.19.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@en-henciso I don't understand, it is fine in one project while failing in another or what? or it is working when gitextractor gets disabled? 
And the screenshot you shared contains sensitive information, I suggest that you revoke it.

@keon94 Would you like to follow up the issue? thanks

**Comment by en-henciso** [comment]
this issue is fixed in version 0.20.0-beta1
