### ISSUE TITLE
[Bug][Gitlab] `Deployable.Commit.Message` can be bigger than 255

### ISSUE THREAD

**Issue by antoniomuso** [apache/devlake#6455]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Pipeline crash when `Deployable.Commit.Message` is bigger than 255: https://github.com/apache/incubator-devlake/blob/c1e0310a6b965e9f6e64e54a709690bf1a8f6b95/backend/plugins/gitlab/tasks/deployment_extractor.go#L102 

### What do you expect to happen

Pipeline is executed without crash.

### How to reproduce

You can reproduce by adding into GitLab a commit message bigger than 255.

### Version

v0.20.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @antoniomuso , do you mean that you have a commit message longer than 255? How did that happen?

**Comment by antoniomuso** [comment]
I don't know, but I have it. Maybe the commit message includes the commit body.

**Comment by Startrekzky** [comment]
@antoniomuso May I know why the commit message included the commit body? I asked because IDEs like vscode will limit the length of the commit message. I'm trying to figure out the root reason for this and evaluate how common this problem is.

**Comment by antoniomuso** [comment]
If you see in the GitLab [API](https://docs.gitlab.com/ee/api/deployments.html), you can see that `deployable.commit.message` includes the commit title and the commit body. Then there is no limit in git for the commit body. 
```json
{
    "created_at": "2016-08-11T11:32:35.444Z",
    "updated_at": "2016-08-11T11:34:01.123Z",
    "status": "created",
    "deployable": {
      "commit": {
        "author_email": "admin@example.com",
        "author_name": "Administrator",
        "created_at": "2016-08-11T13:28:26.000+02:00",
        "id": "a91957a858320c0e17f3a0eca7cfacbff50ea29a",
>        "message": "Merge branch 'rename-readme' into 'main'\r\n\r\nRename README\r\n\r\n\r\n\r\nSee merge request !2",
        "short_id": "a91957a8",
        "title": "Merge branch 'rename-readme' into 'main'\r"
      },
 ...
 }
 ```

**Comment by moritz-deissner-turbinekreuzberg** [comment]
i our case renovate bot is the talkative culprit

**Comment by abeizn** [comment]
This issue is the precursor to https://github.com/apache/incubator-devlake/issues/6521. I will fix it later.
