### ISSUE TITLE
[Refactor]Grafana - Engineering Throughput and Cycle Time] PR review depth and PR size take forever/don't work

### ISSUE THREAD

**Issue by robgutsopedra** [apache/devlake#6457]
## What and why to refactor
PR review depth and PR size take forever/don't work at all. 

## Describe the solution you'd like
I assume they should work as any other panel within Grafana

## Related issues
None that I have found

## Additional context
I have been focusing my efforst on PR review depth

I was using v0.18.0 query, but also tried query at main branch (which I believe are the same). For context, this: 
```
SELECT
  DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,
  count(distinct prc.id)/count(distinct pr.id) as "PR Review Depth"
FROM 
  pull_requests pr
  left join pull_request_comments prc on pr.id = prc.pull_request_id
  join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' 
WHERE
  $__timeFilter(pr.created_date)
  and pm.project_name in ($project)
  and pr.merged_date is not null
group by 1
```

I also tried a solution proposed by @Startrekzky -- 
```
with t1 as(
   select 
       pull_request_id, count(*) as pr_comment_number
   from
       pull_request_comments
   group by 1
)


SELECT
  DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,
  sum(t1.pr_comment_number)/count(distinct pr.id) as "PR Review Depth"
FROM 
  pull_requests pr
  left join t1 on t1.pull_request_id = pr.id
  join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' 
WHERE
  $__timeFilter(pr.created_date)
  and pm.project_name in ($project)
  and pr.merged_date is not null
group by 1
```

Which _I think_ it's working better, but still far from perfect. 

In _my_ case, I have around 3600 PRs, 23254 PR comments - 8 * 3600 * 23254 = 669M. I understand it might be big, but I think devLake handles heavier situations than this. Am I the only one getting degraded performance on these queries? 

Anyway, I'm far from an SQL expert but I'm more than happy to test/try anything you throw my way! 

Thanks a lot!

**Comment by Startrekzky** [comment]
Thanks for reporting. I'll look at it soon.

**Comment by Startrekzky** [comment]
@robgutsopedra Thanks, I've made further modifications based on the original SQL. Please try it out:

```
with t1 as(
   select 
       pull_request_id as pr_id, 
       count(*) as pr_comment_number
   from
       pull_request_comments
   group by 1
),

t2 as(
  SELECT
    DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,
    pr.id as pr_id
  FROM 
    pull_requests pr
    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' 
  WHERE
    $__timeFilter(pr.created_date)
    and pm.project_name in ($project)
    and pr.merged_date is not null
)

-- select t2.*, t1.pr_comment_number FROM  t2 left join t1 on t2.pr_id = t1.pr_id
select 
  t2.time,
  t1.pr_comment_number,
  t2.pr_id,
  sum(t1.pr_comment_number)/count(distinct t2.pr_id) as "PR Review Depth"
from 
  t2
  left join t1 on t2.pr_id = t1.pr_id
group by 1
```

**Comment by Startrekzky** [comment]
@robgutsopedra  Hmm. It worked when I tested it on my local machine. I'll get back to you soon.

**Comment by Startrekzky** [comment]
> Agh, sorry @Startrekzky , I was referring to PR Review Depth, that's the only one not working yet!
> 
> Sorry for the confusion!

I see. I'll check it out.
