### ISSUE TITLE
[Bug][Config UI]  The UI displays a loading icon after updating from version v0.19.0-beta6 to v0.20.0-beta1

### ISSUE THREAD

**Issue by naveenreddymanukonda** [apache/devlake#6467]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The UI is showing a loading icon after the update from version v0.19.0-beta6 to v0.20.0-beta1. No console issues or network problems have been observed.

<img width="1432" alt="image" src="https://github.com/apache/incubator-devlake/assets/40488776/d6ef4a91-ec94-4644-99b3-98c1d2bc1975">

<img width="1432" alt="image" src="https://github.com/apache/incubator-devlake/assets/40488776/3b72617a-311c-4a1c-b330-e95c7a355303">

<img width="1432" alt="image" src="https://github.com/apache/incubator-devlake/assets/40488776/9bdf60ae-b088-4330-97b4-a6e546d7e2e1">

### What do you expect to happen

UI to be loaded

### How to reproduce

Update the version from v0.19.0-beta6 to v0.20.0-beta1, then we are facing the issue with UI 

### Version

v0.20.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
v0.20  is no longer supported. Please upgrade to v1.0.1
