### ISSUE TITLE
[Bug][Azure Devops] 403 on adding a project

### ISSUE THREAD

**Issue by klemen-df** [apache/devlake#6469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I want to add a new repo I get 'Operation failed.'

In F12 I can see:

![image](https://github.com/apache/incubator-devlake/assets/93664973/c2eebc69-79ca-47ae-ac6d-1408bc106ddf)

using Helm chart installation, everything else works fine

### What do you expect to happen

Repository should be added.

### How to reproduce

- Add new data scope
- select organization
- select repository

Click save.

### Anything else

Nothing in container logs.

### Version

v0.19.1-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@KlemenDanfoss How about the other plugins, are they working when adding scopes?

**Comment by keon94** [comment]
@KlemenDanfoss Please share the backend logs. Also ensure your Azure token has full RW access.

**Comment by KlemenDanfoss** [comment]
@klesh , yes - I already have an additional project where this (Azure Devops) is working (in the same devlake installation).

@keon94 - yes. Nothing in any of the container logs when this happens.

**Comment by keon94** [comment]
@KlemenDanfoss Anything different about these failing repos? Are they private? Where are they hosted? etc.

**Comment by KlemenDanfoss** [comment]
No, all the same - azure repos (in the cloud)

Poslano iz Outlook za Android<https://aka.ms/AAb9ysg>


Classified as Business

________________________________

**Comment by keon94** [comment]
@KlemenDanfoss 
We'll need to narrow this down. Please paste this into a test python file inside `backend/python/plugins/azuredevops` and run it (after filling out the variables). Does it fail in the same way?

```python
from azuredevops.main import AzureDevOpsPlugin
from azuredevops.models import AzureDevOpsConnection

# assign values to these variables
token = ''
organization = ''
project = ''
#####################################

plugin_instance = AzureDevOpsPlugin()

connection = AzureDevOpsConnection(name='test', token=token, organization=organization)
group_id = organization + '/' + project
scopes = list(plugin_instance.remote_scopes(connection, group_id))

print(scopes)
```

**Comment by KlemenDanfoss** [comment]
@keon94 please close this - the issue was that WAF (web application firewall) was blocking some requests.
