### ISSUE TITLE
[Question] Release 0.19.0 missing

### ISSUE THREAD

**Issue by ghaabor** [apache/devlake#6470]
## Question
Hey folks, according to the website, the latest stable Devlake release is 0.19.0, however there's no tagged version of it here nor in the helm charts repo, while there's already a 0.19.1-beta1 and 0.20.0-beta1. When can we expect the 0.19.0 version to be released?

## Screenshots
<img width="162" alt="image" src="https://github.com/apache/incubator-devlake/assets/3968828/9242f16f-7f8c-4250-bb10-fc4e61c4a2d1">
<img width="521" alt="image" src="https://github.com/apache/incubator-devlake/assets/3968828/de4853ee-5423-4aad-96b4-adaedaf2241f">

**Comment by abeizn** [comment]
@ghaabor Thank you for your question. v0.19.0 is going through the voting process. When the process is over, v0.19.0 will be released based on v0.19.0-rc2. The main reason why v0.19.1-beta1 is released first is to solve some important problems for some users question

**Comment by ghaabor** [comment]
@abeizn thanks for the response! In that case, can you please confirm form me if the fix for https://github.com/apache/incubator-devlake/issues/5723 is included in 0.19.1-beta1/2? I don't want to necessarily go to 0.20.0-beta1 yet to have that fix in place.

**Comment by klesh** [comment]
@ghaabor Sorry for replying so late, seems the fix does exist on the versions you mentioned.
![image](https://github.com/apache/incubator-devlake/assets/61080/4326d8b7-d4d1-4163-a28c-e167febcdc32)

**Comment by ghaabor** [comment]
@klesh Thanks for the answer!
