### ISSUE TITLE
[Feature][Api] API to Provide the Most Recent Synchronization Time for a Data Scope

### ISSUE THREAD

**Issue by narrowizard** [apache/devlake#6520]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a user of Apache DevLake, I want to have an API that can provide the most recent synchronization time for a data scope. This is important because a data scope can exist in multiple blueprints (BPs), and using the most recent synchronization time of a BP cannot accurately describe the most recent synchronization time of a data scope.

### Description

Currently, Apache DevLake allows us to synchronize data from various DevOps tools. However, there is a need for an API that can provide the most recent synchronization time for a data scope. This is because a data scope, which is the smallest collection of data that can be synchronized by DevLake (like a Jira board or a Jenkins job), can exist in multiple BPs. The synchronization time of a BP cannot accurately represent the synchronization time of a data scope, hence the need for this feature.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Needs to cherrypick to v0.20

**Comment by Startrekzky** [comment]
@narrowizard What are the request parameters and responses of this API?

- request body: `data scope id`?
- responses: 
   - If this data scope has synced before: `the finish time of the last sync`? Is `only transform data` considered a sync?
   - Else, `NULL`?

Please point out the wrong parts.

**Comment by narrowizard** [comment]
@Startrekzky 
- request body: multi data scope ids is better since I can get several results in a request.
- response: `only transform data` should be exclude when calculate `the finish time of last sync`.
