### ISSUE TITLE
[Feature][CICD] Get the commit msg when collecting deployments and pipelines in GitHub/GitLab/BitBucket/Bamboo

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#6521]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

When viewing the deployment list in GitHub/BitBucket UI, one of the key differentiators for deployments is the `commit_msg`, so it's better to collect it while collecting deployments.

GitHub
![image](https://github.com/apache/incubator-devlake/assets/14050754/171bb489-2176-4207-800d-74a30a3dbedc)

BitBucket
![image](https://github.com/apache/incubator-devlake/assets/14050754/71e55a61-1f64-453b-89b5-b69bf8c6ff6b)

### Description

- [ ] Get the commit msg in the github deployment/workflow run collector -
- [ ] Get the commit msg in the github-graphql deployment/workflow run collector - 
- [ ] Get the commit msg in the gitlab deployment/pipeline collector -
- [ ] Get the commit msg in the bitbucket deployment/pipeline collector -
- [ ] Get the commit msg in the bamboo deploy build/plan build collector -

and write it to table cicd_deployment_commits and cicd_pipeline_commits

### Related issues

#6262

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
The commit message cannot be obtained directly through the original deployment/workflow interface.
To get the commit_msg, you should go to the commits or pr_commits table.
