### ISSUE TITLE
[Bug][Jenkins] Unable to delete data scope

### ISSUE THREAD

**Issue by en-rzaharioaei** [apache/devlake#6522]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

So, I do have a Jenkins connection for a multibranch pipeline. If I select a `feature/branch` as a data scope, then merge & delete that branch, I won't be able to delete that data scope. Also if that data scope shares the scope config with another data scope, let's called it `feature/branch2`. I delete the scope config and `feature/branch2`, you can't delete any other data scope that shared that scope config with, in you case you can't delete data scope `feature/branch1`.
![image](https://github.com/apache/incubator-devlake/assets/148552825/243caf75-6fce-47e9-991b-d32942a1bf61)

### What do you expect to happen

delete the data scope

### How to reproduce

create a data scope for a branch -> merge & delete the branch -> try to delete the data scope
create a second data scope for another branch -> select the same scope config -> use it in a project -> delete scope config -> delete the second data scope -> try to delete the first data scope

### Anything else

I encountered the second issue on Azure DevOps as well.

### Version

v0.20.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Seems like the scope name is not encoded correctly. @mintsweet would you take a look?

**Comment by mintsweet** [comment]
@klesh Do you have any idea?

**Comment by klesh** [comment]
Fixed by https://github.com/apache/incubator-devlake/pull/7357
