### ISSUE TITLE
[Bug][Projects] Manage Data Scope for Jenkins does not show the pipeline name

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#6536]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

For pipelines, we have branches with the same name; it is impossible to select the correct one using the UI as the picture:
![Screenshot 2023-11-29 at 1 00 48 PM](https://github.com/apache/incubator-devlake/assets/17132893/19ffaa0f-eee8-496c-84a8-d4fa4784fd00)

### What do you expect to happen

Display the pipeline name and the branch to be selected.

### How to reproduce

Add more than one Jenkins Pipeline with multiple branches and try to select it in the project side.

### Version

v0.20.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Thanks for reporting the problem.

**Comment by abeizn** [comment]
Fixed in v0.20.0-beta4. @msarzijr
