### ISSUE TITLE
Need to configure okta integrated jenkins with apache devlake

### ISSUE THREAD

**Issue by akshay369vm** [apache/devlake#6555]
## Question
My jenkins is Okta integrated and I need a solution to integrate the jenkins with apache devlake.

**Comment by klesh** [comment]
Not familiar with Okta , but I think you should be able to generate API tokens after logging into jenkins with Okta, no?

**Comment by akshay369vm** [comment]
Thanks for the response @klesh
I am able to generate the api token and I gave all the detail to test the connection as well.
I am facing this issue
`error requesting https://jenkins-ci.aaa.com/ Wraps: (2) Get "https://jenkins-ci.aaa.com/": tls: failed to verify certificate: x509: certificate signed by unknown authority Wraps: (3) Get "https://jenkins-ci.aaa.com/" Wraps: (4) tls: failed to verify certificate Wraps: (5) x509: certificate signed by unknown authority Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *url.Error (4) *tls.CertificateVerificationError (5) x509.UnknownAuthorityError`

**Comment by klesh** [comment]
I see, seems like a certificate problem, are you using a self-signed certificate? Please refer to this doc https://devlake.apache.org/docs/Troubleshooting/Configuration#failed-to-collect-data-from-the-server-with-a-self-signed-certificate

**Comment by namejsjeongkr** [comment]
@akshay369vm How to solve this one ?

**Comment by namejsjeongkr** [comment]
Any update about this one ?

**Comment by d4x1** [comment]
> Any update about this one ?

No.

**Comment by klesh** [comment]
@namejsjeongkr Can you elaborate on where are you struggling?

**Comment by klesh** [comment]
@akshay369vm Okay....
So, Was the problem solved? What can I do for you?

**Comment by akshay369vm** [comment]
@klesh The issue is not resolved. Now I have created secure endpoint for the devlake and tried connecting, Still not working.
Not sure, Jenkins is connecting, If I gave http endpoint in the connection. But not able to add any data scope.

**Comment by klesh** [comment]
Any error logs? message?

**Comment by akshay369vm** [comment]
@klesh here is what I am getting while adding data scope with http connection.

'error decoding response from http://jenkins.xx.com/api/json?tree=jobs%5BfullName%2Cname%2Cclass%2Curl%2Ccolor%2Cbase%2Cjobs%2CupstreamProjects%5Bname%5D%5D%7B0%2C100%7D: raw response: <html> | <head><title>404 Not Found</title></head> | <body bgcolor="white"> | <center><h1>404 Not Found</h1></center> | <hr><center>nginx/1.14.0 (Ubuntu)</center> | </body> | </html> | (404) Wraps: (2) invalid character '<' looking for beginning of value Wraps: (3) invalid character '<' looking for beginning of value Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *json.SyntaxError'

**Comment by klesh** [comment]
I'm noticing the full name doesn't seem quite right. To help me understand, could you record a video of the entire process? This would be very helpful in identifying the issue.
