### ISSUE TITLE
[Bug][gitextractor] Dockerfile - devlake user cannot run update-ca-certificates

### ISSUE THREAD

**Issue by clement-igonet** [apache/devlake#6556]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Configuration Troubleshooting page [here](https://devlake.apache.org/docs/Troubleshooting/Configuration) indicates to make run update-ca-certificates to import rootCA.
However, it is not possible as a devlake (non root) user (at least on v0.18.0 and above)

See backend/Dockerfile:
```
RUN useradd -ms /bin/bash -d /app devlake -u 1010
USER devlake
```

### What do you expect to happen

I expect `update-ca-certificates` to be runnable.

### How to reproduce

Follow the documentation:
```
  devlake:
    image: apache/devlake:v...
    ...
    volumes:
      ...
      - /path/to/your/rootCA.crt:/usr/local/share/ca-certificates/rootCA.crt
    command: [ "sh", "-c", "update-ca-certificates; lake" ]
    ...
 ```

### Version

v0.18.0 and above

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@clement-igonet You are right, this is problematic, thanks for reporting the issue.
@ZhangNing10 please take a look

**Comment by ZhangNing10** [comment]
@clement-igonet you can try below solution:
`mkdir certs
chown -R 1010:1010
`
then in the docker-compose.yml, mount ./certs to /etc/ssl/certs
<img width="734" alt="image" src="https://github.com/apache/incubator-devlake/assets/135692613/940c04cc-d2a6-44e6-979d-c3bc41bc87d8">

**Comment by klesh** [comment]
Nice work, @ZhangNing10 Please update the doc as well, thanks

**Comment by clement-igonet** [comment]
However, for such chmod operation, it forces the user to be able to use root priviledges in the host machine...
Is it better than keeping a root user inside the container ?
