### ISSUE TITLE
[Bug][Gitlab connection] Cannot add Data Scope on gitlab connection

### ISSUE THREAD

**Issue by clement-igonet** [apache/devlake#6557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After creating Gitlab (on-premise) connection, when clicking on `Add Data Scope`, I get this error message: `TypeError: (n ?? []).map is not a function`

FYI: I added convenient root certs in the devlake container.

### What do you expect to happen

I expect to be able to select my gitlab group and project as I usually do in v0.18.0

### How to reproduce

Created an internal gitlab connection and select `Add Data Scope`

### Version

* [main] 5581670a17466f0ae198a4c62fd9fb6f0066913d
* v0.19.0-rc3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
What GitLab version are you on? DevLake only supports the Cloud and Community Edition 11+.

**Comment by mintsweet** [comment]
hi @clement-igonet Are you running locally or docker?

**Comment by clement-igonet** [comment]
I use a gitlab ee 16.2.
However, it should work, I guess, as gitlab ee API is just an extension of gitlab ce. Isn't it ?
Also, support was ok on DevLake v0.18.0
I'll check deeply to understand.
So, the fact it work on CE should mean that it work in EE I though...

**Comment by mintsweet** [comment]
@clement-igonet Can you tell me your browser and browser's version?
