### ISSUE TITLE
[Bug][GitHub]I performed scope config configuration, and it matched the first regex of the second item for runs. In the cicd_pipelines table, the type is empty.

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Configure the GitHub connection.
2. Select data scope, apache/incubator-devlake.
3. Configure the scope config.
![image](https://github.com/apache/incubator-devlake/assets/142298906/1bb7701f-a64d-429e-ae17-abec0352ffad)

4. Collect data.
5. Check the cicd_deployments table, there are data converted from _raw_github_api_runs, but the type field in these data in the cicd_pipelines table is empty.    
![image](https://github.com/apache/incubator-devlake/assets/142298906/0c0bcb8d-e19f-4779-af0e-7e7943f66897)
![image](https://github.com/apache/incubator-devlake/assets/142298906/61e53457-a84d-497d-ae8b-9c19ae98e5ad)

-----------
1.配置GitHub的connection 
2.选择data scope，apache/incubator-devlake 
3.配置scope config 
4.收集数据 
5.检查表cicd_deployments表，有从 _raw_github_api_runs转换来的数据，但是这些数据在 cicd_pipelines表中的type字段 都为空。
6.预期是，符合上述规则的数据，cicd_pipelines.type应该是DEPLOYMENT

### What do you expect to happen

The expectation is that for data matching the above rules, cicd_pipelines.type should be DEPLOYMENT.

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
`cicd_pipelines.type` is from `_tool_github_runs.type`, and `_tool_github_runs.type` is set as "DEPLOYMENT" when `_tool_github_runs.name` statisfied the regexp. Regexp `Build and Push(.*)` cannot match any `_tool_github_runs.name` in  test(repo: incubator-apache/devlake). 
When configurating `unit-test(.*)` as the regexp, the `_tool_github_runs.type` will be "DEPLOYMENT", shown as below:
<img width="768" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/30c1e494-1835-48d3-aa71-053ac0dc294a">
@xiaomingzhang12

**Comment by xiaomingzhang12** [comment]
![image](https://github.com/apache/incubator-devlake/assets/142298906/23e04c5a-c5d0-4eb4-bd05-a9bc76cbabf0)
I need help confirming whether the 'cicd_pipelines.type' field is marked as 'DEPLOYMENT' if either the name of the 'workflow run' or the name of one of its jobs satisfies a regular expression, or is it solely based on whether the 'workflow run.name' matches the regular expression.  
@Startrekzky
