### ISSUE TITLE
[Feature][Gitlab job] gitlab trigger job `bridge` as job for Scope Config

### ISSUE THREAD

**Issue by clement-igonet** [apache/devlake#6576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

In the CI/CD deployment setup, we can set job name in order to define what to consider as a DevLake Deployment.

However, gitlab CI/CD can also have trigger job (useful to delegate deployment part) that are seen as "bridge" in gitlab API.

### Description

Gitlab `bridge` trigger job type should be also collected as any other job to identify a deployment job.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@Startrekzky

**Comment by clement-igonet** [comment]
Maybe a clone of https://github.com/apache/incubator-devlake/issues/6135

**Comment by d4x1** [comment]
> Maybe a clone of https://github.com/apache/incubator-devlake/issues/6135

Yes it's duplicated. Let's move the the original issue for further discussion.
