### ISSUE TITLE
[Bug][Pipeline] Scheduled Blueprint Fails to Execute and Blocks Process in DevLake

### ISSUE THREAD

**Issue by narrowizard** [apache/devlake#6577]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After scheduling a blueprint (BP) to run at specified intervals, we observed an issue where the program became unresponsive. This was noticed when, following the initiation of a task (as indicated by the logs showing the task trigger), there was a lack of subsequent logs that typically indicate task execution. The system seemed to be in a blocked state where no further tasks were executed.

### What do you expect to happen

The expected behavior is for the scheduled blueprint to trigger and execute the tasks seamlessly, without any program blockage. After the initiation of a task, subsequent tasks should proceed as planned, with appropriate logging at each stage to indicate task progress and completion.

### How to reproduce

Not sure, it occurs occasionally

### Anything else

The latest log for pipeline 50838, then it blocks at least one day. (there are no any more logs about 50838 keyword)
```
time="2023-12-05 07:05:00" level=info msg=" [pipeline service] run pipeline, 50838, now running runningParallelLabels are [parallel/lake_data_sync parallel/ee_dimension_sync]"
```
It recover after I restart the devlake service.

### Version

release-v0.19

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Not sure what happened, here is what I think we should do:

1. We should add a timeout mechanism for all database operations because reports were suggesting that the task could hang if the database is not responding.
2. Add more logging points around this part might help us figure out where is the problem in the future.
