### ISSUE TITLE
[Doc][Gitlab] DORA metrics

### ISSUE THREAD

**Issue by clement-igonet** [apache/devlake#6606]
## Documentation Scope
The goal is to help user on a full use case to get DORA metrics from Gitlab inputs.

## Describe the Change
Currently, its not clear how Gitlab incident are managed by DevLake, and how the link is made between a deployment and an incident.
For instance, for Median Time to Restore Service metric, we need to make this kind of link.

What an incident should contain in case of webhook, or in case of Gitlab incident?

What about the dates (created, started, finished) ? Are they used to link to latest or next deployment ?

An full example would be welcome, step by step, with ability to check if mysql table are well filled for the convenient grafana dashboard.

For instance, what `project_issue_metrics` mysql table should contain, and what to check if it's empty ? What is the blueprint pipeline state that manage the connexion between deployment and incident, what is the used algorithm ?

A very tiny example with curl/webhook with connected deployment and incident would be very usefull to go further in the DORA/DevLake adoption.

**Comment by klesh** [comment]
@clement-igonet I'm not sure, but isn't [DORA - Change Failure Rate | Apache DevLake - Open-Source Dev Data Platform for Productivity](https://devlake.apache.org/docs/Metrics/CFR) a step-by-step guide? As of the algo, I believe [DORA - Change Failure Rate | Apache DevLake - Open-Source Dev Data Platform for Productivity](https://devlake.apache.org/docs/Metrics/CFR) mentioned it. 
Do you think it is not clear and need to be improve or were you referring to some debug
ging guide?

**Comment by clement-igonet** [comment]
Finally, the explanations I needed was:
* devlake is able to rely on gitlab as a single input tool
* take care of "incident", to create them in gitlab when your application is down
* grafana/prometheus or any other tool able to send webhook alert/incident to gitlab
Then, you'll get all convenient data in a single gitlab input, and you'll be able to let devlake parse your gitlab data.
