### ISSUE TITLE
[Feature][Webhook] Auto-populate the value of the created_date in the incident registration webhook

### ISSUE THREAD

**Issue by clement-igonet** [apache/devlake#6613]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

When posting an incident, `created_date` field is defined as mandatory.
However, it would be convenient not to force user to define this field as the date of the post request could be used as `created_date` when not defined.
Also, it would simplify the use of the webhook, limiting the number of field to define, when using non programmatic alerting tool.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
It makes sense. Waiting for someone to take it.

**Comment by Startrekzky** [comment]
The solution should support two scenarios:

1. Users posted the `created_date`: Use the time that users posted.
2. Users didn't post the `created_date`: Use the time when the record is created.
