### ISSUE TITLE
[Bug][Jira] When configuring the scope config in Jira Cloud, it is not possible to select the original types of issues. 

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6617]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.  Choose to deploy the main branch, with the specific commit hash as follows:
![image](https://github.com/apache/incubator-devlake/assets/142298906/e032ffc4-c0c8-4ff6-851b-537fd6d4d437)

2. Add a new Jira Cloud connection, selecting the data scope.
3. When configuring the scope config, it is noted that the original types of issues are not present in the options.
4. The first time, do not enter a type value, click the ❌ in the top right corner, and then click 'Add new scope config'. This will cache the content entered during the previous attempt.
![20231212184056_rec_](https://github.com/apache/incubator-devlake/assets/142298906/a940c01b-822c-4536-8d23-c77c2b667aba)

### What do you expect to happen

1。 The original types of issues can be correctly selected.
2. If the content entered for the first time is not saved by clicking 'Save', it does not need to be cached.

### How to reproduce

See  above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaomingzhang12** [comment]
![img_v3_0264_64048052-70b1-4264-aca8-38a87c9eaa2g](https://github.com/apache/incubator-devlake/assets/142298906/2cc2a9fc-4138-4060-9ec4-b0c897aea550)
This is the phenomenon observed in the latest main branch.
1. The status bar below cannot find the corresponding content.
2. Clicking on the contents of the list does not select them.
@mintsweet

**Comment by mintsweet** [comment]
this issue has already been fixed.
