### ISSUE TITLE
[Feature][Data Connection] Need Tekton DataConnection Support

### ISSUE THREAD

**Issue by pavanreddy07385** [apache/devlake#6618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Similar to Jenkins, Need to connection for tekton, as JenkinsX is build on tekton 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
I start a vote, there are many tools that DevLake can make a plugin.
https://github.com/apache/incubator-devlake/discussions/6619
