### ISSUE TITLE
[Bug][AzureDevops] Subtask convertAzureDevopsBuilds ended unexpectedly

### ISSUE THREAD

**Issue by ambrisolla** [apache/devlake#6620]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Some blueprints taks when I run pipelines with AzureDevops scopes, end unexpectedly with the following error:

![Screenshot from 2023-12-12 17-49-32](https://github.com/apache/incubator-devlake/assets/9435929/8de6486d-d40e-4572-a9a1-cd0b19089773)

After make changes to the  "cicd_pipeline_commits" table,  the task was completed successfully. Basically I removed the primary key attribute from the "commit_sha" column on "cicd_pipeline_commits" table:

![Screenshot from 2023-12-12 18-17-31](https://github.com/apache/incubator-devlake/assets/9435929/6d1a365f-868e-4fed-b903-0ae6494ff7d3)

Task result after table changes:

![Screenshot from 2023-12-12 18-24-08](https://github.com/apache/incubator-devlake/assets/9435929/8003bcd2-f126-4e58-aadf-ab8c7cfd2060)

Thank you!

### What do you expect to happen

Blueprint pipeline completed successfully.

### How to reproduce

Run pipelines with AzureDevops scope(some, not all) .

### Anything else

It's possible change commit_sha attributes in new Versions?

![image](https://github.com/apache/incubator-devlake/assets/9435929/5a675210-b217-425d-938b-7403260b9c4e)

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@ambrisolla Thanks for reporting the problem. But I don't think the Primary key is the cause of it, I wonder if some of the `commit_sha`s were empty?

**Comment by ambrisolla** [comment]
Hi @klesh , you all right! 

I discovered that the build in question doesn't have "commit_sha" because AzureDevops  was unable to communicate with Github, maybe some authentications errors ocurred.

![Screenshot from 2023-12-13 09-53-20](https://github.com/apache/incubator-devlake/assets/9435929/ca5b456f-eb65-4c0d-93a5-d99ae519881e)

In this case,  I think we have a bug when an AzureDevops build ends like this.

Thank you.
