### ISSUE TITLE
[Bug][GitHub] Only the first 250 commits of a pull request are retrieved

### ISSUE THREAD

**Issue by danieljuhasz93** [apache/devlake#6646]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Context:**
We use the GitFlow branching strategy in our team. This means that we only merge the changes to the main branch when we are ready for a (internal) release. Because of this pull requests from the develop to the main branch can include several commits.

**Issue:**
We encountered an issue with the calculation of the Lead Time for Changes DORA metric. If a pull request has more than 250 commits, then only the first 250 commits are retrieved, and the oldest retrieved commit is treated as the first commit of the pull request. This leads to the incorrect calculation of the PR coding time and PR change lead time.

### What do you expect to happen

I would expect that all of the commits in a PR are retrieved instead of only the first 250 commits.

### How to reproduce

Prerequisites: a merged PR with more than 250 commits should exist in the repository.

1. Collect data from the beforementioned repository with the DORA option enabled
2. Inspect the Lead Time for Changes values on the built-in DORA dashboard.

### Anything else

The issue occurs every time, if we have a PR with more than 250 commits.

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@danieljuhasz93 
I'm sorry, this is a [limitation](https://docs.github.com/zh/rest/pulls/pulls?apiVersion=2022-11-28#list-commits-on-a-pull-request) imposed by GitHub itself, and unfortunately, we can't resolve it. Although you can retrieve all commit data through another interface using 'list commits,' there is still no direct way to obtain all commits through a pull request."

Additionally, this is an [issue](https://github.com/jenkinsci/pipeline-github-plugin/issues/63) that someone else has raised with GitHub, and it is still in an open status.

**Comment by danieljuhasz93** [comment]
Is this limitation still imposed by GitHub if [pagination](https://docs.github.com/en/rest/using-the-rest-api/using-pagination-in-the-rest-api?apiVersion=2022-11-28) is used?

**Comment by klesh** [comment]
@danieljuhasz93 Unfortunately, pagination have been supported since long long time ago https://github.com/apache/incubator-devlake/blob/main/backend/plugins/github/tasks/pr_commit_collector.go#L108 . 😂
