### ISSUE TITLE
[Bug][PR Size Query] PR Size is getting duplicated when using query from the documentation given

### ISSUE THREAD

**Issue by naveenreddymanukonda** [apache/devlake#6651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The query in the documentation is creating inconsistencies in the count of lines of code changes (additions and deletions) by including both pull request (PR) merges and PR sync, even for declined and still open PRs. It's worth exploring the option of excluding PRs without merges from the calculation. Please review this aspect and provide your thoughts on whether lines of code changes from PRs that have been merged should be included.

### What do you expect to happen

To accurately count the lines of code, it's suggested to only consider the lines changed in the merged commit.

### How to reproduce

`SELECT
    DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,
    pr.id as pr_id,
    prc.commit_sha,
    sum(c.additions)+sum(c.deletions) as loc
  FROM 
    pull_requests pr
    left join pull_request_commits prc on pr.id = prc.pull_request_id
    left join commits c on prc.commit_sha = c.sha
  WHERE
    $__timeFilter(pr.created_date)
    and pr.base_repo_id in ($repo_id)
  group by 1,2,3`

### Anything else

Below is the proposed query
`SELECT
    DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,
    pr.id as pr_id,
    prc.commit_sha,
    sum(c.additions)+sum(c.deletions) as loc
  FROM 
    pull_requests pr
    left join pull_request_commits prc on pr.id = prc.pull_request_id
		and pr.merge_commit_sha = prc.commit_sha
    left join commits c on prc.commit_sha = c.sha
  WHERE
    $__timeFilter(pr.created_date)
    and pr.base_repo_id in ($repo_id)
    and pr.original_status = 'MERGED'
  group by 1,2,3`

### Version

v0.20.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Feel free to put up an PR. It is similar to https://github.com/apache/incubator-devlake/issues/6457
