### ISSUE TITLE
[Bug][GitLab] The base_commit_sha and head_commit_sha in table pull_requests are empty

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#6671]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/incubator-devlake/assets/14050754/40a9c53f-4a85-447e-8a1d-a489589aace5)

### What do you expect to happen

It should not be empty.

### How to reproduce

Add a GitLab connection and collect the data.

### Version

v0.20.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
This requires calling a new api(https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr), which will cause the gitlab plug-in to run much slower, so we will not do it for the time being.
