### ISSUE TITLE
API_KEY not accesible with v0.18 version. V0.19 and v0.20 versions are unstable 

### ISSUE THREAD

**Issue by dgoel02** [apache/devlake#6672]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We are working on apache devlake version v0.18.0. But we could not find the api keys tab as mentioned in the official documentation attaching both the screenshots of our UI and official documentation.. 
![image](https://github.com/apache/incubator-devlake/assets/136561881/d402b998-72bf-4791-88ba-b5262cbb2458)

Officially Documentation screenshot:
![image](https://github.com/apache/incubator-devlake/assets/136561881/a8cde643-938d-4f80-8e2b-1bbb891492d2)

Additionally, we tried installing the later version v0.19 as mentioned as stable latest version.
1- we could not find any stable version on github or dockerhub for v0.19. 
2- With beta and rc3 versions that are present in github, the ui is failing with an error. DevLake API
Offline. Attaching snipped of the same. Version used here is devlake-config-ui:v0.19.0-rc3.
![image](https://github.com/apache/incubator-devlake/assets/136561881/7b3d3211-eae4-4df1-bd38-0fb649593cc9)

We even tried to do "devlake auth login" to generate api_token from cli. that doesnt seem to work as well. So can you please guide us the latest stable version with which we can access the api_key.

### What do you expect to happen

We need to understand the how can we get the api_key from the ui or the solution if we can get the same or which devlake version should we take to get the api_key. 
Additionally need an image of v0.19 devlake stable version.

### How to reproduce

Try deploying any version between v0.18 to v0.20.. Not been able to get the api_token.

### Version

v0.18

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
hi, the default doc is pointing to the latest development version, please switch to versioned doc first.
The v0.19 stable release is under ASF review, you can follow the thread https://lists.apache.org/thread/ymth9hgp6p82pclcbtght4cpdvyvz5mf for the progress.

Meanwhile, I suggest you try out the latest v0.20 beta release if you need the API-Key feature,

**Comment by dgoel02** [comment]
Hi @klesh , Can you please tell me the exact version on beta version of 20? As i could see so many beta versions.
Additionally is there any way we can get token key for v0.18 version for res api or any alternative or documentation that you can guide us to ?

Thanks,
Diksha Goel

**Comment by klesh** [comment]
sorry for the confusion, please visit this page https://github.com/apache/incubator-devlake/releases and the first release on it is the latest beta.

**Comment by d4x1** [comment]
> sorry for the confusion, please visit this page https://github.com/apache/incubator-devlake/releases and the first release on it is the latest beta.

@dgoel02 Do you try this? Can it help?

**Comment by dgoel02** [comment]
@klesh Any Specific version can you please mention ?

**Comment by dgoel02** [comment]
Tried with all these n still not having that feature. 
![image](https://github.com/apache/incubator-devlake/assets/136561881/ac67fece-8ab8-4da2-aa29-b87b99ab9547)

**Comment by dgoel02** [comment]
devlake-config-ui:v0.20.0-beta10
![image](https://github.com/apache/incubator-devlake/assets/136561881/c86015f0-9a2a-4405-a51a-3ef833f52202)

**Comment by d4x1** [comment]
Interesting. Can you paste some log of DevLake backend when Config UI is requesting?  Let me find out what's going wrong.
