### ISSUE TITLE
Component Field Not Syncing to SQL Issue Table after Jira-DevLake Integration

### ISSUE THREAD

**Issue by SakshiSharma-29** [apache/devlake#6673]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have successfully established a connection between my Jira instance and Apache DevLake. However, upon updating the 'component' field in an issue within Jira, the updated value does not reflect in the corresponding SQL table of issues in DevLake. The expected behavior is that any updates made in Jira should synchronize across to DevLake and be visible in the database. Attached are the screenshots displaying the configuration and the issue update in Jira.

### What do you expect to happen

The 'component' field value in the DevLake SQL 'issues' table should be updated to match the value in Jira after synchronization.

### How to reproduce

Steps to Reproduce:

Establish a connection between Jira and Apache DevLake.
Ensure that the 'Issue Tracking' and 'Cross Domain' data entities are selected in the DevLake configuration.
Update the 'component' field in a Jira issue.
Execute the synchronization process in DevLake to update the SQL tables.
Check the 'issues' SQL table in DevLake for the updated 'component' field value.
Notice that the 'component' field value is not updated in the SQL table.
Expected Result:
The 'component' field value in the DevLake SQL 'issues' table should be updated to match the value in Jira after synchronization.

Actual Result:
The 'component' field value is not present in the SQL 'issues' table after synchronization.

Please refer to the attached screenshots for a visual representation of the problem.

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SakshiSharma-29** [comment]
@klesh The component field is a jira standard field

**Comment by klesh** [comment]
@Startrekzky i think this is a bug

**Comment by Startrekzky** [comment]
Will fix it in v0.21 if it is reproduced.
