### ISSUE TITLE
[Bug][DORA] The DORA dashboard seems have been reverted

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#6677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The construction way of calendar month in the deployment frequency of DORA dashboard is 
![image](https://github.com/apache/incubator-devlake/assets/14050754/42e07fc1-a163-410f-8bc5-456c575cf26f)

However, this was changed in a PR a long time ago.
https://github.com/apache/incubator-devlake/pull/5179

### What do you expect to happen

1. It should use the calendar_months table to construct a time series
2. I'm not sure if other changes have been reverted. We must find out and make it up-to-date.

### How to reproduce

-

### Version

v0.20.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
The dora monthly table is not a revert, and it has not been changed. The reason is that the screenshot you took is based on days, while calendar_months is based on months. It cannot be replaced directly.
