### ISSUE TITLE
[Bug][JIRA - Weekly Bug Retro] Issue created on Sunday are not being considered

### ISSUE THREAD

**Issue by dwaghulade** [apache/devlake#6681]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

metrics on weekly-bug-retro dashboard are not considering bugs created or fixed on Sunday. May be it is because SQL consider end date as Sunday 00:00AM . 

![image](https://github.com/apache/incubator-devlake/assets/148270787/40f07492-318a-4f9c-a185-39a20869caba)

### What do you expect to happen

Consider bugs created/fixed on Sunday as well on Weekly buf retro dashboard. 

### How to reproduce

Create  and fix bug on Sunday and check report next week. 

### Version

v0.20.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@abeizn The problem is that the current SQL is like [Previous Monday 0 AM, Previous Sunday 0 AM], while it should be [Previous Monday 0 AM, This Monday 0 AM).
