### ISSUE TITLE
[Bug][devlake] Getting type error in devlake container when deploying using docker-compose

### ISSUE THREAD

**Issue by Alok650** [apache/devlake#6687]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have tried deploying devlake on local using docker-compose. the issue I am facing is:
the devlake container keeps on restarting. the result on devlake url is 
```
DevLake API
Offline
DEVLAKE_ENDPOINT: /api

Please wait for the Lake API to start before accessing the Configuration Interface.
```

error logs in the docker container for devlake:
Scan error on column index 0, name "created_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time;

In my .env, i.e. # Lake Database Connection String is
DB_URL=mysql://<user>:<pass>@<aws_mysql_rds_host_url>:3306/lake?charset=utf8mb4 &
parseTime=true &
loc=IST
E2E_DB_URL=<same as DB_URL>
charset=utf8mb4 &
parseTime=true &
loc=IST

### What do you expect to happen

the devlake UI should be visible at localhost:4000 and should allow me to add connections and see results on grafana

### How to reproduce

Docker images used:
devlake.docker.scarf.sh/apache/devlake-dashboard:v0.20.0-beta5
devlake.docker.scarf.sh/apache/devlake:v0.20.0-beta5
devlake.docker.scarf.sh/apache/devlake-config-ui:v0.20.0-beta5

I am also using my own docker network. for which config is:
networks:
  devlake-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: <ip>
        - gateway: <ip>
          
        
          
    

### Version

v0.20.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
was is a new deployment? try drop and create the db if so.

**Comment by d4x1** [comment]
> was is a new deployment? try drop and create the db if so.

@Alok650  Do you have a try?

**Comment by ces-truongvu** [comment]
I faced the same problem during the second execution of `docker-compose up`. Here the log:

```
devlake-devlake-1  | Wraps: (3)
devlake-devlake-1  | Wraps: (4) sql: Scan error on column index 0, name "created_at"
devlake-devlake-1  | Wraps: (5) unsupported Scan, storing driver.Value type []uint8 into type *time.Time
devlake-devlake-1  | Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *fmt.wrapError (4) *fmt.wrapError (5) *errors.errorString
devlake-devlake-1  | 
devlake-devlake-1  | goroutine 1 [running]:
devlake-devlake-1  | github.com/apache/incubator-devlake/server/services.InitResources()
devlake-devlake-1  | 	/app/server/services/init.go:62 +0x238
devlake-devlake-1  | github.com/apache/incubator-devlake/server/services.Init()
devlake-devlake-1  | 	/app/server/services/init.go:80 +0x2b
devlake-devlake-1  | github.com/apache/incubator-devlake/server/api.SetupApiServer(0xc000103860)
devlake-devlake-1  | 	/app/server/api/api.go:68 +0x36
devlake-devlake-1  | github.com/apache/incubator-devlake/server/api.CreateAndRunApiServer()
devlake-devlake-1  | 	/app/server/api/api.go:62 +0x25
devlake-devlake-1  | main.main()
devlake-devlake-1  | 	/app/server/main.go:33 +0x36
```

**Comment by d4x1** [comment]
Wired.  You can try to run it with another new database(maybe a local MySQL instance), and see what's going on.

**Comment by andyflatt** [comment]
I found I got this issue when using an external sql and not including the parseTime=True attribute to the DB connection string.  I got the clue from [here](https://stackoverflow.com/questions/45040319/unsupported-scan-storing-driver-value-type-uint8-into-type-time-time).
