### ISSUE TITLE
[Feature][DORA] Mono-repo support

### ISSUE THREAD

**Issue by mfogel** [apache/devlake#6690]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As an engineer working in a monorepo, I want to be able to collect and visualize per-project DORA metrics.

### Description

At work, we have a monorepo housing a few dozen projects and another few dozen shared libraries.

It looks like DevLake [can't filter](https://devlake.apache.org/docs/Configuration/HowToOrganizeDevlakeProjects#:~:text=DevLake%20cannot%20differentiate%20which%20commits%20or%20issues%20belong%20to%20specific%20projects.) "commit X affects project Y, but not the other projects". Some of the paid DORA offerings do this by allowing you to define paths to include/exclude when linking a repo with a project. Would be awesome if DevLake had a similar feature!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Thanks for your feedback. It's an reasonable feature request(@Startrekzky  Please keep an eye on it.).

@mfogel Can you explain the flow you expect in detail? (Or paste some screenshots)

FYI:
I have noticed there is a component table in https://github.com/apache/incubator-devlake/blob/main/backend/core/models/domainlayer/code/component.go, in this table, there is an `PathRegex` field .  Hope it can help.

**Comment by mfogel** [comment]
Here's an example of a paid DORA metrics offering (Sleuth) and how their monorepo support works: https://help.sleuth.io/modeling-your-deployments/code-deployments/creating-a-deployment#supporting-monorepos

**Comment by d4x1** [comment]
> Here's an example of a paid DORA metrics offering (Sleuth) and how their monorepo support works: https://help.sleuth.io/modeling-your-deployments/code-deployments/creating-a-deployment#supporting-monorepos

Thanks for your reply!

**Comment by magnus-rovco** [comment]
are there any plans to support this?

**Comment by klesh** [comment]
@magnus-rovco No, but we are open to the topic if any volunteers are willing to work on it.
