### ISSUE TITLE
Integrate Grafana oncall module with Devlake

### ISSUE THREAD

**Issue by pramodh-b** [apache/devlake#6694]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

It will be very helpful if Grafana oncall module can be integrated with devlake.

### Description

Grafana oncall is an incident management module, almost the same as pagerduty. We have started using the Grafana oncall module for our incident management so it would be great If I could integrate with devlake.
https://grafana.com/products/cloud/oncall/

### Related issues

Not able to integrate oncall module

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Let me know if anyone is interested in supporting this.
