### ISSUE TITLE
[Question][DORA] Convert GitLab incidents to DevLake issues with `type` = 'INCIDENTS'

### ISSUE THREAD

**Issue by clement-igonet** [apache/devlake#6710]
## Question
What are the rules to import gitlab `incident` as devlake `issue` with `type`=`INCIDENT` ?

In my case, I created a CRITICAL gitlab `incident`, devlake imports it as issue, but not with `type`=`INCIDENT`

That's a problem cause `Median Time to Restore Service` DORA metric consideres only `type = 'INCIDENT'` for calculation.

**Comment by klesh** [comment]
Are you referring to the **Type** field?
![image](https://github.com/apache/incubator-devlake/assets/61080/b36d4fb7-9605-4d4f-84d3-aa26ccefbe7c)
cc @Startrekzky

**Comment by Startrekzky** [comment]
Yes, you're correct. Do you want to convert other types of GitLab issues to `INCIDENTS`?

**Comment by clement-igonet** [comment]
No, just incident as incident

**Comment by clement-igonet** [comment]
> Are you referring to the **Type** field?
> 
> ![image](https://github.com/apache/incubator-devlake/assets/61080/b36d4fb7-9605-4d4f-84d3-aa26ccefbe7c)
> 
> cc @Startrekzky 

Not really.

In gitlab, `incident` has its own `incident` type, it is not an `issue`.

**Comment by Startrekzky** [comment]
@clement-igonet Got it. It seems to be a bug, the GitLab incidents should be converted to DevLake issues with type = INCIDENT automatically. We'll get it fixed asap.

**Comment by clement-igonet** [comment]
Wonderful !
