### ISSUE TITLE
[Feature][Dashboard] Add links that can explain how metrics are calculated to charts.

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#6722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

There are many dashboards\charts\metrics in devlake's grafana, and sometimes users spend much time on searching how some metrics are calculated in order to have a better understanding about metrics, or just want to customise a similar metrics with tiny modification.
We have offical documents explaining how metrcis are calculated(such as https://devlake.apache.org/docs/Metrics/BugAge#how-is-it-calculated) but users have to open the website and search it by keyword and choose the right document which is inefficient.
So I think a link should be added to the chart, this link can go to a page explaining how this metrics is calculated or related information.

### Description

1. Even through devlake uses trunck-based workflow and therotically charts' links in release v0.18 should be configurated /doc/v0.18. I think setting all links  to /doc/latest is acceptable.
2. Some charts may have no relation documents. It's normal.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
There are two ways:
1. Links in description with html a tag
![image](https://github.com/apache/incubator-devlake/assets/5844806/86d7ad53-50b8-4401-9cbd-996d988659f4)
2. Links with panel links
There are more than one links, title can be shown.
![image](https://github.com/apache/incubator-devlake/assets/5844806/da845018-f0ef-4369-be0e-037098c433ee)
There is only one link, title is hidden. Once clicked, link will be opened in a new tab.
![image](https://github.com/apache/incubator-devlake/assets/5844806/944ecdb1-eefe-4db8-be54-86677b1045ea)


They both can open this link in a new tab.

@Startrekzky Which is better in your opinions?

**Comment by abeizn** [comment]
2
