### ISSUE TITLE
[API][project] Project creation

### ISSUE THREAD

**Issue by clement-igonet** [apache/devlake#6726]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When creating a project using DevLake API, I’m blocked when trying to manage it with the DevLake GUI. Indeed, a linked blueprint must also be created (with API) otherwise DevLake is buggy and the user can’t go further.
Could the API manage project and blueprint creation in a single pass to avoid this blocker ?

### What do you expect to happen

Project could be set up from GUI after created from API

### How to reproduce

Create a simple DevLake project from DevLake API

### Version

v0.20.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
To me, it's a feature request to improve the user experience of using APIs to manage DevLake projects/blueprints, so I updated the label from bug to feature-request.
