### ISSUE TITLE
[Feature] GitHub calculate merged status by matching against description

### ISSUE THREAD

**Issue by codebreach** [apache/devlake#6758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

We use BorsNG to run a merge queue. It automatically batching MRs after automatically squashing them. However, this causes GitHub to report the MR as closed (instead of merged) and thus messes up the metrics. BorsNG automatically adds `[Merged by bors]` to the MRs which it merges.

I think a transform might also be able to do this but I couldn't it figure out, so any pointers on that would also be helpful

### Description

Would it be possible to add a way manually override what is considered merged? Like a `merged_override_regex` that looks at commit messages and marks such MRs as merged instead of closed?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Startrekzky Could you take a look at this when you find time, thanks.

**Comment by codebreach** [comment]
Anything we can do to get an answer faster would be great

**Comment by Startrekzky** [comment]
Hi @codebreach , I found someone sharing the same problem with yours: https://github.com/orgs/community/discussions/12437

So, it seems there's nothing we can do to update PR merge status to `merged` on the GitHub side.

The other perspective is to provide configurations to distinguish merged GitHub PRs from all closed PRs on the DevLake side. But since it's a rare case, we won't be able to support this feature in the short term due to the limited bandwidth.

**Comment by codebreach** [comment]
Thanks for the response @Startrekzky and totally understand that this cannot be done by you as its very specific etc.

Would you be open to an MR that allows this to be configured?

Or can you help me with how I should write such a transform.

Either way we will document and share it with the community here.

**Comment by Startrekzky** [comment]
Hi @codebreach . Thanks for the proposal. However, since we are trying to simplify the GitHub Scope Config, we might not be able to accept a PR to add this configuration. 

@klesh Do you have any idea about the workarounds of this issue?

**Comment by klesh** [comment]
I think you can write a Plugin to enrich the data for you.
