### ISSUE TITLE
[Bug][GitLab] GitLab collection failed with error message Incorrect datetime value: '0000-00-00' for column 'deployable_user_created_at'

### ISSUE THREAD

**Issue by mindspop** [apache/devlake#6764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When synchronizing devLake and GitLab data, the synchronization task failed (the error is as follows).

subtask ExtractDeployment ended unexpectedly Wraps: (2) error adding result to batch (500) Wraps: (3) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'deployable_user_created_at' at row 9 (500) Wraps: (4) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'deployable_user_created_at' at row 9 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError

<img width="811" alt="image" src="https://github.com/apache/incubator-devlake/assets/8045506/7b9f5caf-15d0-4deb-883e-ef36202ea8ae">

### What do you expect to happen

Data synchronization can be performed normally.

### How to reproduce

‌‌‌‌‌‌‌Configure data synchronization for GitLab, including deployment data and having the deployment user account in a blocked state.

install method: docker-compose
GitLab version: 15.2.2-ee

### Anything else

After investigation, it was found that the interface returned by the GitLab API(api/v4/projects/1/deployments/:id) lacks the field deployable.user.created_at (when the user is in a blocked state, this field is not returned), and the devLake GitLab plugin [requires this field to be required](https://github.com/apache/incubator-devlake/blob/013fe67642049a799f2eef352c53288240eacf39/backend/plugins/gitlab/models/deployment.go#L71).

### Version

v0.20.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@mindspop  It would be helpful if you can share the logs of the pipeline. Thank you.

**Comment by mindspop** [comment]
sure, here is the task-302-2-1-gitlab.log (The GitLab API address has undergone privacy processing.)

```
time="2024-01-08 04:04:20" level=info msg=" [pipeline service] [pipeline #51] [task #302] start executing task: 302"
time="2024-01-08 04:04:20" level=info msg=" [pipeline service] [pipeline #51] [task #302] start plugin"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] [api async client] creating scheduler for api \"https://gitlab.***.net/api/v4/\", number of workers: 13, 10000 reqs / 1h0m0s (interval: 360ms)"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] total step: 33"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] executing subtask CollectDeployment"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] [CollectDeployment] start api collection"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] [CollectDeployment] finished records: 1"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] [CollectDeployment] end api collection without error"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] finished step: 1 / 33"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] executing subtask collectApiIssues"
time="2024-01-08 04:04:21" level=info msg=" [pipeline service] [pipeline #51] [task #302] [collectApiIssues] start api collection"
time="2024-01-08 04:04:22" level=info msg=" [pipeline service] [pipeline #51] [task #302] [collectApiIssues] finished records: 1"
time="2024-01-08 04:04:22" level=info msg=" [pipeline service] [pipeline #51] [task #302] [collectApiIssues] end api collection without error"
time="2024-01-08 04:04:22" level=info msg=" [pipeline service] [pipeline #51] [task #302] finished step: 2 / 33"
time="2024-01-08 04:04:22" level=info msg=" [pipeline service] [pipeline #51] [task #302] executing subtask ExtractDeployment"
time="2024-01-08 04:04:22" level=info msg=" [pipeline service] [pipeline #51] [task #302] [ExtractDeployment] get data from _raw_gitlab_api_deployments where params={\"ConnectionId\":1,\"ProjectId\":1} and got 2544"
time="2024-01-08 04:04:22" level=info msg=" [pipeline service] [pipeline #51] [task #302] [ExtractDeployment] finished records: 1"
time="2024-01-08 04:04:22" level=error msg=" [pipeline service] [pipeline #51] [task #302] subtask ExtractDeployment ended unexpectedly\n\tWraps: (2) error adding result to batch (500)\n\tWraps: (3) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'deployable_user_created_at' at row 9 (500)\n\tWraps: (4) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'deployable_user_created_at' at row 9\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError"
```

**Comment by mindspop** [comment]
‌In fact, I think this is a GitLab issue. Even for a blocked user, they should return the created_at field to be reasonable.

**Comment by Startrekzky** [comment]
> ‌In fact, I think this is a GitLab issue. Even for a blocked user, they should return the created_at field to be reasonable.

True. We'll see how to handle this situation in DevLake.
