### ISSUE TITLE
[Bug][Zentao] Zentao's bug sync failed, due to raw data with numeric priOrder

### ISSUE THREAD

**Issue by matrixji** [apache/devlake#6767]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Sync with Zentao project partially failed. 
After investigating it, it seems due to JSON unmarshal failure with the ZentaoBugRes's JSON.

### What do you expect to happen

Hope sync succeeds.

### How to reproduce

Maybe it could be reproduced with several different Zentao's version

### Anything else

We have synced a few bugs previously successfully.
I have noticed, that in the Zentao BUG raw JSON, sometimes it uses the numeric `priOrder`, while sometimes it uses the string `priOrder`.
like(maybe newer version Zentao):
```json
{"priOrder": 3}
```
or(maybe some legacy version):
```json
{"priOrder": "3"}
```
it seems currently only Zentao's BUG has such behaviors, I'll check this for other issue types for Zentao later.
I'll provide the PR if tested successfully locally based on: https://github.com/matrixji/incubator-devlake/commit/96748e6945a4a127bffb683e978a2fa4c73a7ebd

### Version

v.0.19.0-rc4, master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Or you can  solve it like this:
https://github.com/apache/incubator-devlake/blob/main/backend/core/models/common/string_float64.go#L37
https://github.com/apache/incubator-devlake/blob/main/backend/plugins/zentao/models/project.go#L177

**Comment by Startrekzky** [comment]
Hi @matrixji , long time no see. If you're planning to submit a PR, please self-assign the issue.

**Comment by matrixji** [comment]
> Or you can solve it like this: https://github.com/apache/incubator-devlake/blob/main/backend/core/models/common/string_float64.go#L37 https://github.com/apache/incubator-devlake/blob/main/backend/plugins/zentao/models/project.go#L177

That should works, @d4x1 thanks for your advise

**Comment by abeizn** [comment]
@matrixji https://github.com/apache/incubator-devlake/releases/tag/v0.20.0-beta7 has been released
