### ISSUE TITLE
[Bug][JIRA Issues] Dashboard is double counting issues if those are part of multiple projects

### ISSUE THREAD

**Issue by dwaghulade** [apache/devlake#6768]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have two different project added; one for Java & another for PHP
For PHP project dashboard is showing correct number (76) of issues reported within last 30 days.
For Java project dashboard is showing correct number (151) of issues reported within last 30 days.
5 Issues on these two projects are common so when we select both project at a time on the dashboard it should ideally show 222 result instead it is showing 227.

### What do you expect to happen

When multiple project selected with same JIRA connection, it should consider unique count for the issues. 

### How to reproduce

1. Only create 1 connection and add the boards for PHP and Java
2. Create 2 DevLake projects: A and B
3. Add the connection to Project A but only choose the PHP board
4. Add the connection to Project B but only choose the Java board
5. Have some common issue created in JIRA which will return on both projects individually i.e. #3 & #4036 
6. Check no. of issues for project A within last 30 days. 
7. Check no. of issues for project B within last 30 days. 
8. Check no. of issues combined for project A & B. It is just adding up count from #6 & #7 i.e. double counting common issues. 

### Version

v0.20.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, which dashboard is that? Are there duplicated issues in the database?  Can you share the values of the `id` column if there were duplicated issues.

**Comment by dwaghulade** [comment]
Hi Klesh,

Please refer to below details.

which dashboard is that? : Jira (any jira related dashboard with two or more boards selected from boards filter; it should not be selected)
***@***.***


Are there duplicated issues in the database? Can you share the values of the id column if there were duplicated issues.
Yes and No. Duplicated issues in database if we consider just issue id. But these two are mapped with different boards. Please refer to below screenshot for query executed with two boards (Issue Throughtput -> Number of Issues metrics for an example however issue will persist for all metrics with two or more boards selected in filet).  Check at Universal-29314 issue; it is returning twice as it is matching for 'jira:JiraBoard:2:31004' and 'jira:JiraBoard:2:31005' each boards.  It seems join query needs to be updated at all metrics to exclude duplicate issues.

***@***.***

Regards,
Dhiraj Waghulade| Project Manager, LTIMindtree-EA | Desk +1 512 687 9758 | Cell +1 512-665-9513 | email: ***@***.******@***.***>

**Comment by klesh** [comment]
Hi, @dwaghulade I don't see any screenshot, can you re-upload it? thanks.

**Comment by abeizn** [comment]
@dwaghulade It has included in https://github.com/apache/incubator-devlake/releases/tag/v0.20.0-beta8
