### ISSUE TITLE
[Bug][Azure Devops] Azure Devops plugin incorrectly calculating pipeline duration

### ISSUE THREAD

**Issue by adwearing-jisc** [apache/devlake#6784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Setup devlake connection to Azure Pipelines.
Pipelines successfully imported with correct start and end dates.
Mean pipeline duration is less than 1 minute, when most pipelines ran for over 30 minutes.
Looking in the database, all pipelines are showing in seconds rather than the actual duration.

### What do you expect to happen

Expect for the correct duration to be set based on the start and end time.

### How to reproduce

Setup a pipeline in azure devops that runs for a few minutes (could just create a powershell task that sleeps for a bit)
Run the pipeline a few times
Setup devlake to connect to azure pipelines and collect data.
Check imported data in database.
Observe the duration is always in seconds, while the actual duration (end date - start date) is longer.

### Anything else

Digging through code, looks like this line is the perpetrator:

https://github.com/apache/incubator-devlake/blob/b3ab61d22e3affc5b39edf266f8de7b93c1988ee/backend/python/plugins/azuredevops/azuredevops/streams/builds.py#L70

`duration_sec = abs(b.finish_time.second - b.start_time.second)` should be `duration_sec = abs((b.finish_time - b.start_time).seconds)`

### Version

v0.20.beta6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Could you take a look at the problem when you find time, thanks. 🙏

**Comment by pogopaule** [comment]
I can confirm this bug. As a quick fix I have removed `/60` from the corresponding query in grafana.

**Comment by keon94** [comment]
Looks like https://github.com/apache/incubator-devlake/pull/6548 already fixed this problem. It'll have to be cherry-picked back to v0.20.x. FYI @klesh 
I tested and the newest code on the main branch works correctly [here](https://github.com/apache/incubator-devlake/blob/857cb99fc496f6c1c21bc3aad40a0d9ad3921bd2/backend/python/plugins/azuredevops/azuredevops/streams/builds.py#L70).
