### ISSUE TITLE
[Connection][Jira] Pull issues from Jira Service Desk Project

### ISSUE THREAD

**Issue by Bigguy98** [apache/devlake#6791]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I wonder if there's any way to pull issues from Jira Service Desk project? Cause as I see now, Devlake can only pull issues from boards which belong to Software projects. It's would be greate if we can have a function to create Jira data scope linked to Service Desk project.

### Description

When creating Data Scope for Jira Connection, use can choose Project (all type of Project like Software, Service Desk, ...) beside Board (only Software Service).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Please let me know if anyone is interested in this proposal.
