### ISSUE TITLE
Pipeline getting failed with the Github API secondary rate limit

### ISSUE THREAD

**Issue by pramodh-b** [apache/devlake#6801]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have added the Github private repo, with one repo the pipeline fails with the following error.
![image](https://github.com/apache/incubator-devlake/assets/116708310/9cee6659-8739-46f4-aae0-5b74777244e9)

### What do you expect to happen

the pipeline should complete successfully be completed

### How to reproduce

This error occurs every time the pipeline runs.

### Anything else

When this issue occurred last time, I enabled the Graphql APIs, and then the issue was resolved. this time even after enabling Graphql and setting the custom Rate limit also facing the issue.

I tried with another token as well

The private repo has a size of around 1.5 GB

FYI. We are on the GitHub enterprise subscription.

### Version

v0.20.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@pramodh-b https://github.com/apache/incubator-devlake/issues/5864 This problem should have been solved long ago. And regardless of whether graphql is enabled or not, this task is actually executed using non-graphql. You may need to wait for a while before running again.

**Comment by pramodh-b** [comment]
> @pramodh-b #5864 This problem should have been solved long ago. And regardless of whether graphql is enabled or not, this task is actually executed using non-graphql. You may need to wait for a while before running again.

Hi @abeizn FYI I'm running this pipeline weekly once. still same error.

**Comment by abeizn** [comment]
@pramodh-b  
I don't mean the frequency of running once a week, I mean that before executing the collectApiPrReviewComments task, a lot of other data such as issues, pull_requests, cicd, etc. are collected. You need to run it again after a while after failure. 

And you can reduce the rate limit value to solve this problem：
![image](https://github.com/apache/incubator-devlake/assets/101256042/868a8aa4-f96d-49cc-95ef-16ecb482cf29)
