### ISSUE TITLE
[Bug][UI] Error 404 if the backend doesn't have all Go plugins loaded

### ISSUE THREAD

**Issue by keon94** [apache/devlake#6808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/incubator-devlake/assets/25063936/89115bb8-cd13-467e-9864-2ffcfdbbd22e)

Cannot open the UI (connections page and therefore any other) unless the backend has all the plugin endpoints registered for all the plugins that are hardcoded in the front end code.

### What do you expect to happen

If the backend does not support a particular plugin (it's not loaded there), the UI should ignore it.

### How to reproduce

Encountered while manual-testing using the Go testing utilities I developed in the past ([Readme](https://github.com/apache/incubator-devlake/blob/main/backend/DevelopmentManual.md#full-scale-testing-using-the-client)).

Unless every Go plugin is manually declared in there, this 404 error happens. Another way would be to manually delete one of the plugin folders and build and start the backend server. In general, inconsistency between the compiled Go plugins list in the backend and the [list](https://github.com/apache/incubator-devlake/blob/main/config-ui/src/plugins/register/index.ts) in the frontend will cause this.

### Anything else

This wasn't an issue in the past (v0.18.x and possibly v0.19.x).

### Version

v0.20.0-beta6 and main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, @keon94 . Thanks for reporting the problem and I am sorry that I had missed the doc. Please take a look at the PR and see if it solves your problem, thanks.
https://github.com/apache/incubator-devlake-website/pull/697
