### ISSUE TITLE
[Feature][Config-ui] Add base path for config UI

### ISSUE THREAD

**Issue by antoniomuso** [apache/devlake#6814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

My use case is to have: 
- config-ui: at URL `/${basePath}`
- Grafana: at URL `/` (This is supported by Grafana)

### Description

Add the possibility to configure a custom base path for config-ui.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @antoniomuso , may I ask why you want to configure a custom base path for config ui?

**Comment by antoniomuso** [comment]
I need a base path because the config-ui should be accessible only by fewer users, while the Grafana should be accessible by more users. For this reason, it Is useful for me to have the Grafana dashboard accessible on `/` and the config-ui accessible, for example, on `/admin.`

**Comment by klesh** [comment]
In this case, I suggest:
1. set up a `oauth2_proxy` to protect the whole `config-ui` container
2. expose the `grafana` to everyone instead of accessing it via `config-ui`

**Comment by antoniomuso** [comment]
> In this case, I suggest:
> 
> 1. set up a `oauth2_proxy` to protect the whole `config-ui` container
> 2. expose the `grafana` to everyone instead of accessing it via `config-ui.`

Ok, thanks, @klesh, for the suggestion. I have seen that the config-ui compiles in a static HTML, so supporting a base path can be a problem.  Then I will follow your suggestion. Thank you.
