### ISSUE TITLE
[Bug][AzureDevopos] When creating a new connection, allowing the same name to exist does not meet the expectations.

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6818]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Select the Azure DevOps plugin and create a new connection, naming this connection 'Azure'.

Create another new connection, also naming this connection 'Azure'.

Click 'save connection'. The creation is successful. After creating three times, the effect is as shown in the picture: 
![image](https://github.com/apache/incubator-devlake/assets/142298906/8c9019d1-550c-410e-9fc9-33d4d3e0c57e)

The problem with this situation is: Based on the current circumstances, it is not easy to select when associating connections with projects.

### What do you expect to happen

Expectation: Similar to the handling with the Jira plugin, when the name is the same as an existing connection name, the interface/api/plugins/azuredevops/connections should give an error message. Below is an example from Jira:
![image](https://github.com/apache/incubator-devlake/assets/142298906/d99c0563-d4e7-49bc-a296-fa02c7e56faf)

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
@klesh There's no uniqueness index on the name fields of Azure connections. This can be added via migrations but what do you want to do about existing duplicates? We can't really automate deleting them: how do we know which ones to delete? How do you want to tell the user they have to delete duplicates before migrations can proceed? Just error out?

**Comment by keon94** [comment]
@klesh That's a smart solution. Yes, that should be doable.

**Comment by keon94** [comment]
PR: #6911
