### ISSUE TITLE
[Bug][Blueprints] Unable to enable blueprint

### ISSUE THREAD

**Issue by uptickmetachu** [apache/devlake#6825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="901" alt="image" src="https://github.com/apache/incubator-devlake/assets/67882333/dd93ad95-606b-4de8-b5e6-ae758c45c438">

Associated sync policy.

<img width="1448" alt="image" src="https://github.com/apache/incubator-devlake/assets/67882333/62f6fb49-0de9-4df8-939a-438c545f31ae">

With devlake v0.20.0-beta6, I am unable to enable a blueprint for automatic scheduling.

The enable pill is greyed out with no text/indicator as to how to actually enable it. Clicking it does nothing.

### What do you expect to happen

I expect clicking the slider to enable the blueprint.

### How to reproduce

Uncertain.

### Version

v0.20.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Hi @uptickmetachu, If your blueprint is associated with a project, it cannot be directly operated. You need to delete your project.

**Comment by klesh** [comment]
Should not be happening no more since #7449 and #7462
