### ISSUE TITLE
[Bug][Dashboard] Unable to access Dashboard, devlake dashboard resolves in a 500 status code

### ISSUE THREAD

**Issue by Monarene** [apache/devlake#6831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We upgraded our devlake version from v0.17.0 to v0.20.0-beta. After the upgrade,everything worked perfectly until. couple of days ago. We realised that our dashboboards were not being updated since December and on attempting to log in, I kept on seeing the "Request failed with 500" error.
![Screenshot 2024-01-11 at 12 45 54](https://github.com/apache/incubator-devlake/assets/30388498/ba3953ee-83b3-48a2-879f-0d69c9d213f9)

### What do you expect to happen

I expected that attempting to view the devlake deployment would take me to my projects so I can review the deployments

### How to reproduce

I have no idea

### Anything else

Nothing else

### Version

v0.20.0-beta2.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Can you share  the `devlake` container log for diagnosis?
