### ISSUE TITLE
[Bug][Grafana] Dupilicated UID in /etc/grafana/dashboards/Circleci.json and /etc/grafana/dashboards/Jenkins.json

### ISSUE THREAD

**Issue by dom-cn** [apache/devlake#6833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

logger=provisioning.dashboard t=2024-01-17T09:26:45.813841486Z level=warn msg="the same UID is used more than once" orgId=1 uid=W8AiDFQnk times=2 providers="[My Dashboard]"
logger=provisioning.dashboard t=2024-01-17T09:26:45.813967044Z level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider="My Dashboard" orgId=1
logger=provisioning.dashboard type=file name="My Dashboard" t=2024-01-17T09:26:45.856063013Z level=warn msg="Not saving new dashboard due to restricted database access" provisioner="My Dashboard" file=/etc/grafana/dashboards/Jenkins.json folderId=0
logger=provisioning.dashboard type=file name="My Dashboard" t=2024-01-17T09:26:50.838393271Z level=warn msg="Not saving new dashboard due to restricted database access" provisioner="My Dashboard" file=/etc/grafana/dashboards/Jenkins.json folderId=0

### What do you expect to happen

there should be no this duplicated uids.

### How to reproduce

at initial installation, there will be this bug on both v0.20.0-beta4 and v0.20.0-beta6.

### Anything else

Always.

### Version

v0.20.0-beta4 and v0.20.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@dom-cn https://github.com/apache/incubator-devlake/releases/tag/v0.20.0-beta7 has been released
