### ISSUE TITLE
[Bug][Module Name] Syncronization Schedule not happening

### ISSUE THREAD

**Issue by Matoro17** [apache/devlake#6844]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm using Apache 2.0 License
v0.18.0-beta1@
With the schedule for synchronization enabled the schedule never happens
![image](https://github.com/apache/incubator-devlake/assets/30204464/8ad2f26e-c74d-45be-8634-a2f845da6afb)
The next print shows the last syncs and they only happened because of a manual trigger:
![image](https://github.com/apache/incubator-devlake/assets/30204464/352c432f-8d2a-4c77-9092-dba030b3b0cf)

### What do you expect to happen

The schedule work, and the sync happens daily

### How to reproduce

This is a Devlake instance deployed in Google Cloud Run using this Image:
apache/devlake:v0.18.0-beta1

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Matoro17 v0.18-beta1 is quite old, please upgrade to v0.20-beta7 from https://github.com/apache/incubator-devlake/releases
