### ISSUE TITLE
[Feature][GitExtractor] Support incremental sync when collecting Git data

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#6853]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a user who has large repos with more than 100,000 commits, I'd like to have incremental sync when collecting Git data. 

Currently, every pipeline takes more than 5 hours to collect data. That makes it difficult to utilize DevLake in my org.

### Description

Support incremental sync in the GitExtractor plugin. Specifically,

| Entity | Sync Mode | Cursor Field |
| ------| ------------| ------------ |
| repos  | Full refresh. There's no need to be incremental | N/A |
| refs     | Full refresh. There's no create/update date of the ref as far as I know | N/A |
| commits  | Incremental |  committed_date. It seems to make more sense than commits.authored_date |
| commit_files  | Incremental |  committed_date. Update the commit_files of the new commits. |

### Related issues

https://github.com/apache/incubator-devlake/issues/6138

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Closed by #7319
