### ISSUE TITLE
[Install via Docker Compose][CMD lake] Error creating devlake through Docker Compose

### ISSUE THREAD

**Issue by SxjAccount** [apache/devlake#6870]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Error creating devlake through Docker Compose: Unable to create database lake
![5](https://github.com/apache/incubator-devlake/assets/85595603/b89e2340-fb71-4035-b77b-ca59af1cf028)
![4](https://github.com/apache/incubator-devlake/assets/85595603/b5641a96-6ce1-4028-8e15-9d2d11ca2a81)
![3](https://github.com/apache/incubator-devlake/assets/85595603/7e83f5bd-2d49-45a9-b979-aee6e9745bc1)
![2](https://github.com/apache/incubator-devlake/assets/85595603/2711d6ee-5af1-4d08-a17d-89adcc651554)
![1](https://github.com/apache/incubator-devlake/assets/85595603/a8bc4599-8693-4e5a-8588-b4b034084efa)

### What do you expect to happen

normal setup

### How to reproduce

Creating a devlake on a virtual machine through Docker Compose

### Version

v0.20.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Can you paste your command and comspose file when running devlake with docker compose?

**Comment by ZhangNing10** [comment]
hi @SxjAccount , could you paste the docker-compose.yml here?

**Comment by SxjAccount** [comment]
![6](https://github.com/apache/incubator-devlake/assets/85595603/aefa1f0b-a281-488d-b3a6-f3ec474baa1e)


 docker-compose.yml

**Comment by ZhangNing10** [comment]
@SxjAccount strange, why error says lake unknown... could you try below?

`docker-compose down`
`docker volume ls`
`docker volume rm the-mysql-volume`

and then docker-compose up -d again?

**Comment by SxjAccount** [comment]
The same problem will still arise

**Comment by SxjAccount** [comment]
The same problem will still arise


> @SxjAccount strange, why error says lake unknown... could you try below?
> 
> `docker-compose down` `docker volume ls` `docker volume rm the-mysql-volume`
> 
> and then docker-compose up -d again?

**Comment by ZhangNing10** [comment]
@SxjAccount still unknown database lake?

**Comment by SxjAccount** [comment]
@ZhangNing10 By observation, it is likely that devlake did not obtain the. env file, which caused a deployment error and resulted in the database not being created. It is unclear why the. env file cannot be obtained now

**Comment by ZhangNing10** [comment]
did you put the .env file in the same directory with the docker compose file?

**Comment by ZhangNing10** [comment]
the db creation is done by mysql service itself, not created by devlake @SxjAccount

**Comment by SxjAccount** [comment]
@ZhangNing10 Please review the initial image

**Comment by SxjAccount** [comment]
@ZhangNing10 How was the creation of the database lake completed

> the db creation is done by mysql service itself, not created by devlake

**Comment by ZhangNing10** [comment]
@SxjAccount you can enter the mysql pod and try to connect the db with merico:merico, and show database to have a look whether the db was created successfully

**Comment by SxjAccount** [comment]
@ZhangNing10 Now the devlake has not been successfully started, and the database lake has not been created either
> t you can enter the mysql pod and try to connect the db with merico:merico, and show database to have a look whether the db was created successfully

**Comment by ZhangNing10** [comment]
@SxjAccount i can't reproduce the issue by my side, db creation has no problem by my side, could you manually create the db lake and wait for devlake to start up?

**Comment by SxjAccount** [comment]
@ZhangNing10 I followed the official installation steps yesterday and suddenly succeeded. The program is running normally. When I deleted the installed image and reinstalled it, I inexplicably encountered the same problem again. I was wondering if it was caused by my system being installed on a virtual machine. But it's not very clear where the problem came from
