### ISSUE TITLE
[Bug]Install via Docker Compose] docker daemon issue 

### ISSUE THREAD

**Issue by mparthi3-ford** [apache/devlake#6888]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am trying to install docker-compose.yaml but blocked with the below issue after running the **command docker-compose up -d**

"**Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?**"

### What do you expect to happen

devlake should get successfully installed.

### How to reproduce

Follow the below steps:
Launch DevLake

Download docker-compose.yml and env.example from the [latest release](https://github.com/apache/incubator-devlake/releases) into a folder.

Rename env.example to .env. For Mac/Linux users, please run mv env.example .env in the terminal. This file contains the environment variables that the Devlake server will use. Additional ones can be found in the compose file(s).

Generate a secure encryption key using a method such as OpenSSL. For example, run the following command to generate a 128-character string consisting of uppercase letters:

openssl rand -base64 2000 | tr -dc 'A-Z' | fold -w 128 | head -n 1

Copy the generated string. Set the value of the ENCRYPTION_SECRET environment variable:

Method 1: In the docker-compose.yml, set an environment variable ENCRYPTION_SECRET: "copied string"

Method 2: Alternatively, you can set the ENCRYPTION_SECRET environment variable in the .env file: ENCRYPTION_SECRET="copied string"

If you set the ENCRYPTION_SECRET environment variable in both docker-compose.yml and the .env file, the value set in docker-compose.yml takes precedence.

Please make sure to keep the ENCRYPTION_SECRET safe as it is used to encrypt sensitive information in the database, such as personal access tokens and passwords. If ENCRYPTION_SECRET is lost, it may not be possible to decrypt this sensitive information.

By default, the timezone is UTC. You can change it by adjusting the env variable TZ in docker-compose.yml

Run docker-compose up -d if the version of Docker Desktop is too low to use docker compose up -d.

### Version

v0.20.0-beta10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, I would like to help but the error message suggested that it is a Docker problem which is out of the scope of our project.
Please make sure your docker daemon is up and working correctly before trying to deploy Apache DevLake on it.
You may ask for help in the Docker/Docker-compose community.

**Comment by klesh** [comment]
Feel free to re-open the issue if you think it is a mistake.
