### ISSUE TITLE
[Bug][GitLab] raw table is missing when collecting api trigger jobs

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#6892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In #6167, `CollectApiTriggerJobs` was added, but in function `GetAllPipelinesIterator`, `_raw_gitlab_api_trigger_job` is used before this table was created. 
And when I running a project with a gitlab connection, some errors happened.

```
time="2024-01-29 19:39:08" level=info msg=" [pipeline service] [pipeline #8] [task #59] executing subtask collectApiTriggerJobs"
time="2024-01-29 19:39:08" level=info msg="\x1b[31;1m/Users/houlinwei/Code/go/src/github.com/merico-dev/lake-feat-6854/backend/impls/dalgorm/dalgorm.go:188 \x1b[35;1mError 1146 (42S02): Table 'lake._raw_gitlab_api_trigger_job' doesn't exist\n\x1b[0m\x1b[33m[2.624ms] \x1b[34;1m[rows:-]\x1b[0m SELECT gp.gitlab_id, gp.gitlab_id as iid FROM _tool_gitlab_pipelines gp WHERE gp.project_id = 50751699 and gp.connection_id = 1 and gp.gitlab_id not in (select json_extract(tj.input, '$.GitlabId') as gitlab_id from _raw_gitlab_api_trigger_job tj)"
time="2024-01-29 19:39:08" level=error msg=" [pipeline service] [pipeline #8] [task #59] subtask collectApiTriggerJobs ended unexpectedly\n\tWraps: (2) Error 1146 (42S02): Table 'lake._raw_gitlab_api_trigger_job' doesn't exist (500)\n\tWraps: (3) Error 1146 (42S02): Table 'lake._raw_gitlab_api_trigger_job' doesn't exist\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError"
```

### What do you expect to happen

Run project sucessfully.

### How to reproduce

Create a project with a gitlab connection, collect data.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Marco-De-Stefani** [comment]
[This](https://github.com/apache/incubator-devlake/pull/6943) should solve it, but I didn't have time to properly test it using GitLab. If someone can do it, I would appreciate it. In case not, I'll do it over the weekend

**Comment by meeroslaph** [comment]
@Marco-De-Stefani, did you manage to test the change?

> [This](https://github.com/apache/incubator-devlake/pull/6943) should solve it, but I didn't have time to properly test it using GitLab. If someone can do it, I would appreciate it. In case not, I'll do it over the weekend

**Comment by meeroslaph** [comment]
> [This](https://github.com/apache/incubator-devlake/pull/6943) should solve it, but I didn't have time to properly test it using GitLab. If someone can do it, I would appreciate it. In case not, I'll do it over the weekend

@Marco-De-Stefani, did you manage to check the fix? The ticket got closed due to staleness, thus not sure if the fix was successful.
