### ISSUE TITLE
[Bug][Dora Metrics] Date Range for Benchmarks(Performance Levels) of Deployment Frequency is not correct.

### ISSUE THREAD

**Issue by estefaniasuasti** [apache/devlake#6907]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I was trying to understand in a better way the Benchmarks for Deployment Frequency. As a part of the learning/testing put the all steps separated in tables, then I select a different time range from August 2023 to September 2023. However, the tables for the calculation still picking the date range from August 2023 until Today. 

 As you can see during August to September we have deployments therefore at least the Deployment Frequency should be "one per month  and  once every 6 months" and not "Fewer than once per six months".

![Screenshot 2024-02-01 at 4 13 57 PM](https://github.com/apache/incubator-devlake/assets/39221859/aea19ae8-9e64-4b7e-9278-96ab3749a20f)

### What do you expect to happen

The date range for deployment frequency benchmarks should follow the date filter that the user selects in the dashboard, and not be set to in SYSDATE().

### How to reproduce

Bug
![image](https://github.com/apache/incubator-devlake/assets/39221859/08d55207-e164-4f95-a65c-95e26c4c4097)

### Anything else

Possible solution:
![image](https://github.com/apache/incubator-devlake/assets/39221859/6bc48a03-08e4-470c-9511-a8263a9e270c)

### Version

v0.19.0-rc4@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
I think you are right.  I am not sure why DevLake use `SYSDATE` instead of `$__timeTo`. 
cc @Startrekzky

**Comment by estefaniasuasti** [comment]
Good morning @d4x1, I also created tables for all the steps of the Benchmarks(Performance Levels) of Deployment Frequency, and as you can see here, all of them use the wrong date range. In this case the date range should be just June. 

![image](https://github.com/apache/incubator-devlake/assets/39221859/56f9b060-4778-48b4-918b-e44caa770807)

**Comment by estefaniasuasti** [comment]
And here, you can see the difference using $__timeTo.  Date range just June . 

![image](https://github.com/apache/incubator-devlake/assets/39221859/1d1a4571-f4db-4ba5-b8a2-f6c9390d550f)

**Comment by Startrekzky** [comment]
It's because I wanted to fixate the date range to six months. That's why I wrote this way. I've considered using your solution in the first place, but I forgot why I chose the current way. What's your thoughts on this, should we change it? @abeizn 

Cc. @d4x1

**Comment by abeizn** [comment]
@estefaniasuasti Thanks, very good suggestion, we will revamp it in the v1.0 version.  cc @Startrekzky @d4x1

**Comment by estefaniasuasti** [comment]
Thanks @abeizn :)
