### ISSUE TITLE
[Bug][GitLab] Issue collecting the deployment frequency data from a specific Job of a pipeline.

### ISSUE THREAD

**Issue by estefaniasuasti** [apache/devlake#6908]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am facing an issue collecting the deployment frequency data. My pipeline reaching production has 3 stages: **_Dry-run, deploy, and health check._** The logic would be to grab as a deployment date the last time when the "Deploy" stage was run, however DevLake is taking the last time when the health-check stage was run. The issue is in order to check the health of our system we sometimes just run the health-check stage, months after the deployment was done.

To be more precise we had a deployment _**"prod-deploy"**_ during December, however we run a health-check **_"prod-healthcheck"_** on January and now the monthly deployments shows that the deployment happened during January, which is not accurate.

![Screenshot 2024-01-30 at 1 08 44 PM (2)](https://github.com/apache/incubator-devlake/assets/39221859/60d50607-465b-4bfb-baa3-48b740424eea)

The **_Scope config_**, that I am using is:

(?i)(^(branchName)$) and
(?i)(prod-deploy) 

**_Data source:_** GitLab
 

### What do you expect to happen

With this scope the idea was just to collect the data only if the "prod-deploy" job had been run.

### How to reproduce

Having a pipeline with different stages and run a no deployment job later on. 

![image](https://github.com/apache/incubator-devlake/assets/39221859/264142e7-6d31-4fed-be04-244db48864e9)

### Version

v0.19.0-rc4@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
What kind of data source is it? Jenkins?

**Comment by d4x1** [comment]
I think it's a bug, because in scope config
<img width="867" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/ed515753-af7c-495e-9cf9-43e63e79eef2">
the wording is  `one of its jobs` , but in code 
https://github.com/apache/incubator-devlake/blob/release-v0.19/backend/plugins/gitlab/tasks/pipeline_detail_extractor.go#L74
only `ref`'s name was checked. (it's the same with main branch https://github.com/apache/incubator-devlake/blob/main/backend/plugins/gitlab/tasks/pipeline_detail_extractor.go#L71).

@estefaniasuasti Thanks for your feedback.   

It will be good  if this bug can be resolve ASAP.

**Comment by estefaniasuasti** [comment]
Good morning @klesh, sorry I forgot to mention that in the description of the issue. I am using **### GitLab** as a data source. Let me update it.

**Comment by estefaniasuasti** [comment]
Good morning @d4x1. That is a really good point. And based on my short experience using DevLake , yes, because I modified the regex for the **_Scope Config_** several time but it didn't work, it only check the branch name (ref). And based on the code that you shared, there is no parameter that compares the "Stage" name or the job "name".

**Comment by Startrekzky** [comment]
Collecting votes if you're encountering the same problem.

**Comment by abeizn** [comment]
@estefaniasuasti 'the wording is one of its jobs' maybe right,  It is executed [here](https://github.com/apache/incubator-devlake/blob/release-v0.19/backend/plugins/gitlab/tasks/job_convertor.go#L106), not in the pipeline extractor

**Comment by estefaniasuasti** [comment]
Thanks for your answer @abeizn, as a result do you think there is a way for my project fit the current structure for calculating Dora metrics or not at all because of the **_health-check_** stage situation?

**Comment by d4x1** [comment]
To solve this problem, I think DevLake's scope config needs to support kinds of "filter" when generating a pipeline.
