### ISSUE TITLE
[chore][python] upgrade python to latest LTS

### ISSUE THREAD

**Issue by wanis-fahmy** [apache/devlake#6918]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

At the moment, DevLake needs python 3.9 which doesn't have active support since almost 2 years (only security fixes).
It would be nice to upgrade the base image and dependencies to run against a newer version.

side thought: I believe adding dependabot or renovate will benefit DevLake, I am not currently sure how dependency management is handled 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
IIRC the dbt plugin requires pinning it to v3.9. We tried upgrading a few months ago and that plugin broke. cc @klesh

**Comment by klesh** [comment]
Yes, that is correct. 
@abeizn any update on the DBT side?

**Comment by klesh** [comment]
@wanisfahmyDE Thanks for the input, seems like we have to wait 😂.
