### ISSUE TITLE
[Grafana][Dashboard] Forgot Password flow in grafana is not working. 

### ISSUE THREAD

**Issue by mparthi3-ford** [apache/devlake#6951]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am not receiving emails after I tapped on "Forgot Password" link in grafana screen

### What do you expect to happen

I should get an email triggered that provides my temporary password

### How to reproduce

Go to Config-UI and click on "Dashboard" option at the top right corner of the screen.
User is navigated to the grafana screen where you would be prompted to provide user id and password. Also, you would have "Forgot password" link as well.
After I tap on "Forgot Password" I was prompted to provide user id and after I did reset, I expect the system to send temporary password to the email id provided but did not receive.

### Anything else

no

### Version

v0.20.0-beta10

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
I have never touched this feature, but I think it's normal. Because there is no email service provider. 
You can make this feature work as expected by adding an email configuration.

Hope https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/ can help.
