### ISSUE TITLE
[Feature][Multiple Production Environments] Support multiple production environments

### ISSUE THREAD

**Issue by JosephSalisbury** [apache/devlake#6953]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I'm trying to gather DORA metrics for projects that will be deployed to multiple production environments. 

In our specific use case, we have multiple Kubernetes clusters running in customer environments. We deploy applications to these clusters, and want to measure (for example) the lead time of commits being deployed to these environments.

### Description

There are likely to be lots of implications of this, but as a subset:

- DORA metrics should be sliceable by subsets of the multiple production environment (e.g: customer, provider)
- The webhook integration should support any environment key

### Related issues

See https://devlake-io.slack.com/archives/C03APJ20VM4/p1707406054877179 for some related discussion on the DevLake Slack.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Collecting votes

**Comment by mieliespoor** [comment]
Not stale

**Comment by KarolisL** [comment]
Not stale

**Comment by RashmiRam** [comment]
not stale
