### ISSUE TITLE
[Bug][Config-UI] Health endpoint is not accessible for livenessProbe/readinessProbe when basicAuth is enabled

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#6957]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have deployed devlake using helm chart in AWS EKS cluster. 

We noticed that when basicAuth is enabled in config-ui, the /health endpoint which seems to be added as part of this PR https://github.com/apache/incubator-devlake/pull/5745 is not accessible without auth. Hitting /health shows up the authentication popup. Refer screenshot.

<img width="1728" alt="Screenshot 2024-02-15 at 12 24 02 PM" src="https://github.com/apache/incubator-devlake/assets/1550131/a5e9dacb-b526-4052-81cb-4b0b84fe544e">

So we are not able to configure /health for our liveness/readiness probe. With basicAuth enabled, the existing probes also fail due to authencation error and the config-ui pod doesn't come up.

To overcome this, we had to disable the probes using kubectl patch deployment command. 

### What do you expect to happen

/health endpoint should be accessible without auth.

### How to reproduce

1. Deploy devlake through helm chart with basicAuth enabled. 
2. Hit the /health endpoint. Basic auth pop-up will come up.

### Anything else

Always reproducible.

### Version

0.21.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ankurkejriwal** [comment]
The end point specified in the `default.conf.tp` is `/health/` maybe try using that instead of `/health`

**Comment by sayeedhussain** [comment]
@ankurkejriwal Doesn't work. Already tried.

**Comment by klesh** [comment]
@sayeedhussain Weird, it is working perfectly on my local machine: `/health` requires authorization while `/health/` does not.
![image](https://github.com/apache/incubator-devlake/assets/61080/10c60bab-d11c-4dc1-a0ff-92900d7c4437)

Could you try it again and share screenshots if it didn't work.

**Comment by sayeedhussain** [comment]
@klesh Tried again and found it works when we give a trailiing slash after health/.  thanks!

It will be better to remove the trailing slash from nginx as trailing slashes is not a good idea and source of confusion when we don't need it as is the case here.

**Comment by klesh** [comment]
Yeah, I'm OK with it as long as it won't break the existing users.

**Comment by sayeedhussain** [comment]
@klesh It's hard to tell if it will be break existing consumers or not as that depends on how their respective libraries handle a trailing slash (strictly or loosely).

Personally I prefer to break consumers if it fixes a source of confusion or mistake and deal with the backlash. Your call.

Feel free to close the issue whichever way you decide.

**Comment by klesh** [comment]
@sayeedhussain Maybe supporting both? That way we can sure it will work for both and future users.

**Comment by sayeedhussain** [comment]
@klesh  https://github.com/apache/incubator-devlake/pull/7009. 

Once this gets incorporated in a release and the helm chart repo accommodates that release, will raise the PR there.

**Comment by klesh** [comment]
You may need to cherry-pick it back to v0.21(beta phase) or it will not be available until `v1.0`(development phase)

**Comment by sayeedhussain** [comment]
@klesh Do you mean cherry-pick this commit to release-v0.21 branch?

**Comment by klesh** [comment]
Yes. 👍

**Comment by sayeedhussain** [comment]
@klesh, @Startrekzky PR to release branch https://github.com/apache/incubator-devlake/pull/7038
