### ISSUE TITLE
[Feature][Deployment] Multy deploy in a single pipeline

### ISSUE THREAD

**Issue by antoniomuso** [apache/devlake#6959]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

My software in a single deploy pipeline can have deployment jobs for more than one product. This can happen when the application is a multi-tenant.

### Description

The regex used in the scope config, even if it matches a specific job, assigns the tag deployment to the entire pipeline. The feature should allow the count of a single job as deployment or to mark the job matched by the scope config regex.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Sounds interesting, could you share more concrete examples (fake data maybe) to help us understand the problem better? Thanks.

**Comment by antoniomuso** [comment]
Hi, @klesh. Thanks for the answer. 
I have a project, for example, let's call it `anime` that has different deploys for each region, anime.com/anima.us, etc...; the project in my organization is a single Gitlab repository, and when I do I release, I create a single pipeline where there are n manual deployment jobs one for each tenant. I want to track each job as a single deployment. Then, for example, if I have two tenants, anime.com and anime.us, I wish to obtain two deployments. I haven't found a way to do it with devlake without using a regex on SQL.

**Comment by klesh** [comment]
Thanks for the thorough explanation.
loop @Startrekzky

**Comment by hezyin** [comment]
Here's another data point contributed by a DevLake user:

![Untitled-2023-09-13-1844](https://github.com/apache/incubator-devlake/assets/2908155/02f2abc0-0f3e-428e-8015-5be583f2637d)


They release a new "cluster chart" at regular intervals, but enterprise customers, each with unique change requirements and schedules, may not upgrade immediately.

As shown in the diagram, they serve multiple customers. Each customer may have one or more management clusters, primarily for georeplication. Each management cluster oversees multiple workload clusters (corresponding to different development stages like dev, staging, prod).

This DevLake user's primary concern is to minimize the number of distinct cluster chart versions in circulation to reduce maintenance costs. They track the time from a new cluster chart release to its deployment across most workload clusters. Additionally, they need to segment deployment data by customer, management cluster name, type (WAS, Azure, VMware, bare metal), and workload cluster name.

To measure the percentage of workload clusters on a specific release version, we need to know how many workload clusters are there in total. We can approximate this number using the total number of workload clusters we have seen in the past.

**Comment by Startrekzky** [comment]
@hezyin Since the use case you brought up was slightly different from the original feature request, I created a new issue #7415 to track it.
