### ISSUE TITLE
[Bug][Grafana] auth_basic in config-ui interfere with grafana login

### ISSUE THREAD

**Issue by kirestamenov** [apache/devlake#6961]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Enabling the auth_basic interfere with grafana login. Before entering grafana credentials, you need to enter auth_basic credentials for the config-ui.

### What do you expect to happen

I expect that when I enable auth_basic those to be valid for config-ui only and do not interfere with grafana login possibilities.

### How to reproduce

Enable auth_basic for config-ui and open grafana. You will be asked for config-ui credentials before you see grafana login screen.

### Version

latest

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
Add `auth_basic off;` to https://github.com/apache/incubator-devlake/blob/main/config-ui/nginx.conf#L47.

**Comment by abeizn** [comment]
@kirestamenov  It has taken effect in [v0.20.0-beta4](https://github.com/apache/incubator-devlake/releases/tag/v0.21.0-beta4) version

**Comment by kirestamenov** [comment]
@abeizn tested and it works as expected! Thanks a lot for the fast action
