### ISSUE TITLE
calendar_weeks table missing from Lake database

### ISSUE THREAD

**Issue by javaface** [apache/devlake#6962]
## Question
Should I have a calendar_weeks table in my Lake database?  

## Screenshots
![image](https://github.com/apache/incubator-devlake/assets/5598089/c388e9c6-5260-4bc0-8c6d-12f0a32c2bae)
![image](https://github.com/apache/incubator-devlake/assets/5598089/23a9f60c-3668-4758-a73e-e21a93e0e4e1)

## Additional context
I have some opendora devlake-go dora api queries returning zero values and I find the queries are referencing a calendar_weeks table not in my Lake database.  I see a calendar_months table but no calendar_weeks table.

**Comment by javaface** [comment]
With some help I see the calendar_weeks is a temporary, dynamic if you will, table.  The root of my problem appears to be that the the query is returning zeroes due to lake.cicd_deployment_commits table not having values in repo_id column. Not sure why that is.

**Comment by javaface** [comment]
> @javaface Which version are you using? And only is field `repo_id` empty? If your datasouce has no deployment_commits , then [`cicd_deployment_commits`](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#cicd_deployment_commits) will be empty.

cicd_deployments_commits is not empty. However, the repo_id column is not being populated.  Any idea why that would be?  Should have valued like **github:GithubRepo:1:607853062**.

**Comment by d4x1** [comment]
@javaface  What's the version of DevLake you are using?

**Comment by javaface** [comment]
In my previous comment I indicated "I'm using v0.19.0 (latest)".  Is that what you're looking for?

**Comment by Startrekzky** [comment]
Hi @javaface , we added the table calendar_months to simplify the SQL in the DORA dashboard. Since we don't have a weekly-level DORA metrics, we didn't add the calendar_weeks table.

**Comment by javaface** [comment]
Hello, I figured out that calendar_weeks has nothing to do with my issue.  The opendora team is working on it.  See [](https://github.com/DevoteamNL/opendora/issues/139) if interested.  Thanks.
