### ISSUE TITLE
[Bug][website] Image doesn't be loaded in official website

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#6974]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I open https://devlake.apache.org/docs/DORA/,  I found this image cannot be seen.
<img width="1014" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/5364835e-dc98-4b65-8a0f-5733d5f8dc28">
But when I try to open this image with a new tab, it can be shown correctly.

### What do you expect to happen

Image should be loaded and shown.

### How to reproduce

Open the link.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
@d4x1 I can see it. Maybe you need to check your internet.

![image](https://github.com/apache/incubator-devlake/assets/37237996/131e958a-03f4-4de6-9a9c-41ec09b28c5b)

**Comment by d4x1** [comment]
It works now.
