### ISSUE TITLE
[Bug][Devlake-config-ui] Request failed with status code 500

### ISSUE THREAD

**Issue by mparthi3-ford** [apache/devlake#6989]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Getting "Request failed with status code 500" in config-ui screen after successful Installation of Devlake

### What do you expect to happen

Devlake dashboard should work successfully

### How to reproduce

1. Install devlake in your local host. After successful installation of devlake, the user would get to view the below services
   mysql, grafana, devlake and config-ui
2. Click "**config-ui**" (http://localhost:4000) in your browser for devlake configuration and data collection
3. Right after clicking  the "config-ui" , the user is navigated to the browser and get to see the internal error **"Request failed with status code 500"**
 4. I tried continue button which was displayed in the config-ui screen but no anvil. I ahve attached the screen shot for reference.
<img width="2055" alt="devlake_config_ui_internal_error_500" src="https://github.com/apache/incubator-devlake/assets/95069195/0d23ab23-eadb-42ee-b50f-35cb4a2c8bea">

### Anything else

Please help to prioritise this issue at the earliest possible time.

### Version

v0.21.0-beta4

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, can you share the log of the `devlake` container? thanks.

**Comment by mparthi3-ford** [comment]
Looks like the issue got resolved. It was the cached data that was sing the issue. Its working fine after clearing the cache completely.

**Comment by mparthi3-ford** [comment]
I shall close this ticket.
