### ISSUE TITLE
[Question][Lake] Unable to link deployment.id to issue.id in project_issue_metrics table

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#7006]
## Question
I am importing incidents into devlake using webhooks as my incident management tool (ServiceNow) is not supported by Devlake yet. 

When I import, the issue is getting created in the `issues` table in mysql correctly. However, there is no way to map that issue to a deployment for the `Change Failure Rate` metric whose sql query seem to be querying project_issue_metrics table to perform a join to tie an issue to a deployment. Refer https://devlake.apache.org/docs/Metrics/CFR/#how-is-it-calculated.

In my case, the project_issue_metrics table is empty and logically so because the webhook is only populating issues table.

How to solve this?

thanks in advance.

## Screenshots
NA

## Additional context
NA

**Comment by abeizn** [comment]
@sayeedhussain You need to execute the dora plug-in in the project (remember to add the webhook operation in this project)
https://github.com/apache/incubator-devlake/blob/main/backend/plugins/dora/tasks/incident_deploy_connector.go#L47

![image](https://github.com/apache/incubator-devlake/assets/101256042/6ba6d1b1-81de-4b29-9b72-6c9be9922195)
![image](https://github.com/apache/incubator-devlake/assets/101256042/6cb28fb4-049f-4f7a-a17d-d1d6f11ad3c8)

**Comment by sayeedhussain** [comment]
thanks! @abeizn. Collecting data again after adding the webhook to the project fixed the issue. Closing this.
