### ISSUE TITLE
[Question][lake] Why so few unit tests?

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#7007]
## Question
I am looking at the repo, there is very few unit tests and not sure if they are even being run on PRs as I don't see any pipelines in gha. Any reason why this is the case for a large codebase like this?

## Screenshots
NA

## Additional context
NA

**Comment by klesh** [comment]
Apache DevLake is mainly a data-collecting and processing analytic system.
So, most of the time, we deal with 3rd APIs in which unit-test is not applicable, and data processing which is covered by a massive amount of e2e-tests.
We do have some unit tests where we thought it was needed, and yes, the situation can be improved, feel free to share your thoughts on how to do so. 😊

**Comment by sayeedhussain** [comment]
@klesh Let me review and get back 👍

**Comment by sayeedhussain** [comment]
@klesh My bad. I missed looking at all the tests. The coverage seems to be good. thanks! 

Closing this.
