### ISSUE TITLE
[Question][grafana] Lost my saved grafana dashboards after upgrade of devlake

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#7008]
## Question
Lost my saved grafana dashboards after upgrade of devlake. This is problematic for adoption of devlake if it happens after every upgrade. How can this be avoided. thanks! 

## Screenshots
NA

## Additional context
NA

**Comment by klesh** [comment]
Are you updating the provisioned dashboards? They will be overwritten after the upgrade because we do need to update them from time to time.
Please save your modified dashboards as a new copy to avoid it.
Maybe we should put it somewhere on https://devlake.apache.org/
@Startrekzky

**Comment by sayeedhussain** [comment]
@klesh 
1. Yes I had updated the provisioned dashboards.
2. Sure will save them as a copy. This helps. 
3. Yes, it will be good to document this as on devlake website. Please consider documenting this on the grafana dashboard as well as in Read only info in a panel. That way, it is more user experience friendly.
cc: @Startrekzky

**Comment by Startrekzky** [comment]
Hi @sayeedhussain  It is documented on DevLake website
![img_v3_028e_a7a473b1-b46a-4e4b-aa00-dacabf7d1e0g](https://github.com/apache/incubator-devlake/assets/14050754/5df4e3bb-cdac-4a53-a329-dd78d5e19dab)

However, I put up a PR to make it more visible https://github.com/apache/incubator-devlake-website/pull/725

**Comment by sayeedhussain** [comment]
this looks good @Startrekzky. thanks!
