### ISSUE TITLE
[Bug][Jira] Worklogs are not always imported completely 

### ISSUE THREAD

**Issue by richard-fletcher** [apache/devlake#7010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

It seems that Worklogs are not always imported completely. In many cases, I see only the first page of Worklogs collected (20 items). I think that the expectations of this logic may not be met when the Worklogs are extracted from the Issue:

https://github.com/apache/incubator-devlake/blob/main/backend/plugins/jira/tasks/worklog_collector.go#L72

Additionally, I see cases where Epics have no Worklogs. I suspect that this may be due to the order of Tasks where Worklogs are extracted before Epics are collected. This is just a guess however.

### What do you expect to happen

All worklogs are imported from issues.

### How to reproduce

- Attempt to import an Issue with more than 20 Worklogs.

### Version

v0.21.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Sorry for the late report, will look into it ASAP
