### ISSUE TITLE
[Bug][Grafana] Dora dashboard configuration for Change Failure Rate metric is incorrect

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#7026]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The threshold for Elite is supposed to be 0.05 but is instead set to 5 in `Change Failure Rate` metric in  Dora/DoraByTeam dashboards.

<img width="1428" alt="Screenshot 2024-02-26 at 10 13 10 PM" src="https://github.com/apache/incubator-devlake/assets/1550131/eafc6706-3bc8-4307-9b7d-541c94d49737">

<img width="1434" alt="Screenshot 2024-02-26 at 10 13 22 PM" src="https://github.com/apache/incubator-devlake/assets/1550131/8dedee61-4698-426c-aa98-d5c1ad9cd557">

### What do you expect to happen

Threshold value should be 0.05

### How to reproduce

Open Dora/DoraByTeam dashboards in Graphana and view the sql query.

### Anything else

NO

### Version

0.21.0-beta5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks. Could you get it fixed in both main and v0.21? @abeizn

**Comment by Startrekzky** [comment]
This is fixed. Will be released in v0.21.0-beta6

**Comment by sayeedhussain** [comment]
Great @Startrekzky
