### ISSUE TITLE
[Feature][GitHub App] Support for multiple Github Apps for github extraction

### ISSUE THREAD

**Issue by pimguilherme** [apache/devlake#7049]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

We are looking to have most of our company's Github repositories within DevLake to get an overview of the development process. This amounts to over 6000 repositories. 

Currently, we have around 400 repositories and we observe an average lag of 1 day with syncing. We are currently syncing only one blueprint at a time due to rate limit errors we've hit in the past.

Before we add the remaining repositories to DevLake, we are looking to tackle the Github extraction portion of this by requesting a round robin fashion of extraction not only with PAT but also with Github Apps.

### Description

This would basically mean being able to register multiple Github Apps for each Github connection and round robin through them just like we do with Github PATs.

Is this something you considered when implementing the Github PAT round robin?

Also, would you have other remarks in terms of scalability considering the amount of repositories we want to add to DevLake? (ex database bottlenecks etc)

We have figured that a workaround could be using Github PATs and using a script/service to automatically rotate them via API by generating tokens from Github Apps, but that would be quite a bit hacky haha

Thank you for you time in advance!
All the best

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Interesting idea of Generating Github App 😄.
It is more than welcome if you would like to work on Round Robining GitHub Apps. Feel free to reach out to me on Slack if you need any assistance.

**Comment by pimguilherme** [comment]
okay, thanks for welcoming the idea @klesh ! I will discuss with our team internally and see if we can prioritize this

I will let you know

Cheers!
