### ISSUE TITLE
[Project Monitoring][UI] Simplify viewing Pipeline Status from the Projects UI

### ISSUE THREAD

**Issue by pakfur** [apache/devlake#7050]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

.....be able to more efficiently view the pipeline status from the Projects UI. 

### Description

Currently, to view the detailed status of a project run, I have to click on the config icon on the projects screen (image 1), then click on status (image 2) to view the pipeline status. 

It would be more efficient for the project UI Status field to directly link the latest pipeline run, either on the pipeline page or from the blueprint page.

image 1
<img width="1452" alt="image" src="https://github.com/apache/incubator-devlake/assets/1521847/848f82bd-18e4-4159-8aa1-7e4e00f5729b">

image 2
<img width="884" alt="image" src="https://github.com/apache/incubator-devlake/assets/1521847/a782b7d3-d3d0-4eee-ab57-572544ac3121">

<img width="194" alt="image" src="https://github.com/apache/incubator-devlake/assets/1521847/b52aedf3-22f8-4ec8-b4a6-196e71f6663d">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
I agree. @Startrekzky @hezyin

**Comment by d4x1** [comment]
+1
