### ISSUE TITLE
[Bug][Module Name] DevLake Pipelines show undefined for the task names

### ISSUE THREAD

**Issue by prateekj201** [apache/devlake#7059]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

For this version, the project sync status shows undefined task name

![image](https://github.com/apache/incubator-devlake/assets/16081342/ebb384a9-525f-4783-963e-8031b232e0a6)

### What do you expect to happen

The task name should have been as per the jenkins job names instead of undefined

### How to reproduce

Add a new project for jenkins connection and when the pipeline run, you should be able to see the undefined task names in the pipeline status

### Version

v0.21.0-beta4@9192e52

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Fixed, new beta on the way.

**Comment by klesh** [comment]
ffw
