### ISSUE TITLE
[Bug][Lake] Unable to delete sonarqube connection

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#7075]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Unable to delete sonarqube connection. Get an error. Version: 0.21.0-beta5. 

![1](https://github.com/apache/incubator-devlake/assets/1550131/599a3e47-6f9c-4402-99ea-8c2d4c9b79fd)

<img width="1840" alt="Screenshot 2024-02-29 at 10 01 42 PM" src="https://github.com/apache/incubator-devlake/assets/1550131/36ee2c32-a63d-4d1b-b002-ea27c5cfbaf6">

### What do you expect to happen

Connection should get deleted

### How to reproduce

1. Create a sonarqube connection in config-ui
2. Delete the connection in config-ui

### Anything else

No

### Version

0.21.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@sayeedhussain It will take effect in v0.21.0-beta7 version, expected to be released this week.

**Comment by sayeedhussain** [comment]
Great @abeizn
