### ISSUE TITLE
[Feature][Config-UI] Provide tooltip text on icons in config-ui

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#7076]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Currently in config-ui, there is a range of icons used on buttons but their function is not obvious. Refer screenshot. For better user experience, it will be useful to add tool-tip text that comes when hovering on the buttons.

![1](https://github.com/apache/incubator-devlake/assets/1550131/d5350432-ebd2-4ab9-86fb-b323e6d73c0c)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Please take a look @Startrekzky
