### ISSUE TITLE
[Bug][Lake] CodeReview (pull requests) data pulled by lake app does not honour the sync policy time range in config-ui

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#7079]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

CodeReview (pull requests) data pulled by lake app does not honour the sync policy time range in config-ui. Additional data is getting pulled from github. Refer screenshots.

<img width="1728" alt="Screenshot 2024-03-01 at 11 33 39 AM" src="https://github.com/apache/incubator-devlake/assets/1550131/25d3f310-6e6c-473e-b83d-0c318e6dcce2">

<img width="1724" alt="Screenshot 2024-03-01 at 11 33 29 AM" src="https://github.com/apache/incubator-devlake/assets/1550131/96f1c258-0c6e-49b8-b2f1-6b23c520ab77">

### What do you expect to happen

The sync policy time range in config-ui should be honoured by lake app while pulling data.

### How to reproduce

1. Create a project with sync policy time range of 3 months.
2. Create a github datasource connection with scopeconfig for CodeReview. Ensure the repository has pull requests for more than 3 months in the past.
3. Collect data
4. View pr.created dates for the project in MySQL
5. PRs with created date before 3 months is also available

### Version

0.21.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
That's beacuse DevLake fetches GitHub pull request via its graphql API, and this API doesn't support `createdAt` filter. So Devlake collect all pull requests.

<img width="1516" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/71e51849-d02a-4710-a4ee-eb01f23f4099">

Maybe we can collect pull request via `search` API, just like this: https://github.com/orgs/community/discussions/24611 . We can vote ont this matter.

**Comment by d4x1** [comment]
@sayeedhussain IMO, using search API is not the right way. I think we should ask GitHub to update its graphql API, it will take too long. 
Maybe we can filter out records that don't satisfy the time range.   @abeizn 
Will it lead to other problems?

**Comment by sayeedhussain** [comment]
@d4x1 Sure. My suggestion was that it will be good to fix the issue. How to fix is best decided by you/team. thanks!

**Comment by klesh** [comment]
Had been fixed in https://github.com/apache/incubator-devlake/pull/7878/files#diff-cebf96cf757874a695c6c6a61c75035530e6f6e33e61cbe594138736bbf45fb6R214
