### ISSUE TITLE
[Bug] Jenkins build name populating as the job name itself instead of the actual build name

### ISSUE THREAD

**Issue by prateekj201** [apache/devlake#7083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

if using currentBuild.displayName to change the build name for any job, devlake table **_tool_jenkins_stages**  shows **build_name** as the job name itself instead of the custom build name being set.
Also, "{jenkins_url}/job/{JobName}/api/json" shows job name instead of custom build name which could be causing this

### What do you expect to happen

**build_name** in **_tool_jenkins_stages**  to be as custom build name being populated as per job configuration

### How to reproduce

use  currentBuild.displayName to change the build name for any job to reproduce this

### Version

Apache 2.0 License v0.19.0@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
IMO, the best way is DevLake provides some an option with a default rule in scope config , and user can change it manually.

@Startrekzky

**Comment by Startrekzky** [comment]
@d4x1 A configuration to let users decide the assignment logic of the Jenkins build_name?

**Comment by d4x1** [comment]
> @d4x1 A configuration to let users decide the assignment logic of the Jenkins build_name?

Yes.
