### ISSUE TITLE
[Bug][gitlab] Data collect fails when commit title is too long

### ISSUE THREAD

**Issue by MarcViola** [apache/devlake#7088]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Receive this error and a partial success when collecting data.

`subtask ExtractDeployment ended unexpectedly Wraps: (2) error adding result to batch (500) Wraps: (3) Error 1406 (22001): Data too long for column 'deployable_commit_title' at row 82 (500) Wraps: (4) Error 1406 (22001): Data too long for column 'deployable_commit_title' at row 82 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError`

### What do you expect to happen

I see commit title in gitlab like the following:
"updated the active-nets-suppression and the etl-filter for atm-oe" 

Can it not support a long commit title?  What's the limit?  what sets the limit? Can it be truncated instead of failing?

### How to reproduce

gitlab commit with long tittle. collect data and see it fail.

### Version

v0.21.0-beta4@9192e52

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MarcViola** [comment]
I think it's the same as
[https://github.com/apache/incubator-devlake/issues/6455](url)

**Comment by klesh** [comment]
Thanks for reporting the issue.

**Comment by abeizn** [comment]
@MarcViola It will take effect in v0.21.0-beta7 version, expected to be released this week.
