### ISSUE TITLE
[Bug][gitlab] Deployment is counted when a job fails but pipeline passes

### ISSUE THREAD

**Issue by MarcViola** [apache/devlake#7089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

A gitlab project allows a pipeline to pass even though a deployment to production job fails (with option allow_failure: true)
So we have a situation where there was no deployment to production but DevLake counted it as a sucessful deployment in DORA.

Here are the conditions we verified:
![Screenshot 2024-02-26 at 2 29 33 PM](https://github.com/apache/incubator-devlake/assets/31352762/1cbeb39e-045e-4add-9e26-e471bdcfb103)

### What do you expect to happen

We expect the deployment not to count in the DORA metrics as a successfull deployment if the job fails, regardless of the status of the pipeline.

### How to reproduce

Create a pipeline in gitlab with 2 jobs. 1 test and 1 deploy.  The deploy must have option allow_failure: true
Make the test job pass, and the deploy job fails.  When the pipeline runs, the status of the pipeline will be "Warning" because the test job passed and the deploy job was allowed to fail.
Configure DevLake to count the "deploy" as deployment to prod in gitlab.

### Version

v0.21.0-beta4@9192e52

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Can you justify the `allow_failure: true` option? It doesn't make much sense to me, and how can we detect if the deployment goes through or not? screenshots and a more thorough explanation is needed because there are too many data sources right now. People tend to get confused by the behavior of different platforms.

**Comment by MarcViola** [comment]
Hi,
See also the related bug above for more information and screenshots.
Essentially it is possible to "allow" the pipeline to fail certain jobs and still deploy to production (could be a business decision). In the pipeline itself, it will show as warning and continue to the next job.  If the deployment to production job is successful, then we want to count it in the DORA metric.  If we don't allow a job to fail, then the deployment to production would never happen and therefore never count.  Basically DORA metric should look at the deployment job status regardless of the pipeline status.  Since the regex points to the job than it should be possible, no?

**Comment by Startrekzky** [comment]
Hi @MarcViola , do you use GitLab deployments or you only GitLab pipelines? If you use GitLab deployments, then the status of the deployment corresponding to a pipeline's failed deployment job should be 'failed'.

**Comment by MarcViola** [comment]
Hi, in some cases we do and others we don't.  Let me check.  Thanks.
