### ISSUE TITLE
[Bug][Lake] repos table is not getting cleared when Project/Connection is deleted

### ISSUE THREAD

**Issue by sayeedhussain** [apache/devlake#7096]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After deleting Project/Connection of my github datasource, the repos table was not cleared and the dropdown showed the deleted Project's/Connection's repos as well. Refer screenshot.

<img width="1714" alt="Screenshot 2024-03-04 at 4 43 06 PM" src="https://github.com/apache/incubator-devlake/assets/1550131/4959a87b-e7b3-4db0-9910-5b5e901cb55d">

### What do you expect to happen

repos of deleted Project/Connection should also get deleted from repos table.

### How to reproduce

1. Create a github connection and add to a project.
2. Sync data from github including repositories
3. Delete Project and Connection
4. View repos table. The repos from the deleted Project / Connection is still visible.
5. View the default github dashboard as shown in below screenshot. The repos from deleted Project/Connection are still visible in the dropdown.

<img width="1714" alt="Screenshot 2024-03-04 at 4 43 06 PM" src="https://github.com/apache/incubator-devlake/assets/1550131/87bdff43-cbda-4a34-a7e2-ba7b7b13f73b">

### Anything else

Problem happens always.

### Version

0.21.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@sayeedhussain Have you deleted the data scope and connection?
After I deleted the project, I pressed 1 and 2 to delete the data scope and connection respectively. The data in the repos table was indeed deleted.

![image](https://github.com/apache/incubator-devlake/assets/101256042/ecfcf6d4-da91-47c5-88fa-5b65e42b2d22)
![image](https://github.com/apache/incubator-devlake/assets/101256042/275b5257-c2e9-4543-8f6c-21fb158f83a6)

**Comment by sayeedhussain** [comment]
@abeizn Will re test this in upcoming beta7 and get back.

**Comment by sayeedhussain** [comment]
@abeizn Issue not happening in 0.21.0-beta7. Closing this card.
