### ISSUE TITLE
[Bug][Jenkins] Jenkins jobs are marked incorrectly as a production deployment.

### ISSUE THREAD

**Issue by Geni2** [apache/devlake#7097]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When you collect data from Jenkins and you specify in the data scope only collect if that is a production deployment.
But DevLake has no info if the stage `production deployment` on that job was running or it was skipped.

The pipeline was successful but it's not a production deployment and it should not be marked as one.
![jenkins](https://github.com/apache/incubator-devlake/assets/51850738/378f92d7-c1a0-4587-a558-f39902ca591e)

### What do you expect to happen

If the stage that I have specified in the data scope e.g. deploy production was skipped we should count that as a production deployment.

### How to reproduce

1. Connect Jenkins with DevLake and make the configuration with the data scope.
2. Make the configuration of the Scope Config.
3. Create a Jenkins pipeline with 2 or 3 stages, the name is not important but call one stage `deploy prod`.
4. Run the job and make sure the `deploy prod` was skipped but the pipeline was successful.
5. If you go to the Grafana board you will see that the job was counted as a production deployment but in fact, that wasn't.

### Version

v0.19.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@Geni2 You can upgrade to v1.0.0-beta3 or v0.21.0-beta9. We have made some improvements to see if we can meet your needs.

**Comment by Geni2** [comment]
Hi @abeizn, thank you for the response. I just upgraded DevLake to v1.0.0-beta4 and I will test it and let you know if this issue is fixed.

**Comment by Startrekzky** [comment]
Hi @Geni2 , any updates here?

**Comment by Geni2** [comment]
@Startrekzky, sorry for the late response. We tested this with devlake v1.0.0-beta4 and the issue still persists.
So devlake tags prod deployments although the stage that is marked for prod is not executed.

**Comment by abeizn** [comment]
To be investigated.

**Comment by abeizn** [comment]
@Geni2 It takes effect in version v1.0.0-beta7.

**Comment by Geni2** [comment]
@abeizn Thank you for the work, I will update to that version and will test it.
