### ISSUE TITLE
[Bug][Config UI] Pipeline option under Advanced is disabled 

### ISSUE THREAD

**Issue by mparthi3-ford** [apache/devlake#7098]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have deployed Devlake in Openshift and were able to access Config UI service. However, the **pipeline** option that is available on the left pane within Advanced Settings is disabled. Owing to this I could not connect to Grafana URL and the metrics pertaining to the data sources Github, SonarQube and Jira were not available.

### What do you expect to happen

1. After the data source, data scope , scope config configurations are completed, the next step is to collect the data so that the metrics wold be displayed in grafana.

### How to reproduce

AFter the devlake is hosted in openshift, verify that the "pipeline" option is enabled. It will be in disabled state.
We would like to know as to how to enable tghe pipeline within config UI so that the automation step is enabled.

### Version

v.0.19.1 -beta

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
fixed by https://github.com/apache/incubator-devlake/pull/7449 and https://github.com/apache/incubator-devlake/pull/7462
