### ISSUE TITLE
[Bug][config-ui] Allow NOT to not be forced to use ipV6

### ISSUE THREAD

**Issue by mlasevich** [apache/devlake#7100]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When https://github.com/apache/incubator-devlake/issues/6954 was merged, ipv6 was enabled in nginx, however the side-effect was to break the container if ipv6 is not enabled. config-ui container does not start if ipv6 is disabled. Get error:

```
2024/03/04 18:20:37 [emerg] 11#11: socket() [::]:4000 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:4000 failed (97: Address family not supported by protocol)
```

### What do you expect to happen

Container to run, with only ipv4 enabled

### How to reproduce

Run config-ui container on a host without ipv6 stack enabled.

### Anything else

Ideally it would be an optional thing.

### Version

release-v0.21_240301_0901_460517a

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, @mlasevich Thanks for reporting the issue, I'm assigning the issue to you since the "Yes I am willing to submit a PR!" was checked. Let me know if I am mistaken.

**Comment by ivansumak** [comment]
Hello, 

@mlasevich  any progress with this issue? If there is none, I can take over.

**Comment by mlasevich** [comment]
Sorry, been slammed with the day job work, did not have a chance to look at this. Thank you for addressing this :-)

**Comment by klesh** [comment]
> Sorry, been slammed with the day job work, did not have a chance to look at this. Thank you for addressing this :-)

No problem, @ivansumak had kindly addressed the bug.
