### ISSUE TITLE
[Bug][lake] devlake add data scope of zentao, cannot load project information and prompt error

### ISSUE THREAD

**Issue by marymwu** [apache/devlake#7101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

devlake add data scope of zentao, cannot load project information and prompt error
zentao version: flagship version 4.10
devlake: 0.21.0-beta1
![error2](https://github.com/apache/incubator-devlake/assets/19792306/48dc7879-8f4e-462b-978a-83372b960587)
![error1](https://github.com/apache/incubator-devlake/assets/19792306/3ad21813-8631-41d5-9f48-672100a41519)

### What do you expect to happen

successfully add data scope of zentao

### How to reproduce

add data scope of zentao in devlake, and click project, cannot load project information and prompt error

### Version

0.21.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
I would guess they have changed AGAIN. It is hard to keep up with it.

**Comment by d4x1** [comment]
@marymwu  You can try the latest code in branch `release-v0.21`(I am not sure which version, just use the latest code.).  I have submitted some code related to Zentao.

**Comment by marymwu** [comment]
> @marymwu You can try the latest code in branch `release-v0.21`(I am not sure which version, just use the latest code.). I have submitted some code related to Zentao.

ok, I'll try, thank u!
