### ISSUE TITLE
[Feature][config-ui] Connections pagination isn't wired up to page size drop down

### ISSUE THREAD

**Issue by wouldd** [apache/devlake#7114]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have hundreds of repositories and I needed to add ac config scope to them all however you can only select 'all' for the currently displayed page of 10. there is a drop down to select larger page sizes but it does not work.

### What do you expect to happen

I expected the drop down to reload the page with the selected number of items per page

### How to reproduce

have more than 10 repo connection. select the drop down on the bottom right and select any page size other than 10

### Anything else

this is the git diff patch for the fix:
--- a/config-ui/src/routes/connection/connection.tsx
+++ b/config-ui/src/routes/connection/connection.tsx
@@ -53,7 +53,7 @@ export const Connection = () => {
   const [operating, setOperating] = useState(false);
   const [version, setVersion] = useState(1);
   const [page, setPage] = useState(1);
-  const [pageSize] = useState(10);
+  const [pageSize, setPageSize] = useState(10);
   const [scopeId, setScopeId] = useState<ID>();
   const [scopeIds, setScopeIds] = useState<ID[]>([]);
   const [scopeConfigId, setScopeConfigId] = useState<ID>();
@@ -97,7 +97,7 @@ export const Connection = () => {
   const handleHideDialog = () => {
     setType(undefined);
   };
-
+
   const handleShowDeleteDialog = () => {
     setType('deleteConnection');
   };
@@ -332,6 +332,10 @@ export const Connection = () => {
             pageSize,
             total,
             onChange: setPage,
+            onShowSizeChange: (current,size)=> {
+              setPage(1);
+              setPageSize(size);
+            }
           }}
           rowSelection={{
             selectedRowKeys: scopeIds,

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@mintsweet What do you think.
cc @Startrekzky

**Comment by mintsweet** [comment]
hi @wouldd, thank you for your suggestion. I think this is an optimization that can be made ([I have left an entry in the code](https://github.com/apache/incubator-devlake/blob/main/config-ui/src/routes/connection/connection.tsx#L56)), but it is not a bug, and to ensure the unity of the UI, we cannot modify one place alone. At the same time, we currently have no energy to optimize here. I hope you can submit PR.

**Comment by luongc** [comment]
I noticed that, even though the page size is 10, the backend service call doesn't respect the pagination limit/size. Will this be addressed from this change as well?

**Comment by mintsweet** [comment]
Sorry @luongc, I don't think so. This issue has nothing to do with this, you can submit another issue.
