### ISSUE TITLE
[Feature][Dash board] AWS Native DevOps Dashboard

### ISSUE THREAD

**Issue by kgoswami4** [apache/devlake#7117]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Connect to AWS Native DevOps services (CodeCommit, CodePipeline, CodeBuild, CodeDeploy, CodeGuru) and show the DORA metrics on the dashboard

### Description

Connect to AWS Native DevOps services (CodeCommit, CodePipeline, CodeBuild, CodeDeploy, CodeGuru) and show the DORA metrics on the dashboard

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Geekays** [comment]
Seems this repository is dead!

**Comment by ZhangNing10** [comment]
hi @kgoswami4 @Geekays , thanks for the report! we will have a look
