### ISSUE TITLE
[Bug][Jenkins] The Field “triggerd_by” in database table _tool_jenkins_builds is empty

### ISSUE THREAD

**Issue by realmyy** [apache/devlake#7141]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I want to use the  field “trigger_by” to distinguish the build tasks in Jenkins, but I found that this field is empty in the data table

### What do you expect to happen

the field “triggerd_by”  should record the build action trigger information

### How to reproduce

open the database lake and find the table  _tool_jenkins_builds，notice the field “triggerd_by” is empty，as shown below.
![empty](https://github.com/apache/incubator-devlake/assets/42348913/ac6bb731-425b-475f-86de-56cf9b47b595)

### Version

v0.20.0 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
`triggered_by` is assigned in this line https://github.com/apache/incubator-devlake/blob/main/backend/plugins/jenkins/tasks/build_extractor.go#L110. It has some pre conditions, please check weather it's satisfied.

**Comment by Startrekzky** [comment]
Feel free to reopen it if it still exists. Thanks.
