### ISSUE TITLE
[Question][] How can we get/export openapi spec instead of swagger

### ISSUE THREAD

**Issue by sha-intelli** [apache/devlake#7154]
## Question
Hi, I would like to find out how I can export the openai spec instead of swagger based on the functions shown in the code [here](https://github.com/search?q=repo%3Aapache%2Fincubator-devlake%20openapi&type=code). I can see the function here. It is unclear as to what I should do exactly.

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by klesh** [comment]
I would like to know that as well, would you like to share the information if you figured it out? 😄

**Comment by dc-seena** [comment]
BUMP - Our team can use a valid openapi spec to extend a lot of integration/automation features - Any chance someone can chime in, seems based on this plugin/code there might be a way to export API spec: https://github.com/apache/incubator-devlake/blob/main/backend/core/plugin/plugin_openapi_spec.go

Also tagging and @CamilleTeruel and @wanisfahmyDE that had some related commits - Appreciate any clues anyone can provide.

**Comment by wanisfahmyDE** [comment]
Hey @dc-seena, I am not sure if that's what you're looking for but I had a look at:
https://github.com/apache/incubator-devlake/blob/main/backend/server/api/api.go#L176-L201 and found the generated json file `doc.json`, then locally I started DevLake and got the API definition in json format when hitting:
[http://localhost:8080/swagger/doc.json](http://localhost:8080/swagger/doc.json).

Does this help?
