### ISSUE TITLE
When will bitbucket server land in bèta ?

### ISSUE THREAD

**Issue by martynvdijke** [apache/devlake#7155]
Hi all,

Just wondering when bitbucket server plugin will land in a new beta release?
I just upgrade to beta7 but can't see the change.
I would love to play wih this.

_Originally posted by @martynvdijke in https://github.com/apache/incubator-devlake/pull/6689#issuecomment-1985561204_

**Comment by ohjongsung** [comment]
I'm curious too. I thought it would be included in beta-7, but when will I be able to use it?

**Comment by klesh** [comment]
bitbucket server will be available on `v1.0.0`, maybe in 2 weeks.

**Comment by realmyy** [comment]
I also looking forward this plugin

**Comment by mieliespoor** [comment]
See https://github.com/apache/incubator-devlake/releases/tag/v1.0-beta1
