### ISSUE TITLE
[Bug][DORA Dashboard] Cannot load dora main table

### ISSUE THREAD

**Issue by SantiagoGalicia** [apache/devlake#7156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1435" alt="Captura de pantalla 2024-03-11 a la(s) 10 14 23 a m" src="https://github.com/apache/incubator-devlake/assets/47221871/e0ff0d72-2375-4aee-b368-5888adb74f55">

the main table contains an error on the query

### What do you expect to happen

display the dora information 

### How to reproduce

create a dora project and verify if one of the main metrics is displayed

### Anything else

no

### Version

v0.21.0-beta3@a959768

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@SantiagoGalicia Did you use the grafana dashboard on main? I tested it, the v0.21.0-beta3 version is ok, and the dora_report field was only changed on main.
![image](https://github.com/apache/incubator-devlake/assets/101256042/d361ca35-cf17-4460-b678-6f6add8dbd23)

**Comment by Startrekzky** [comment]
Hi @SantiagoGalicia , since it's hard to reproduce, could you upgrade to v1.0.0-beta4 to retry it? Feel free to reopen it if it still exists. Thanks.

**Comment by SantiagoGalicia** [comment]
resolved, with the new version the graph works, thank you @Startrekzky
