### ISSUE TITLE
[Bug][CICD] Error converting float to uint64

### ISSUE THREAD

**Issue by timrog** [apache/devlake#7172]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I tried to add a Github scope including CI/CD to pull data from GitHub Actions jobs. During the run, step 5 produces the error shown.

```
time="2024-03-13 16:06:55" level=info msg=" [pipeline service] [pipeline #1368] [task #51229] start executing task: 51229"
time="2024-03-13 16:06:55" level=info msg=" [pipeline service] [pipeline #1368] [task #51229] start plugin"
time="2024-03-13 16:06:55" level=info msg=" [pipeline service] [pipeline #1368] [task #51229] total step: 3"
time="2024-03-13 16:06:55" level=info msg=" [pipeline service] [pipeline #1368] [task #51229] executing subtask generateDeployments"
time="2024-03-13 16:06:55" level=info msg=" [pipeline service] [pipeline #1368] [task #51229] [generateDeployments] finished records: 1"
time="2024-03-13 16:06:55" level=error msg=" [pipeline service] [pipeline #1368] [task #51229] subtask generateDeployments ended unexpectedly\n\tWraps: (2) error fetching rows (500)\n\tWraps: (3) sql: Scan error on column index 17, name \"duration_sec\": converting driver.Value type float64 (\"2.592547e+06\") to a uint64: invalid syntax (500)\n\tWraps: (4) sql: Scan error on column index 17, name \"duration_sec\"\n\tWraps: (5) converting driver.Value type float64 (\"2.592547e+06\") to a uint64: invalid syntax\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *fmt.wrapError (5) *errors.errorString"

```

### What do you expect to happen

It should run without errors

### How to reproduce

Create GitHub data scope including CI/DI and run

### Anything else

Appears to be related to [this issue](https://github.com/apache/incubator-devlake/issues/6136) and its fix. Column type was changed from uint64 to float and this error indicates something still expects uint64.

### Version

v20.0.0-beta10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@timrog  It's fixed in release v0.21.  Just have a try.
