### ISSUE TITLE
[Bug] Lake container in Helm chart doesn't start

### ISSUE THREAD

**Issue by anthonybe98** [apache/devlake#7174]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I tried to deploy devlake using Terraform and the helm chart. The pods start fine but I get this error:
 level=info msg="no [.env] file, please make sure you have set the environment variable."
 
 I can't find documentation or anything in values.yaml that says what to do with the .env file when using helm.
 
 I tried passing in env variables thinking it might create the env file but nothing:
 ` lake:
      encryptionSecret:
        secret: secret-value
      envs:
        API_TIMEOUT: "120s"
        API_RETRY: "3"
        API_REQUESTS_PER_HOUR: "10000"
        PIPELINE_MAX_PARALLEL: "1"
        IN_SECURE_SKIP_VERIFY: "false"
        LOGGING_DIR: "/app/logs"
        # debug, info, warn, error
        LOGGING_LEVEL: "info"`

### What do you expect to happen

It should run an not give the /etc error

### How to reproduce

Create a terraform k8s deployment and this will happen

### Version

0.21.0-beta7 and any other version

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
No, `.env` is optional and readonly.
You may pass your setting via Environment Variable which has been proven more flexible and practical.

**Comment by anthonybe98** [comment]
@klesh when the pods run I get this error:
level=info msg="no [.env] file, please make sure you have set the environment variable."

What is this error referring to then?
