### ISSUE TITLE
JIRA Transformation for calculating DORA not working as expected.

### ISSUE THREAD

**Issue by ibrahimejaz** [apache/devlake#7190]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

While computing the Stability metrics on DORA we've using JIRA transformation but it didn't work with getting the Median time to restore service it shows "N/A. Please check if you have collected incidents.".

Hereby attaching our JIRA workflow just in case. https://share.anysnap.app/fEzg7XJzjao9
The Devlake version we use is v0.21.0-beta3@a959768

### What do you expect to happen

To calculate the proper stability metrics

### How to reproduce

Configure the JIRA transformation mention the board name and configure the DORA for which field it should take for incident in our case its incident ticket only

### Version

v0.21.0-beta3@a959768

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ibrahimejaz** [comment]
Hi Team,
Any update on this pls.

**Comment by klesh** [comment]
Loop in @Startrekzky I think we should cover the use case in the future.

**Comment by Startrekzky** [comment]
Copied from my Slack comment:

> Only two DORA metrics are related to incidents (issues),  MTTR and CFR. Among these, CFR doesn’t use the status at all, so I guess you’re asking how MTTR is calculated.
> 
> DevLake regards incidents/issues with statusCategory = 'DONE' as resolved incidents/issues. It seems the three green statues’ statusCategory is ‘DONE’ (pic 1). Therefore, issues in any of the three statuses have a resolution_date in Jira and will be counted to calculate MTTR by DevLake.
> 
> ![image](https://github.com/apache/incubator-devlake/assets/14050754/71923637-53ff-44cb-baa1-f85051d0152c)
