### ISSUE TITLE
[Bug][devlake] Pipeline execution error

### ISSUE THREAD

**Issue by assert6** [apache/devlake#7196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![56222971c9d3b1c8bc7b6a7be446869](https://github.com/apache/incubator-devlake/assets/28561563/1dd76346-3d2c-4d2f-8def-1183ff76522c)
![441358cfcf79a086c73463cd8536de6](https://github.com/apache/incubator-devlake/assets/28561563/e311ec3d-330a-4dd6-b84c-97f4d3d65d32)
![fd9c865991938e29b9a96bbfff8a383](https://github.com/apache/incubator-devlake/assets/28561563/089c35e3-19c0-4f44-8162-6ad2800c6e90)
The blueprint with ID 1 did not execute a scheduled task and a non-existent blueprint with ID 3 is executing a scheduled task🤣

### What do you expect to happen

Blueprint with ID 1 executes scheduled tasks instead of 3

### How to reproduce

I'm not sure

### Version

devlake:v0.20.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @assert6 , since it's hard to reproduce. Could you upgrade to v1.0.0-beta4 to retry it? Thanks.
