### ISSUE TITLE
[Bug][Bitbucket] Error in collectGitCommits mysql, Incorrect string value unicode

### ISSUE THREAD

**Issue by duhow** [apache/devlake#7198]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

gitextractor task failed.
> subtask collectGitCommits ended unexpectedly Wraps: (2) Error 1366 (HY000): Incorrect string value: `'\xFChn\x0A'` for column 'message' at row 38 (500) Wraps: (3) Error 1366 (HY000): Incorrect string value: `'\xFChn\x0A'` for column 'message' at row 38 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError

### What do you expect to happen

Being able to import git history, with no crash in Task.

### How to reproduce

Caused by importing commit https://github.com/apache/nuttx-apps/commit/535566435364604265cdac368c16c79ecc48926c 

> NET: Another missing header file. Noted by Manuel Stühn

Note the unicode character escaped from the title.

```sql
time="2024-03-20 19:41:59" level=info msg="\x1b[31;1m/app/impls/dalgorm/dalgorm.go:251 \x1b[35;1mError 1366 (HY000): Incorrect string value: '\\xFChn\\x0A' for column 'message' at row 38\n\x1b[0m\x1b[33m[17.757ms] \x1b[34;1m[rows:0]\x1b[0m
INSERT INTO `commits` (`created_at`,`updated_at`,`_raw_data_params`,`_raw_data_table`,`_raw_data_id`,`_raw_data_remark`,`sha`,`additions`,`deletions`,`dev_eq`,`message`,`author_name`,`author_email`,`authored_date`,`author_id`,`committer_name`,`committer_email`,`committed_date`,`committer_id`) VALUES
('2024-03-20 19:41:59.109','2024-03-20 19:41:59.109','','',0,'','de5c7fa462debb0b33a7490ac62a44a3296c9058',61,61,0,'NxWM: Slightly improvied minimize icon\n','Gregory Nutt','gnutt@nuttx.org','2014-07-14 01:36:30','gnutt@nuttx.org','Gregory Nutt','gnutt@nuttx.org','2014-07-14 01:36:30','gnutt@nuttx.org'),
('2024-03-20 19:41:59.109','2024-03-20 19:41:59.109','','',0,'','535566435364604265cdac368c16c79ecc48926c',2,0,0,'NET: Another missing header file.  Noted by Manuel St\xfchn\n','Gregory Nutt','gnutt@nuttx.org','2014-07-05 13:06:51','gnutt@nuttx.org','Gregory Nutt','gnutt@nuttx.org','2014-07-05 13:06:51','gnutt@nuttx.org'),
```

### Version

558dabc

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by duhow** [comment]
Seems to be fixable with:

```sql
ALTER TABLE commits MODIFY COLUMN message LONGTEXT CHARACTER SET binary;
```

**Comment by klesh** [comment]
Hi, @duhow , Thanks for reporting the issue, seems like adding a migration script could fix the problem, would you like to work on it?

**Comment by klesh** [comment]
Here is a PR for your reference https://github.com/apache/incubator-devlake/pull/4685/files
