### ISSUE TITLE
[Bug] We added a project with a long name, but the /api/blueprints interface is throwing an error. The created project cannot enter the settings page, so we can't delete this project from the UI

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#7200]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Version where the issue was found: test-v20240314-1@77de98f
2. Operation steps:
    1. On the Projects page, click on New Project, and enter a very long project name:
xmt_321aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaa
Save
    2. The API endpoint api/projects is successful, but the endpoint api/blueprints returns an error. Error details are shown in the attached image.
![img_v3_0296_5478eeab-044d-459b-95d5-2a776c88530g](https://github.com/apache/incubator-devlake/assets/142298906/823f1e9a-a18b-4b7e-91f3-bf8eb971c0ef)

    3. Clicking on the Settings button on the right side of the project name "xmt_321....." results in an error, as shown in the attached image. 
![image](https://github.com/apache/incubator-devlake/assets/142298906/49f0db96-8365-4339-8120-6c846432b7a3)

I want to delete the problematic project that was not created successfully, but I am unable to delete it from the UI.

### What do you expect to happen

1. Go to the projects page, click New Project, enter a long project name：
[xmt_321aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaa](https://test.devinsight.ai/config/projects/xmt_321aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeaaa?tab=configuration)
2. Click Save. See the API response

### How to reproduce

See Above

### Version

0.21

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
This problem has been solved by limiting the length of the project.
