### ISSUE TITLE
[Bug][devlake] Timeout in Add Data Scope in Azure DevOps 

### ISSUE THREAD

**Issue by TPAlves** [apache/devlake#7207]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When adding a scope I had the Timeout error on the following endpoint: http://localhost:8080/api/plugins/azuredevops/connections/4/remote-scopes?groupId=my-company-brasil%2FProjectXPTO
<img width="954" alt="Error" src="https://github.com/apache/incubator-devlake/assets/74566269/952e4b46-aa93-4924-8802-32e36a30e467">

However, in the other scope the error did not occur. 
<img width="956" alt="scope-with-success" src="https://github.com/apache/incubator-devlake/assets/74566269/2eaaba60-bf7e-4802-b772-85f10bc56067">

### What do you expect to happen

I hope that all projects that are part of Scope will return without any timeout errors.

### How to reproduce

Unfortunately I don't know the pattern that causes this error.

### Version

v1.0.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, please try to new `azuredevop-go` plugin and see if the problem persists.

**Comment by guilhem** [comment]
I had same problem.
go fix it. Looks lightning now.

**Comment by TPAlves** [comment]
It worked, thank you very much for your help.
