### ISSUE TITLE
[Bug][Azure Devops] cicd_deployment gets incorrect Environment

### ISSUE THREAD

**Issue by KollarM** [apache/devlake#7211]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In Azure Devops we are using multistage CICD pipeline with 4 stages: Build, Dev, Test and Prod. 
![image](https://github.com/apache/incubator-devlake/assets/13602658/b4d29347-7914-433b-9596-d5fc4d5ccb52)

Prod stage requires approval, this approval requirement timeouts after 5 minutes. 
![image](https://github.com/apache/incubator-devlake/assets/13602658/022b57ea-eb9d-4bdb-b0d2-2dc0293650ba)

DevLake Scope Config is set to "The name of the Azure pipeline or one of its jobs matches
(deploy|push-image|Deploy)" and "If the name also matches
(.*prod.*)|(.*Prod.*)|(.*PROD.*)|(.*production.*)|(.*Production.*)|(.*PRODUCTION.*)
, this Deployment is a ‘Production Deployment’"
![image](https://github.com/apache/incubator-devlake/assets/13602658/ca1754fa-b247-4c4e-8af0-c5dce804b723)

**Issue is that DevLake Server doesn't check if Prod stage was finished or not.**

### What do you expect to happen

Excepted is that deployment is considered as "TESTING"when Azure Devops pipeline stage with name matching (.*prod.*)|(.*Prod.*)|(.*PROD.*)|(.*production.*)|(.*Production.*)|(.*PRODUCTION.*) was skipped (in our case because of approval timeout).

It is also expected and very important that when Azure Devops pipeline stage with name matching (.*prod.*)|(.*Prod.*)|(.*PROD.*)|(.*production.*)|(.*Production.*)|(.*PRODUCTION.*) is retried after several days and Approved and ends with success, then new deployment is created in DevLake with environment "PRODUCTION".

### How to reproduce

In Azure Devops create multistage CICD pipeline similar to this:

stages:
- stage: Build
  jobs:
  - job: Build
  ...

  - stage: Deploy_to_test
    displayName: Deploy to test
    jobs:
    - job: push
      displayName: Push docker image
      steps:
        ....
    - deployment: deploy
      dependsOn: push
      displayName: deploy
      environment: test

  - stage: Deploy_to_prod
    displayName: Deploy to prod
    dependsOn: test
    jobs:
    - job: push
      displayName: Push docker image
      steps:
        ....
    - deployment: deploy
      dependsOn: push
      displayName: deploy
      environment: prod

In Azure Devops setup Environmet with name "prod" that requires approval and timeouts after 5 minutes
Ran the pipeline and leave "prod" stage to timeout.
Setup Apache DevLake Connection with regex and collect data.
  

### Anything else

This is happening after each merge to master branch and makes metrics Deployment Frequency and Lead Time For Changes not correct.

### Version

v1.0.0-beta1 and v0.21.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Interesting, thanks for the thorough explanation. May I ask when the pipeline gets triggered? on PR merged?
Loop in @Startrekzky 
cc @hezyin

**Comment by KollarM** [comment]
Yes, the pipeline gets triggered after a PR is merged to main branch.

**Comment by klesh** [comment]
@KollarM I checked the code that SKIPPED jobs are excluded https://github.com/apache/incubator-devlake/blob/7ec58111290e8f2b036ccdcb733b764249638459/backend/plugins/dora/tasks/deployment_generator.go#L73 .
So, I'm wondering why they were still converted...
What were the `result` in the `cicd_pipelines` and `cicd_pipeline_commits`?

**Comment by KollarM** [comment]
select * from cicd_deployments where id like '%278014' 
--one record with result:SUCCESS status:DONE environment:TESTING

select * from cicd_deployment_commits where cicd_deployment_id = 'azuredevops:Build:1:278014' order by created_at desc
--one record with result:SUCCESS status:DONE environment:TESTING

**Comment by KollarM** [comment]
select * from cicd_pipelines where id like '%278014' 
-- one record with result:SUCCESS status:DONE type:BUILD
select * from cicd_pipeline_commits where pipeline_id  like '%278014' 
--one record  result column is not present

**Comment by klesh** [comment]
> select * from cicd_deployments where id like '%278014' --one record with result:SUCCESS status:DONE environment:TESTING
> 
> select * from cicd_deployment_commits where cicd_deployment_id = 'azuredevops:Build:1:278014' order by created_at desc --one record with result:SUCCESS status:DONE environment:TESTING

Thanks.
I'm confused, is it what you got or what you wanted? I thought you were saying the `environment` should be `TESTING` but got `PRODUCTION`.

**Comment by KollarM** [comment]
I'm sorry for the confusion, by accident I picked wrong example. The example shows situation of manual running the pipeline and forcing it to not have "test" and "prod" stage at all.
![image](https://github.com/apache/incubator-devlake/assets/13602658/3c7f1ba6-a9da-49b3-9767-93c87b37fc1b)


Data for normal situation when pipeline runs automatically after code is merged to main branch:
select * from cicd_deployments where id like '%277449'
--one record with result:SUCCESS status:DONE environment:PRODUCTION
select * from cicd_deployment_commits where cicd_deployment_id = 'azuredevops:Build:1:277449' order by created_at desc
--one record with result:SUCCESS status:DONE environment:PRODUCTION


select * from cicd_pipelines where id like '%277449' 
-- one record with result:SUCCESS status:DONE type:BUILD environment:NULL
select * from cicd_pipeline_commits where pipeline_id  like '%277449' 
--one record  result column is not present

**Comment by klesh** [comment]
@KollarM Got you.
I would like to ponder around the problem for a bit, will get back to you.

**Comment by KollarM** [comment]
Hi @klesh if more examples or clarification needed, I'm ready to help.

**Comment by KollarM** [comment]
I think I know where the problem was. Originally I looked on our pipeline just from a Stages perspective.
![image](https://github.com/apache/incubator-devlake/assets/13602658/65414aab-b11b-472d-b7d5-1e7222c0cf02) and I expected that this is not a DevLake Production Deployment because "Deploy to prod" Stage is skipped.

But when I expand the Stages, there are Jobs, one Job in "Build" Stage has name "Build bicep prod" and therefore whole pipeline is considered as environment Production.
![image](https://github.com/apache/incubator-devlake/assets/13602658/5bc51098-73a4-4aa3-bf41-d9e1795da4c9)


A change that helped is to rename our Jobs as in the picture below and adapt regex determining Production Deployment to be "(?i)(deploy.*prod)"
![image](https://github.com/apache/incubator-devlake/assets/13602658/d913edd5-db56-43ed-bd8a-e7b86e534e4c)
![image](https://github.com/apache/incubator-devlake/assets/13602658/b08f86ae-36cd-47f8-a781-4f065d8a799b)

**Comment by klesh** [comment]
Nice, did it solve your problem?

**Comment by KollarM** [comment]
Yes

**Comment by Startrekzky** [comment]
Problem solved.
