### ISSUE TITLE
[Feature][devlake] Supporting human readable project naming

### ISSUE THREAD

**Issue by hayk96** [apache/devlake#7217]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Hello Team,

Could we possibly add support for space characters in project names? The aim of this feature is to enable better naming conventions for projects in the DevLake UI and Grafana.

### Description

Example:
**My_Project** -> **My Project**

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks for the feedback. This makes sense.

**Comment by hayk96** [comment]
Hi @klesh and @Startrekzky, thanks for following up on this issue. It seems it's still impossible to create a project with a name like e.g. `My Project`  

Version `v1.0.0-beta11`

<img width="1503" alt="Screenshot 2024-06-16 at 14 26 05" src="https://github.com/apache/incubator-devlake/assets/46712946/f2ba9d09-c298-497c-9d07-d60f7b826860">

**Comment by hayk96** [comment]
Hello @mintsweet, I've just tried the `v1.0.1-beta8` and seems this issue still presents. 
c.c. @klesh @d4x1 
![Screenshot 2024-08-30 at 12 08 09](https://github.com/user-attachments/assets/6275c4e6-055e-4baa-8c62-767e1ac7a416)

**Comment by mintsweet** [comment]
Hi @hayk96, this is a mix-up; you should use `v1.0.1-beta8` instead of `v1.0.0-beta8`.

![image](https://github.com/user-attachments/assets/97cc0ad6-7755-4b43-ad19-4a95213069e5)

**Comment by hayk96** [comment]
Hi @mintsweet, thanks! Seems I haven't noticed the last 1 😄. BTW the appropriate version of the Helm charts is not available yet, I need to wait a bit.
