### ISSUE TITLE
[Question][ DORA] Lead Time for Changes Calculation method

### ISSUE THREAD

**Issue by Alok650** [apache/devlake#7220]
## Question
When calculating the lead time for changes in a GitHub repository with feature, stage, and production branches, Is the lead time for changes in Devlake based on the timestamps of commits in the feature branch, which represent the development effort, or on the timestamp of the pull request merged from the stage branch to the production branch, which indicates when the changes were deployed to production?

<img width="1305" alt="image" src="https://github.com/apache/incubator-devlake/assets/58817460/ffab82b0-8d01-4cc7-89c1-25ac1544d962">

**Comment by Startrekzky** [comment]
Hi @Alok650 , please check the doc for more details https://devlake.apache.org/docs/Metrics/LeadTimeForChanges
