### ISSUE TITLE
[Feature][Azure DevOps] Support PATs with the scope less than ALL ACCESSIBLE ORGANIZATIONS

### ISSUE THREAD

**Issue by nalexeyev** [apache/devlake#7243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Getting PATs for the scope of all organizations is almost impossible in a large organizations
Requirements to permissions in Azure DevOps PATs should be well-documented and follow the principle of least privilege

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Looking for volunteers

**Comment by nalexeyev** [comment]
> Looking for volunteers

I was implemented in the backend. Someone, please, add an option to UI
https://github.com/apache/incubator-devlake/issues/6221#issuecomment-1757613769

**Comment by mr-ks** [comment]
> Looking for volunteers

@klesh 
I will start working on this issue (focusing on the go plugin). I will try to make the frontend changes compatible with the python plugin.

**Comment by klesh** [comment]
@mr-ks Thanks for volunteering. Good coding!
