### ISSUE TITLE
[Bug][Bitbucket_server] collectApiPullRequestCommits fails when a PR losese it's commit

### ISSUE THREAD

**Issue by TihomirPop** [apache/devlake#7258]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Bitbucket Server data collection task fails because one pull request has corrupted/deleted commits.

> subtask collectApiPullRequestCommits ended unexpectedly
> Retry exceeded 3 times calling rest/api/1.0/projects/{projectKey}/repos/{repoName}/pull-requests/{pullRequestId}/commits. The last error was: Http DoAsync error calling [method:GET path:rest/api/1.0/projects/{projectKey}/repos/{repoName}/pull-requests/{pullRequestId}/commits query:map[limit:[100] state:[all]]]. Response: {\"errors\":[{\"context\":null,\"message\":\"Commit '{commitHash}' does not exist in repository '{repoName}'.\",\"exceptionName\":\"com.atlassian.bitbucket.commit.NoSuchCommitException\"}]} (404)

### What do you expect to happen

I think it would make sense for the data collection to continue even if a commit is missing, since we don't want to lose all of those Bitbucket metrics for the repository if just a single commit is missing.

### How to reproduce

Start data collection for a project with a Bitbucket Server plugin connection.
The data scope needs to be a repository where a commit from a pull request was deleted/corrupted after the pull request got merged. 

### Version

v1.0.0-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
I agree. It should skip the pr with no commits.

**Comment by sstojak1** [comment]
HI team, any updates regarding this issues?

**Comment by klesh** [comment]
@sstojak1 Not yet, but soon.
