### ISSUE TITLE
[Bug][Config UI] Onboarding process showing and mandatory after an upgrade

### ISSUE THREAD

**Issue by pimguilherme** [apache/devlake#7274]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I upgraded devlake from an existing installation to v1.0.0-beta2 and it shows the onboarding process as if I was using it for the first time, and it never goes away until I complete it

![image](https://github.com/apache/incubator-devlake/assets/1406885/cb223731-8272-4b4e-9915-240c54395649)

### What do you expect to happen

I think that it's not really a problem to show the initial onboarding screen, but it should not be sticky forever until I finish it if I have already got something configured in DevLake, or at least it should be possible to dismiss it.

### How to reproduce

- Install devlake in an earlier version
- configure plguins/projects
- upgrade devlake to v1.0.0-beta2
- log into the UI

### Version

v1.0.0-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pimguilherme** [comment]
I am not sure this is a bug though, sorry 😅

**Comment by Startrekzky** [comment]
Hi @pimguilherme , it is. We added a close icon at the top right corner at this card in the beta3.
![image](https://github.com/apache/incubator-devlake/assets/14050754/23196ef7-62d4-40b7-8788-f8c05ae68aa5)
