### ISSUE TITLE
[Bug][Devlake Api] Can't GET projects which have "/" in their name

### ISSUE THREAD

**Issue by pimguilherme** [apache/devlake#7275]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have a use case of using a project naming convention like this: my/project/name, and we are not longer able to GET /project/my/project/name, or the escaped version of it, /project/my%2Fproject%2Fname

### What do you expect to happen

We would expect to either of the formats to work.. we are coming from v0.18.0, where format "my/project/name" used to work, but now it no longers retrieves the project:

![image](https://github.com/apache/incubator-devlake/assets/1406885/1d103b8b-ed37-4aaa-8ff2-511b4166005b)

The interface indicates this should be supported, and I was also able to create a new project using the /:

![image](https://github.com/apache/incubator-devlake/assets/1406885/ed2eb1f4-a530-49f3-833b-2c83345e7675)

### How to reproduce

- online devlake locally
- create a project named "my/test/project" on the interface
- attempt to open it

### Version

v1.0.0-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pimguilherme** [comment]
I guess it is related to this change? https://github.com/apache/incubator-devlake/commit/e9c25792fea4226a5f7d9b9e611e6b0062b1c7e0#

But then how to be able to have / in the project name but also have a /check in the end of the other route? :thinking:

**Comment by klesh** [comment]
Weird, escaped project name should work.

**Comment by klesh** [comment]
Need triage

**Comment by davidpvilaca** [comment]
![image](https://github.com/apache/incubator-devlake/assets/9597125/8da45a14-8a92-43df-9bfb-7aa5325ccb8d)

I managed to get the route working again with '/' in the project name, but I think the '/check' route will continue to fail if we keep using ':projectName' instead of '*projectName'.

My draft pull request: https://github.com/apache/incubator-devlake/pull/7281

**Comment by klesh** [comment]
Will be fixed in v1.0.0-beta5
