### ISSUE TITLE
[Question][JIRA] Test connect from Config UI fails due to x509: certificate

### ISSUE THREAD

**Issue by extensure123** [apache/devlake#7287]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Tring to add Jira Cloud connection from Config UI but the test connection fails with below error
`Get "https://<mydomain>.atlassian.net/rest/api/2/serverInfo": tls: failed to verify certificate: x509: certificate signed by unknown authority Wraps: (4) x509: certificate signed by unknown authority Error types: (1) *hintdetail.withDetail (2) *url.Error (3) *tls.CertificateVerificationError (4) x509.UnknownAuthorityError`

### What do you expect to happen

Jira connection status should reflect "Connected"

### How to reproduce

1) Spin up the devlake using docker-compose on an on-prem Ubuntu 22x VM
2) Add the JIRA cloud connection from Config UI
3) Provide the required details and API key
4) Test the connection

### Anything else

The following in .env file is left blank.
IN_SECURE_SKIP_VERIFY=

I'm able to setup connection and test them successfully for my GitHub Cloud and local Jenkins connection without any issue but seems with Jira there is some SSL or cert issue.

As part of troubleshooting, I tested the **below curl command from the VM and it does work and passes**
`curl -v https://xxx.atlassian.net --user xxx@xxx:<my API key>`
However when I log in the **apache-devlake-config-ui-1** **container** or the **apache-devlake-devlake-1** **container** to test the **above curl command it fails**.

High level workaround is to somehow move the certs on my local VM to the devlake containers to make things work but I cannot manually add these certs in the container and then update certs command and not sure how to deploy these certs to the container using docker-compose

### Version

v1.0.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by extensure123** [comment]
This is not really a bug but I'm unable to change the label.
As a workaround, I've set the IN_SECURE_SKIP_VERIFY that bypasses the x509 certs issue.

However, it would be nice if **someone can guide on the changes required in docker-compose to mount a volume with local custom certs to the lake container and run the update the certs on those containers** so that it avoids enabling the IN_SECURE_SKIP_VERIFY flag.

**Comment by klesh** [comment]
Please check https://devlake.apache.org/docs/Troubleshooting/Configuration#failed-to-collect-data-from-the-server-with-a-self-signed-certificate

**Comment by Startrekzky** [comment]
Hi @extensure123 , feel free to reopen the bug if your problem hasn't been solved.
