### ISSUE TITLE
[Bug][Dashboard] DORA Details - Deployment Frequency dashboard malfunctioning 

### ISSUE THREAD

**Issue by hayk96** [apache/devlake#7290]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Somehow these panels of the dashboard [DORA Details - Deployment Frequency](https://github.com/apache/incubator-devlake/blob/main/grafana/dashboards/DORADetails-DeploymentFrequency.json) show zero value, but as visible in the second image the status of deployments works properly. The source is the GitLab.  

_p.s. The screenshots were done for one of our projects called `Search`_.

#### Screenshot 1
![image](https://github.com/apache/incubator-devlake/assets/46712946/6f0048c9-73f3-48c8-9c72-c784f305313e)

#### Screenshot 2
![image](https://github.com/apache/incubator-devlake/assets/46712946/76331567-f7ce-4360-9e7f-6194de672b31)

### What do you expect to happen

These panels shouldn't be empty and need to visualize the appropriate data
![image](https://github.com/apache/incubator-devlake/assets/46712946/2c348d86-3779-4d7c-8e29-bb3797124d3e)

### How to reproduce

Use GitLab as a source of **Source Code Management** then select any project in the following dashboard [DORA Details - Deployment Frequency](https://github.com/apache/incubator-devlake/blob/main/grafana/dashboards/DORADetails-DeploymentFrequency.json).

### Version

v1.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thans for reporting. I'll look at it now.
