### ISSUE TITLE
[Doc][Module Name] Fix broken link in main README

### ISSUE THREAD

**Issue by tonyjw** [apache/devlake#7304]
## Documentation Scope
Main README fixing broken link

## Describe the Change
The "Develop a Plugin" link is broken and results in a 404. It incorrectly references `https://github.com/apache/incubator-devlake/blob/main/backend/DevelopmentSetup`

I believe it should reference `https://github.com/apache/incubator-devlake/blob/main/backend/DevelopmentManual.md` instead

## Screenshots
![Screenshot 2024-04-09 at 10 24 47 AM](https://github.com/apache/incubator-devlake/assets/98004/716b14f7-41d0-4fbb-8b26-65d4a281b2b5)

**Comment by abeizn** [comment]
@tonyjw Already effective in v1.0.0-beta6
