### ISSUE TITLE
UI is slow and unstable for Podman installed Devlake

### ISSUE THREAD

**Issue by vidhyasasi** [apache/devlake#7312]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Devlake UI is slow and unstable when installed via Podman.

Throws 502 error regularly, and reloading the page after some time seems to be working in this case,

<img width="1199" alt="Screenshot 2024-04-11 at 12 03 03" src="https://github.com/apache/incubator-devlake/assets/64778227/3ed77eff-8c94-45d7-aae6-e5d587218540">

Also when trying to add Datscope for Gitlab connection, it either do not shows all the gitlab repos, mostly says no data found, even though there are gitlab repos. Sometime throws error like:

<img width="830" alt="Screenshot 2024-04-11 at 12 07 49" src="https://github.com/apache/incubator-devlake/assets/64778227/2bb07e91-3345-4a9e-afb7-a3dc9bd6f855">

I already tested this with docker, everything is working with it. The problem seems to be existing only for podman installed Devlake.

Could you have a look into that? 

### What do you expect to happen

The UI is expected to be stable and all the gitlab repos to load properly. 

### How to reproduce

Install Devlake through podman compose.

### Version

v1.0.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@vidhyasasi Seems like it is a `podman` specific problem, I use `podman` in the other machine too, and never ran into the same problem.
I would recommend that you report the issue to the `podman` team, they are quite active IIRC.

**Comment by vidhyasasi** [comment]
Hi, 
Thanks for the reply.
But I can list all the gitlab repo in a group with curl command.
The problem is in the UI to add scope, it shows "no data to select" .
Do you think it is a podman problem ?

**Comment by klesh** [comment]
Can you open the Developer toolbar and inspect if the API requests sent by `config-ui` is working correctly under the Network tab?

**Comment by vidhyasasi** [comment]
Sorry I need more information regarding your comment.
Did you mean to install Developer Setup and check it ?
If not could you provide the steps regarding what to do ?
Thanks!

**Comment by klesh** [comment]
oh, sorry, I missed the "Browser" part. Sth look like the following
![image](https://github.com/apache/incubator-devlake/assets/61080/33e6e749-9073-401b-a261-365f30ed75f5)

**Comment by vidhyasasi** [comment]
Thanks for the response.
I checked the API senting the request properly and I can see all the repos listed, but not in the UI still. 

<img width="962" alt="Screenshot 2024-04-17 at 09 31 01" src="https://github.com/apache/incubator-devlake/assets/64778227/bf50ded6-8bb2-49ff-a2bd-ac0263fa7668">

But what I noticed is that, if I click on the response while it is loading, it shows no data even after it finish loading,

<img width="1912" alt="Screenshot 2024-04-17 at 09 38 51 (2)" src="https://github.com/apache/incubator-devlake/assets/64778227/a7715c72-15d5-4e26-9701-3d8422bddf5b">

<img width="967" alt="Screenshot 2024-04-17 at 09 39 02" src="https://github.com/apache/incubator-devlake/assets/64778227/f5997f0d-671a-4271-9d53-3165ce6f2607">


and a lot of subtask error showing 

" {
    "success": false,
    "message": "bad pipelineID format supplied (400)\nWraps: (2) strconv.ParseUint: parsing \"subtasks\"\nWraps: (3) invalid syntax\nError types: (1) *hintdetail.withDetail (2) *strconv.NumError (3) *errors.errorString",
    "causes": null,
    "data": null
}"

**Comment by klesh** [comment]
In that case, please make sure the image tags of the `devlake` and the `config-ui` are match

**Comment by guilhem** [comment]
I have the same error in logs `v1.0.0-beta5` using a lot of Azure DevOps go.
