### ISSUE TITLE
[Feature][DORA] API access to DORA metrics

### ISSUE THREAD

**Issue by paco-sparta** [apache/devlake#7318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

We would like to integrate DevLake into backstage.io or our internal metrics website.

### Description

We would like to have DORA metrics included in either a project view `projects/{projectName}` or as its own top-level route in `plugins/dora/{projectName}`

### Related issues

No

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Maybe you can connect to the database and run SQL query to fetch the metric you need?
