### ISSUE TITLE
[Question][jira] How to show metrics such as 'ratio of unplanned issues', 'completion rate of sprint issues', etc

### ISSUE THREAD

**Issue by rborgwald** [apache/devlake#7320]
## Question
I just started using devlake and have found the documentation super helpful! I did come across something in the docs for v0.21 that I'm questioning though. I've been trying to find a way to show planning accuracy which would require me to know if stories were added/removed from sprints. Looking through the database at tables like sprints, sprint_issues, and issues I wasn't finding quite what I needed so I went back to the documentation. In the Domain Layer Schema section under sprint_issues it reads:

> This table shows the relation between sprints and issues that have been added to sprints. This table can be used to show metrics such as 'ratio of unplanned issues', 'completion rate of sprint issues', etc

which sounds exactly what I'm looking for but based on the columns in the sprint_issues table (sprint_id and issue_id) - I'm not seeing how it's possible to come up with those metrics.
(referencing these docs: [sprint_issues](https://devlake.apache.org/docs/v0.21/DataModels/DevLakeDomainLayerSchema#sprint_issues)).

I did find that if I go back to the [docs for v0.15](https://devlake.apache.org/docs/v0.15/DataModels/DevLakeDomainLayerSchema#sprint_issues), I see a lot more columns in the table and I can see how you'd be able to surface the metrics with those columns.

So I'm wondering: are we not able to surface these metrics in newer versions, or did the data get moved to a different table?

**Comment by klesh** [comment]
Hi, @rborgwald we once have this sprint performance calculation. However, it was not very stable and no one really used it so it was removed from the codebase.

**Comment by klesh** [comment]
Thanks to @narrowizard s contribution: https://github.com/apache/incubator-devlake/pull/7544

We now have the issue changelog enrichers back in play, you may want to take a look at the plugin.
