### ISSUE TITLE
[Bug][Upgrade] Error: UPGRADE FAILED: cannot patch "devlake-ui" with kind Deployment

### ISSUE THREAD

**Issue by amila77kashyapa** [apache/devlake#7326]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm trying to upgrade DevLake from v0.19.0-beta4 to v1.0.0-beta4 using Helm and am getting the error below. Same Issue came up with  v1.0.0-beta3 also. Thank you.

"Error: UPGRADE FAILED: cannot patch "devlake-ui" with kind Deployment: Deployment.apps "devlake-ui" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"devlake", "app.kubernetes.io/name":"devlake", "devlakeComponent":"ui"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "devlake-lake" with kind Deployment: Deployment.apps "devlake-lake" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"devlake", "app.kubernetes.io/name":"devlake", "devlakeComponent":"lake"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "devlake-mysql" with kind StatefulSet: StatefulSet.apps "devlake-mysql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden"

### What do you expect to happen

Upgrade to newer version v1.0.0-beta4

### How to reproduce

export ENCRYPTION_SECRET="your_current _secret"

helm upgrade devlake devlake/devlake --version=1.0.0-beta4 --set API_REQUESTS_PER_HOUR="10000" --set API_RETRY="3" --set PIPELINE_MAX_PARALLEL="1" --set IN_SECURE_SKIP_VERIFY="true" --set lake.encryptionSecret.secret=$ENCRYPTION_SECRET

### Version

v0.19.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by amila77kashyapa** [comment]
Hello,

Is there any update on this?

Thanks.

**Comment by klesh** [comment]
@ZhangNing10 is working on sth else, maybe later.

**Comment by ZhangNing10** [comment]
hi @amila77kashyapa , you can firstly delete the ui deployment and then upgrade

**Comment by amila77kashyapa** [comment]
Hi @ZhangNing10 When I delete UI deployment then it giving below error. 

"Error: UPGRADE FAILED: cannot patch "devlake-lake" with kind Deployment: Deployment.apps "devlake-lake" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"devlake", "app.kubernetes.io/name":"devlake", "devlakeComponent":"lake"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "devlake-mysql" with kind StatefulSet: StatefulSet.apps "devlake-mysql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden"

with deleting both UI and devlake-lake deployment it give below error. But also it creates new deployments "UI and devlake-lake"  with the new version "1.0.0-beta4" and after running DB migration via UI, devlake is working with new version.
 
"Error: UPGRADE FAILED: cannot patch "devlake-mysql" with kind StatefulSet: StatefulSet.apps "devlake-mysql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden"
