### ISSUE TITLE
[Bug][Config UI] Unable to add data connections in projects 

### ISSUE THREAD

**Issue by ghost** [apache/devlake#7327]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![GIF Recording 2024-04-15 at 15 39 53](https://github.com/apache/incubator-devlake/assets/31725457/4426afc4-ba3b-4a6c-90e2-fec1aa496640)

On clicking on "Add data data connection" it shows the existing connections only

### What do you expect to happen

It should redirect the user to the connections

### How to reproduce

Follow same steps as shown above.

`Open a Project > Configuration > Add a connection`

### Version

v1.0.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaomingzhang12** [comment]
This is a matter of understanding. The product itself is fine and has been communicated in Feishu. So I will close this issue first. @JoshuaPoddoku

**Comment by Startrekzky** [comment]
Please add the entry in either way:

1. Add a text link to the dropdown list
![image](https://github.com/apache/incubator-devlake/assets/14050754/77b51101-3fbe-4858-927a-a76d9e2409c4)


2. Add a text link in the description if the component doesn't support adding the text link to the dropdown list
![image](https://github.com/apache/incubator-devlake/assets/14050754/5860a9db-39f9-437f-93cf-5e48a33593ac)

**Comment by abeizn** [comment]
@JoshuaPoddoku Already effective in v1.0.0-beta6
