### ISSUE TITLE
[Bug][Grafana] Grafana infinitely loop /login after upgrade to version 1.0.0-beta4

### ISSUE THREAD

**Issue by ghost** [apache/devlake#7328]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After upgrade from `1.0.0-beta3` to `1.0.0-beta4` I am not able to access /grafana Dashboards anymore.
It keep looping the /login page with 302 http status.
I deleted the cookies but no help

### What do you expect to happen

Able to access /grafana

### How to reproduce

Upgrade to `1.0.0-beta4`

Go to /grafana

### Version

1.0.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Which deployment method: helm, docker-compose, or local？

**Comment by itungnt** [comment]
> Which deployment method: helm, docker-compose, or local？

hi @abeizn it was deployed with helm chart https://github.com/apache/incubator-devlake-helm-chart

**Comment by pevks** [comment]
```devlake-grafana-79775f95f8-6cxcn grafana logger=context userId=0 orgId=0 uname= t=2024-04-16T08:57:51.070330645Z level=info msg="Request Completed" method=GET path=/grafana/user/auth-tokens/rotate status=302 remote_addr=65.2.19.112 time_ms=0 duration=831.86µs size=55 referer= handler=notfound status_source=server```

The logs from grafana has the line above being printed multiple times.
