### ISSUE TITLE
git extractor getting failed after the update to v1.0.0-beta3@0b891d5, because of this commits data is not getting extracted from bitbucket

### ISSUE THREAD

**Issue by naveenreddymanukonda** [apache/devlake#7333]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Connected bitbucket through cloud connection, git extractor is failing with bad gateway error

Error message
`subtask Clone Git Repo ended unexpectedly Wraps: (2) Get "https://phenom_revant_menta:***@bitbucket.org/phenompeople/dojo.git/info/refs?service=git-upload-pack": Bad Request Wraps: (3) Get "https://phenom_revant_menta:***@bitbucket.org/phenompeople/dojo.git/info/refs?service=git-upload-pack" Wraps: (4) Bad Request Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *url.Error (4) *errors.errorString`

![image](https://github.com/apache/incubator-devlake/assets/40488776/74b29dd7-5d22-4cbe-87c4-1a8005f2808c)

### What do you expect to happen

Run the git extractor successfully and extract commits data

### How to reproduce

Create a bitbucket cloud account and run the pipeline

### Version

v1.0.0-beta3@0b891d5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Geni2** [comment]
Hi @naveenreddymanukonda, I have the same issue but for Bitbucket server and it was the problem with the self-signed certificate. I don't know if that could also be in your case!
