### ISSUE TITLE
[Bug][Azure DevOps] subtask collectAzuredevopsBuilds ended unexpectedly 

### ISSUE THREAD

**Issue by ichuniaiev** [apache/devlake#7342]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
time="2024-04-17 09:58:17" level=error msg=" [pipeline service] [pipeline #1] [task #2] [collectAzuredevopsBuilds] ERROR: DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)"
time="2024-04-17 09:58:17" level=error msg=" [pipeline service] [pipeline #1] [task #2] [collectAzuredevopsBuilds] (MySQLdb.DataError) (1406, \"Data too long for column 'url' at row 1\")"
time="2024-04-17 09:58:17" level=error msg=" [pipeline service] [pipeline #1] [task #2] [collectAzuredevopsBuilds] [SQL: INSERT INTO _raw_azuredevops_builds (params, data, url, input, created_at) VALUES (%!!(MISSING)s(MISSING), %!!(MISSING)s(MISSING), %!!(MISSING)s(MISSING), %!!(MISSING)s(MISSING), %!!(MISSING)s(MISSING))]"
```

### What do you expect to happen

The pipeline runs without an error.

### How to reproduce

I checked it on my private Azure DevOps project.
But flow was standard: Create project; configure data connection; run collect data
I've used python plugin

### Anything else

every run

### Version

v1.0.0-beta1, v1.0.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Was it the python or golang version?

**Comment by ichuniaiev** [comment]
> Was it the python or the golang version?
It's a python version

**Comment by ichuniaiev** [comment]
yeah, with go version it works perfectly, but fails on shallow clone :)
That's why I've raised another issue for it - https://github.com/apache/incubator-devlake/issues/7343

**Comment by Startrekzky** [comment]
For users who have encountered this issue, please use the Go version Azure plugin as a workaround. This issue will be fixed later.

**Comment by klesh** [comment]
@ichuniaiev The shallow clone issue has been fixed
