### ISSUE TITLE
[Bug][Azure DevOps Go] fatal: Server does not support --shallow-since

### ISSUE THREAD

**Issue by ichuniaiev** [apache/devlake#7343]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

gitextractor log:
```
time="2024-04-17 11:11:20" level=error msg=" [pipeline service] [pipeline #1] [task #3] [Clone Git Repo] [gitcli] git exited with error\nstderr: Cloning into bare repository '/tmp/gitextractor2679208'...\nstderr: fatal: Server does not support --shallow-since\nstderr: fatal: the remote end hung up unexpectedly\n\n\tcaused by: exit status 128"
time="2024-04-17 11:11:20" level=error msg=" [pipeline service] [pipeline #1] [task #3] subtask Clone Git Repo ended unexpectedly\n\tWraps: (2) git exit error\n\tError types: (1) *hintdetail.withDetail (2) *errors.errorString"
```

### What do you expect to happen

Repo is cloned and pipeline runs without errors

### How to reproduce

Use Azure DevOps Go plugin and run pipeline

### Anything else

It happens every execution

### Version

v1.0.0-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Will fix it soon.

**Comment by abeizn** [comment]
@ichuniaiev Already effective in v1.0.0-beta6

**Comment by ichuniaiev** [comment]
I still get the same error on v1.0.0-beta6

> time="2024-05-06 09:34:53" level=info msg=" [pipeline service] [pipeline #1] [task #3] start executing task: 3"
time="2024-05-06 09:34:53" level=info msg=" [pipeline service] [pipeline #1] [task #3] start plugin"
time="2024-05-06 09:34:53" level=info msg=" [pipeline service] [pipeline #1] [task #3] [gitextractor.PrepareTaskData] UseGoGit: false"
time="2024-05-06 09:34:53" level=info msg=" [pipeline service] [pipeline #1] [task #3] [gitextractor.PrepareTaskData] SkipCommitStat: false"
time="2024-05-06 09:34:53" level=info msg=" [pipeline service] [pipeline #1] [task #3] [gitextractor.PrepareTaskData] SkipCommitFiles: true"
time="2024-05-06 09:34:53" level=info msg=" [pipeline service] [pipeline #1] [task #3] total step: 4"
time="2024-05-06 09:34:53" level=info msg=" [pipeline service] [pipeline #1] [task #3] executing subtask Clone Git Repo"
time="2024-05-06 09:34:54" level=error msg=" [pipeline service] [pipeline #1] [task #3] [Clone Git Repo] [gitcli] git exited with error\nstderr: Cloning into bare repository '/tmp/gitextractor2289418913'...\nstderr: fatal: Server does not support --shallow-since\nstderr: fatal: the remote end hung up unexpectedly\n\n\tcaused by: exit status 128"
time="2024-05-06 09:34:54" level=info msg=" [pipeline service] [pipeline #1] [task #3] finished step: 1 / 4"
time="2024-05-06 09:34:54" level=info msg=" [pipeline service] [pipeline #1] [task #3] executing subtask Collect Commits"
time="2024-05-06 09:34:54" level=error msg=" [pipeline service] [pipeline #1] [task #3] run task failed with panic\n\tcaused by: run task failed with panic (github.com/apache/incubator-devlake/plugins/gitextractor/tasks.getGitRepo:87)\n\tWraps: (2) git repo is empty, please check subtask: clone repo\n\tError types: (1) *hintdetail.withDetail (2) *errors.errorString"

**Comment by klesh** [comment]
Aah.. I see. The fix was overwritten by this https://github.com/apache/incubator-devlake/pull/7364/files#diff-3847a66dd0632d39d27b84431808b867768544cc141ead4545f1d967fb31eea9L143 😂
Will create another PR
