### ISSUE TITLE
Docker Compose Error

### ISSUE THREAD

**Issue by bmnoorulameen** [apache/devlake#7349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am trying the setup the local environment by using Docker Compose metod. when running "docker-compose up -d" I am getting below error "Error response from daemon: manifest for devlake.docker.scarf.sh/apache/devlake:v0.21.0 not found: manifest unknown: manifest unknown"

![image](https://github.com/apache/incubator-devlake/assets/57080605/03716609-5f3c-4a25-b3c3-9264194bebae)

### What do you expect to happen

Successful docker compose run.

### How to reproduce

Run "docker-compose up -d"

### Version

v0.21.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@bmnoorulameen v0.21.0 has not been officially released yet. It is currently in the voting stage and there is no corresponding image.

**Comment by klesh** [comment]
Close it now, feel free to re-open.
