### ISSUE TITLE
[Bug][MySQL] Cannot collect data from Jira Project 

### ISSUE THREAD

**Issue by tmylonidis** [apache/devlake#7358]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After setting up a project, the task that is responsible for collecting data from Jira is failing with the following error:
Error 1054 (42S22): Unknown column 'all_fields' in 'field list' (500) Wraps: (4) Error 1054 (42S22): Unknown column 'all_fields' in 'field list' Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError

### What do you expect to happen

Data to be fetched from Jira without errors.

### How to reproduce

Set up a project with a Jira data scope

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Please upgrade to v0.21

**Comment by klesh** [comment]
Close it now, feel free to re-open.
