### ISSUE TITLE
[Plugin][GCP Plugin] Add a cloud plugin

### ISSUE THREAD

**Issue by estefaniasuasti** [apache/devlake#7360]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

We are currently working in a GCP project, therefore the policies and alerts are in cloud. As a result, the incidents that occurs are storage in cloud. Having this plugin would help us to collect the information of those incidents to be able to implement Dora Metrics.

### Description

Request to adding a feature, GCP Plugin. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gustavobini** [comment]
I also work with Google Cloud, so I am interested in this too.

Based on my knowledge, a customized webhook that understands alerting events from Google Cloud is enough. This is the official documentation for [webhooks as notification channels](https://cloud.google.com/monitoring/support/notification-options#webhooks).

**Comment by estefaniasuasti** [comment]
Hi @gustavobini, are you currently using that approach? or is it a suggestion?

**Comment by gustavobini** [comment]
> Hi @gustavobini, are you currently using that approach? or is it a suggestion?

It's a suggestion for the plugin.

However, if you wanna solve this problem today, you could create a Cloud Function as a notification channel for GCP alerts, and call Devlake's webhook from it.

**Comment by Startrekzky** [comment]
Hi @gustavobini , would you like to do a more detailed design about the customized webhook? If you do, please create a new issue with the details. Thank you.
