### ISSUE TITLE
[Bug][azuredevops_go] Incorrect datetime value: '0000-00-00' for column 'finish_time'

### ISSUE THREAD

**Issue by guilhem** [apache/devlake#7369]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When collectiong data:
```
subtask extractApiBuilds ended unexpectedly Wraps: (2) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'finish_time' at row 180 (500) Wraps: (3) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'finish_time' at row 180 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError
```

### What do you expect to happen

no error

### How to reproduce

collecting data on azure DevOps with go plugin

### Version

v1.0.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, @mr-ks would you like to take a look at the issue? Thanks.

**Comment by abeizn** [comment]
@guilhem @mr-ks Already effective in v1.0.0-beta6
