### ISSUE TITLE
[Bug][azuredevops_go] No data found for the selected time range 

### ISSUE THREAD

**Issue by guilhem** [apache/devlake#7370]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When collecting data, whatever range I'm putting:
```
subtask Clone Git Repo ended unexpectedly Wraps: (2) No data found for the selected time range. Please revise the 'Time Range' on your Project/Blueprint/Configuration page or in the API parameter. (400) Error types: (1) *hintdetail.withDetail (2) *errors.errorString
```

### What do you expect to happen

no error

### How to reproduce

Collecting data from azdo

### Anything else

Must be linked to:
`fatal: Server does not support --shallow-since`

```
time="2024-04-24 13:34:16" level=error msg=" [pipeline service] [pipeline #21] [task #2268] [Clone Git Repo] [gitcli] git exited with error\nstderr: Cloning into bare repository '/tmp/gitextractor3989293820'...\nstderr: fatal: Server does not support --shallow-since\nstderr: fatal: the remote end hung up unexpectedly\n\n\tcaused by: exit status 128"
time="2024-04-24 13:34:16" level=error msg=" [pipeline service] [pipeline #21] [task #2268] subtask Clone Git Repo ended unexpectedly\n\tWraps: (2) No data found for the selected time range. Please revise the 'Time Range' on your Project/Blueprint/Configuration page or in the API parameter. (400)\n\tError types: (1) *hintdetail.withDetail (2) *errors.errorString"
```

### Version

v1.0.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by thiDucTran** [comment]
I am seeing this exact issue.

**Comment by srikanthgoud07** [comment]
I am also facing this same issue
and I am using devlake v1.0.0-beta5 version

**Comment by abeizn** [comment]
@guilhem @thiDucTran @srikanthgoud07 Already effective in v1.0.0-beta6

**Comment by thiDucTran** [comment]
can we reopen the issue? I am still seeing error as below
```bash
time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] start executing task: 288"
time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] start plugin"
time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] [gitextractor.PrepareTaskData] UseGoGit: false"
time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] [gitextractor.PrepareTaskData] SkipCommitStat: false"
time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] [gitextractor.PrepareTaskData] SkipCommitFiles: true"
time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] total step: 4"
time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] executing subtask Clone Git Repo"
time="2024-04-29 01:56:09" level=error msg=" [pipeline service] [pipeline #60] [task #288] [Clone Git Repo] [gitcli] git exited with error\nstderr: Cloning into bare repository '/tmp/gitextractor3459727601'...\nstderr: fatal: Server does not support --shallow-since\nstderr: fatal: the remote end hung up unexpectedly\n\n\tcaused by: exit status 128"
time="2024-04-29 01:56:09" level=info msg=" [pipeline service] [pipeline #60] [task #288] finished step: 1 / 4"
time="2024-04-29 01:56:09" level=info msg=" [pipeline service] [pipeline #60] [task #288] executing subtask Collect Commits"
time="2024-04-29 01:56:09" level=error msg=" [pipeline service] [pipeline #60] [task #288] run task failed with panic\n\tcaused by: run task failed with panic (github.com/apache/incubator-devlake/plugins/gitextractor/tasks.getGitRepo:87)\n\tWraps: (2) git repo is empty, please check subtask: clone repo\n\tError types: (1) *hintdetail.withDetail (2) *errors.errorString"

```

**Comment by d4x1** [comment]
> can we reopen the issue? I am still seeing error as below with `v1.0.0-beta6`
> 
> ```shell
> time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] start executing task: 288"
> time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] start plugin"
> time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] [gitextractor.PrepareTaskData] UseGoGit: false"
> time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] [gitextractor.PrepareTaskData] SkipCommitStat: false"
> time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] [gitextractor.PrepareTaskData] SkipCommitFiles: true"
> time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] total step: 4"
> time="2024-04-29 01:56:08" level=info msg=" [pipeline service] [pipeline #60] [task #288] executing subtask Clone Git Repo"
> time="2024-04-29 01:56:09" level=error msg=" [pipeline service] [pipeline #60] [task #288] [Clone Git Repo] [gitcli] git exited with error\nstderr: Cloning into bare repository '/tmp/gitextractor3459727601'...\nstderr: fatal: Server does not support --shallow-since\nstderr: fatal: the remote end hung up unexpectedly\n\n\tcaused by: exit status 128"
> time="2024-04-29 01:56:09" level=info msg=" [pipeline service] [pipeline #60] [task #288] finished step: 1 / 4"
> time="2024-04-29 01:56:09" level=info msg=" [pipeline service] [pipeline #60] [task #288] executing subtask Collect Commits"
> time="2024-04-29 01:56:09" level=error msg=" [pipeline service] [pipeline #60] [task #288] run task failed with panic\n\tcaused by: run task failed with panic (github.com/apache/incubator-devlake/plugins/gitextractor/tasks.getGitRepo:87)\n\tWraps: (2) git repo is empty, please check subtask: clone repo\n\tError types: (1) *hintdetail.withDetail (2) *errors.errorString"
> ```

which type of connection are you using?

**Comment by klesh** [comment]
What were the options for the `gitextractor` task?
![image](https://github.com/apache/incubator-devlake/assets/61080/79c5f85c-d4bd-4f6b-9399-f6c91a4f659a)

**Comment by thiDucTran** [comment]
here's the full json
```json
{
  "id": 63,
  "name": "dfgfdgdfgdf-Blueprint",
  "plan": [
    [
      {
        "plugin": "org",
        "subtasks": [
          "setProjectMapping"
        ],
        "options": {
          "projectMappings": [
            {
              "projectName": "dfgfdgdfgdf",
              "scopes": [
                {
                  "rowId": "azuredevops_go:AzuredevopsRepo:1:1d7bfc84-68c4-4ccf-84c8-b0ffbc8f23f4",
                  "table": "repos"
                }
              ]
            }
          ]
        }
      }
    ],
    [
      {
        "plugin": "azuredevops_go",
        "subtasks": [
          "collectAccounts",
          "collectApiPullRequests",
          "convertRepo",
          "extractAccounts",
          "convertAccounts",
          "extractApiPullRequests",
          "collectApiPullRequestCommits",
          "convertApiPullRequests",
          "convertPrLabels",
          "extractApiPullRequestCommits",
          "convertApiPullRequestsCommits",
          "convertApiTimelineRecords"
        ],
        "options": {
          "connectionId": 1,
          "externalId": "",
          "name": "WebBackend",
          "organizationId": "<redacted>",
          "projectId": "<redacted>",
          "repositoryId": "1d7bfc84-68c4-4ccf-84c8-b0ffbc8f23f4",
          "repositoryType": "TfsGit"
        }
      },
      {
        "plugin": "gitextractor",
        "subtasks": null,
        "options": {
          "name": "WebBackend",
          "proxy": "",
          "repoId": "azuredevops_go:AzuredevopsRepo:1:1d7bfc84-68c4-4ccf-84c8-b0ffbc8f23f4",
          "url": "https://git:****************************************************@dev.azure.com/<redacted>/<redacted>/_git/WebBackend"
        }
      }
    ],
    [
      {
        "plugin": "refdiff",
        "subtasks": null,
        "options": {
          "tagsLimit": 10,
          "tagsPattern": "/v\\d+\\.\\d+(\\.\\d+(-rc)*\\d*)*$/"
        }
      }
    ],
    [
      {
        "plugin": "dora",
        "subtasks": [
          "generateDeployments",
          "generateDeploymentCommits",
          "enrichPrevSuccessDeploymentCommits"
        ],
        "options": {
          "projectName": "dfgfdgdfgdf"
        }
      }
    ],
    [
      {
        "plugin": "refdiff",
        "subtasks": [
          "calculateDeploymentCommitsDiff"
        ],
        "options": {
          "projectName": "dfgfdgdfgdf"
        }
      }
    ],
    [
      {
        "plugin": "dora",
        "subtasks": [
          "calculateChangeLeadTime",
          "ConnectIncidentToDeployment"
        ],
        "options": {
          "projectName": "dfgfdgdfgdf"
        }
      }
    ]
  ],
  "skipOnFail": true
}
```

**Comment by klesh** [comment]
Was it a `Normal` mode blueprint?

With [this fix](https://github.com/apache/incubator-devlake/pull/7356/files#diff-3847a66dd0632d39d27b84431808b867768544cc141ead4545f1d967fb31eea9R143)

The `azuredevops_go` plugin should generate options with `noShallowClone=true` for the `gitextractor` plugin.  Please make sure:

1. The `devlake` version is correct by looking at the bottom left corner on the `config-ui`
2. Make sure that you hit the `Collect data` button to re-generate the `plan` instead of the `Rerun` button
![image](https://github.com/apache/incubator-devlake/assets/61080/b08d2881-8364-4f80-b3b0-2824f47c605e)

**Comment by thiDucTran** [comment]
1. my devlake version is showing `v1.0.0-beta6@ea2cdbc`
2. I do `Collect Data` and `Collect Data in full refresh mode` and is not seeing `noShallowClone=true` option in json

fyi..i deleted project and even the connection for good measure....idk..may be delete the deployment and even my persistent storage?

![image](https://github.com/apache/incubator-devlake/assets/37130368/debe25b5-fb8c-478f-b127-b3d186df931a)

**Comment by guilhem** [comment]
I also still have same problem on beta6:
![image](https://github.com/apache/incubator-devlake/assets/486876/15c069bb-c1a7-42e0-9cfd-ee5855245b0e)
```
time="2024-04-29 12:54:27" level=error msg=" [pipeline service] [pipeline #32] [task #3521] [Clone Git Repo] [gitcli] git exited with error\nstderr: Cloning into bare repository '/tmp/gitextractor1060078586'...\nstderr: fatal: Server does not support --shallow-since\nstderr: fatal: the remote end hung up unexpectedly\n\n\tcaused by: exit status 128"
```

**Comment by abeizn** [comment]
@guilhem @thiDucTran It takes effect in version v1.0.0-beta7.

**Comment by guilhem** [comment]
Yes ! <3
I tested it right now and working really well
