### ISSUE TITLE
[Question][CI/CD] How can we stop auto collection of CI/CD metrics?

### ISSUE THREAD

**Issue by thiDucTran** [apache/devlake#7375]
## Question
Hi, what is the correct config to use if we do not want to automatically collect deployment/builds/etc data? Referencing https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#data-models, I have tried not choosing CI/CD for my data scope config...but deployment data is still being collected. Using `v1beta5` with `azure devops GO connection`

FYI: i asked this also in slack. see https://devlake-io.slack.com/archives/C03APJ20VM4/p1714025708040129

## Screenshots
![image](https://github.com/apache/incubator-devlake/assets/37130368/21c910bf-2032-4a81-a1bc-8d1fb26156d8)
![image](https://github.com/apache/incubator-devlake/assets/37130368/48e4ceec-b8d4-4efb-a2a6-2de0d148a83c)

**Comment by klesh** [comment]
@thiDucTran Hi, by design, the previously collected data of selected entities won't be deleted but simply skipping those related subtasks,  please check if the `collectApiBuilds` subtask is showing in the pipeline plan JSON for the plugin
![image](https://github.com/apache/incubator-devlake/assets/61080/7f60ffed-23bb-40f6-bd70-cb28cca4a661)

**Comment by thiDucTran** [comment]
i dont see `collectApiBuilds`

```json
    [
      {
        "plugin": "azuredevops_go",
        "subtasks": [
          "collectAccounts",
          "collectApiPullRequests",
          "convertRepo",
          "extractAccounts",
          "convertAccounts",
          "extractApiPullRequests",
          "collectApiPullRequestCommits",
          "convertApiBuilds",
          "convertApiPullRequests",
          "convertPrLabels",
          "extractApiPullRequestCommits",
          "convertApiPullRequestsCommits",
          "convertApiTimelineRecords"
        ],
```

**Comment by klesh** [comment]
Weird, why there is a `convertApiBuilds` in the `subtasks` list.
It looks like a bug indeed, would you like to file it in a separate issue and we will look into it?

**Comment by abeizn** [comment]
@thiDucTran Already effective in v1.0.0-beta6

**Comment by thiDucTran** [comment]
issue is not resolved for me in ` v1.0.0-beta6` ? CI/CD metrics still gets collected... I even deleted the project...purge scope's data...make sure CI/CD is not in my scope config...colleted data..and I still see ci/cd metrics in Azure DevOps dashboard

**Comment by abeizn** [comment]
@thiDucTran What is the value of your environment variable ENABLE_SUBTASKS_BY_DEFAULT?

**Comment by klesh** [comment]
@thiDucTran That is weird, I don't see any related subtasks in the list. Can you check the raw tables and see if the data gets purged?

**Comment by thiDucTran** [comment]
i edited my previous comment....seems data is not purged

**Comment by klesh** [comment]
To be investigated.

**Comment by thiDucTran** [comment]
Hi, would I need to create another issue for the table `cicd_deployment_commits` ? I have delete the project and data scope..but data of of deleted project is still there in `cicd_deployment_commits`
