### ISSUE TITLE
[Feature][Jenkins Dashboard] Filter the Jenkins builds by the build result

### ISSUE THREAD

**Issue by Geni2** [apache/devlake#7379]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

We wanted to measure the build duration of our PR pipelines from Jenkins but that was not possible because of the failures which can change the duration time a lot.

### Description

What could suggest here is adding a filter close to the job name where you can filter by `build result` with the values(Success, Failure, Abort). This will give an accurate number of the build duration when you select successful pipeline only.

![Jenkins Dashboard-fotor-20240425141223](https://github.com/apache/incubator-devlake/assets/51850738/a965ec26-2041-49c5-b7e1-82ceced6cdf7)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
I'll consider it. By the way, do you have any updates about #7097 ?

**Comment by Geni2** [comment]
Thank you @Startrekzky for considering this.

**Comment by Geni2** [comment]
Hey @Startrekzky , is there any news regarding this?
