### ISSUE TITLE
[Bug][Github Plugin] API call to remote-scopes returns a list of 1 and no github data 

### ISSUE THREAD

**Issue by andyflatt** [apache/devlake#7381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When calling `plugins/github/connections/[github_conn]/remote-scopes?groupId=[github_org]` with a connection enabled with a GithubApp the response returns a page size of 1 and the returning result is missing data.

```
{
    "children": [
        {
            "type": "scope",
            "parentId": "org",
            "id":  [some_id],
            "name": "repo",
            "fullName": "org/repo",
            "data": null
        }
    ],
    "nextPageToken": "eyJwYWdlIjoyLCJwZXJfcGFnZSI6MTAwfQ=="
}
```

When calling the same API with the github connection setup with a token I a full response with the data populated correctly.

### What do you expect to happen

I expected to see the same result as with a token.

### How to reproduce

I have recently upgraded from v0.20 to v1.0.0 beta 5.

Setup two github connections one using an API key and the other using a token.  They are both enabled to use the graphql API.

### Version

v1.0.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Sounds like some essential permissions are missing.
Did you following [this guide](https://devlake.apache.org/docs/Configuration/GitHub#github-apps) and set up the required permissions?
