### ISSUE TITLE
[Bug][Bitbucket_server] search-remote-scopes endpoint always returns the same result

### ISSUE THREAD

**Issue by TihomirPop** [apache/devlake#7393]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have many repositories on Bitbucket, but we can't use the GET `api/plugins/bitbucket_server/connections/1/search-remote-scopes` endpoint to get the ones that we want. For any search term it always returns the same single repository and nothing else.

### What do you expect to happen

We expect to be able to search for remote scopes by using repository name, project key or Bitbucket id.

### How to reproduce

In our case it happens every time for any search term on the `api/plugins/bitbucket_server/connections/1/search-remote-scopes` endpoint.

### Version

v1.0.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@TihomirPop It takes effect in version v1.0.0-beta7.
