### ISSUE TITLE
[Bug][Grafana] Some KPIs show 0 or 100 if data is incomplete

### ISSUE THREAD

**Issue by gabrielenosso** [apache/devlake#7398]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

PR Cycle Time looks 0 if PR Deploy Time is not tracked (in both Dashboards "Engineering-throughput" and "DORA - Lead Time for Changes")

On-time Delivery shows 100% if not tracked (IMHO should show "no data") - Dashboard: Engineering overview

### What do you expect to happen

If I have partial data, it should still calculate the PR Cycle Time using the data available.

If I have no data, the On-time Delivery chart should show "no data".

### How to reproduce

use partial data from GitHub

### Version

1.0.5 beta

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gabrielenosso** [comment]
adding pictures:
![image](https://github.com/apache/incubator-devlake/assets/4018887/de837b49-4f0a-47f8-8d41-ac1b01e9e297)
![image](https://github.com/apache/incubator-devlake/assets/4018887/a15764d1-25c8-4f03-8013-fcae74605889)
![image](https://github.com/apache/incubator-devlake/assets/4018887/e55f53ae-09a8-4fa3-8aed-aad56643ec8f)

**Comment by Startrekzky** [comment]
Hi @gabrielenosso  , thanks for the feedback. I'll consider it.

**Comment by Startrekzky** [comment]
Hi @abeizn ,  what do you think of the suggestion?
