### ISSUE TITLE
[Bug][Grafana] Month filter in Engineering Overview Dashboard destroys User Experience

### ISSUE THREAD

**Issue by gabrielenosso** [apache/devlake#7399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the engineering Overview dashboard, some KPIs are shown using the Month filter at the top, which doesn't have lot of sense, as the labels does not indicate that.
Would have more sense to just indicate the total, following the data selected by the main time filter.

Even worse: the Month filter by default selects 2024-01, creating a very confusing user experience.

Possible solution would be to select the latest month.
But IMHO, best and easiest solution would be to remove that month filter and display totals for those KPIs.

### What do you expect to happen

Understanding the data present in the dashboard without having to understand the meaning for 30 minutes.

### How to reproduce

Look at the Engineering Overview Dashboard

### Version

1.0.5 beta

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
It might be due to the different time filters. Please take a look @abeizn

**Comment by Startrekzky** [comment]
Hi @gabrielenosso , the month filter was required by other users who wanted to see metrics for a certain month. So, we'll keep it.

As for the default value, it's a bug. It should default to null or the latest month.

**Comment by abeizn** [comment]
@gabrielenosso  Default value now defaults to null. cc @Startrekzky 
![img_v3_02ac_7b635e43-9aa8-4323-bdcb-9c023d3a772g](https://github.com/apache/incubator-devlake/assets/101256042/f79d4073-4963-43dc-a247-2dab4e5541c6)
![img_v3_02ac_a1e4a474-9722-45c6-8d61-6107c843831g](https://github.com/apache/incubator-devlake/assets/101256042/7cda474c-2dd5-4c74-8422-794f0d173fb4)

**Comment by gabrielenosso** [comment]
It's absolutely fine to keep it, but the title of the kpi should be different.Maybe adding in the label "(selected month)?
Da: "Louis.z" ***@***.***
A: "apache/incubator-devlake" ***@***.***
Cc: "Gabriele Nosso" ***@***.***,"Mention" ***@***.***
Data: Sat, 27 Apr 2024 20:58:54 -0700
Oggetto: Re: [apache/incubator-devlake] [Bug][Grafana] Month filter in Engineering Overview Dashboard destroys User Experience (Issue #7399)


Hi @gabrielenosso , the month filter was required by other users who wanted to see metrics for a certain month. So, we'll keep it.
As for the default value, it's a bug. It should default to null or the latest month.
