### ISSUE TITLE
[Question][Jenkins] Most Jenkins Projects Not Selectable

### ISSUE THREAD

**Issue by tc-jason-gregory** [apache/devlake#7400]
## Question
I'm running version v1.0.0-beta5@e6ea5f6. Can you advise as to why almost all my Jenkins projects in the "Add Data Scope" section are not selectable.  I have tried with different Jenkins users (highest permission levels) and cannot determine why this is occurring.  I am running a self hosted Jenkins instance (version 2.363)

Thank you!

## Screenshots
![image](https://github.com/apache/incubator-devlake/assets/127858964/3753b781-823f-486e-9369-9d385493cf68)

**Comment by klesh** [comment]
Maybe caused by https://github.com/apache/incubator-devlake/pull/7213/files#diff-ef2d9899f5788356b03b7c5c1320ad5bb7e78aa63047d202cde86ed1360bd7abR79

What is the job type?

@gustavobini What do you think?

**Comment by gustavobini** [comment]
@klesh that could be the reason.

@tc-jason-gregory do you know the type of those jobs you're unable to select? Adding `/api/json` to the end of the URL should tell you that, if you look at the `_class` property.

**Comment by tc-jason-gregory** [comment]
@gustavobini 

here is what I show for one that is not selectable…

`{"_class":"hudson.model.FreeStyleProject","name":"PROD - Release Analytics_UI", `

… then for one that is selectable…

`{"_class":"org.jenkinsci.plugins.workflow.job.WorkflowJob","name":"TC_terraform",`

**Comment by tc-jason-gregory** [comment]
@klesh @gustavobini Is there an updated docker image that includes this change I should work with?

**Comment by gustavobini** [comment]
@tc-jason-gregory this is the image generated by the commit https://hub.docker.com/layers/apache/devlake/main_240430_0413_cb146f8/images/sha256-312317a5b98734d030dd6b667d9342f5a05105e8fd0e464df474a837f5cc7e2b?context=explore. There's no beta yet with the commit included

**Comment by abeizn** [comment]
@gustavobini @tc-jason-gregory It takes effect in version v1.0.0-beta7.
