### ISSUE TITLE
[Bug][Config UI] Error when trying to save an existing scope config

### ISSUE THREAD

**Issue by cstump** [apache/devlake#7413]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When trying to save a (CircleCI) scope config I get the behavior in the attached video and the attached output on Safari's dev console.

![devlake_scope_config_bug](https://github.com/apache/incubator-devlake/assets/569564/aecd5b4f-2924-463f-b9b1-eefb3b3a7214)

[Console.txt](https://github.com/apache/incubator-devlake/files/15155443/Console.txt)

### What do you expect to happen

I expect the scope config to save without error

### How to reproduce

Attempt to edit an existing scope config using either beta5 or beta6

### Anything else

This happens every time for me. First noticed in beta5. Also exists in beta6.

### Version

v1.0.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@cstump It takes effect in version v1.0.0-beta7.
