### ISSUE TITLE
[Question][Module Name] Configure mTLS with mysql

### ISSUE THREAD

**Issue by varun-corr** [apache/devlake#7420]
## Question
There is an example on apache devlake website on how to configure the DB_URL to connect with a mysql instance using server certificate. Can we also add an example on how to configure the DB_URL to connect with client cert, client key _and_ server certificate?

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by klesh** [comment]
I think mounting the client cert/key to the `devlake` container and referring them within the `DB_URL` should do the trick.
Would you like to try it out and maybe contribute to the [doc](https://github.com/apache/incubator-devlake-website)?
