### ISSUE TITLE
Missing information in the "commits" table

### ISSUE THREAD

**Issue by naveenreddymanukonda** [apache/devlake#7424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

There are two problems with our commit data:

- **Missing information in the "commits" table:** Commit information for Bitbucket is not being stored in the "commits" table. This information is actually present in the "_tool_bitbucket_commits" table, but it's not being copied over.
- **Incomplete data in the "_tool_bitbucket_commits" table:** This table captures information about additions and deletions, but it seems like this data is not being recorded properly.

### What do you expect to happen

The commits table should have all the information which _tool_bitbucket_commits has the commits

### How to reproduce

Run the bitbucket pipeline for any of the projects and check the PR size related metricize-related

### Version

v1.0.0-beta6@ea2cdbc

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
I would guess that the records come from the PullRequests which is Enabled by default while the commit_converter is NOT.
That is why the _tool_bitbucket_commits is populated while the `commits` table is NOT.
