### ISSUE TITLE
[Bug][GitHub] LOC additions/deletions are wrong for the first commit in the specified time range

### ISSUE THREAD

**Issue by antomer** [apache/devlake#7426]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Noticed some weird data in the commits table, some commits have random huge numbers for additions/deletions, for example, 182511 lines added, but in reality commit has only 7 lines added, moreover, if I fetch commit data from GitHub rest API it also shows correct data - 7 lines added.

such incorrect data screws up the PR size metric

re-collect data in full refresh mode doesn't help.

[Slack thread ](https://devlake-io.slack.com/archives/C03APJ20VM4/p1714637554485249)

### What do you expect to happen

Expect additions/deletions to be correct

### How to reproduce

1. create a new project
2. add a new GitHub data scope for repository (should have some commits)
3. add new data scope from 2. to project from 1. with sync time to be later than first commits in the repo
4. trigger data collection
5. observe that  in commits table additions entry for the oldest collected commit are incorrect, seems like they include total amount of LOC in the repo.

### Version

1.0.0-beta5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi, we'll fix it soon.
