### ISSUE TITLE
[Bug][Projects] Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by dwaghulade** [apache/devlake#7427]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Project created intially without any data connection is showing in the project list and would like to dlete it however when click on project or setting icon getting error message as "Cannot read properties of null (reading 'id')"

![image](https://github.com/apache/incubator-devlake/assets/148270787/2df2d147-0e94-4e08-bcac-f2afec100d20)

### What do you expect to happen

Should able to open setting for project so that it can be deleted.

### How to reproduce

Issue in highlighted project

![image](https://github.com/apache/incubator-devlake/assets/148270787/ae77418d-6afa-4af7-9cf1-ba488e1c4527)

### Version

v1.0.0-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
How did you create the project, by API or Config UI?

**Comment by ArtRout1313** [comment]
Hi everyone.

Faced with the same issue. 

Also noticed, for that new project there is no Blueprint created. And in database tables ‘_devlake_blueprint*’ there are rows filled with ’null’. 

<img width="1264" alt="Screenshot 2024-05-09 at 19 29 03" src="https://github.com/apache/incubator-devlake/assets/141954670/0b334334-2a93-468c-a68a-dcab15a81448">
<img width="1583" alt="Screenshot 2024-05-09 at 19 29 24" src="https://github.com/apache/incubator-devlake/assets/141954670/c3c0c8cd-13f4-4770-9938-3533beda62af">

**Comment by dwaghulade** [comment]
> Config UI

Project created with Config UI

**Comment by dwaghulade** [comment]
Upgraded to v1.0.0-beta8 however issue still persist.

**Comment by mintsweet** [comment]
Hi @dwaghulade, I'm so sorry for this issue, but existing data cannot be modified, please create a new project.

**Comment by klesh** [comment]
@dwaghulade The fix can only prevent the problem for the new projects onward

**Comment by dwaghulade** [comment]
Thanks @mintsweet & @klesh for the clarification.

Any way to clean-up existing projects as those are unnecessary being displayed in the list.

**Comment by klesh** [comment]
@dwaghulade try deleting the project from the database.

**Comment by dwaghulade** [comment]
@klesh I was avoiding to use direct DB deletion approach because of any dependencies impact. Do you have list of tables from where I need to delete entries to make sure all related data as well deleted for these projects?

**Comment by klesh** [comment]
@dwaghulade I assumed that the problematic project has never been actually used, correct? you may delete it from the `projects` table if so.

**Comment by dwaghulade** [comment]
Thanks @klesh for your help. I have removed entries from projects tables which has cleared unwanted projects from the list on UI.

**Comment by klesh** [comment]
Glad to know, close the issue  now
