### ISSUE TITLE
[Bug][Github] Github deployments without Github Actions

### ISSUE THREAD

**Issue by carocad** [apache/devlake#7435]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The devlake documentation says that Github deployment are read in order to compute DORA metrics. However, in several of my (private) projects, I have Github deployments that are created without using Github Actions. In those cases, devlake doesn't detect the Deployments as (it seems to) assume that Deployments can only come from Github Actions as seen [here](https://github.com/apache/incubator-devlake/blob/main/backend/plugins/github/tasks/cicd_run_collector.go#L53).

<img width="1024" alt="image" src="https://github.com/apache/incubator-devlake/assets/10408729/9ec12d25-8603-4e25-9809-8dc3956fcbd2">

### What do you expect to happen

devlake should take the Deployment information from the Github Deployment API not from the Github Actions API; see [docs](https://docs.github.com/en/rest/deployments?apiVersion=2022-11-28). As per the previous docs it is possible to create Github deployments without using Github actions.

### How to reproduce

- setup a github repository
- setup a ci/cd system outside of Github that creates Github Deployments when doing a Deployment
- setup devlake to connect to Github and fetch ci/cd information from there
- Deployment data will be missing even though Deployments are clearly visible on the Github UI

### Anything else

See steps above. It happens every time even with the latest version

### Version

v1.0.0-beta6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
I think we do collect Github Deployment as well https://github.com/apache/incubator-devlake/blob/470669d603f792927d1313194a408597a1c145fd/backend/plugins/github_graphql/tasks/deployment_collector.go#L42

Select the CICD entities in the configuration and it should be good to go, just ignore the  Github Action if you don't need them.

**Comment by carocad** [comment]
Maybe I misunderstood the code (I haven't taken a deep look) but it looks like that is only used by the graphql implementation but in our case we are using the "plain api". 

> just ignore the Github Action if you don't need them.

We tried this, we have 2 projects :
- one with Github deployments but no Github Action and
- another one with Github deployments through Github Actions

In the first case we don't get any deployment information shown in devlake/grafana dashboards but on the second case we do get the information which is what pointed me to the distinction mentioned on the bud description.

Please let me know if I can provide you some debug logs or similar to further clarify this :)
PS: we are using Github Enterprise edition not github.com

**Comment by klesh** [comment]
That is weird, the `subtasks` for collecting and converting Github Deployment are enabled by default.
Can you share the configuration which you can find by following this screenshot
![image](https://github.com/apache/incubator-devlake/assets/61080/3eb5018f-38da-4b13-a3b1-c2baa1c6870a)

**Comment by carocad** [comment]
> That is weird, the `subtasks` for collecting and converting Github Deployment are enabled by default. Can you share the configuration which you can find by following this screenshot

Sure thing, here you go.

[ghe+actions.json](https://github.com/apache/incubator-devlake/files/15296544/ghe%2Bactions.json)
[ghe+jenkins.json](https://github.com/apache/incubator-devlake/files/15296545/ghe%2Bjenkins.json)

The first file is the one where deployments are made with github actions; whereas the second one is where the deployments are made outside of it. On the json files I can see that "Collect Workflow Runs" is a subtasks but there is no "Collect Deployments" or similar.

**Comment by klesh** [comment]
I see, did you disable the github graphql feature on the connection detail?

**Comment by klesh** [comment]
Try enable it and see if the problem got fixed.

**Comment by carocad** [comment]
> Try enable it and see if the problem got fixed.

just tried it but unfortunately it crashes. See logs below

```txt
time="2024-05-14 08:46:28" level=info msg=" [pipeline service] [pipeline #87] [task #618] start executing task: 618"
time="2024-05-14 08:46:28" level=info msg=" [pipeline service] [pipeline #87] [task #618] start plugin"
time="2024-05-14 08:46:28" level=info msg=" [pipeline service] [pipeline #87] [task #618] [api async client] creating scheduler for api \"https://github.boschdevcloud.com/api/v3/\", number of workers: 13, 9500 reqs / 1h0m0s (interval: 378.947368ms)"
time="2024-05-14 08:46:28" level=error msg=" [pipeline service] [pipeline #87] [task #618] run task failed with panic\n\tcaused by: run task failed with panic (github.com/apache/incubator-devlake/helpers/pluginhelper/api.CreateAsyncGraphqlClient:71)\n\tWraps: (2) non-200 OK status code: 404 Not Found body: \"{\\\"message\\\":\\\"Not Found\\\",\\\"documentation_url\\\":\\\"https://docs.github.com/enterprise-server@3.11/rest\\\"}\"\n\tWraps: (3) non-200 OK status code: 404 Not Found body: \"{\\\"message\\\":\\\"Not Found\\\",\\\"documentation_url\\\":\\\"https://docs.github.com/enterprise-server@3.11/rest\\\"}\"\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *errors.errorString"

```

**Comment by klesh** [comment]
Seems like you are using the enterprise version, is it Cloud or On-premise?

**Comment by carocad** [comment]
> Seems like you are using the enterprise version, is it Cloud or On-premise?

GitHub Enterprise Server 3.11.9 (OnPremise)

**Comment by klesh** [comment]
It sounds like there might be some specific behaviors with GitHub Enterprise Server 3.11.9 (On-Premise). Unfortunately, since we don't currently have access to this version for testing, it limits our ability to directly replicate the issue.

Here are a few ways we can move forward:

Community Resources: Have you checked the GitHub Enterprise Server documentation or community forums for known quirks or workarounds related to your specific version? There might be existing solutions or insights from other users.
Consider Upgrading (Optional): If feasible, upgrading to a newer version of GitHub Enterprise Server might resolve the issue and provide access to the latest features and bug fixes.

**Comment by carocad** [comment]
Hello @klesh ,
It seems that the rate limit behavior is deactivated by default on Github Enterprise Server. See docs: https://docs.github.com/en/enterprise-server@3.11/graphql/overview/rate-limits-and-node-limits-for-the-graphql-api#primary-rate-limit

Would it be possible for devlake to handle that case with a default value or another method which avoid a panic? I can also contact the administrators on our side and ask if they can set one but since this is the default behavior from Github Server I would assume that this wouldn't be an isolated case.

**Comment by klesh** [comment]
@carocad Sure, you may find the "Custom Rate Limit" on the connection page.

![image](https://github.com/apache/incubator-devlake/assets/61080/a5ce2497-d011-4942-b4fd-9bc56534da9d)

**Comment by carocad** [comment]
> @carocad Sure, you may find the "Custom Rate Limit" on the connection page.

Unfortunately that didn't work either. See logs below

```log
time="2024-05-21 07:48:30" level=info msg=" [pipeline service] [pipeline #145] [task #971] start executing task: 971"
time="2024-05-21 07:48:30" level=info msg=" [pipeline service] [pipeline #145] [task #971] start plugin"
time="2024-05-21 07:48:30" level=info msg=" [pipeline service] [pipeline #145] [task #971] [api async client] creating scheduler for api \"https://github.boschdevcloud.com/api/v3/\", number of workers: 6, 4500 reqs / 1h0m0s (interval: 800ms)"
time="2024-05-21 07:48:31" level=error msg=" [pipeline service] [pipeline #145] [task #971] run task failed with panic\n\tcaused by: run task failed with panic (github.com/apache/incubator-devlake/helpers/pluginhelper/api.CreateAsyncGraphqlClient:71)\n\tWraps: (2) non-200 OK status code: 404 Not Found body: \"{\\\"message\\\":\\\"Not Found\\\",\\\"documentation_url\\\":\\\"https://docs.github.com/enterprise-server@3.11/rest\\\"}\"\n\tWraps: (3) non-200 OK status code: 404 Not Found body: \"{\\\"message\\\":\\\"Not Found\\\",\\\"documentation_url\\\":\\\"https://docs.github.com/enterprise-server@3.11/rest\\\"}\"\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *errors.errorString"
```

I can only assume from this that DevLake would check the rate limit endpoint regardless of the custom rate limit and only after it receives a response it would then overwrite it. If you agree that this is a bug, I would happily try to create a PR to fix it :)

**Comment by carocad** [comment]
> ... I can also contact the administrators on our side and ask if they can set one but since this is the default behavior from Github Server I would assume that this wouldn't be an isolated case.

I just got an answer from the administrators on my site. The GraphQL endpoints on our side already have a rate limit so this shouldn't be the case. I also tried querying it myself and got an response without any issues. I submitted from the github.com docs (see [ref](https://docs.github.com/en/graphql/overview/rate-limits-and-node-limits-for-the-graphql-api#checking-the-status-of-your-primary-rate-limit))
```graphql
query {
  viewer {
    login
  }
  rateLimit {
    limit
    remaining
    used
    resetAt
  }
}
```
I don't know which query does dev-lake uses but I can only guess that one of the fetched parameters was introduced on a version of github newer than `3.11.9`. In any case, my proposal above still stands.
If you point me in the right direction I can definitely give it a try :)

**Comment by carocad** [comment]
> Do you run this query
> 
> ```
> query {
>   viewer {
>     login
>   }
>   rateLimit {
>     limit
>     remaining
>     used
>     resetAt
>   }
> }
> ``` on [github](https://docs.github.com/en/graphql/overview/explorer) or  your github enterpise version?

On my github enterprise version of course :)

<img width="902" alt="image" src="https://github.com/apache/incubator-devlake/assets/10408729/1e929c23-1f85-40de-becb-94798252a006">


> I think it's your github version doesn't support to query rate limit info. You can have a try.
> 
> And btw, DevLake's query is: ...


Yeah, it works on my github enterprise version. That query seems like a subset of the one I posted above on https://github.com/apache/incubator-devlake/issues/7435#issuecomment-2122171826 (see response section).

**Comment by carocad** [comment]
@klesh we continued to follow up on this and now I am 99% sure that this is an issue on devlake. The issue is that for Github Servers it is required to set the endpoint URL. This generally ends in `/api/v3/{{suffix}}` as per Rest guide of Github. Unfortunately the graphql endpoint doesn't follow this convention. So its endpoint is `/api/graphql` (notice the missing `/v3/`).

This line [here](https://github.com/apache/incubator-devlake/blob/main/backend/plugins/github_graphql/impl/impl.go#L207). Assumes that the graphql suffix can be added to previously defined endpoint URL resulting in `/api/v3/graphql` which doesn't exists and therefore results in a 404 error --> panic. Since graphql doesn't follow the convention of suffix, simply harcoding it to `/api/graphql` should solve the issue. Please let me know if you would like me to make a PR for it or if you prefer to do it yourselves. Either way works for me.


<img width="818" alt="image" src="https://github.com/apache/incubator-devlake/assets/10408729/b2bc245d-fda1-4796-a6ca-73b6d6ff2c08">

**Comment by klesh** [comment]
Try removing `v3/` suffix from the endpoint and see if it solves your problem, e.g. `https://github.boschdevcloud.com/api/`

**Comment by carocad** [comment]
> Try removing `v3/` suffix from the endpoint and see if it solves your problem, e.g. `https://github.boschdevcloud.com/api/`

It seems that some other functionality relies on the `/v3` suffix. Changing the connection endpoint fails to validate the token.  Even ignoring the error still leads to an error while collecting/analysing the data. See logs below

<img width="819" alt="image" src="https://github.com/apache/incubator-devlake/assets/10408729/aa0ad667-2833-4ccb-b142-03630f3ef517">

```log
time="2024-05-28 00:00:02" level=info msg=" [pipeline service] [pipeline #211] [task #1411] start executing task: 1411"
time="2024-05-28 00:00:03" level=info msg=" [pipeline service] [pipeline #211] [task #1411] start plugin"
time="2024-05-28 00:00:03" level=info msg=" [pipeline service] [pipeline #211] [task #1411] [api async client] creating scheduler for api \"https://github.boschdevcloud.com/api/\", number of workers: 6, 4500 reqs / 1h0m0s (interval: 800ms)"
time="2024-05-28 00:00:03" level=info msg=" [pipeline service] [pipeline #211] [task #1411] github graphql init success with remaining 5000/5000 and will reset at 2024-05-28 01:00:03 +0000 UTC"
time="2024-05-28 00:00:03" level=info msg=" [pipeline service] [pipeline #211] [task #1411] total step: 37"
time="2024-05-28 00:00:03" level=info msg=" [pipeline service] [pipeline #211] [task #1411] executing subtask Collect Milestones"
time="2024-05-28 00:00:03" level=info msg=" [pipeline service] [pipeline #211] [task #1411] [Collect Milestones] start api collection"
time="2024-05-28 00:00:03" level=error msg=" [pipeline service] [pipeline #211] [task #1411] [Collect Milestones] end api collection error\n\tcaused by: error parsing response from repos/eBike/devops-launch-assist/milestones (200)"
time="2024-05-28 00:00:03" level=error msg=" [pipeline service] [pipeline #211] [task #1411] subtask Collect Milestones ended unexpectedly\n\tWraps: (2) Error waiting for async Collector execution\n\tWraps: (3) error parsing response from repos/eBike/devops-launch-assist/milestones (200)\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *errors.errorString"
```

**Comment by klesh** [comment]
@carocad You are right, it appears that the URL patterns are different between Cloud and On-premise...

However, it is hard to tell whether it is caused by the implementation of the On-premise version or something specific to your configuration.

It is hard for us to fix the problem without a working On-premise instance, would you like to work on the issue and fix it for others?

**Comment by carocad** [comment]
> It is hard for us to fix the problem without a working On-premise instance, would you like to work on the issue and fix it for others?

Sure thing, I opened a PR for it. I tested it on the Github Enterprise instance we use and it worked fine. I was not able to find any tests for the code though. I assume that as you mentioned, there are none since it would require both a github.com and github enterprise organization.
