### ISSUE TITLE
[Bug][Bitbucket] Error looping indefinitely during Bitbucket sync due to failed getting SubTaskInfo 

### ISSUE THREAD

**Issue by yusufsyaifudin** [apache/devlake#7440]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am using Postgres as my database and connect to one of my repositories in Bitbucket, but during sync I found this error

<img width="1453" alt="image" src="https://github.com/apache/incubator-devlake/assets/1698600/242473da-8dff-47e5-9d2f-9acb5956af31">

I am sure that it is triggered by this code:
https://github.com/apache/incubator-devlake/blob/v1.0.0-beta6/backend/server/services/task.go#L309

This happened because Postgres doesn't support compare boolean in column `is_collector` with operator `= 1`.

![image](https://github.com/apache/incubator-devlake/assets/1698600/c90c2496-5cef-45eb-9c44-eff02d9f3a1c)

### What do you expect to happen

It should not break both for Postgres and MySQL.

### How to reproduce

Install Devlake and Devlake Config UI version v1.0.0-beta6, using Postgres as database.

### Version

v1.0.0-beta6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
@yusufsyaifudin It takes effect in version v1.0.0-beta7.

**Comment by yusufsyaifudin** [comment]
> @yusufsyaifudin It takes effect in version v1.0.0-beta7.

sorry, haven't tried it again yet, I use v0.21.0 because the db migration (only creating schema at first run) seems too long, so I use v0.21.0
