### ISSUE TITLE
[Bug][Module Name] Sonar qube data is not consistent

### ISSUE THREAD

**Issue by naveenreddymanukonda** [apache/devlake#7450]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm noticing inconsistencies in the SonarQube data stored in cqissues. It seems like some data might be getting deleted after a week. I can't find information from a week ago, even though the screenshot shows values for April 29th and 19th. There's a gap in the data between those dates.

We are referring cqissues table

Where we did some pushes into Sonarqube.

![image](https://github.com/apache/incubator-devlake/assets/40488776/8ae0e16b-d1b3-4d53-9c14-401d1fbac3b7)

### What do you expect to happen

We need to have the data whenever we run the scan

### How to reproduce

NA

### Version

v1.0.0-beta6@ea2cdbc

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi , did you conduct any scans during Aprile 19th and 29th?

**Comment by Startrekzky** [comment]
Hi @naveenreddymanukonda , the current logic for SonarQube is that:

Before collecting SonarQube's data, DevLake will clear the existing data for SonarQube, and then start collecting the new data.

The purpose is not to mix the data of multiple Sonar scans up.

**Comment by naveenreddymanukonda** [comment]
@Startrekzky Can you explain how this works? Does it replace existing data for past days or for the same day?  Also, if DevLake clears data, why did we have old data for a month?

**Comment by Startrekzky** [comment]
@naveenreddymanukonda 
1. SonarQube's data is organized by scans.
2. SonarQube's APIs can only be used to get the data for the last scan. 

So, DevLake's SonarQube plugin will always collect the full data from SonarQube, which is the result of the last scan. But before that, we'll remove the existing data in DevLake's DB, the data might be the result of the previous Sonar scan.
