### ISSUE TITLE
[Feature][Linear] Add support for Linear

### ISSUE THREAD

**Issue by seanknox** [apache/devlake#7465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As an engineering director I want to use data from Linear to understand cycle/lead/etc time in our SDLC.

### Description

Hi, I saw [this existing request](https://github.com/apache/incubator-devlake/issues/5579) for Linear support was closed, opening this new one. Happy to close this and resurrect the original issue if that's better.

### Related issues

https://github.com/apache/incubator-devlake/issues/5579

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @seanknox , thanks for your proposal. Are you planning to put up a PR?

**Comment by hezyin** [comment]
Hi @seanknox , let us know if you're interested in contributing a DevLake plugin for Linear. We're happy to discuss the plan and help review the PR or anything else you might need.

**Comment by seanknox** [comment]
I won't be able to contribute directly. Sorry!
