### ISSUE TITLE
[Bug][Config UI] Unable to collect data owing to which Newly added GitHub metrics are not reflected

### ISSUE THREAD

**Issue by mparthi3-ford** [apache/devlake#7488]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am getting the following error everytime I cilck “Collect Data” after performing the following steps, especially for the repos that I a using.

**Steps Followed:**

Established Connections for GitHub using the API URL : https://github.**xxxx**.com/api/v3/
where (xxxx -> Enterprise name)
Added Data scope and data config
Added Project
Mapped the corresponding conenction with the newly added project .
Hit “Collect Data” 
Struck with the issue **"time="2024-05-20 02:53:31" level=info msg=" [pipeline service] [pipeline #692] [task #10282] start executing task: 10282"
time="2024-05-20 02:53:31" level=info msg=" [pipeline service] [pipeline #692] [task #10282] start plugin"
time="2024-05-20 02:53:31" level=error msg=" [pipeline service] [pipeline #692] [task #10282] PlainCloneContext\n\tcaused by: Get \"https://git:***@github.ford.com/AV-TaaS/gcp-app-terraform-trr-backend.git/info/refs?service=git-upload-pack\": proxyconnect tcp: dial tcp :0: connect: connection refused**"

Attached the screenshot of the issue for your reference.

<img width="2056" alt="image" src="https://github.com/apache/incubator-devlake/assets/95069195/572fbc29-6f8f-4d07-aa73-9468b39d7885">

<img width="1400" alt="image" src="https://github.com/apache/incubator-devlake/assets/95069195/c416024f-2213-424b-bc11-996c1733d1a7">

### What do you expect to happen

Data collection should be seamless and I should be able to view the metrics pertaining to the newly added repo in Grafana

### How to reproduce

Established Connections for GitHub using the API URL : https://github.**xxxx**.com/api/v3/
Added Data scope and data config
Added Project
Mapped the corresponding conenction with the newly added project .
Hit “Collect Data” 

### Anything else

Please prioritise to get this issue resolved.

### Version

v0.19.1-beta3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
The error message said "proxyconnect tcp", did you set the Proxy for the connection?
![image](https://github.com/apache/incubator-devlake/assets/61080/ba9b35cf-36a2-44c6-9c4b-d569cf109251)

**Comment by mparthi3-ford** [comment]
@klesh : I am using GitHub not GitLab. Also, I have not added teh proxy URL for the other projects. however, I was able to make the connection and collect the data successfully.

**Comment by mparthi3-ford** [comment]
Hi @klesh : After adding the proxy URL in the Proxy field, I was able to collect the data successfully for GitHub.
