### ISSUE TITLE
[Bug][Gitlab] Data scopes can have the same name.

### ISSUE THREAD

**Issue by antoniomuso** [apache/devlake#7490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When you have two repositories in two different groups but with the same name, for example: `firstgroup/website` and `secondgroup/website.` The name assigned to the scopes config is the same, and you cannot distinguish one from the other.

### What do you expect to happen

I expect that the group name will be added to the data scope ex

### How to reproduce

You can reproduce by adding to repositories with the same name but in different GitLab groups.

### Version

v0.21.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @antoniomuso , I think this one has been fixed in the latest v1.0.0-beta8 by adding the namespace before the repo name in the data scope configuration dialogue. Please give it a go.

**Comment by Startrekzky** [comment]
Hi @antoniomuso , I tried in the v1.0.0-beta8. I didn't have repos with the same names, but I can confirm when selecting data scope, the group name is displayed.
![image](https://github.com/apache/incubator-devlake/assets/14050754/7c24ad75-688b-4acb-b832-26089e80bc53)

Not sure if I have understood your question correctly.

**Comment by antoniomuso** [comment]
I mean, when you add the data scope to the project, if you have two data scopes with the same name, I don't know which data scope I am adding. 
![image](https://github.com/apache/incubator-devlake/assets/16511436/de4e4df1-748d-436b-af2d-1d3602200fee)

**Comment by Startrekzky** [comment]
@antoniomuso I see, the group name is not displayed in the `project connection's data scope list`.

**Comment by klesh** [comment]
We've identified a potential issue with the `config-ui` component's reliance on the optional field `scope.fullName` within the API response. This inconsistency can affect not only Gitlab but also potentially other integrations.

Currently, the behavior of `scope.fullName` depends on the implementation of individual plugins, leading to potential errors. We're exploring solutions to address this:

1. **Enforce fullName in Plugins**: We could require all plugins to include fullName in the scope entity. This ensures consistency but requires modifying a significant number of plugins and maintaining compatibility.
2. **Modify scopeHelper to Inject fullName or Response Format**: We could modify the scope helper to inject value for fullName or redesign the entire response format. 

Both options require careful consideration and thorough testing. We're actively evaluating the best approach and will keep you updated.

In the meantime, if you have any questions or suggestions, feel free to comment below!
