### ISSUE TITLE
[Bug][github data source] Data is not populating in pull_requests table 

### ISSUE THREAD

**Issue by Rbathular** [apache/devlake#7491]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have configured github data source connection and triggered the collect data pipeline. Pipeline is success but after that I'm not able to see the data in pull_requests table . In grafana dashboard also I'm not seeing any pull requests related data . All the github metrics it's giving no data 

### What do you expect to happen

I should be able to see data in contribution (PRs) , How PRsare Handled metrics 

### How to reproduce

1. create github data connection 
2. add data scope 
3. create project and add data connection 
4. click on collect data .
5. once pipeline is success check the grafana dashboard . 
6. check the grafana dashboard . 

### Version

v1.0.0-beta7@2cc08c7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Rbathular** [comment]
1. logs from data connection pipeline 
[logging.tar-3.gz](https://github.com/apache/incubator-devlake/files/15377511/logging.tar-3.gz)
2.  please see the below attachment for configuration details 
<img width="812" alt="Screenshot 2024-05-20 at 6 49 27 PM" src="https://github.com/apache/incubator-devlake/assets/137270549/5daa5085-d50b-4916-8919-9ef564ebc423">
<img width="1277" alt="Screenshot 2024-05-20 at 6 49 36 PM" src="https://github.com/apache/incubator-devlake/assets/137270549/b9aa910a-b3ea-4a77-aab8-b8d370a04196">
3. Shared the grafana logs :
[devlake-qa-grafana-7b88dfbd8-l72ch-grafana.log](https://github.com/apache/incubator-devlake/files/15377527/devlake-qa-grafana-7b88dfbd8-l72ch-grafana.log)

**Comment by Rbathular** [comment]
@dosu I have verified all the points which you provided . All the details are proper , still not able to see the pull_requests metrics.

Note : Previously we are using v0.19.1-beta3@ version devlake and with v0.19.1-beta3@ we are able to get pull_request data metrics in grafana , Today we installed devlake newly with version v1.0.0-beta7@2cc08c7 . With this v1.0.0-beta7@2cc08c7 version we are not able to get pull_request data . Jira and Sonarqube data is populating as expected .

**Comment by klesh** [comment]
How about the `_tool_github_pull_requests` table? 
There is a `Time After` under the Sync policy, what was the value of it? Are you sure that there is PR in the period?

**Comment by Rbathular** [comment]
@klesh Added the sync policy details . please see 
<img width="1048" alt="Screenshot 2024-05-21 at 11 47 24 AM" src="https://github.com/apache/incubator-devlake/assets/137270549/56096256-80e6-4611-af65-1259314710ca">

**Comment by Rbathular** [comment]
@klesh Defenetily Pr's available in that period

**Comment by d4x1** [comment]
> @klesh Added the sync policy details . please see <img alt="Screenshot 2024-05-21 at 11 47 24 AM" width="1048" src="https://private-user-images.githubusercontent.com/137270549/332305887-56096256-80e6-4611-af65-1259314710ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODk0MjgsIm5iZiI6MTcxNjI4OTEyOCwicGF0aCI6Ii8xMzcyNzA1NDkvMzMyMzA1ODg3LTU2MDk2MjU2LTgwZTYtNDYxMS1hZjY1LTEyNTkzMTQ3MTBjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxMDU4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGZkNzdkZTJjMjE5ODc3NzliNTJhZGMxNjg0NjRjZjllNTQ0MzcxYzE5NmFhNjQ0YThmMTZjYmI1OGM4MTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NxD_D5k41WAcKnQLU16Z59tJ0A-18XBh2PlZYbxgOUY">

Thank you for your screenshot.
I think @klesh wants you to help to confirm whether theres are some records in table `_tool_github_pull_requests ` or not.

With the addtional confirmation, we can dive into this issue, and see what's wrong.

I have searched your log, there is an error 
```
 [pipeline service] [pipeline #7] [task #67] [Clone Git Repo] [gitcli] git exited with error\nstderr: Cloning into bare repository '/tmp/gitextractor83455746'...\nstderr: fatal: error processing shallow info: 4\n\n\tcaused by: exit status 128"
```
This error occurs randomly. @Rbathular  You can try to re run this pipeline, until there is no errors in config ui.(If there are errors in log, the config ui will show failed tasks.)

And, at the same time, @klesh  Can you help to confirm whether it's the root cause ?

**Comment by Rbathular** [comment]
@d4x1 One update from my side : yesterday I configured 2 projects in devlake config ui . 
Project1 : it has 2 repositories  --> I'm not able to see any pull requests related data in github metrics in grafana dashboard. 
project 2 : it has 2 repositories --> yesterday I triggerd the pipelines but yesterday I'm not able to see any data yesterday . Today as part of sync policy one more pipeline triggered and after that able to see one repository pull requests data and data also not consistent. 2nd repository data still not able to see . 

I have added both project logs . Could you please help on this 
[project1.gz](https://github.com/apache/incubator-devlake/files/15390369/project1.gz)
[project2.gz](https://github.com/apache/incubator-devlake/files/15390370/project2.gz)

**Comment by klesh** [comment]
The log shows that no PR in the time range, it also explained `fatal: error processing shallow info:` because no commits as well.
Please make sure you the repo you were collecting has PR created/updated AFTER 2023-11-20. Screenshot would be helpful.

**Comment by Rbathular** [comment]
@klesh 
One of the repository added in github connection 
<img width="1091" alt="Screenshot 2024-05-23 at 7 48 36 PM" src="https://github.com/apache/incubator-devlake/assets/137270549/97d7f3d0-90a7-4147-8701-10a8c3bf47c8">
and  it's github pull request screenshot 
<img width="1274" alt="Screenshot 2024-05-23 at 7 52 50 PM" src="https://github.com/apache/incubator-devlake/assets/137270549/4fdb153b-c1be-43e9-82a9-7772746b1002">

**Comment by Rbathular** [comment]
strange thing is I'm able to see data for few repositires and for many off them I'm not able to get data in pull_requests table. 

Note: The repositories which I added are 1 year old repositories

**Comment by klesh** [comment]
To clarify, do you mean that you added a bunch of 1-year-old repositories and were able to fetch PRs for a few of them while others were not?

Correct me if I am wrong:
1. The repo `AV-TaaS/vehicle-reservation-ui` is alive and active, it has PRs merged recently
2. A Apache DevLake Project was created with Sync Policy time range starting from 2023-11-20
3. The "CollectPullRequest" subtask appeared in the pipeline under the task for the repo
4. No PRs collected for the repo
5. However, PRs can be collected for newer repos

Can you try deploying a new instance with a brand new database to collect the repo and see if the PRs can be collected.
