### ISSUE TITLE
[Bug][Bitbucket] GET endpoint for Bitbucket scope-configs always fails

### ISSUE THREAD

**Issue by riskpeep** [apache/devlake#7494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The GET endpoint /plugins/jira/connections/{connectionId}/scope-configs/{id} always fails.

### What do you expect to happen

The scope-configs endpoint should return 200 with a scope-config json

e.g. 

```
{
  "connectionId": 0,
  "createdAt": "string",
  "deploymentPattern": "string",
  "entities": [
    "string"
  ],
  "id": 0,
  "issueStatusDone": "string",
  "issueStatusInProgress": "string",
  "issueStatusOther": "string",
  "issueStatusTodo": "string",
  "name": "string",
  "productionPattern": "string",
  "refdiff": {},
  "updatedAt": "string"
}
```

Instead, the endpoint always returns a 400 error w/ the result:
  
```
{
  "code": 0,
  "success": false,
  "message": "missing path variable scopeConfigId (400)",
  "causes": null,
  "data": null
}
```

### How to reproduce

Call the GET endpoint /plugins/jira/connections/{connectionId}/scope-configs/{id} using curl or the swagger UI

```
curl -X 'GET' 'http://localhost:8080/api/plugins/bitbucket/connections/1/scope-configs/2' -H 'accept: application/json'
```

(Note that the connection id (1 above) and scope-config id (2 above) must exist.)

### Anything else

This occurs every time the endpoint is called.

### Version

v1.0.0-beta8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Fixed by #7498
