### ISSUE TITLE
[Bug][Scope Config] Only the first 10 items are inheriting the scope config

### ISSUE THREAD

**Issue by slaterx** [apache/devlake#7503]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Created a new project, added 100 data scopes from existing github connection in it:

![image](https://github.com/apache/incubator-devlake/assets/15024405/f27d79ae-4915-4fc7-85a3-85018c92b06f)

However, only the first 10 are inheriting the scope config, all other 90 are showing N/A for scope config:

![image](https://github.com/apache/incubator-devlake/assets/15024405/8f5845b5-261c-456d-a82f-f461d6e38f30)

### What do you expect to happen

All scopes have a valid scope config in it

### How to reproduce

- Add a github connection with lots of repo (ours have more than 1000)
- Add a scope config to add repos in the connection
- Create new project
- Add 100 repos to the data scope

### Anything else

We're troubleshooting why we are not seeing any numbers/data in DORA grafana charts, and we arrived at this situation.

### Version

1.0.0-beta6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Can you share screenshots of the connection detail page for those scopes that are NOT inheriting scope config?

**Comment by slaterx** [comment]
@klesh it's all in the same connection, not a new one. Installation has only one project with only one connection in it. And all repos in it have a configured scope in it.
