### ISSUE TITLE
[Bug][Blueprints] 400 error when adding Azure DevOps scope to existing project

### ISSUE THREAD

**Issue by slaterx** [apache/devlake#7504]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

On a project with an existing github connection (such as #7503), adding an Azure DevOps connection to it gives a 400 error in the UI:

![image](https://github.com/apache/incubator-devlake/assets/15024405/2f4a51f5-4457-450c-b68b-54f992c22526)

Inside lake microservice container, the error is the below:

```
time="2024-05-24 12:40:03" level=error msg="HTTP 400 error\n\tcaused by: error patching the blueprint (400)\n\tWraps: (2)\n\tWraps: (3) fork/exec ./run.sh: argument list too long\n\tWraps: (4) fork/exec ./run.sh\n\tWraps: (5) argument list too long\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *fs.PathError (5) syscall.Errno"
[GIN] 2024/05/24 - 12:40:03 | 400 | 4.889660007s | 10.253.240.52 | PATCH "/blueprints/2"
```

### What do you expect to happen

AzureDevops scopes are added to existing project.

### How to reproduce

- Create a project
- Successfully add data scopes from GitHub
- Try to add Azure DevOps scopes

### Anything else

Same environment where #7503 is happening.

### Version

1.0.0-beta6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Would you like to try the `AzureDevopsGo` plugin? It is more robust and actively maintained by @mr-ks

**Comment by slaterx** [comment]
Will do! What's the difference between the two?

**Comment by slaterx** [comment]
@klesh somehow the repos I can see in the python plugin are not showing up in the go plugin.

**Comment by klesh** [comment]
Oh, I see. What is the different between those repos? loop @mr-ks

**Comment by mr-ks** [comment]
@slaterx, the two plugins use different database tables, did you manage to successfully create the connection in the go plugin?

One important distinction is that the Go version excludes disabled repositories. Is this possibly why you're not seeing some repositories?

https://github.com/apache/incubator-devlake/blob/288c01e3c7b86a0f5beb3e073320ebb69d4f206b/backend/plugins/azuredevops_go/api/remote_helper.go#L150-L155

**Comment by slaterx** [comment]
@mr-ks thank you for explaining the distinction, indeed the difference comes from the disabled repos showing up on the python plugin. 

In Azure DevOps land, a disabled repo means that only the source code is unavailable. Pipelines, boards and other items might still be available and actively used by teams (which is our case).

**Comment by mr-ks** [comment]
Sounds good. I'll re-enable disabled repositories but exclude them from tasks of the `code` domain. I think pr‘s and such are not available for disabled repos. What do you think @klesh, @slaterx
