### ISSUE TITLE
[Question][Module Name] getting "ERROR: Service 'devlake' failed to build: failed to parse platform : "" is an invalid component of      "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument"

### ISSUE THREAD

**Issue by chrisolido** [apache/devlake#7512]
## Question
I am getting "ERROR: Service 'devlake' failed to build: failed to parse platform : "" is an invalid component of      "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument"

## Screenshots

---
[root@ip-172-27-0-126 incubator-devlake]# docker-compose up -d
WARNING: The HTTPS_PROXY variable is not set. Defaulting to a blank string.
WARNING: The GOPROXY variable is not set. Defaulting to a blank string.
Building devlake
Step 1/61 : FROM --platform=linux/amd64 debian:bullseye as debian-amd64
 ---> 53ceee7f0775
Step 2/61 : RUN apt-get update
 ---> Using cache
 ---> 73ff9bf8541c
Step 3/61 : RUN apt-get install -y libssh2-1-dev libssl-dev zlib1g-dev
 ---> Using cache
 ---> 8fd20c10b506
Step 4/61 : FROM --platform=linux/arm64 debian:bullseye as debian-arm64
 ---> 53ceee7f0775
Step 5/61 : RUN apt-get update
 ---> Using cache
 ---> 73ff9bf8541c
Step 6/61 : RUN apt-get install -y libssh2-1-dev libssl-dev zlib1g-dev
 ---> Using cache
 ---> 8fd20c10b506
Step 7/61 : FROM --platform=$BUILDPLATFORM golang:1.20.4-bullseye as builder
ERROR: Service 'devlake' failed to build: failed to parse platform : "" is an invalid component of      "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
[root@ip-172-27-0-126 incubator-devlake]# vi .env
[root@ip-172-27-0-126 incubator-devlake]# uname -a
Linux ip-172-27-0-126.ap-southeast-1.compute.internal 5.10.216-204.855.amzn2.x86_64 #1 SMP Sat May      4 16:53:27 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
[root@ip-172-27-0-126 incubator-devlake]#

---
## Additional context
I am installing from amz2 ec2. New installation.

**Comment by chrisolido** [comment]
I have check my docker-compose.yml and it does not have "platform: linux/x86_64"

`# limitations under the License.
#
version: "3"
services:
  mysql:
    image: mysql:8
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --skip-log-bin

  postgres:
    image: postgres:14.2
    volumes:
      - postgres-storage:/var/lib/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lake
      POSTGRES_USER: merico
      POSTGRES_PASSWORD: merico
      TZ: UTC

  grafana:
    image: devlake.docker.scarf.sh/apache/devlake-dashboard:latest
    build:
      context: grafana/
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:4000/grafana"
      GF_USERS_DEFAULT_THEME: "light"
      MYSQL_URL: mysql:3306
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    restart: always
    depends_on:
      - mysql

E486: Pattern not found: platform      `

**Comment by klesh** [comment]
Hi, I think you used the wrong `docker-compose` file.
1. where did you get the `docker-compose.yml` file?
2. what is the full content of your `docker-compose.yml` file?

**Comment by chrisolido** [comment]
Hi Klesh,

Thanks for answering i got it from the repo :

`incubator-devlake]# git remote -v
origin  https://github.com/apache/incubator-devlake.git (fetch)
origin  https://github.com/apache/incubator-devlake.git (push)
`

**Comment by klesh** [comment]
@chrisolido It doesn't make sense, there is no `docker-compose.yml` file in the repo root folder, only `docker-compose-dev.yml` for developers, and `docker-compose up -d` won't take it as the input file unless you passed the option `-f docker-compose-dev.yml` . So, what exactly did you do? I would guess that you renamed the file, but I could never be sure of it. for others to help you, please be specific, it is hard to help without knowing what happened. 😂

If and only if my assumption was correct, you may consider: 
1. download the `docker-compose.yml` from the release page
![image](https://github.com/apache/incubator-devlake/assets/61080/f6cc3ab3-93b4-48cc-b81f-ef5971c34d85)
2. Or use the one located in the `devops/releases` folder.

**Comment by chrisolido** [comment]
I followed the documentation and did renamed the file. let me download the file in release page thank you for your help :D

**Comment by chrisolido** [comment]
It looks like i got it working thanks Klesh. I download the files from the release /devops/ folder. Thats fixed the issue. Thank you!

**Comment by klesh** [comment]
@chrisolido Which documentation did you follow? It needs to be updated I believe.

**Comment by chrisolido** [comment]
I use chatgpt so not sure where in your current docu was it..

I do have another issue .

I cant see it in public:

`[root@ip-172-27-0-126 staging]# docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS          PORTS                                       NAMES
9f25ffb803ab   mericodev/config-ui:v0.9.0   "/docker-entrypoint.…"   56 minutes ago   Up 31 minutes   443/tcp, 127.0.0.1:4000->80/tcp             staging_config-ui_1
9f80ba6968bf   mericodev/grafana:v0.9.0     "/run.sh"                56 minutes ago   Up 31 minutes   0.0.0.0:3002->3000/tcp, :::3002->3000/tcp   staging_grafana_1
5397c2526f16   mericodev/lake:v0.9.0        "lake"                   56 minutes ago   Up 31 minutes   127.0.0.1:8080->8080/tcp                    staging_devlake_1
fd5895c8de18   mysql:8.0.26                 "docker-entrypoint.s…"   56 minutes ago   Up 31 minutes   127.0.0.1:3306->3306/tcp, 33060/tcp         staging_mysql_1
[root@ip-172-27-0-126 staging]#
`

I have my security group allow eveything i can telnet to port 22, have added 4000, 443 in iptables still not able to see the UI. Im using amazon ec2.

**Comment by chrisolido** [comment]
fix already change the config-ui to 0.0.0.0. How to run this with ssl?

**Comment by chrisolido** [comment]
And also with the latest release i see a different UI compare with the docs in the website
latest release : red UI with only four
in the docs: blue with many options

What I am missing here?
