### ISSUE TITLE
[Question][Module Name] cant connect to Jira

### ISSUE THREAD

**Issue by chrisolido** [apache/devlake#7521]
## Question
I am trying to connect to my JIRA cloud and its always failing when testing and and run the pipeline to sync failed to get server info
![image](https://github.com/apache/incubator-devlake/assets/343307/47ab1d43-57c4-4e2d-9f88-86696b44e53c)

please help what i am doing wring here? (Newbie)

## Screenshots
![image](https://github.com/apache/incubator-devlake/assets/343307/5de3611d-a38e-4b5a-9441-d2219f903ad2)
Telling me its failing.

reason is this.
![image](https://github.com/apache/incubator-devlake/assets/343307/d3b61e6d-67e1-40de-94a0-1627d1332737)

## Additional context
Add any other context here.

**Comment by klesh** [comment]
Try adding `/rest` suffix to your endpoint.
