### ISSUE TITLE
[Question][Module Name] Gitextractor cant clone repos from gitlab

### ISSUE THREAD

**Issue by claudious05** [apache/devlake#7524]
## Question
Im trying to collect data from gitlab, im running devlake(v0.21.0@ac4f7fe) using docker compose. The data collection pipeline fails everytime at the gitextractor job and i get this error:

**_github.com/apache/incubator-devlake/core/runner.runSubtask | /app/core/runner/run_task.go:332 | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks | /app/core/runner/run_task.go:273 | github.com/apache/incubator-devlake/core/runner.RunPluginTask | /app/core/runner/run_task.go:159 | github.com/apache/incubator-devlake/core/runner.RunTask | /app/core/runner/run_task.go:133 | github.com/apache/incubator-devlake/server/services.runTaskStandalone | /app/server/services/task_runner.go:113 | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1 | /app/server/services/task.go:186 | runtime.goexit | /usr/local/go/src/runtime/asm_amd64.s:1598 Wraps: (4) plain clone git error Wraps: (5) plain clone git error Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *errors.errorString_**

I really apreciate some help.

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Our Gitlab is running On premise, we tried to mount the CA Certificate into the devcontainer but unfortunately nothing changed.

**Comment by claudious05** [comment]
In which file is the shallow clone option located?

**Comment by claudious05** [comment]
can't I just enable it disable it using the .env file or a environment setting?

**Comment by klesh** [comment]
@claudious05 This seems like another issue to me, please file a new issue if the problem persists.
