### ISSUE TITLE
[Bug][Jira] A issue has been deleted in Jira，but devlake didnot delete it in devlake mysql，so when execute config-ui collect data ,the issue still exist

### ISSUE THREAD

**Issue by Challen-V** [apache/devlake#7534]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Devlake seems not sync Jira issue  status

### What do you expect to happen

devlake sync the deleted issue status

### How to reproduce

Delete a issue in Jira，then execute collect in config-ui，see the data in Grafana

### Version

v0.21.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Try this: 
![Uploading image.png…]()
