### ISSUE TITLE
[Bug][AzureDevOpsPlugin] Unauthorized request

### ISSUE THREAD

**Issue by ajayesf** [apache/devlake#7535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Getting the below error while connecting to Azure devops Projects.

remote error response: | Traceback (most recent call last): | File "/app/python/plugins/azuredevops/azuredevops/main.py", line 157, in <module> 
| AzureDevOpsPlugin.start() | File "/app/python/pydevlake/pydevlake/plugin.py", line 254, in start | fire.Fire(PluginCommands(plugin)) | File 
"/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire | component_trace = _
Fire(component, args, parsed_flag_args, context, name) | File "/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py", 
line 466, in _Fire | component, remaining_args = _CallAndUpdateTrace( | File "/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py",
 line 681, in _CallAndUpdateTrace | component = fn(*varargs, **kwargs) | File "/app/python/pydevlake/pydevlake/ipc.py", line 62, in wrapper | for each in ret: | File
 "/app/python/pydevlake/pydevlake/ipc.py", line 114, in remote_scopes | yield from self._plugin.make_remote_scopes(c, group_id) | File "/app/python/pydevlake/pydevlake/plugin.py",
 line 117, in make_remote_scopes | for tool_scope in self.remote_scopes(connection, group_id): | File "/app/python/plugins/azuredevops/azuredevops/main.py", line 104, 
 in remote_scopes | res = api.external_repositories(org, proj, provider, endpoint['id']) | File "/app/python/plugins/azuredevops/azuredevops/api.py", line 92,
 in external_repositories | return self.get(org, project, '_apis/sourceProviders', provider, 'repositories', serviceEndpointId=endpoint_id) | File
 "/app/python/pydevlake/pydevlake/api.py", line 154, in get | resp = self.send(req) | File "/app/python/pydevlake/pydevlake/api.py", line 136, in send
 | response = self._apply_hooks(response, self.response_hooks()) | File "/app/python/pydevlake/pydevlake/api.py", line 142, in _apply_hooks | result =
 hook.apply(target, self) | File "/app/python/pydevlake/pydevlake/api.py", line 203, in apply | return self.fn(api, response) | File "
 /app/python/pydevlake/pydevlake/api.py", line 342, in handle_error | raise APIException(response) | pydevlake.api.APIException: APIException: 
 https://dev.azure.com/esf-somatus/CCA/_apis/sourceProviders/github/repositories?serviceEndpointId=1b82133a-1054-4310-9b11-d6c9b3427ba3&api-version=7.0: 
 400 body: b'{"$id":"1","innerException":null,"message":"Unauthorized request. GitHub returned the error: \'Bad credentials\'","typeName":"Microsoft.TeamFoundation.Bui
 ld.WebApi.ExternalSourceProviderException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"ExternalSourceProviderException","errorCode":0,"eventId":3000}' Wraps: (2
 ) exit status 1 Wraps: (3) exit status 1 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *exec.ExitError
 

### What do you expect to happen

As I am having the oraganization Admin and all reuired access to the project. All repos should be loaded properly

### How to reproduce

After creating a connection. when trying to add new scope the issue is happening.

In the screenshot, higlited the projects having issues. Which is also grayed out

![image](https://github.com/apache/incubator-devlake/assets/158130029/b8cf0e5c-1e16-4468-a58a-b0dd1c046a07)

### Anything else

Every time I add a new scope to the conection

### Version

v1.0.beta

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ajayesf** [comment]
Hey Thanks for the comment. I have verified that the PAT is configured properly. I am able to load the other Projects in the same organization which is having same access as the projects having issues. As I am have the project Admin access, i dont see any reason to get unauherized acceess to selected projects.Please help on this

**Comment by ajayesf** [comment]
The PAT has full access and set to access All accessible organizations. May I know how to enable the logging and the to check the logs?
Even I verified the specific project access and which is similar to the once it is working.

**Comment by ajayesf** [comment]
Please see the abovew comments  @dosu.

**Comment by klesh** [comment]
@ajayesf Would you like to try the Go version and see if it works for you.

**Comment by ajayesf** [comment]
@klesh I was able to resolve this issue. There were few invalid  github service connections availble . Whn I deleted the unused one, I am able to configure the projects now. Thank you so uch for your support
