### ISSUE TITLE
[Feature][Keycloak] Can't add SSO in Apache Devlake.  

### ISSUE THREAD

**Issue by vanshita12345** [apache/devlake#7539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

The Apache Devlake currently operates without any authentication. I aim to incorporate Single Sign-On (SSO) for enhanced security and user experience.

### Description

I propose integrating SSO functionality into Apache DevLake to bolster security and streamline user authentication processes. This feature would enable users to access DevLake seamlessly with their existing credentials, enhancing usability and security simultaneously.

### Related issues

While there have been similar requests in the past, they have become inactive and subsequently closed due to inactivity. References: #5140, #5127, #5353, #5389, #5389.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pimperator** [comment]
I am also very interested in having an sso solution available
