### ISSUE TITLE
[Feature][Convertor] Add data processing for Issue tracking to compute issue status and assignee history

### ISSUE THREAD

**Issue by narrowizard** [apache/devlake#7542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

The new feature should enable the system to handle data processing tasks within the issue tracking domain. This includes calculating and maintaining records of issue statuses and the history of assignees in the respective tables issue_status_history and issue_assignee_history.

### Description

In order to enhance the transaction management capabilities of DevLake, there is a need to introduce a new data processing function. The goal is to develop tasks that can compute and store changes over time for issue statuses and assignee data.

- The issue_status_history table will hold records of all status changes for issues, including timestamps and the duration for how long each status was maintained.

- The issue_assignee_history table will track the history of assignees for each issue, documenting who was handling each issue at any point in time and for how long.

These tables will be critical for generating insights into the workflow of issues and how they are managed by different assignees over time. It will aid in historical analysis and improve transparency in issue tracking.

Please consider adding these capabilities to enhance the analytical power of DevLake and provide teams with in-depth tracking and metrics regarding issue handling and status transitions.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
That sounds great, it should be helpful in many cases.
