### ISSUE TITLE
[Bug][Config UI] I can still add an existing scope in AzureDevops 

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#7547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have an Azure DevOps connection and with some scopes configurated.
When I try to add a new scope and I found the scope that I have added before can be selected and submited again.
And I click submit button, it will return an error.
![image](https://github.com/apache/incubator-devlake/assets/5844806/6f1e3dc4-59d6-448f-9bfe-0138a46fb5c2)

### What do you expect to happen

These scopes which have been added before cannot be selected.

### How to reproduce

See `What happened` part.

### Anything else

None.

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Try the AzureDevopGo plugin.
