### ISSUE TITLE
[Bug][Module Name] my data doesnt show on the dashboard can someone help me please

### ISSUE THREAD

**Issue by DavidW1519** [apache/devlake#7549]
## Question
im havin trouble getting my data to show un the dashboard, the data connection was a success but when i go to dashboard is not showing anything

## Screenshots
![image](https://github.com/apache/incubator-devlake/assets/171082546/8c868ec0-2f2a-464c-bba6-d91acf30ccfb)
when i inspect im getting those error messages and i dont know what to do please and thanks for your help

**Comment by d4x1** [comment]
@DavidW1519  You can change this issue's type to bug, and provide more details about the version and your operations to help us reproduce it.

**Comment by DavidW1519** [comment]
how to reproduce:
- downloaded docker compose.yml and env.example from https://github.com/apache/incubator-devlake/releases ver 1.0.0 beta9
- generated the encryption key with openssl and put it on the file .env
- Run docker-compose up -d
- go to http://localhost:4000 did the tutorial to connect to github
- imported this https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel to my repository to make a test also made the token
- after the tutorial i went to dashboard and nothing is showing so i press f12 and found this error
- 
![image](https://github.com/apache/incubator-devlake/assets/171082546/03a3e540-5d93-4a30-b5c2-e33bcf0eee67)

also tried what dosubot said but still not working
-
