### ISSUE TITLE
[Bug][PagerDuty] not enough info for Pagerduty execution (400)

### ISSUE THREAD

**Issue by yoramshai** [apache/devlake#7561]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After upgrade to v1.0.0-beta9 PagerDuty tasks stopped to work? 
`error preparing task data for pagerduty (400) Wraps: (2) not enough info for Pagerduty execution (400) Error types: (1) *hintdetail.withDetail (2) *errors.errorString`

### What do you expect to happen

Pipeline will be completed

### How to reproduce

In my case if was upgrade from v1.0.0-beta6 --> v1.0.0-beta9

### Version

v1.0.0-beta9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, can you share the  `plan` detail of the failed pipeline?
![image](https://github.com/apache/incubator-devlake/assets/61080/27ab3dc6-d0f6-4c84-bd9b-b67e56bdc798)

**Comment by yoramshai** [comment]
@klesh absolutely  
`{
  "id": 632,
  "name": "foo-Blueprint",
  "plan": [
    [
      {
        "plugin": "org",
        "subtasks": [
          "setProjectMapping"
        ],
        "options": {
          "projectMappings": [
            {
              "projectName": "foo",
              "scopes": [
                {
                  "rowId": "github:GithubRepo:1:569576293",
                  "table": "repos"
                },
                {
                  "rowId": "github:GithubRepo:1:569576293",
                  "table": "cicd_scopes"
                },
                {
                  "rowId": "github:GithubRepo:1:569576293",
                  "table": "boards"
                },
                {
                  "rowId": "pagerduty:Service:1:P5GD7S8",
                  "table": "cicd_scopes"
                },
                {
                  "rowId": "webhook:27",
                  "table": "cicd_scopes"
                },
                {
                  "rowId": "webhook:27",
                  "table": "boards"
                }
              ]
            }
          ]
        }
      }
    ],
    [
      {
        "plugin": "github_graphql",
        "subtasks": [
          "Collect Milestones",
          "Extract Milestones",
          "Collect Issues",
          "Extract Issues",
          "Collect Pull Requests",
          "Extract Pull Requests",
          "Collect Workflow Runs",
          "Extract Workflow Runs",
          "Collect Job Runs",
          "Extract Jobs",
          "Collect Comments",
          "Extract Comments",
          "Collect Events",
          "Extract Events",
          "Collect PR Review Comments",
          "Extract PR Review Comments",
          "Collect Users",
          "Extract Users",
          "Convert Workflow Runs",
          "Convert Jobs",
          "Enrich PR Issues",
          "Convert Repos",
          "Convert Issues",
          "Convert Issue Labels",
          "Convert PR Commits",
          "Convert Pull Requests",
          "Convert PR Reviews",
          "Convert PR Labels",
          "Convert PR Issues",
          "Convert Issue Assignees",
          "Convert Issue Comments",
          "Convert PR Comments",
          "Convert Milestones",
          "Convert Users",
          "Collect Deployments",
          "Extract Deployments",
          "Convert Deployments",
          "Collect Releases",
          "Extract Releases",
          "Convert Releases"
        ],
        "options": {
          "connectionId": 1,
          "fullName": "bar/foo",
          "githubId": 569576293,
          "name": "bar/foo"
        }
      },
      {
        "plugin": "gitextractor",
        "subtasks": null,
        "options": {
          "fullName": "bar/foo",
          "name": "bar/foo",
          "proxy": "",
          "repoId": "github:GithubRepo:1:569576293",
          "url": "https://git:****************************************@github.com/bar/foo.git"
        }
      },
      {
        "plugin": "pagerduty",
        "subtasks": [
          "collectIncidents",
          "extractIncidents",
          "convertIncidents",
          "convertServices"
        ],
        "options": {
          "connectionId": 1,
          "serviceId": "P5G****"
        }
      }
    ],
    [
      {
        "plugin": "dora",
        "subtasks": [
          "generateDeployments",
          "generateDeploymentCommits",
          "enrichPrevSuccessDeploymentCommits"
        ],
        "options": {
          "projectName": "foo"
        }
      }
    ],
    [
      {
        "plugin": "refdiff",
        "subtasks": [
          "calculateDeploymentCommitsDiff"
        ],
        "options": {
          "projectName": "foo"
        }
      }
    ],
    [
      {
        "plugin": "dora",
        "subtasks": [
          "calculateChangeLeadTime",
          "ConnectIncidentToDeployment"
        ],
        "options": {
          "projectName": "foo"
        }
      }
    ]
  ],
  "skipOnFail": true
}`
