### ISSUE TITLE
[Bug][Module Name] AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by kzhou57** [apache/devlake#7562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

It works very well, until today, when I access the projects page, I got this error : 

AxiosError: Request failed with status code 500

And on grafana , my dora dashboard shows no data and some errors like : 

Templating [project]
Error updating options: error when executing the sql query

### What do you expect to happen

The project pages loads, and grafana shows my dora dashboard. 

### How to reproduce

I don't how. 

### Version

Latest, I assume, we install it last month

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Please check if your database system is up and running.
