### ISSUE TITLE
[Bug][CircleCI] CircleCI regex is not working to collect data

### ISSUE THREAD

**Issue by chrisolido** [apache/devlake#7563]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When configuring the scope config the regex is not working

![image](https://github.com/apache/incubator-devlake/assets/343307/2e5ffbb4-5ac0-42c3-b292-2bf0469073b0)

### What do you expect to happen

It should collect data and show in DORA metrics.

### How to reproduce

Go to - project - connections - scope config - transformations 

![image](https://github.com/apache/incubator-devlake/assets/343307/d71fd0c0-7637-4e9e-a972-6a70e0b32068)

No data collected when run.
![image](https://github.com/apache/incubator-devlake/assets/343307/5aa9785f-61f6-4e25-a14b-a6c89c5fd30d)

### Anything else

This is present since the installation.

### Version

v0.21.0@ac4f7fe

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Hi, can you check if there is any records in the `cicd_pipelines` and `cicd_deployments` tables?

**Comment by klesh** [comment]
It seems to working fine on my local machine:

![image](https://github.com/apache/incubator-devlake/assets/61080/6e539854-8e24-4750-9236-1faac3a64246)

![image](https://github.com/apache/incubator-devlake/assets/61080/b9503e34-3de7-489a-b4d7-34b702970c16)
