### ISSUE TITLE
[Bug][SonarQube] subtask convertIssueCodeBlocks ended unexpectedly

### ISSUE THREAD

**Issue by klemen-df** [apache/devlake#7586]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

when running scraping I get this error:

`subtask convertIssueCodeBlocks ended unexpectedly Wraps: (2) error adding result to batch (500) Wraps: (3) Error 1406 (22001): Data too long for column 'component' at row 209 (500) Wraps: (4) Error 1406 (22001): Data too long for column 'component' at row 209 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError`

### What do you expect to happen

The process should end without an error.

### How to reproduce

Add SonarQube project and run.

### Version

v1.0.0-beta10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klemen-df** [comment]
hi @klesh , anything new here?

**Comment by klesh** [comment]
Hi, @klemen-df we are short of hands, might take a look at the problem in a couple of weeks.
