### ISSUE TITLE
[Bug][Sonarqube] data too long

### ISSUE THREAD

**Issue by irkhamdayat** [apache/devlake#7593]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When running collect data sonarqube i am getting error that "data too long for column name. when i check in the mysql table column name varchar was 500
<img width="568" alt="sonarqube_connections" src="https://github.com/apache/incubator-devlake/assets/26671338/de4873da-c54a-40f8-bb6b-a9e3fed846ed">
<img width="640" alt="sonarqube_scope_configs" src="https://github.com/apache/incubator-devlake/assets/26671338/0e0ad19e-128f-4cab-afa2-c97cb1c3391d">

<img width="686" alt="devlake-failure" src="https://github.com/apache/incubator-devlake/assets/26671338/1832673c-e989-4be3-837a-62ec5a237ce2">

<img width="946" alt="select-devlake" src="https://github.com/apache/incubator-devlake/assets/26671338/7a75778a-6548-45b3-aa15-4f415df851a2">

### What do you expect to happen

The process should end without an error.

### How to reproduce

Add SonarQube project and run.

### Version

v0.21.0@ac4f7fe

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by irkhamdayat** [comment]
i was increase the lenght of the name, still get error

**Comment by d4x1** [comment]
@irkhamdayat  I think it's `name` field in table `_tool_sonarqube_accounts`.

Can you check the actual length of account names in your SonarQube ?

**Comment by irkhamhidayat** [comment]
my lenght of account names in _tool_sonarqube_accounts is 
![WhatsApp Image 2024-06-12 at 14 14 09](https://github.com/apache/incubator-devlake/assets/77187192/02d3b7fe-612b-49b2-ab73-1afc12f9bb4b)

**Comment by d4x1** [comment]
@irkhamdayat  I mean the username's length in sonarqube, not in devlake's database.
We should change database's fields according to the real name's length.

**Comment by abeizn** [comment]
@irkhamhidayat You can try changing the 'name' field in the '_tool_sonarqube_accounts' table and the 'full_name' field in the 'accounts' table to 'text' type, and then try again. It seems you have some dirty data or very special data that is causing the 'name' field to be too long. We apologize, but we can't indefinitely expand the field length to accommodate all possible data, as no other users have encountered the same issue. So, we can only trouble you to make this temporary change for now.
