### ISSUE TITLE
[Bug][opsgenie] Testing API Key not working

### ISSUE THREAD

**Issue by guilhem** [apache/devlake#7596]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Testing API Key with the right rights is failing with:
![image](https://github.com/apache/incubator-devlake/assets/486876/e2b1f859-7b09-49d4-8b27-47f043428181)

### What do you expect to happen

Testing ok.

### How to reproduce

Add a key with read and Configuration Access rights

### Version

v1.0.0-beta10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
So... What rights did you grant for the key?
