### ISSUE TITLE
[Bug][Jenkins] MavenModuleSet should be treated as a scope 

### ISSUE THREAD

**Issue by sstojak1** [apache/devlake#7598]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The logic for categorizing Devlake Remote Scopes has [changed](https://github.com/apache/incubator-devlake/pull/7213/files#diff-ef2d9899f5788356b03b7c5c1320ad5bb7e78aa63047d202cde86ed1360bd7ab) in version v1.0.0-beta5. Previously, the default category was "scope," but now it is "group." This change has led to issues, such as `hudson.maven.MavenModuleSet` Jenkins project type being treated as a group instead of a scope. As a result, you cannot add a new Devlake Remote Scope because it's incorrectly categorized as a group.

### What do you expect to happen

I expect that `hudson.maven.MavenModuleSet` Jenkins project is not categorized as group by Devlake

### How to reproduce

Create a new Maven Project in Jenkins and try to add it through Devlake:
![image](https://github.com/apache/incubator-devlake/assets/18380216/2c20479d-7e14-4ec5-be83-f8b60ba6f6a5)

### Version

v1.0.0-beta11

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Lovely

**Comment by klesh** [comment]
I like the report-and-fix vibe here. 👍
