### ISSUE TITLE
[Bug][Bitbucket Server] Activities collector fails when PR is corrupt 

### ISSUE THREAD

**Issue by sstojak1** [apache/devlake#7601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Bitbucket Server data collection task fails because one pull request is corrupted. Error that Devlake throws:
`  | 	Retry exceeded 3 times calling rest/api/1.0/projects/{projectKey}/repos/{repoName}/pull-requests/{pullRequestId}/activities. The last error was: Http DoAsync error calling [method:GET path:rest/api/1.0/projects/{projectKey}/repos/{repoName}/pull-requests/{pullRequestId}/activities query:map[limit:[100] state:[all]]]. Response: {"errors":[{"context":null,"message":"'git update-ref --stdin -z --no-deref' exited with code 128 saying: fatal: cannot update ref 'stash-refs/pull-requests/{pullRequestId}/from': trying to write ref 'stash-refs/pull-requests/{pullRequestId}/from' with nonexistent object {commitSHA}","exceptionName":"com.atlassian.bitbucket.scm.CommandFailedException"}]} (500)
`

### What do you expect to happen

I think it would make sense for the data collection to continue even if one pull request is corrupted since we don't want to lose all of those Bitbucket metrics for the repository.

### How to reproduce

We have this kind of a state in our env. Not sure how to reproduce.

### Version

v1.0.0-beta11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sstojak1** [comment]
this is similar to [7258](https://github.com/apache/incubator-devlake/issues/7258)

**Comment by klesh** [comment]
I believe it is fixed already, will be available in coming `rc` version which should be ready in a couple of days.

**Comment by sstojak1** [comment]
@d4x1 This option is already on for all our projects.
Here a single task is falling since one PR is corrupt in Bitbucket. As a result, other repository information won't be collected.

@klesh 
Are you referring to [7577](https://github.com/apache/incubator-devlake/pull/7577)? 
7577 is connected with PR commits and it's handling 40X error status. This error is with 500 status and it's connected with PR activities.
If it's ok, we can do it like @abeizn did for commits but handle 500 + body message - `com.atlassian.bitbucket.scm.CommandFailedException`?
What do you think?
![image](https://github.com/apache/incubator-devlake/assets/18380216/bd37291e-183c-4f95-8572-e33a0e6b6389)

**Comment by klesh** [comment]
Ahh.. 500 errors? I am not sure, 500 represents Server Internal Errors, It might suggest that the server is corrupted or down, in this case, it is hard to say if it is appropriate to skip the PR.
It makes more sense to fix the 500 errors on the bitbucket server rather than ignoring them on the devlake end.

**Comment by sstojak1** [comment]
You're correct. Deciding whether to skip something based on the message content will be challenging. Resolving the ticket...
