### ISSUE TITLE
[Question][REST API] I can't find a way to attach Connection to DevLake Project.

### ISSUE THREAD

**Issue by kamiyariko** [apache/devlake#7610]
I successfully created a DevLake project and my GitLab connection using the following APIs:
POST: /projects
POST: /plugins/gitlab/connections

Now, I'm trying to attach the connection to the project, but I couldn't figure out which API to use from the manual and Swagger documentation. Could someone tell me which API I should use?

**Comment by kamiyariko** [comment]
curl -X 'POST' \
  'https://***/api/plugins/gitlab/test' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "endpoint": "https://***/api/v4/",
  "proxy": "string",
  "rateLimitPerHour": 0,
  "token": "***"
}'

{"code":0,"success":true,"message":"success","causes":null,"data":null,"Connection":{"endpoint":"https://***/api/v4/","proxy":"string","rateLimitPerHour":0,"token":"**********************"}}


The command you executed returned the following result, but no connection was attached to the project.

We want to configure settings using the API instead of the GUI.
Have such features been implemented or will be implemented?

**Comment by d4x1** [comment]
@kamiyariko 

To attach a connection to an existing project, I think these stes are neccessary:
1. create a `blueprint` via `{api}/blueprints` in your project, get a `blueprint_id`.
2. post your connection to projects via `{api}/blueprints/{blueprint_id}`, because `blueprint_id` is belongs to your project, so connections can be added successfully.

You can view the payload using browser's dev tools.

**Comment by kamiyariko** [comment]
@dosu
I tried it, but it returned 404.
Sorry, I forgot to mention the version.
We use v1.0.0-beta10.

**Comment by d4x1** [comment]
@kamiyariko  dosu is a bot, you can try my advice.

**Comment by jensrotne** [comment]
I just had the same issue when I tried to POST a new project, and it seems to me like a bug in the projects API endpoint

As @d4x1 said, then you first need to create the project using the `POST /api/projects` endpoint, and then patch the blueprint afterwards with the `PATCH /api/blueprints/{blueprintId}` you get back from the POST request towards the projects endpoint.

**Comment by jensrotne** [comment]
@kamiyariko I haven't used gitlab before, but I'm pretty sure that the connection plugin name you put in is incorrect. I think it might needs to be Gitlab and not Gitextractor.

Additionally, nothing will happen before you put in the Blueprint plans.

**Comment by kamiyariko** [comment]
@jensrotne I changed the PluginName to "gitlab" and executed the command, but I encountered this error message.
`{"code":0,"success":false,"message":"error creating blueprint (400)\nWraps: (2)\nWraps: (3) *models.GitlabProject not found (404)\nWraps: (4) record not found (404)\nWraps: (5) record not found\nError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *hintdetail.withDetail (5) *errors.errorString","causes":["*models.GitlabProject not found (404)","record not found (404)"],"data":null}`
If I have already assigned existing scopeIds to the Connection, is there anything else I need to do? 

Should I write something in afterPlan and beforePlan? 
I just want to attach the Blueprint to projects that collect data from GitLab.

**Comment by jensrotne** [comment]
@kamiyariko one thing you could try is to create the Project and connections manually in the config-ui, and then use the `GET /api/blueprints/{blueprint_id}` endpoint to see how it should look.

That's at least what I did when I have to make my API integration.

**Comment by klesh** [comment]
You need to create the GitlabProject by calling [the PutScopes API](https://github.com/apache/incubator-devlake/blob/d01c71cda4287bfedfa1949d6b3d22d31e88c526/backend/plugins/gitlab/api/scope_api.go#L40) beforehand

**Comment by klesh** [comment]
I suggest that you use the `config-ui` to go through the whole setup process and observe what APIs were called.

**Comment by kamiyariko** [comment]
I tried the PutScopes API but it was just associating scope with scope-config.
```
curl -X 'PUT' \
  'https://xxxxx/api/plugins/gitlab/connections/5/scopes' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "data": [
    {
      "archived": true,
      "connectionId": 5,
      "creatorId": 0,
      "defaultBranch": "string",
      "description": "string",
      "forkedFromProjectId": 0,
      "forkedFromProjectWebUrl": "string",
      "gitlabId": 3,
      "httpUrlToRepo": "string",
      "name": "string",
      "openIssuesCount": 0,
      "pathWithNamespace": "string",
      "scopeConfigId": 4,
      "starCount": 0,
      "visibility": "string",
      "webUrl": "string"
    }
  ]
}'
```
"Thank you for your support. 
Since @jensrotne has created a bug ticket, let's continue the discussion there. I will close this question now.
