### ISSUE TITLE
[Feature][Sentry]New Data Sources

### ISSUE THREAD

**Issue by jcoste-ied** [apache/devlake#7626]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a DevOps engineer, I want to integrate Sentry with DevLake so that I can monitor and manage application errors and performance issues directly within DevLake. This integration will help streamline our workflows, reduce the need to switch between multiple tools, and provide a more comprehensive view of our DevOps pipeline. Ultimately, this will improve the observability and reliability of our applications.

### Description

I propose adding an integration with Sentry, a popular open-source error tracking tool, to DevLake. This feature would allow users to:

- Centralized Monitoring: Monitor and manage errors from Sentry within DevLake, reducing the need to switch between multiple tools.
- Enhanced Data Correlation: Correlate Sentry error data with other metrics and logs collected by DevLake for more thorough analysis and troubleshooting.
- Automated Alerts: Set up automated alerts in DevLake based on Sentry error thresholds, allowing for quicker responses to critical issues.
- Improved Workflow Efficiency: Streamline DevOps workflows by integrating error tracking directly into the pipeline management tool.

This integration will enhance DevLake’s capabilities as a comprehensive DevOps tool and provide significant value to its users.

Thank you for considering this request. I am happy to provide any further details or assist in any way needed to implement this feature.

Regards,
Jérome

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Collecting votes.

**Comment by xlmnxp** [comment]
I need this feature

**Comment by bidhanbaruah** [comment]
I need this feature

**Comment by iautushka** [comment]
Need this feature as well.

**Comment by dlotthtx** [comment]
Would love this feature
