### ISSUE TITLE
[Bug][SonarQube] Plugin not work with a bearer token

### ISSUE THREAD

**Issue by emschimmel** [apache/devlake#7638]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We are using a hosted version of SonarQube (not cloud). I have an admin token. 
Using the api endpoints via Postman I have to use the Bearer keyword for authentication.
example: `Authorization: Bearer squ_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

### What do you expect to happen

Since we don't use a cloud version of SonarQube we did expect it to work. 

### How to reproduce

Using the test connection feature it gives a connection failed. Possibly because in the connection model in the SetupAuthentication method the keyword Basic is being used. and obviously the rest of the endpoints wont work either. 
I tryed to chance this to Bearer but no effect. When I inspect the request headers after the call I don't see the autorization header unless I add it twice (with obviously also does not result in a success response).

### Anything else

We tested multiple versions of Devlake.

### Version

v0.17.0-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by emschimmel** [comment]
That is the exact chance I made to try to fix it and didn't work.

**Comment by klesh** [comment]
1. What is the version of your SonarQube?
2. 0.17 is way too old, please upgrade to v1.0.0-rc1

**Comment by emschimmel** [comment]
Maybe it is to new in that case. The company bought it 2 weeks ago. So this is the version:
`Enterprise Edition v10.5.1`

**Comment by klesh** [comment]
I see, it is much newer than what we tested before.
But you can try the latest `v1.0.0-rc1` and see if it works for you first.
