### ISSUE TITLE
[Question][Jira] Service Project Type Support?

### ISSUE THREAD

**Issue by tc-jason-gregory** [apache/devlake#7641]
## Question
I'm not able to select projects in Jira Cloud that are "Service Project" type.  It appears DevLake can only see the "Software Project" type. My incidents are captured under the "Service Project" so I cannot connect them in to produce certain Dora metrics.  Is this something the application is intended to support?

**Comment by Startrekzky** [comment]
Hi, do you mean projects in the Jira Service Desk? They're not supported now. And we have no plan supporting them in the short term.

**Comment by tc-jason-gregory** [comment]
Yes, thanks.  I'll look for another means to get incidents into DevLake via the Software Project type as Service project type not intended to be supported. Appreciate your prompt response. Great project!!!!
