### ISSUE TITLE
[Bug][Projects] Projects API POST endpoint does not create blueprint connections

### ISSUE THREAD

**Issue by jensrotne** [apache/devlake#7650]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I try to create a new project with the `POST /api/projects` endpoint, then even if I include the `blueprint` field in the JSON body, then it doesn't correctly create the blueprint connections.

I was able to do a workaround where I create the project using the POST endpoint, fetch the blueprint ID from the response, and then use the `PATCH /api/blueprints/{blueprint_id}` to correctly set the connections.

### What do you expect to happen

I expect that when putting a complete Project payload with a Blueprint field, that it will fully create the blueprint and it's dependencies as well.

### How to reproduce

Create a new Project using the `POST /api/projects` endpoint with a a blueprint containing connections.

### Anything else

The following issue exists, but is not classified as a bug: https://github.com/apache/incubator-devlake/issues/7610

### Version

v1.0.0-rc1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Weird, it has been tested. Would you share your request in `curl` or any other executable format to reproduce the problem?

**Comment by klesh** [comment]
It should be working according to https://github.com/apache/incubator-devlake/pull/7449

**Comment by kamiyariko** [comment]
When attempting to create a new blueprint, I'm unable to proceed because I must specify the project name at that point. If I create the project first, the blueprint is automatically generated and attached to the project, preventing me from creating a blueprint specifically for that project afterward.

When trying to PATCH an existing blueprint, the Swagger API provided is:
```
curl -X 'PATCH' \
  'https://xxxxx/api/blueprints/{blueprint_id}' \
  -H 'accept: application/json'
```
However, this command does not allow me to specify which project to attach the blueprint to.

What is the purpose of the PATCH /blueprints/{blueprint_id} command? 
I need clarification on how to specify the project to which the blueprint should be attached.

**Comment by jensrotne** [comment]
@klesh I just did another test with the API using `v1.0.0-rc1`, and same issue on endpoint `POST /api/projects`

Example body:
```
{
  "name": "B2B3",
  "description": "",
  "metrics": [
    {
      "pluginName": "dora",
      "pluginOption": null,
      "enable": true
    }
  ],
  "blueprint": {
    "name": "B2B3-Blueprint",
    "projectName": "B2B3",
    "mode": "NORMAL",
    "plan": [
      "**REDACTED**"
    ],
    "enable": true,
    "cronConfig": "0 0 * * *",
    "isManual": false,
    "beforePlan": null,
    "afterPlan": null,
    "labels": [],
    "connections": [
      {
        "pluginName": "circleci",
        "connectionId": 2,
        "scopes": [
          {
            "scopeId": "1"
          },
          {
            "scopeId": "3"
          },
          {
            "scopeId": "4"
          }
        ]
      },
      {
        "pluginName": "github",
        "connectionId": 2,
        "scopes": [
          "**REDACTED**"
        ]
      }
    ],
    "skipOnFail": false,
    "skipCollectors": false,
    "fullSync": false
  }
}
```

It created the project fine, but the blueprint is missing the connections. I was still able to patch it afterwards using the `PATCH /api/blueprints/{blueprint_id}` endpoint.

**Comment by jensrotne** [comment]
There are no errors in the backend container either. Just got this log entry: `lake time="2024-06-28 07:29:15" level=info msg="added blueprint 20 to cronjobs, cron id: 4, cron config: 0 0 * * *"`

**Comment by kamiyariko** [comment]
> When attempting to create a new blueprint, I'm unable to proceed because I must specify the project name at that point. If I create the project first, the blueprint is automatically generated and attached to the project, preventing me from creating a blueprint specifically for that project afterward.
> 
> When trying to PATCH an existing blueprint, the Swagger API provided is:
> 
> ```
> curl -X 'PATCH' \
>   'https://xxxxx/api/blueprints/{blueprint_id}' \
>   -H 'accept: application/json'
> ```
> 
> However, this command does not allow me to specify which project to attach the blueprint to.
> 
> What is the purpose of the PATCH /blueprints/{blueprint_id} command? I need clarification on how to specify the project to which the blueprint should be attached.

I have resolved the issue by including the request body in the PATCH /api/blueprints endpoint. 
Thank you for your assistance.
