### ISSUE TITLE
[Bug][Blueprints] Duplicate CircleCI scopes in same connection allowed

### ISSUE THREAD

**Issue by jensrotne** [apache/devlake#7653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I had an issue, where I was able to input the same CircleCI sco
pe identifier twice in the `connections` field of the blueprint. This causes the API to throw a 500 request, but the blueprint was still created and ended up in a bad state, where I had to manually delete it and try again.

![screenshot](https://github.com/apache/incubator-devlake/assets/91874767/1e8f8f21-b3e9-4a34-bf39-107589ae6adb)

### What do you expect to happen

To give me a 400 response telling me that I had a duplicate value in the connections scopes.

### How to reproduce

Adding a Blueprint with the something like the following connection plugin:

```
{
  "pluginName": "circleci",
  "connectionId": 2,
  "scopes": [
    {
      "scopeId": "1"
    },
    {
      "scopeId": "1"
    },
    {
      "scopeId": "3"
    },
    {
      "scopeId": "4"
    }
  ]
}

```

This will cause the API to throw an error.

### Version

v1.0.0-rc1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Sounds reasonable to me.
