### ISSUE TITLE
[Bug][Devlake] the devlake pipeline is partially success even after modifying the mysql with the utf8mb4 character and utf8mb4_bin collation

### ISSUE THREAD

**Issue by Puvendhan** [apache/devlake#7654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am getting the same error as mentioned the github issue https://github.com/apache/incubator-devlake/issues/7528.
I modified the mysql with the utf8mb4 character and utf8mb4_bin collation., however i am still seeing the error in the devlake pipeline that the pipeline is partially success.
![image](https://github.com/apache/incubator-devlake/assets/29087906/fe1c6559-afd5-4062-9194-3324d18f1a27)

Devlake is currently running on v1.0.0-beta11

### What do you expect to happen

The devlake pipeline should be fully success.

### How to reproduce

Just add a gitlab connection in the devlake ui and run the pipeline.

### Version

v1.0.0-beta11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Try re-creating the whole db instead?

**Comment by Puvendhan** [comment]
Hi , i am getting the below error after changing the charset to utf8mb3. kindly suggest

<img width="714" alt="Screenshot 2024-06-24 at 11 09 08" src="https://github.com/apache/incubator-devlake/assets/29087906/a7da4b32-8082-47ee-ab1e-e56daa9ad94f">

**Comment by klesh** [comment]
@Puvendhan Why would you change the charset to `utf8mb3`? It won't work if I recall correctly.
What did you expect to happen after doing so?
