### ISSUE TITLE
[Bug][DORA] Change failure rate regression 

### ISSUE THREAD

**Issue by yoramshai** [apache/devlake#7656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Data of Pagerduty is missing from the DORA board

### What do you expect to happen

See the data and the correct score of "Change Failure Rate" and "Failed Deployment Recovery Time"

### How to reproduce

On Dora dashboard, in some of the projects the data is missing even I'm able to see it in pagerduty dashboard.

### Anything else

Looks like a regression, When I'm checking the same thing on the latest stable release "v0.21.0" the data is there for the same project while it is missing on "v1.0.0-beta11" release.

see attachments, you can to see the missing data on the latest version compare to latest stable version (same data in the data base, created from a snapshot).

![image](https://github.com/apache/incubator-devlake/assets/11707803/3233d24e-b271-4c7a-9935-913733c95b66)
![image](https://github.com/apache/incubator-devlake/assets/11707803/d9a9ddf8-45cb-4f7c-b6a6-00bbbeafd0ee)

### Version

v1.0.0-beta11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
It appears to me that it is the `deployments` created by the `webhook` were missing and the incidents from `pagerduty` were there just fine.

**Comment by yoramshai** [comment]
Thanks @klesh; I will check this. 
Is it supposed to affect the historical data (i.e. May) ?

**Comment by klesh** [comment]
it should, data is recalculated on each run
