### ISSUE TITLE
[Doc][Developer Docs] Developer docs assume that users use git - they should also talk about source releases

### ISSUE THREAD

**Issue by pjfanning** [apache/devlake#7668]
## Documentation Scope
Developer docs assume that users use git - they should also talk about source releases

## Describe the Change
https://devlake.apache.org/docs/DeveloperManuals/DeveloperSetup/ should also describe how non-Git users can build the app.
The key release as far as ASF is concerened are the source releases. You need to facilitate users of these releases.

## Additional context
I am a PMC member of the Apache Incubator and I have to be able to build your app to review it.

**Comment by pjfanning** [comment]
I've given up trying to build the app. Too much time and too many errors that need to be worked through.

One of the errors that I get:
```
make dev
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by abeizn** [comment]
@pjfanning Thank you for your feedback. We will address this issue before the release of the next ASF version.

**Comment by Startrekzky** [comment]
Hi @pjfanning , could you check if this problem has been solved? Thanks.
