### ISSUE TITLE
[Question][GitHub] GitOps-like repos belonging to multiple projects.

### ISSUE THREAD

**Issue by jluque0101** [apache/devlake#7684]
## Question
I have a question regarding projects and shared repositories.

**Use Case:** I have two teams, Team A and Team B. Each team has its own repository, and they share a GitOps-like repository where they publish new releases for deployment.
The shared repository uses GitHub Actions (with different names depending on which files were updated) to track deployments. However, the regex used in scope-config should be different for each project because the action name to be tracked as a deployment is different for each team.

**Question:** Is there a way to associate multiple scope-configs for a repository depending on which project it is associated with? Alternatively, what is the best approach to handle this use case ?

**Comment by d4x1** [comment]
@jluque0101 You can set up two connections with different scope-configs to circumvent this issues.

**Comment by KyriosGN0** [comment]
i have also ran into this, @jluque0101, did you end up solving this ?

**Comment by jluque0101** [comment]
@KyriosGN0 not really, setting up 2 connections as @d4x1 suggested would imply that data is duplicated if I understand correctly.
