### ISSUE TITLE
Axios Error 504

### ISSUE THREAD

**Issue by kapptob** [apache/devlake#7687]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After Installing on my system using WSL Ubuntu and Helm, starting the Cluster with minikube and trying to access via kubectl port forwarding I get the following message:

AxiosError: Request failed with status code 504

I noticed following problem when running kubectl get pods:
NAME                                                 READY STATUS     RESTARTS     AGE
devlake-grafana-66fcd84bcb-wjsgn   0/1      Running   0                   4m21s
devlake-lake-7b6f7d647f-jdjvk           0/1      Running   1 (55s ago)   4m21s

After reinstalling:

NAME                                                READY STATUS   RESTARTS     AGE
devlake-lake-7455659445-8nh8v      0/1     Running   4 (61s ago)   5m1s

and a few minutes later: 
NAME                                                READY STATUS                   RESTARTS           AGE
devlake-lake-7455659445-8nh8v      0/1     CrashLoopBackOff   6 (3m31s ago)   12m

The other devlake service run fine, so maybe that could be part of the problem.
I tried to reinstall but it didn't help.

![image](https://github.com/apache/incubator-devlake/assets/99869742/604495c2-a957-499c-8046-ba18996417f9)

### What do you expect to happen

Open Apache DevLake UI as usual.

### How to reproduce

Install as documented on WSL Ubuntu with Helm.

### Anything else

Happens everytime.

### Version

v1.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Please share the pod log for diagnosis.

**Comment by kapptob** [comment]
Here are the logs:

ubuntu@dds-t14-007:~$ kubectl logs devlake-lake-7b6f7d647f-jdjvk
Defaulted container "lake" out of: lake, waiting-database-ready (init)
time="2024-07-02T08:36:58Z" level=info msg="no [.env] file, devlake will read configuration from environment, please make sure you have set correct environment variable."
Version:  v1.0-beta1@60faf14
time="2024-07-02 08:36:58" level=info msg="migration initialized"
time="2024-07-02 08:36:58" level=info msg="plugin loaded ae"
time="2024-07-02 08:36:59" level=info msg="plugin loaded azuredevops_go"
time="2024-07-02 08:36:59" level=info msg="plugin loaded bamboo"
time="2024-07-02 08:36:59" level=info msg="plugin loaded bitbucket"
time="2024-07-02 08:36:59" level=info msg="plugin loaded bitbucket_server"
time="2024-07-02 08:36:59" level=info msg="plugin loaded circleci"
time="2024-07-02 08:36:59" level=info msg="plugin loaded customize"
time="2024-07-02 08:36:59" level=info msg="plugin loaded dbt"
time="2024-07-02 08:37:01" level=info msg="plugin loaded dora"
time="2024-07-02 08:37:01" level=info msg="plugin loaded feishu"
time="2024-07-02 08:37:02" level=info msg="plugin loaded gitee"_

ubuntu@dds-t14-007:~$ kubectl logs devlake-ui-6c9777d847-xw6f2
2024/07/02 08:30:45 [notice] 10#10: using the "epoll" event method
2024/07/02 08:30:45 [notice] 10#10: nginx/1.25.4
2024/07/02 08:30:45 [notice] 10#10: built by gcc 12.2.0 (Debian 12.2.0-14)
2024/07/02 08:30:45 [notice] 10#10: OS: Linux 5.10.207
2024/07/02 08:30:45 [notice] 10#10: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/07/02 08:30:45 [notice] 10#10: start worker processes
2024/07/02 08:30:45 [notice] 10#10: start worker process 11
2024/07/02 08:30:45 [notice] 10#10: start worker process 12
10.244.0.1 - - [02/Jul/2024:08:30:50 +0000] "GET /health/ HTTP/1.1" 200 0 "-" "kube-probe/1.30" "-"

**Comment by klesh** [comment]
The log looks ok, seems like a k8s problem, please check your setup.
