### ISSUE TITLE
[Bug][Webhook] Can't associate an existing webhook with a project

### ISSUE THREAD

**Issue by tomerc-everc** [apache/devlake#7688]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Can't associate an existing webhook with a project, opposed to what mentioned in the docs.

### What do you expect to happen

When creating a wehbhook (not from within the Project screen), to be able to associate it with any project I want.

### How to reproduce

1. Login to devlake
2. Connections > Webhook > Add a Webhook
3. Give it a name, click "Generate POST URL"
4. Navigate to Projects > choose any existing project
5. Navigate to "Webhooks" tab
6. No "Select Existing Webhooks"

### Anything else

Documentation says it is possible: https://devlake.apache.org/docs/Configuration/webhook#step-3---use-webhook-in-a-project

Screenshot from my system:
![Screenshot 2024-07-01 at 14 53 05](https://github.com/apache/incubator-devlake/assets/168529559/3ba86188-6800-4a2f-b8bc-b1b6a0e69b41)

### Version

v1.0-beta1@60faf14

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tomerc-everc** [comment]
Makes sense. However, still not possible to create a Webhook and later associate with even a single project. If it will not be supported, feel free to close the issue.
I will remove my existing webhooks and will recreate from within each project.

Thanks

**Comment by klesh** [comment]
Hi, @tomerc-everc , actually, it is entirely possible and supported.
1. Go to the connections page and there is a Webhook icon, you can create Webhook here before creating any project.
![image](https://github.com/apache/incubator-devlake/assets/61080/bbf00103-8f4b-4f55-8d5a-61318154c980)
2. Go to the project page and click on the "Select Existing Webhooks" and off you go.
![image](https://github.com/apache/incubator-devlake/assets/61080/0c725f87-c323-4e90-8ff9-46457dd31d4e)

**Comment by klesh** [comment]
I believe the correct place to look would be : https://devlake.apache.org/docs/v1.0/Configuration/webhook#step-1---add-a-new-incoming-webhook

**Comment by d4x1** [comment]
@tomerc-everc  How about this issue ?
