### ISSUE TITLE
[Bug][GitHub] wrong pipeline name column if run-name is defined

### ISSUE THREAD

**Issue by IgorIgnatevSky** [apache/devlake#7698]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

If my workflow uses run-name then the name column in _tool_github_runs and cicd_pipelines tables collected with display_title instead of workflow name, as a result, it's hard to filter and query statistics for such workflows.
<img width="485" alt="image" src="https://github.com/apache/incubator-devlake/assets/150010866/b1c0886e-66ae-4c9d-a55d-2145a72da7dd">

### What do you expect to happen

name column the same as without run-name definition with name of workflow instead dynamic display_title as without run-name
<img width="389" alt="image" src="https://github.com/apache/incubator-devlake/assets/150010866/e134f718-03ce-46d1-8a2a-f64c5d040b7a">

### How to reproduce

use run-name in any workflow definition eq:
`run-name: "Deploy on ${{ inputs.app_name || github.event.label.name || 'production' }}`

### Anything else

github connection with github app and graphql configured
no transformation rules enabled

### Version

v1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
The current implementation does not differentiate when collecting names for pipelines, as far as I recall. Consequently, GitHub may return different names depending on whether the run-name was specified.

Both returned names can be meaningful in different contexts. Therefore, I suggest that we maintain both in separate fields to accommodate various users and scenarios, provided they are both available from the API.

I admit that I do not fully grasp the specifics of this issue, nor do I have the time to delve deeply into it at the moment. However, I am open to advancing the development by adding another field for your scenario. If you could investigate what the API offers and outline what needs to be done, it would greatly help us move forward.
