### ISSUE TITLE
[Bug][Onboard] Option `enableGraphQL` is disabled by default.

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#7703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I start a new devlake instance and set up a project with GitHub connection using the onboard guide.
FInish the onboard guide and go to connecionts page, click the connection config.
And I find GitHub connections don't enable graphql APIs.
![image](https://github.com/apache/incubator-devlake/assets/5844806/474d5def-be79-4489-9c22-e71f3af0232f)

### What do you expect to happen

Use GraphQL APIs by default for GitHub connections created during onboaring process.
![image](https://github.com/apache/incubator-devlake/assets/5844806/e9d3106a-726b-491d-ada3-17277976d6fd)

### How to reproduce

Use the correct version, set up a new instance and follow the onboard guide, you'll find it.

### Version

2e56bdd

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment]
Closed by #7711
