### ISSUE TITLE
[Bug][GitLab] Sometimes Project data are automatically deleted. 

### ISSUE THREAD

**Issue by antoniomuso** [apache/devlake#7732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Sometimes project data are automatically deleted, and I don't know why this happens. In the logs, there isn't information about it.

### What do you expect to happen

I expect project data should not be deleted at random.

### How to reproduce

I don't know how to reproduce it. It happened to me for a project that only has a GitLab repository. If I try to do a `Collect Data in Full Refresh Mode` but it does not fix the problem. The only way I found to fix it is by going to the "sync policy" option and resetting the Time Range,  after a `Collect Data in Full Refresh Mode` it works.

### Version

v0.21.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Can you be specific? What kind of data were missing? from what data source? any pattern? What did you do? any theory you have in mind?
It is not possible for anyone to help with such a vague description.

**Comment by klesh** [comment]
I am sorry that you ran into such a problem. But there is nothing we can do based on what we know at this point.
I am closing the issue and feel free to re-open it if you could find a way to reproduce the problem.
