### ISSUE TITLE
[Bug][Gitlab]  v1.0.1-beta2 Data Time Range not working

### ISSUE THREAD

**Issue by xlqbyy** [apache/devlake#7742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Gitlab, Data Time Range, v1.0.1-beta1 is working , but v1.0.1-beta2 not working.

### What do you expect to happen

v1.0.1-beta2 will collect all commits
![image](https://github.com/user-attachments/assets/69c80986-dd6b-4d57-971e-66078b54e564)
![image](https://github.com/user-attachments/assets/92b29b48-aeeb-4c6e-8403-4bba5391b7a5)

### How to reproduce

1、Upgrade to version v1.0.1-beta2
2、Set Time Range to 2024-06-01
3、Collect Data
4、Select commits table 

### Version

v1.0.1-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
![image](https://github.com/user-attachments/assets/d1bdc231-d7f2-49b5-afa1-4b1702f877b9)
try perform a full refresh and see if the problem goes away.

**Comment by klesh** [comment]
Sorry? what do you mean by "Data before June 2024 will still be collected."? 
The screenshot you posted showed commits from 2024-09-17 to 18, I thought you were talking about commits between 2024-06-01 and 2024-09-17 were not collected.

Are you expecting data in the database to be deleted? if so, that is not supported at the moment, commits will never be deleted once collected.

**Comment by klesh** [comment]
Are you two working together? 😂

**Comment by xlqbyy** [comment]
@klesh  Sorry, I may not have made it clear. What I meant is that if the Time Range value is set to 2024-06-01, the commit data before 2024-06-01 will not be collected, but the v1.0.1-beta2 version will also collect the commit data before 2024-06-01.

**Comment by xlqbyy** [comment]
@klesh I changed my account name this afternoon..😂

**Comment by xlqbyy** [comment]
I redeployed devlake, added the gitlab project, set the Time Range to 2024-06-01, and then clicked the collect data button. The commits before 2024-06-01 will also be collected (I don’t want the commits to be collected).

**Comment by xlqbyy** [comment]
Please see that committed_date is 2014, not 2024

**Comment by xlqbyy** [comment]
Please take a closer look at the screenshot of the database table. The committed_date is 2014, not 2024.

**Comment by klesh** [comment]
Aah, sorry, I see what you meant now.
Can you check the ``_raw_data_table` and see if those commits were collected by the `gitextractor` plugin.

**Comment by xlqbyy** [comment]
> Aah, sorry, I see what you meant now. Can you check the `_raw_data_table` and see if those commits were collected by the `gitextractor` plugin.
@klesh  Yes, using the **gitextractor** plugin
![image](https://github.com/user-attachments/assets/dad7798c-446b-488c-8ab2-6b751ac6ba43)

**Comment by klesh** [comment]
After reviewing the details, I can confirm that the functionality is performing as expected. The purpose of this PR (https://github.com/apache/incubator-devlake/pull/7727) was to address the issue where new commits from non-default branches were not being collected. The implemented solution involves fetching all branches from the remote server—this includes fetching at least some old commits from all branches—before executing the shallow fetch. Therefore, it's likely that the old commits are originating from those branches that have not been deleted.

**Comment by xlqbyy** [comment]
> After reviewing the details, I can confirm that the functionality is performing as expected. The purpose of this PR (#7727) was to address the issue where new commits from non-default branches were not being collected. The implemented solution involves fetching all branches from the remote server—this includes fetching at least some old commits from all branches—before executing the shallow fetch. Therefore, it's likely that the old commits are originating from those branches that have not been deleted.

@klesh Ok, many thanks for your help!

**Comment by xlqbyy** [comment]
@klesh  Can you help me create v1.0.1-beta4 based on the main branch? Let me test this function.

**Comment by d4x1** [comment]
You can try the latest release: https://github.com/apache/incubator-devlake/releases

**Comment by xlqbyy** [comment]
@abeizn Hello, please ask why this commit was not released to [v1.0.1-beta4](https://github.com/apache/incubator-devlake/releases/tag/v1.0.1-beta4). I want to test this commit. https://github.com/apache/incubator-devlake/pull/7760

**Comment by klesh** [comment]
@xlqbyy Note that #7760 doesn't fix the issue but merely reduces the total number of collected commits.

**Comment by klesh** [comment]
@xlqbyy I just CPed #7760 back to v1.0, will release a new beta this week.

**Comment by xlqbyy** [comment]
> @xlqbyy I just CPed #7760 back to v1.0, will release a new beta this week.


Okay, thank you for your answer. I would like to ask you, will this bug be fixed soon?

**Comment by klesh** [comment]
> After reviewing the details, I can confirm that the functionality is performing as expected. The purpose of this PR (#7727) was to address the issue where new commits from non-default branches were not being collected. The implemented solution involves fetching all branches from the remote server—this includes fetching at least some old commits from all branches—before executing the shallow fetch. Therefore, it's likely that the old commits are originating from those branches that have not been deleted.

@xlqbyy As discussed previously, it is an unintended side-effect of PR #7727. While it would be ideal to avoid this behavior, we haven't found a viable solution yet. Therefore, it's unlikely to be fixed anytime soon unless a solution to the underlying issue emerges.
