### ISSUE TITLE
[Bug][Config UI] AxiosError: Request failed with status code 502

### ISSUE THREAD

**Issue by harivignesh-git** [apache/devlake#7751]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I try to access Config UI using http://localhost:4000, I get the AxiosError: Request failed with status code 502 error

### What do you expect to happen

I want to view Config UI dashboard

### How to reproduce

None

### Version

v1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Was it docker-compose or helm-chart?

**Comment by adityai** [comment]
I have the same problem. I am a first-time user. I am using docker-compose. All I have to work with is a docker-compose.yml and a .env file. I am following instructions from this url https://devlake.apache.org/docs/GettingStarted/DockerComposeSetup.

**Comment by adityai** [comment]
When I checked the logs of the docker container that was running devlake, I saw an error stating that 'ENCRYPTION_SECRET' was missing and that I needed to enter that in the .env file. The instructions on the Getting Started guide suggested to add it as an env var locally, but that didn't work. I saved the encryption secret in the .env file and did a docker-compose up -d. Then it worked.
