### ISSUE TITLE
[Bug][Gitlab] Component and File-Level Metrics not displaying

### ISSUE THREAD

**Issue by SiliconSatchel** [apache/devlake#7752]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm having some trouble with the "Component and File-Level Metrics" dashboard, none of the "file dimension" metrics are displaying properly. 
![Screenshot from 2024-07-16 16-07-13](https://github.com/user-attachments/assets/b13569bc-909d-4970-b877-e04bc6063143)

In particular (I suspect the other metrics are having similar issues) the SQL query for files with maximum number of authors is erroring out, the Grafana pod logs give this error:
```
logger=tsdb.mysql endpoint=queryData pluginId=mysql dsName=mysql dsUID=P430005175C4C7810 uname=admin t=2024-07-15T17:32:42.710897017Z level=error msg="Query error" error="Error 3995 (HY000): Character set 'binary' cannot be used in conjunction with 'utf8mb4_unicode_ci' in call to regexp_like."
```

Going to the "explore" tab and manually querying:
```
SELECT * FROM commits 
```
doesn't show any file_path column, which looks important for this dashboard.

### What do you expect to happen

The "file dimension" metrics are displayed in the dashboard.

### How to reproduce

- Deploy DevLake v1.0.1-beta2 using docker-compose.
- Setup a project with a Gitlab connection scoped to one repository.
- Open the "Component and File-Level Metrics" dashboard.

### Anything else

I saw this bug on both v1.0.0 and v1.0.1-beta2. I asked about it in slack and was told to open an issue here.

### Version

v1.0.1-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Component and File-Level metrics are not collected by default because it would produce a huge number of records which brings performance penalties.
You can turn it on by setting the Environment Variable `SKIP_COMMIT_FILES=false` and see if the time of the collection and storage requirement is acceptable to you.

**Comment by SiliconSatchel** [comment]
Thank you, I'll try adding that environment variable to the .env file and rerunning collection.

**Comment by SiliconSatchel** [comment]
After rerunning collection (on a small repo, it was pretty quick) the `largest files with lowest number of authors` and `[total]files with most modifications` panels are populated, but `files with maximum number of authors` and `files with most modifications` are not. Looking more closely at `largest files with lowest number of authors`, the SQLite query
```
SELECT file_path,
        count(distinct sha) AS modified_num
FROM commits
JOIN commit_files
JOIN repo_commits rc
    ON commit_files.commit_sha = rc.commit_sha
        AND sha=commit_files.commit_sha
        AND $__timeFilter(commits.authored_date)
WHERE repo_id IN (${repo_id}) and file_path REGEXP  '(${selected_path:regex})'
AND $__timeFilter(commits.authored_date)
GROUP BY  file_path
ORDER BY  modified_num desc
LIMIT 15;
```
is causing this error in the Grafana pod:
```
logger=tsdb.mysql endpoint=queryData pluginId=mysql dsName=mysql dsUID=P430005175C4C7810 uname=admin t=2024-07-17T19:44:17.454747932Z level=error msg="Query error" error="Error 3995 (HY000): Character set 'binary' cannot be used in conjunction with 'utf8mb4_unicode_ci' in call to regexp_like."
```

Removing the line `WHERE repo_id IN (${repo_id}) and file_path REGEXP  '(${selected_path:regex})'` causes the query to succeed. I'm a little unclear on what `selected_path` should be set to, the query fails when I set it to the empty string, `.`, or the name of a top-level directory in the repo.

**Comment by klesh** [comment]
Yes, it is fast for small repos and could be super slow for big ones.

The `commit_files.file_path` column is of type `varbinary` which I think doesn't support the `REGEX` operator.
Can you try changing it to `varchar` and see if it fixes the problem?

**Comment by SiliconSatchel** [comment]
I'm not very familiar with SQL, using `cast(file_path as CHAR)` in the REGEXP check fixes the problem. Is that what you meant?

**Comment by klesh** [comment]
@SiliconSatchel Not extactly, but your answer confirms my theory. I think we need to change the type of the column, and maybe add a index to speed up the query a little bit
