### ISSUE TITLE
[Bug][Pagerduty] The PagerDuty connection is pulling incident data but this is not being reflected in metrics.

### ISSUE THREAD

**Issue by Puvendhan** [apache/devlake#7766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi Everyone, The PagerDuty connection is pulling incident data but this is not being reflected in metrics.
Devlake is running on v1.0.0-beta11.
The PagerDuty connection is pulling incident data but this is not being reflected in metrics. Where configured Jira data is acting as an incident count but from PagerDuty it is possible to see incidents in DevLake but these are not impacting the counts.

### What do you expect to happen

Hi Everyone, The PagerDuty connection is pulling incident data but this is not being reflected in metrics.
Devlake is running on v1.0.0-beta11.
The PagerDuty connection is pulling incident data but this is not being reflected in metrics. Where configured Jira data is acting as an incident count but from PagerDuty it is possible to see incidents in DevLake but these are not impacting the counts.

### How to reproduce

Hi Everyone, I deployed the devlake and added pagerduty data connection.
Added the dashboards in grafana. 

### Anything else

Hi Everyone, The PagerDuty connection is pulling incident data but this is not being reflected in metrics.
Devlake is running on v1.0.0-beta11.
The PagerDuty connection is pulling incident data but this is not being reflected in metrics. Where configured Jira data is acting as an incident count but from PagerDuty it is possible to see incidents in DevLake but these are not impacting the counts.

### Version

v1.0.0-beta11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@Puvendhan  Please describe your problem in detail, step by step.

**Comment by Puvendhan** [comment]
Is this been rolled out in the helm-charts, if so which version ?

**Comment by Puvendhan** [comment]
Hi Team, Any update on this?

Is this been rolled out in the helm-charts, if so which version ?

**Comment by d4x1** [comment]
@Puvendhan   We have a new release today. https://github.com/apache/incubator-devlake/releases

**Comment by Puvendhan** [comment]
Hi , I rolled out the version [v1.0.1-beta4](https://github.com/apache/incubator-devlake/releases/tag/v1.0.1-beta4) , however the incidents are visible only at the bottom of the dashboard, but still the overall incident count is showing 0. Could please take a look at it?


![image](https://github.com/user-attachments/assets/22d5018d-e0b5-4562-951c-47bc595599d8)

**Comment by d4x1** [comment]
@Puvendhan  Incidents which are related to deployments will be shown here.

```
_failure_caused_by_deployments as (
-- calculate the number of incidents caused by each deployment
	SELECT
		d.deployment_id,
		d.deployment_finished_date,
		count(distinct case when i.type = 'INCIDENT' then d.deployment_id else null end) as has_incident
	FROM
		_deployments d
		left join project_incident_deployment_relationships pim on d.deployment_id = pim.deployment_id
		left join issues i on pim.id = i.id
	GROUP BY 1,2
)
```
Please make sure there are relations in table `project_incident_deployment_relationships`.
