### ISSUE TITLE
[Bug][pagerduty] DevLake does not collect PagerDuty incidents

### ISSUE THREAD

**Issue by hayk96** [apache/devlake#7772]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

DevLake does not collect PagerDuty incidents.
![Screenshot 2024-07-22 at 15 51 05](https://github.com/user-attachments/assets/75f2c13a-db36-4951-b800-1338ec9ca465)

![Screenshot 2024-07-22 at 15 53 14](https://github.com/user-attachments/assets/fe5763c7-3785-4de9-98f1-bb82134c11d6)

### What do you expect to happen

When pipelines run successfully, they must update the `issues` table in the database, but the table is empty

```
mysql> SELECT * FROM issues;
Empty set (0.00 sec)
```

### How to reproduce

1. Install a fresh DevLake instance with version v1.0.1-beta3 (or v1.0.1.*)
2. Create a project by adding a PagerDuty connection/scope. Your PagerDuty service must have incidents.

### Version

v1.0.1-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@hayk96  Can you check tables `_tool_pagerduty_incidents` and `_raw_pagerduty_incidents` if there is any data?

**Comment by hayk96** [comment]
sure @d4x1 
```
mysql> USE lake;
Database changed
mysql> SELECT * FROM _tool_pagerduty_incidents;
Empty set (0.00 sec)

mysql> SELECT * FROM _raw_pagerduty_incidents;
Empty set (0.00 sec)

**Comment by hayk96** [comment]
Thanks, @d4x1, for your help. It seems that incident information is collected only with `Collect Data In Full Refresh Mode` and not through regular pipelines. I hope to see a resolution for this issue in the next release. Thanks again!
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/75729af9-b4df-4599-b731-6f6a23d270b3">

**Comment by abeizn** [comment]
@hayk96 Version has been released: https://github.com/apache/incubator-devlake/releases/tag/v1.0.1-beta4
