### ISSUE TITLE
[Question][AzureDevOps] Pipeline run retention

### ISSUE THREAD

**Issue by benjaminrmoss** [apache/devlake#7788]
Hi - The ADO project I'm working with has a pipeline rention policy of 3 previous runs. When running the data collection in DevLake, any runs that have expired or been deleted from ADO are removed, which leads to the DORA dashboard having no/less data.

Is there any way for me to configure DevLake to retain any pipeline metrics even if the actual pipeline run in ADO has been removed? Thanks for your help.

**Comment by d4x1** [comment]
@benjaminrmoss  You can run your project in `incremental` mode. It will only collect data that changes therotically since last successful sync.

**Comment by benjaminrmoss** [comment]
@d4x1 Thanks for the reply. Would I set this in the project configuration settings? I can't see any option for it here:
![image](https://github.com/user-attachments/assets/7c10c3b1-acf2-4718-afc0-78fd99c6ac64)
Maybe this feature isn't supported for ADO yet? https://devlake.apache.org/docs/Overview/SupportedDataSources/#azure-devops

**Comment by d4x1** [comment]
@benjaminrmoss  You can try azuredevop_go, it can collect data incremantally.
