### ISSUE TITLE
[Bug][devLake config UI] secure PAT is exposed in network tab  

### ISSUE THREAD

**Issue by yurii-chikh-vitech** [apache/devlake#7821]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Secure PAT token exposed in network tab for request [http://localhost:4000/api/plugins/gitlab/connections/1/scopes?page=1&pageSize=10&blueprints=true](http://localhost:4000/api/plugins/gitlab/connections/1/scopes?page=1&pageSize=10&blueprints=true)

![image](https://github.com/user-attachments/assets/83e7280d-2c9b-4a55-a6a5-983de11bbcc8)

### What do you expect to happen

PAT should not be exposed

### How to reproduce

Explore network tab on connection settings page.
 
http://localhost:4000/api/plugins/gitlab/connections/1/scopes?page=1&pageSize=10&blueprints=true

### Version

v1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Aah.. I agree....
Did you revoke that token already? Because I can see the whole token 🤣 ...and, with it anyone could list all your private repos...so ... it is no point to mask the other information...

**Comment by klesh** [comment]
@yurii-chikh-vitech I just removed the screenshot, please revoke the token ASAP if it was not revoked already.

**Comment by yurii-chikh-vitech** [comment]
> @yurii-chikh-vitech I just removed the screenshot, please revoke the token ASAP if it was not revoked already.

Token is old and revoked.

**Comment by d4x1** [comment]
@yurii-chikh-vitech  I think it was fixed in #7767, all codes are cherry picked to v1.0.

which version are you using?  I can help to check.

**Comment by d4x1** [comment]
I've tested it with latest code in branch release-v1.0, and it works.
<img width="348" alt="image" src="https://github.com/user-attachments/assets/9a6a27d1-57f2-427f-adb2-c569f4e4e4bd">

**Comment by yurii-chikh-vitech** [comment]
> @yurii-chikh-vitech I think it was fixed in #7767, all codes are cherry picked to v1.0.
> 
> which version are you using? I can help to check.

@d4x1  v1.0

**Comment by d4x1** [comment]
> v1.0

Do you mean https://github.com/apache/incubator-devlake/releases/tag/v1.0.0 ?

**Comment by yurii-chikh-vitech** [comment]
@d4x1  v1.0.0

**Comment by d4x1** [comment]
> @d4x1 v1.0.0

@yurii-chikh-vitech  You can try the latest version(https://github.com/apache/incubator-devlake/releases/tag/v1.0.1-beta9). It has been fixed.

**Comment by oliviertassinari** [comment]
#2800 was similar in the past.
