### ISSUE TITLE
[Bug][Grafana] Dashboard visualization error

### ISSUE THREAD

**Issue by hayk96** [apache/devlake#7822]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Grafanas' panels return the following errors:  
`Error 1146 (42S02): Table 'lake.project_incident_deployment_relationships' doesn't exist`

---
**DevLake version:** 1.0.1-beta4
**Dashboard:** [DORA](https://github.com/apache/incubator-devlake/blob/main/grafana/dashboards/DORA.json)
**Panels:** Change Failure Rate, Failed Deployment Recovery Time
**Connections I use:** GitLab and PagerDuty

### What do you expect to happen

I expect to see proper visualizations in all panels

### How to reproduce

1. Deploy DevLake v1.0.1-beta4 via Helm and add two connections GitLab and PagerDuty
2. Add a project from DevLake UI that will contain both connections (GitLab and PagerDuty)

### Version

v1.0.1-beta4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@hayk96  table `project_incident_deployment_relationships` is introduced since v1.0.1-beta5. Why do you encounter this issue in v1.0.1-beta4?

**Comment by hayk96** [comment]
I will try @d4x1, thanks!

**Comment by hayk96** [comment]
There is another issue with `Median Time to Restore Service` panel where data is empty (No data) when selecting `DORA Report 2023` variable, and the interesting part is it works (panel shows data) on `DORA Report 2021` mode.

**Comment by d4x1** [comment]
@hayk96  Try the latest release: https://github.com/apache/incubator-devlake/releases/tag/v1.0.1-beta6

**Comment by hayk96** [comment]
thanks @d4x1 seems the issue has been fixed in v1.0.1-beta6
