### ISSUE TITLE
[Bug][devLake:UI] Error: Request failed with status code 502 , while login to devLake

### ISSUE THREAD

**Issue by ravisanrjy** [apache/devlake#7833]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

It was configured last week and it has been working fine till yesterday, when i try to log in, i am getting a 502 error since morning.I did not modify anything. 

### What do you expect to happen

I don't know why suddenly getting this error

### How to reproduce

when i try access datalake from browser i.e <IP.address:4000> i am getting below ereor
![image](https://github.com/user-attachments/assets/21b517e9-e368-4cff-805b-416f1a0b82ef)

Even i click on continue , it is not moving.

### Version

V1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@ravisanrjy check the backend log and see what happened

**Comment by ravisanrjy** [comment]
When i run the docker-compose up -d, i am getting below output
WARN[0000] The "HTTPS_PROXY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GOPROXY" variable is not set. Defaulting to a blank string. 
[+] Running 7/8
 ⠦ Network incubator-devlake_default                                    Created                                                                                                                           2.6s 
 ✔ Container incubator-devlake-authproxy-1                              Started                                                                                                                           0.4s 
 ✔ Container incubator-devlake-mysql-1                                  Started                                                                                                                           0.7s 
 ✔ Container incubator-devlake-postgres-1                               Started                                                                                                                           0.7s 
 ! authproxy Published ports are discarded when using host network mode                                                                                                                                   0.0s 
 ✔ Container incubator-devlake-devlake-1                                Started                                                                                                                           1.4s 
 ✔ Container incubator-devlake-grafana-1                                Started                                                                                                                           1.3s 
 ✔ Container incubator-devlake-config-ui-1                              Started

**Comment by klesh** [comment]
Can you share the backend logs by using the command `docker-compose logs devlake`.

**Comment by ravisanrjy** [comment]
@klesh -Please find the attached logs. Till last week it was working fine, suddently i start getting 502 error since yesterday. I would appreciate your quick response
[devLake_log.txt](https://github.com/user-attachments/files/16508622/devLake_log.txt)
Thankd
Ravi

**Comment by klesh** [comment]
Seems like the `mysql` service is down.
```
time="2024-08-06 06:55:24" level=info msg="\x1b[35m/app/core/runner/db.go:154\n\x1b[0m\x1b[31m[error] \x1b[0mfailed to initialize database, got error dial tcp 172.22.0.3:3306: connect: connection refused"
```

**Comment by ravisanrjy** [comment]
Hi Klesh,
I have checked the docker logs and found below details
time="2024-08-07T07:51:03Z" level=info msg="no [.env] file, please make sure you have set the environment variable."
Version:  
time="2024-08-07 07:51:03" level=info msg="\x1b[35m/app/core/runner/db.go:154\n\x1b[0m\x1b[31m[error] \x1b[0mfailed to initialize database, got error Error 1049 (42000): Unknown database 'lake'"

How set the version in .env . PFA .env file
[env.txt](https://github.com/user-attachments/files/16520169/env.txt)

**Comment by klesh** [comment]
> Hi Klesh, I have checked the docker logs and found below details time="2024-08-07T07:51:03Z" level=info msg="no [.env] file, please make sure you have set the environment variable." Version: time="2024-08-07 07:51:03" level=info msg="\x1b[35m/app/core/runner/db.go:154\n\x1b[0m\x1b[31m[error] \x1b[0mfailed to initialize database, got error Error 1049 (42000): Unknown database 'lake'"

Are you using the `mysql` service in the `docker-compose.yml` file? If you do, the `lake` database should be created automatically.
Or is it a standalone MySQL? if so, create the database and user/pass then update the DB_URL accordingly.

> 
> How set the version in .env . PFA .env file [env.txt](https://github.com/user-attachments/files/16520169/env.txt)

What do you mean by version? what version are you referring to?

**Comment by ravisanrjy** [comment]
@klesh -> I fixed the issue, i removed all docker images and volumes and created again and it's working now. Thanks

**Comment by klesh** [comment]
Nice. Closing issue now.
