### ISSUE TITLE
[Bug][Devlake] unexpected end of JSON when adding more than 31 repositories as data scope to Azure-DevOps Connection

### ISSUE THREAD

**Issue by carmarte** [apache/devlake#7836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Hi There!

Dear Team,

I am having this issue when trying to add more than 31 repositories as data scope to an Azure-DevOps Data Connection.

The error is this:
`level=error msg="HTTP 400 error\n\tcaused by: error patching the blueprint (400)\n\tWraps: (2)\n\tWraps: (3) unexpected end of JSON input\n\tWraps: (4) unexpected end of JSON input\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *json.SyntaxError"`

![image](https://github.com/user-attachments/assets/3c5e4a13-ab37-44aa-b8fb-9ec2a6b616b1)

I have one project, that project has an Azure-DevOps Data Connection, that Data Connection has already 31 repositories added as data scope but when I tried to add one more repository, I got the error mentioned before.

![image](https://github.com/user-attachments/assets/ea801c6f-129d-48e5-8b66-bb7d896fc18b)

### What do you expect to happen

The repository is added as data scope for an Azure-DevOps data connection.

### How to reproduce

Add more than 31 repositories as data scope to an Azure-DevOps Data Connection.

### Version

v1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Please use the Go version plugin instead.
