### ISSUE TITLE
Question about RDS Devlake

### ISSUE THREAD

**Issue by amokkapati** [apache/devlake#7864]
Hi I'm trying to connect a MySQL RDS instance to use as the database in my docker-compose file for Devlake. It is not able to work though, can you guide me through the full setup.

**Comment by amokkapati** [comment]
version: "3"
services:
  mysql:
    image: mysql:8
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --skip-log-bin

  grafana:
    image: devlake.docker.scarf.sh/apache/devlake-dashboard:v1.0.0
    ports:
      - 3002:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: "http://localhost:4000/grafana"
      GF_USERS_DEFAULT_THEME: "light"
      MYSQL_URL: mysql:3306
      MYSQL_DATABASE: lake
      MYSQL_USER: merico
      MYSQL_PASSWORD: merico
      TZ: UTC
    restart: always
    depends_on:
      - mysql

  devlake:
    image: devlake.docker.scarf.sh/apache/devlake:v1.0.0
    ports:
      - 8080:8080
    restart: always
    volumes:
      - devlake-log:/app/logs
    env_file:
      - ./.env
    environment:
      LOGGING_DIR: /app/logs
      TZ: UTC
    depends_on:
      - mysql

  config-ui:
    image: devlake.docker.scarf.sh/apache/devlake-config-ui:v1.0.0
    ports:
      - 4000:4000
    env_file:
      - ./.env
    environment:
      DEVLAKE_ENDPOINT: devlake:8080
      GRAFANA_ENDPOINT: grafana:3000
      TZ: UTC
      #ADMIN_USER: devlake
      #ADMIN_PASS: merico
    depends_on:
      - devlake

volumes:
  mysql-storage:
  grafana-storage:
  devlake-log:
~                

This is my docker-compose file, I don't have the network options from ur first step

**Comment by amokkapati** [comment]
@dosu 
How do I do the part where I set the character server? Right now I have everything except that
# Don't forget to create db named `lake` in your own db, and set character-set-server=utf8mb4, collation-server=utf8mb4_bin as below
#      character-set-server=utf8mb4
#      collation-server=utf8mb4_bin

**Comment by amokkapati** [comment]
# Lake Database Connection String
DB_URL=mysql://merico:merico@mysql:3306/lake?charset=utf8mb4&parseTime=True&loc=UTC
E2E_DB_URL=mysql://merico:merico@mysql:3306/lake_test?charset=utf8mb4&parseTime=True&loc=UTC
# Silent Error Warn Info
DB_LOGGING_LEVEL=Error

Do I need to change both of these or just the first one in .env file

**Comment by amokkapati** [comment]
would it be the same url for both?

**Comment by amokkapati** [comment]
Im getting an error code 500 when I do docker-compose up -d now, do I need to reinstall devlake?

**Comment by amokkapati** [comment]
I have devlake deployed onto an ec2 instance, the rds database and ec2 are in same vpc, same subnet, do I need to configure additional security group rules?

**Comment by amokkapati** [comment]
@dosu which table will help me find github committs for a specific file in the database.

**Comment by amokkapati** [comment]
Where can I find the name of files that were updated in the pull_requests table of the database

**Comment by amokkapati** [comment]
@dosu 

Where can I find the name of files that were updated in the pull_requests table of the database

**Comment by amokkapati** [comment]
@dosu 
I don't see the pull_requests_files table in the database

**Comment by d4x1** [comment]
@amokkapati  Try table `commit_files`.  And please submit a new issue for new questions.
