### ISSUE TITLE
[Question][DORA] About the logic of ‘Median Lead Time for Changes‘

### ISSUE THREAD

**Issue by DevYoungHulk** [apache/devlake#7873]
## Question
I had some questions about this calculation logic when using devlake for DORA metrics calculations.  
    https://devlake.apache.org/docs/Metrics/LeadTimeForChanges
This document describes the calculation of 'Median Lead Time for Changes' using PR cycle time. However, the example only mentions the case where one PR corresponds to one deployment.  
My question is if we have multiple PRs in one deployment, should all of them be calculated in Lead Time for Changes.  
For example i have multiple PRs in one deployment:  PR1 (commit1,commit2), PR2 (commit3,commit4), PR3 (commit5)
'Lead Time for Change' should calculate the time cover all **commit1.... ...commit5** or **Median(PR1,PR2,PR3 to deploy)**

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by DevYoungHulk** [comment]
But PR1,PR2 are not really deployed until PR3 is completed, does that make sense to calculate?

**Comment by klesh** [comment]
From what I can tell, the Median Lead Time for Changes is calculated by:
1. Select deployments within the time range
2. Select all PRs belonging to those deployments
3. Calculate the Median from all Cycle Times of those PRs

So, if the deployment gets selected in the first step, then yes, all 3 PRs would be included.

**Comment by klesh** [comment]
> But PR1,PR2 are not really deployed until PR3 is completed, does that make sense to calculate?

Why is that? You said the following in the issue description:

> For example i have multiple PRs in one deployment: PR1 (commit1,commit2), PR2 (commit3,commit4), PR3 (commit5)"

If  I understand the statement correctly, it means: They were deployed together in one go.

**Comment by DevYoungHulk** [comment]
> > But PR1,PR2 are not really deployed until PR3 is completed, does that make sense to calculate?
> 
> Why is that? You said the following in the issue description:
> 
> > For example i have multiple PRs in one deployment: PR1 (commit1,commit2), PR2 (commit3,commit4), PR3 (commit5)"
> 
> If I understand the statement correctly, it means: They were deployed together in one go.

Yes, the 3 PRS are included in a single deployment.


> From what I can tell, the Median Lead Time for Changes is calculated by:
> 
> 1. Select deployments within the time range
> 2. Select all PRs belonging to those deployments
> 3. Calculate the Median from all Cycle Times of those PRs
> 
> So, if the deployment gets selected in the first step, then yes, all 3 PRs would be included.

So in my example, the lead time for change for this deployment is from P1 start time to go live time, P2, P3 time need not be double counted right?
While calculating median we need to calculate as per deployment not PR. Am i right?

**Comment by klesh** [comment]
@DevYoungHulk No, I don't think so.
It is called "Lead Time for Changes", Changes refer to PRs. In other words, time spent for a PR from creation to production.
So the metric is calculated per PR while deployments are merely a way to select all deployed PRs.
Hence, "Median Lead Time for Changes" is a metric to determine the overall velocity of PRs cycle time (created to deployed).
Imagine we have a couple of developers working on different features, the "Median Lead Time for Changes" metric suggests how fast the team shipping feature.

**Comment by DevYoungHulk** [comment]
@klesh  Sorry I still have doubts. 
We should calculate the delivery time for each PR. This can differentiate the delivery rate of different developers which I agree with.
I see from this code (backend/plugins/dora/tasks/change_lead_time_calculator.go) :
**cycleTime = PrCodingTime + prDuring + PrDeployTime**
**PrDeployTime = computeTimeSpan(pr.MergedDate, deployment.FinishedDate)**
But in **PR1's PrDeployTime** includes **PR1's merging time** and **waiting time for PR2 and PR3**. PR1 developer's CLT becomes longer, but he doesn't do anything, his time is wasted by waiting. This is not favorable for PR1's developer. Should we exclude the time of P2 P3?

Of course the example I gave is our particular business process. Due to some gaps in development and business testing directly. we tend to have a centralized batch of requirements for overall delivery, which is not generic.

**Comment by klesh** [comment]
@DevYoungHulk Ahh, I see. I think you take it all wrong, DORA is not for measuring developer's productivity but to help you improve the overall efficiency of the team.
Now, if what you are saying is true, you should try to change/improve the operation to avoid the developer of PR1 from waiting.
Say, deploy them separately.

**Comment by DevYoungHulk** [comment]
@klesh 
Thank you for your patience. This is very helpful to me.  
![04F4AA42](https://github.com/user-attachments/assets/d1613d6b-5fd1-4238-a14b-0b33d8f60d82)
