### ISSUE TITLE
[Question]Getting file info

### ISSUE THREAD

**Issue by amokkapati** [apache/devlake#7877]
I'm trying to create a custom metric for GitHub relating to files that were updated during commits. I don't see any tables within my lake database that have information about files, I only see commit sha information. How do I access/group by file name?

**Comment by amokkapati** [comment]
@dosu the commit_files table is empty for some reason.

**Comment by amokkapati** [comment]
@dosu 
how would I create the plugin? Is it something that is incorporated within devlake itself?

**Comment by amokkapati** [comment]
@dosu Do I just do this as a new blueprint or can I add it to an existing project?

**Comment by amokkapati** [comment]
Also, how would I get the connection ID and project ID, is it the same as the name?

**Comment by amokkapati** [comment]
@dosu 
How do I access the JSON file from an existing project/connection so that I can modify it to include the new plugin.

**Comment by amokkapati** [comment]
@dosu
{
  "id": 10,
  "name": "GHEDev-Blueprint",
  "plan": [
    [
      {
        "plugin": "org",
        "subtasks": [
          "setProjectMapping"
        ],
        "options": {
          "projectMappings": [
            {
              "projectName": "GHEDev",
              "scopes": [
                {
                  "rowId": "github:GithubRepo:1:7345",
                  "table": "repos"
                },
                {
                  "rowId": "github:GithubRepo:1:7345",
                  "table": "cicd_scopes"
                },
                {
                  "rowId": "github:GithubRepo:1:7345",
                  "table": "boards"
                }
              ]
            }
          ]
        }
      }
    ],
    [
      {
        "plugin": "github",
        "subtasks": [
          "Convert Releases",
          "Convert Repos",
          "Extract Comments",
          "Extract Events",
          "Extract Issues",
          "Extract Milestones",
          "Extract PR Review Comments",
          "Extract Pull Requests",
          "Extract Users",
          "Extract Workflow Runs",
          "Convert Issue Assignees",
          "Convert Issue Comments",
          "Convert Issue Labels",
          "Convert Issues",
          "Convert Milestones",
          "Convert PR Labels",
          "Convert Pull Requests",
          "Convert Workflow Runs",
          "Enrich PR Issues",
          "Convert PR Issues",
          "Extract Jobs",
          "Extract PR Commits",
          "Extract PR Reviews",
          "Convert Jobs",
          "Convert PR Comments",
          "Convert PR Commits",
          "Convert PR Reviews",
          "Extract User Org",
          "Convert Users"
        ],
        "options": {
          "connectionId": 1,
          "fullName": "INFServices/terraform-base",
          "githubId": 7345,
          "name": "INFServices/terraform-base"
        }
      }
    ],
    [
      {
        "plugin": "dora",
        "subtasks": [
          "generateDeployments",
          "generateDeploymentCommits",
          "enrichPrevSuccessDeploymentCommits"
        ],
        "options": {
          "projectName": "GHEDev"
        }
      }
    ],
    [
      {
        "plugin": "refdiff",
        "subtasks": [
          "calculateDeploymentCommitsDiff"
        ],
        "options": {
          "projectName": "GHEDev"
        }
      }
    ],
    [
      {
        "plugin": "dora",
        "subtasks": [
          "calculateChangeLeadTime",
          "ConnectIncidentToDeployment"
        ],
        "options": {
          "projectName": "GHEDev"
        }
      }
    ]
  ],
  "skipOnFail": true
}

How do I modify this existing github project to include gitextractor and customize plugin

**Comment by amokkapati** [comment]
@dosu 
error patching the blueprint Wraps: (2) 1 error(s) decoding: | | * 'Plan[0][0]' expected a map, got 'string' Wraps: (3) 1 error(s) decoding: | | * 'Plan[0][0]' expected a map, got 'string' Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mapstructure.Error

getting this error

**Comment by msabramo** [comment]
@amokkapati: Were you able to get your `commit_files` table populated? I also have an empty table (using GitHub Enterprise self-hosted server).

**Comment by klesh** [comment]
@msabramo Set the following Environment Variables to `true` and try again:
https://github.com/apache/incubator-devlake/blob/61fdbb6488ceca21bd53be5c847ce3ad973ff79a/env.example#L81-L83
