### ISSUE TITLE
[Bug][TimeAfter] Bug title The timeAfter parameter in the DevLake sync API isn't functioning as expected.

### ISSUE THREAD

**Issue by SushmitaMahapatra23** [apache/devlake#7886]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The timeAfter parameter in the DevLake sync API isn't functioning as expected; it's using the time range configured in the config-ui instead.

ex:

```
curl -X 'POST'   'http://localhost:4001/api/rest/blueprints/4/trigger'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -H 'Authorization: Bearer <token>'   -d '{
  "fullSync": true,
  "skipCollectors": false,
  "skipOnFail": false,
  "timeAfter": "2024-08-11T05:00:00Z"
}'
```

### What do you expect to happen

The timeAfter value provided in the API parameter should take precedence over the default timeRange in DevLake.

### How to reproduce

```
curl -X 'POST' \
  'http://localhost:4001/api/rest/blueprints/4/trigger' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer <token>' \
  -d '{
    "fullSync": true,
    "skipCollectors": false,
    "skipOnFail": false,
    "timeAfter": "2024-08-11T05:00:00Z"
  }'
```

**Monitor the sync process and observe whether it respects the timeAfter parameter you provided.
Verify if the sync is using the time range from the config-ui instead.**

## Expected Behaviour
**The sync process should respect the timeAfter parameter provided in the API call and use "2024-08-11T05:00:00Z" as the starting point.**

## Actual Behavior
**The sync process ignores the timeAfter parameter and uses the time range configured in the config-ui.**

### Version

v0.17.0-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@SushmitaMahapatra23 After some investigation, we found out the `skipOnFail` and `timeAfter` were not used by trigger API at all, we believe it was a mistake to put them in the request body in the first place.
I think you can use the `PATCH bluepint` API first if you wish to change these options.
