### ISSUE TITLE
[Bug][CircleCI] Regex Matches Workflows but Fails to Match Jobs

### ISSUE THREAD

**Issue by MattiasSvenssonQred** [apache/devlake#7889]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When configuring the scope configuration, the regex works when matching on workflows, but it does not work for jobs.

### What do you expect to happen

It should collect data and show in DORA metrics. 

### How to reproduce

Go to - project - connections - scope config - transformations

<img width="966" alt="Screenshot 2024-08-13 at 11 25 16" src="https://github.com/user-attachments/assets/f5815d69-ea33-4c03-a2e5-9ab754266d1e">

Verify in _tool_circleci_jobs

<img width="1014" alt="Screenshot 2024-08-13 at 11 35 25" src="https://github.com/user-attachments/assets/8813fa0e-b915-4dc1-9d56-72cae63c3a47">

Verify in cicd_deployments 

<img width="858" alt="Screenshot 2024-08-13 at 11 20 40" src="https://github.com/user-attachments/assets/62008df2-bf46-4225-8225-2e8d71a18958">

### Anything else

Waiting on Bug Fix Release: Merged but Not Yet Released

https://github.com/apache/incubator-devlake/pull/7770

### Version

v1.0.1-beta6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MattiasSvenssonQred** [comment]
@dosu. So you mean that the regex should match both workflow and jobs ?? 

Because the docuemnts tell me that its workflow OR jobs

**Comment by klesh** [comment]
How about the `cicd_tasks` table? Did the corresponding record appear?

**Comment by klesh** [comment]
@MattiasSvenssonQred Thanks.
I guess that the record from your screenshot was with type=DEPLOYMENT, if that so, it is working as expected, the regex in "Scope Config" merely produces such a record.
And it is up to the `dora` plugin to convert them into `cicd_deployments` and `cicd_deployment_commits` tables.
Did the `dora` tasks appear in the pipeline tasks list?

**Comment by MattiasSvenssonQred** [comment]
@klesh Thanks.

Yes, the record from the screenshot was of type=DEPLOYMENT.

Okay, okay. Do I understand correctly that Scope Config is working if we get a row in the cicd_task table with type=DEPLOYMENT?

And now, it's the DORA plugin that should transform the deployment into cicd_deployments and cicd_deployment_commits, right?

From what I could see, the DORA task appears in the pipeline.

<img width="1135" alt="Screenshot 2024-08-15 at 11 35 27" src="https://github.com/user-attachments/assets/b29bb89f-d579-46c9-9cbe-2afc7aab8517">

**Comment by justinphelps** [comment]
I seem to have a similar problem. 
Workflows regex set to (.*) isn't finding the jobs

**Comment by Nickcw6** [comment]
I can replicate this too - I have a fix, will open a PR shortly.
