### ISSUE TITLE
[Bug][Framework] fields are empty in table `_devlake_subtasks`

### ISSUE THREAD

**Issue by d4x1** [apache/devlake#7896]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I want to statisticize the subtasks' time cost from table `_devlake_subtasks`.

### What do you expect to happen

I found some subtasks' fields are empty or null.

![image](https://github.com/user-attachments/assets/933d5a32-dcba-4b44-842e-6b9222674e4f)

### How to reproduce

run sql `select * FROM _devlake_subtasks where began_at is null  order by number asc LIMIT  100`.

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
@klesh

**Comment by abeizn** [comment]
closed by https://github.com/apache/incubator-devlake/pull/7959
