### ISSUE TITLE
[Bug][Grafana] Monthly Deployment SQL Filter

### ISSUE THREAD

**Issue by jeffschaper** [apache/devlake#7899]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I filtered on the "Last 2 days" drop down in the Grafana dashboard and didn't see any metrics related to my application.

### What do you expect to happen

I would expect to see metrics related to my application regardless of the time frame selected.

### How to reproduce

1. Make one or more commits in a new month
2. Wait at least three days into the month
3. Select the "Last 2 days" filter in the Grafana dashboard

Important: The last two days should not overlap the beginning or end of a month. Make sure the "Last 2 days" are in the middle of the month.

### Anything else

I'm not sure if this is a bug or a design decision.

The SQL query appears to use the `BETWEEN` keyword in place of the `$__timeFilter` function. This results in the query looking something like this:

```sql
SELECT 
	cm.month, 
	case when d.deployment_count is null then 0 else d.deployment_count end as deployment_count
FROM 
	calendar_months cm
	LEFT JOIN _deployments d on cm.month = d.month
	WHERE cm.month_timestamp BETWEEN '2024-07-09T15:15:33.784Z' AND '2024-07-11T15:15:33.784Z'
	ORDER BY cm.month;
```

The `calendar_months` table appears to be truncating the `month_timestamp` column, so the `WHERE` clause doesn't catch anything.

Here's the full SQL query:

```sql
-- Metric 1: Number of deployments per month
with
  _deployments as (
    -- When deploying multiple commits in one pipeline, GitLab and BitBucket may generate more than one deployment. However, DevLake consider these deployments as ONE production deployment and use the last one's finished_date as the finished date.
    SELECT
      date_format(deployment_finished_date, '%y/%m') as month,
      count(cicd_deployment_id) as deployment_count
    FROM
      (
        SELECT
          cdc.cicd_deployment_id,
          max(cdc.finished_date) as deployment_finished_date
        FROM
          cicd_deployment_commits cdc
          JOIN project_mapping pm on cdc.cicd_scope_id = pm.row_id
          and pm.`table` = 'cicd_scopes'
        WHERE
          pm.project_name in ($project)
          and cdc.result = 'SUCCESS'
          and cdc.environment = 'PRODUCTION'
        GROUP BY
          1
        HAVING
          $__timeFilter (max(cdc.finished_date))
      ) _production_deployments
    GROUP BY
      1
  )
SELECT
  cm.month,
  case
    when d.deployment_count is null then 0
    else d.deployment_count
  end as deployment_count
FROM
  calendar_months cm
  LEFT JOIN _deployments d on cm.month = d.month
WHERE
  $__timeFilter (cm.month_timestamp)
```

### Version

v0.19.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @jeffschaper , it's a design decision to take the time filter when measuring DORA metrics.

**Comment by jeffschaper** [comment]
> Hi @jeffschaper , it's a design decision to take the time filter when measuring DORA metrics.

@Startrekzky - Thanks for getting back to me! Is there a way to remove these unsupported drop down filters in the Grafana dashboard?

Alternatively, does DevLake have any documentation explaining how these drop down filters are intended to work?

**Comment by jeffschaper** [comment]
> @Startrekzky - Thanks for getting back to me! Is there a way to remove these unsupported drop down filters in the Grafana dashboard?
> 
> Alternatively, does DevLake have any documentation explaining how these drop down filters are intended to work?

@Startrekzky - just checking in to see if you saw my response from a couple weeks ago. Is there a way to remove these unsupported drop down filters from the Grafana dashboard? Does DevLake have any specific documentation explaining how these drop downs are intended to work?

**Comment by Startrekzky** [comment]
> Is there a way to remove these unsupported drop down filters from the Grafana dashboard? 

Hi @jeffschaper , I just checked that this filter has been removed since v1 or earlier versions. You're still on v0.19, which is 3 major versions behind the latest version v1.0.1-rc2. 

> Does DevLake have any specific documentation explaining how these drop downs are intended to work?

Not yet. Since the embedded dashboards change rapidly, we haven't added any dashboard-related docs to the doc site. It is also not easy to describe which filters affect which panels, as a dashboard might have more than 20 panels.

**Comment by Startrekzky** [comment]
> Interesting. I'm running [v1](https://github.com/apache/incubator-devlake/releases/tag/v1.0.0) locally and I still see the "last 2 days" filter, unless I'm doing something wrong.

Hi @jeffschaper , could you take a screenshot of the dashboard? 

I forgot to ask the specific Grafana dashboard(s) you were referring to. I thought you were talking about the DORA dashboard, but it might not be true.

**Comment by jeffschaper** [comment]
> I forgot to ask the specific Grafana dashboard(s) you were referring to. I thought you were talking about the DORA dashboard, but it might not be true.

Oh, yes, good call out, it is the DORA dashboard I was referring to. Here's a screenshot.
<img width="2131" alt="Screenshot 2024-09-20 at 2 12 57 PM" src="https://github.com/user-attachments/assets/15675f73-25c3-4c6d-ba8d-6be9cb4bb648">

**Comment by Startrekzky** [comment]
@jeffschaper  Oh, you're referring to the time filter on the top-right corner. It's the embedded time filter of Grafana, all the dropdown items are determined by Grafana. We can't remove it.

**Comment by jeffschaper** [comment]
> @jeffschaper Oh, you're referring to the time filter on the top-right corner. It's the embedded time filter of Grafana, all the dropdown items are determined by Grafana. We can't remove it.

Gotcha. I assume you were thinking about the `$__timeFilter` function in the SQL query? I still think the SQL query should account for the scenario in the issue description, unless the [update you referred to](https://github.com/apache/incubator-devlake/issues/7899#issuecomment-2362020071) solves that problem?

**Comment by Startrekzky** [comment]
Hi @jeffschaper , do you mean this could be improved?
![image](https://github.com/user-attachments/assets/05463cc6-b3be-4eca-8de7-bfd7133e3d8d)

**Comment by jeffschaper** [comment]
Yeah, that's what I was thinking. In the scenario I explained above, the `WHERE` clause dates did not span between two distinct months in the `calendar_months` table, which caused the query to not return any results. Like I mentioned, I'm not sure if this is a design decision or a bug.

**Comment by Startrekzky** [comment]
Hi @jeffschaper , it could be improved for sure. I'll put up a PR later. 

Is this the only problem remained after the above discussion? If so, I'll close the issue when the PR gets merged.

**Comment by jeffschaper** [comment]
@Startrekzky - Yep! That's the only issue remaining. I appreciate your help!

**Comment by jeffschaper** [comment]
@Startrekzky - What version of DevLake will this fix be released?

**Comment by Startrekzky** [comment]
Hi @jeffschaper , I'll try to cherry-pick it to release-v1.0 to get it released sooner. The release of v1.1 seems to have a long way to go.
