### ISSUE TITLE
[Bug][jira] field_id is empty in issue_changelogs

### ISSUE THREAD

**Issue by usharerose** [apache/devlake#7911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Jira plugin's issue_changelog_convertor doesn't fill `field_id`

### What do you expect to happen

fill `field_id` value

### How to reproduce

Check the data in `issue_changelogs` table

### Version

5de490899c39b6a7e468d5ec6390b20de5e1e5b9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Resloved.
