### ISSUE TITLE
[Question][DevOps]  Deploy devlake with managed GCP Cloud database service (with SSL enabled)

### ISSUE THREAD

**Issue by pmallampati-sift** [apache/devlake#7928]
## Question
Hi currently we are trying to deploy devlake in our dev env. We are trying to integrate devlake using helm chart with managed GCP Cloud database service.
Our DB is SSL enabled and we don't see how to pass the SSL certs in the DB conn string part of helm chart.
Could you please let us know what additional params we need to use for using SSL in additional to below params we pass to helm command.
```
- `mysql.useExternal`: this should be `true`
- `mysql.externalServer`: use your RDS instance's IP address or domain name.
- `mysql.externalPort`: use your RDS instance's database port.
- `mysql.username`: use your `username` for access RDS instance's DB
- `mysql.password`: use your `password` for access RDS instance's DB
- `mysql.database`: use your RDS instance's DB name, you may need to create a database first with `CREATE DATABASE <DB name>;`
```

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by pmallampati-sift** [comment]
Per above suggestion when deployed woth above config it says unknown value `tls=custom` for tls option.
Tried with `tls=skip-verify` which gave access denied error.

```
  --from-literal=DB_URL='mysql://<your-username>:<your-password>@<dbserver>:<port>/<database>?charset=utf8mb4&parseTime=True&tls=custom' \
```

**Comment by pmallampati-sift** [comment]
Now we are seeing below error with certs installed
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1394498]

```

**Comment by pmallampati-sift** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by pmallampati-sift** [comment]
@dosu 
Hi We are seeing below error when deploying with SSL
```
"Wraps: (3) x509: cannot validate certificate for X.X.X.X(ip) because it doesn't contain any IP SANs"
```

**Comment by pmallampati-sift** [comment]
Hi Yes we are already mounting the required certs in to pod in our helm chart config
```
volumeMounts:
            - name: newcerts
              mountPath: /etc/ssl/certs
```

**Comment by pmallampati-sift** [comment]
@dosu
We are using clouds sql from GCP and in the generated ssl certs we have CN=Google Cloud SQL Server CA but missing SAN name in it.
But lake is trying to verify SAN in the certificates.
Any workarounds.

**Comment by pmallampati-sift** [comment]
Hi @dosu
I have executed above suggested steps but still I am getting same error
Also generated a `rootCA.crt` using the DB dns and placed below certs in` /etc/ssl/certs folder.
`
```
devlake-client-key.pem
devlake-client-cert.pem
devlake-server-ca.pem
rootCA.crt
```

Also places `rootCA.crt under /usr/local/share/ca-certificates` in lake container

```
Wraps: (3) x509: cannot validate certificate for 10.252.182.24 because it doesn't contain any IP SANs
```

Also in the init container I am seeing below error.

`ERROR 2024-08-23T06:13:29.444710841Z [resource.labels.containerName: update-ca-certificates] sh: update-ca-certificates: not found`

**Comment by pmallampati-sift** [comment]
@dosu

Per your if we do below step, do we still need to create the `devlake-mysql-auth` with DB url and SSL certs as you have mentioned here https://github.com/apache/incubator-devlake/issues/7928#issuecomment-2300787106

`lake:
  initContainers:
    - name: update-ca-certificates
      image: debian:bullseye
      command: ["sh", "-c", "apt-get update && apt-get install -y ca-certificates && cp /mnt/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && update-ca-certificates"]
      volumeMounts:
        - name: root-ca-cert
          mountPath: /mnt

  volumes:
    - name: root-ca-cert
      secret:
        secretName: root-ca-cert
`

**Comment by pmallampati-sift** [comment]
In that case its still not working with above suggestion I was able to get the both below init containers up and running.
- update-ca-certificates
- database-wait

But after that the lake container is still failing with 
```
Wraps: (3) x509: cannot validate certificate for 10.252.182.24 because it doesn't contain any IP SANs

```

**Comment by klesh** [comment]
It appears that MySQL SSL connections are currently not supported. For now, I recommend trying a connection without an SSL certificate.

**Comment by pmallampati-sift** [comment]
Thank you @klesh yes mysql SSL were not supported, but we were able to resolve the issue by connecting using cloudsql-auth-proxy.

**Comment by pmallampati-sift** [comment]
Hi @dosu
How to add new plugins to devlake using helm chart.

**Comment by pmallampati-sift** [comment]
hi @dosu
Can we integrate devlake with OKTA SSO config....?

**Comment by pmallampati-sift** [comment]
@dosu
How do I get value of OAUTH2_PROXY_COOKIE_SECRET to configure oauth2-proxy....?

**Comment by pmallampati-sift** [comment]
@dosu
Per suggestion I have added the `oauth2-proxy,` but still I get basic auth username/password pop up coming up.

Do we need to delete the pod resources and recreate from scratch...?

**Comment by pmallampati-sift** [comment]
@dosu
Did configuration per above message. I can see ingress got added but oauth2-proxy pod is not coming up.
I can only see 2 pods dev-lake and UI.
```
NAME                            READY   STATUS    RESTARTS        AGE
devlake-lake-   2/2     Running   1 (4m15s ago)   4m16s
devlake-ui    1/1     Running   0               4m16s
```

**Comment by pmallampati-sift** [comment]
Hi @dosu

We are have forked https://github.com/apache/incubator-devlake repo and developed a new internal custom plugin.
Now how can we generate a new devlake image to include new plugin and deploy it in our own cloud using helm chart.

Thanks in advance.

**Comment by pmallampati-sift** [comment]
Thank you @dosu

Can you also send me details on how to generate a image just for plugin by itself and have the plugin image in helm values file.

**Comment by nishasati6oct** [comment]
My helm chart looks like below
lake:
      initContainers:
        - name: update-ca-certificates
          image: debian:bullseye
          command: ["sh", "-c", "apt-get update && apt-get install -y ca-certificates && cp /mnt/root-ca-cert /usr/local/share/ca-certificates/root-ca-cert && update-ca-certificates"]
          volumeMounts:
            - name: root-ca-cert
              mountPath: /mnt
      volumes:
        - name: root-ca-cert
          secret:
            secretName: ca-cert
      envs:
        API_TIMEOUT: "120s"
        API_RETRY: "3"
        API_REQUESTS_PER_HOUR: "10000"
        PIPELINE_MAX_PARALLEL: "1"
        IN_SECURE_SKIP_VERIFY: "true"
        
here ca-cert is the SOPS secret for ca-cert.crt data. I am trying to use SSL integration for Azure MySQL.

Error: 
Defaulted container "lake" out of: lake, waiting-database-ready (init)
time="2024-10-07T08:12:36Z" level=info msg="no [.env] file, devlake will read configuration from environment, please make sure you have set correct environment variable."
Version:  v1.0.1@e061ef2
panic: open /usr/local/share/ca-certificates/root-ca-cert: no such file or directory
Wraps: (2) open /usr/local/share/ca-certificates/root-ca-cert
Wraps: (3) no such file or directory
Error types: (1) *hintdetail.withDetail (2) *fs.PathError (3) syscall.Errno
