### ISSUE TITLE
[Bug][Sonarqube] No option to add scope config even though documentation suggests

### ISSUE THREAD

**Issue by sanjchhoker** [apache/devlake#7931]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Add sonarqube connection and add data scope to the connection - I can see data scopes coming through but cannot see scope config option.
It’s all just N/A 
![IMG_6953](https://github.com/user-attachments/assets/12c446c5-01c2-44c1-a77e-5fc972930c43)

### What do you expect to happen

Expect to see option to add scope config and only then we can get DORA metrics

### How to reproduce

Add sonarqube connection and the add data scope.

### Version

v1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sanjchhoker** [comment]
fyi I am using Sonarqube enterprise v10.6

**Comment by klesh** [comment]
What document were you referring to?
I can clearly see that Sonarqube data source doesn't have any scope config: https://devlake.apache.org/docs/Configuration/SonarQube#step-3---adding-transformation-rules-optional

**Comment by sanjchhoker** [comment]
Step 2 Data entities
https://devlake.apache.org/docs/Configuration/SonarQube/

**Comment by klesh** [comment]
@sanjchhoker I see. 
Sorry for missing the point, my brain somehow filtered the section completely for me. 😂

**Comment by Startrekzky** [comment]
Hi @sanjchhoker , the docs have been updated by: https://github.com/apache/incubator-devlake-website/pull/787

You'll see the latest doc after it gets merged.

**Comment by Startrekzky** [comment]
The updated sonarqube doc: https://devlake.apache.org/docs/Configuration/SonarQube/
