### ISSUE TITLE
[Question][DevOps] ECS Deployment Task Definition

### ISSUE THREAD

**Issue by amokkapati** [apache/devlake#7934]
I'm trying to deploy a task with the following ECS definition, but the Grafana and Config-UI containers always fail to start which doesnt allow for deployment, what do I need to fix?

{
    "family": "devlake-containers-tasks-localsql",
    "containerDefinitions": [
        {
            "name": "devlake",
            "image": "apache/devlake:v1.0.0",
            "cpu": 768,
            "memory": 2048,
            "memoryReservation": 1024,
            "portMappings": [
                {
                    "name": "devlake-port",
                    "containerPort": 8080,
                    "hostPort": 8080,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "restartPolicy": {
                "enabled": true
            },
            "environment": [
                {
                    "name": "FORCE_MIGRATION",
                    "value": "false"
                },
                {
                    "name": "DB_LOGGING_LEVEL",
                    "value": "Error"
                },
                {
                    "name": "API_RETRY",
                    "value": "3"
                },
                {
                    "name": "TZ",
                    "value": "UTC"
                },
                {
                    "name": "MODE",
                    "value": "release"
                },
                {
                    "name": "PLUGIN_DIR",
                    "value": "bin/plugins"
                },
                {
                    "name": "ENDPOINT_CIDR_BLACKLIST",
                    "value": ""
                },
                {
                    "name": "LOGGING_LEVEL",
                    "value": ""
                },
                {
                    "name": "API_TIMEOUT",
                    "value": "120s"
                },
                {
                    "name": "ENABLE_STACKTRACE",
                    "value": "false"
                },
                {
                    "name": "IN_SECURE_SKIP_VERIFY",
                    "value": "false"
                },
                {
                    "name": "DB_URL",
                    "value": "mysql://merico:merico@mysql:3306/lake?charset=utf8mb4&parseTime=True&loc=UTC"
                },
                {
                    "name": "FORBID_REDIRECTION",
                    "value": "false"
                },
                {
                    "name": "API_REQUESTS_PER_HOUR",
                    "value": "10000"
                },
                {
                    "name": "E2E_DB_URL",
                    "value": "mysql://merico:merico@mysql:3306/lake_test?charset=utf8mb4&parseTime=True&loc=UTC"
                },
                {
                    "name": "PIPELINE_MAX_PARALLEL",
                    "value": "1"
                },
                {
                    "name": "ENCRYPTION_SECRET",
                    "value": "\"ZSAZPUQWGJMCSJSNXMEUSBHIHYGAGAFDPPKOOGKATPWWIWMLLNXTYKYXXXHHNJOUJHSATRVZZYURRLLBDHPSZANIXONNNYNDHVDZRAKBWMUNVLLHMFULTHRBYJDETOAE\""
                },
                {
                    "name": "NOTIFICATION_ENDPOIN",
                    "value": ""
                },
                {
                    "name": "LOGGING_DIR",
                    "value": "/app/logs"
                },
                {
                    "name": "NOTIFICATION_SECRET",
                    "value": ""
                }
            ],
            "mountPoints": [
                {
                    "sourceVolume": "devlake-log",
                    "containerPath": "/app/logs",
                    "readOnly": false
                }
            ],
            "volumesFrom": [],
            "dependsOn": [
                {
                    "containerName": "mysql",
                    "condition": "START"
                }
            ],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/",
                    "mode": "non-blocking",
                    "awslogs-create-group": "true",
                    "max-buffer-size": "25m",
                    "awslogs-region": "ca-central-1",
                    "awslogs-stream-prefix": "ecs"
                },
                "secretOptions": []
            },
            "systemControls": []
        },
        {
            "name": "devlake-config-ui",
            "image": "apache/devlake-config-ui:v1.0.0",
            "cpu": 768,
            "memory": 2048,
            "memoryReservation": 1024,
            "portMappings": [
                {
                    "name": "devlake-config-ui-port",
                    "containerPort": 4000,
                    "hostPort": 4000,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "environment": [
                {
                    "name": "FORCE_MIGRATION",
                    "value": "false"
                },
                {
                    "name": "DB_LOGGING_LEVEL",
                    "value": "Error"
                },
                {
                    "name": "API_RETRY",
                    "value": "3"
                },
                {
                    "name": "TZ",
                    "value": "UTC"
                },
                {
                    "name": "MODE",
                    "value": "release"
                },
                {
                    "name": "NOTIFICATION_ENDPOINT",
                    "value": ""
                },
                {
                    "name": "PLUGIN_DIR",
                    "value": "bin/plugins"
                },
                {
                    "name": "ENDPOINT_CIDR_BLACKLIST",
                    "value": ""
                },
                {
                    "name": "LOGGING_LEVEL",
                    "value": ""
                },
                {
                    "name": "API_TIMEOUT",
                    "value": "120s"
                },
                {
                    "name": "ENABLE_STACKTRACE",
                    "value": "false"
                },
                {
                    "name": "IN_SECURE_SKIP_VERIFY",
                    "value": "false"
                },
                {
                    "name": "GRAFANA_ENDPOINT",
                    "value": "grafana:3000"
                },
                {
                    "name": "DEVLAKE_ENDPOINT",
                    "value": "devlake:8080"
                },
                {
                    "name": "DB_URL",
                    "value": "mysql://merico:merico@mysql:3306/lake?charset=utf8mb4&parseTime=True&loc=UTC"
                },
                {
                    "name": "FORBID_REDIRECTION",
                    "value": "false"
                },
                {
                    "name": "API_REQUESTS_PER_HOUR",
                    "value": "10000"
                },
                {
                    "name": "E2E_DB_URL",
                    "value": "mysql://merico:merico@mysql:3306/lake_test?charset=utf8mb4&parseTime=True&loc=UTC"
                },
                {
                    "name": "PIPELINE_MAX_PARALLEL",
                    "value": "1"
                },
                {
                    "name": "ENCRYPTION_SECRET",
                    "value": "\"ZSAZPUQWGJMCSJSNXMEUSBHIHYGAGAFDPPKOOGKATPWWIWMLLNXTYKYXXXHHNJOUJHSATRVZZYURRLLBDHPSZANIXONNNYNDHVDZRAKBWMUNVLLHMFULTHRBYJDETOAE\""
                },
                {
                    "name": "LOGGING_DIR",
                    "value": "./logs"
                },
                {
                    "name": "NOTIFICATION_SECRET",
                    "value": ""
                }
            ],
            "mountPoints": [],
            "volumesFrom": [],
            "dependsOn": [
                {
                    "containerName": "devlake",
                    "condition": "START"
                }
            ],
            "systemControls": []
        },
        {
            "name": "grafana",
            "image": "apache/devlake-dashboard:v1.0.0",
            "cpu": 768,
            "memory": 2048,
            "memoryReservation": 1024,
            "portMappings": [
                {
                    "name": "grafana-tcp",
                    "containerPort": 3000,
                    "hostPort": 3000,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "restartPolicy": {
                "enabled": true
            },
            "environment": [
                {
                    "name": "MYSQL_DATABASE",
                    "value": "lake"
                },
                {
                    "name": "MYSQL_PASSWORD",
                    "value": "merico"
                },
                {
                    "name": "MYSQL_URL",
                    "value": "mysql:3306"
                },
                {
                    "name": "MYSQL_USER",
                    "value": "merico"
                },
                {
                    "name": "TZ",
                    "value": "UTC"
                },
                {
                    "name": "GF_USERS_DEFAULT_THEME",
                    "value": "\"light\""
                },
                {
                    "name": "GF_SERVER_ROOT_URL",
                    "value": "\"http://localhost:4000/grafana\""
                }
            ],
            "mountPoints": [
                {
                    "sourceVolume": "grafana-storage",
                    "containerPath": "/var/lib/grafana",
                    "readOnly": false
                }
            ],
            "volumesFrom": [],
            "dependsOn": [
                {
                    "containerName": "mysql",
                    "condition": "START"
                }
            ],
            "systemControls": []
        },
        {
            "name": "mysql",
            "image": "mysql:8",
            "cpu": 768,
            "memory": 2048,
            "memoryReservation": 1024,
            "portMappings": [
                {
                    "name": "my-sql-port",
                    "containerPort": 3306,
                    "hostPort": 3306,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "restartPolicy": {
                "enabled": true
            },
            "command": [
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_bin",
                "--skip-log-bin"
            ],
            "environment": [
                {
                    "name": "MYSQL_DATABASE",
                    "value": "lake"
                },
                {
                    "name": "MYSQL_PASSWORD",
                    "value": "merico"
                },
                {
                    "name": "MYSQL_ROOT_PASSWORD",
                    "value": "admin"
                },
                {
                    "name": "MYSQL_USER",
                    "value": "merico"
                },
                {
                    "name": "TZ",
                    "value": "UTC"
                }
            ],
            "mountPoints": [
                {
                    "sourceVolume": "mysql-storage",
                    "containerPath": "/var/lib/mysql",
                    "readOnly": false
                }
            ],
            "volumesFrom": [],
            "systemControls": []
        }
    ],
    "executionRoleArn": "arn:aws:iam::32985728957298:role/ecsTaskExecutionRole",
    "networkMode": "awsvpc",
    "volumes": [
        {
            "name": "grafana-storage",
            "host": {}
        },
        {
            "name": "devlake-log",
            "host": {}
        },
        {
            "name": "mysql-storage",
            "host": {}
        }
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "4096",
    "memory": "8192",
    "runtimePlatform": {
        "cpuArchitecture": "X86_64",
        "operatingSystemFamily": "LINUX"
    }
}

**Comment by ZhangNing10** [comment]
hi @amokkapati , what are the errors of Grafana and Config-UI ?
