### ISSUE TITLE
[Question][Grafana] Grafana Permission Error

### ISSUE THREAD

**Issue by amokkapati** [apache/devlake#7946]
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later 
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable. 

Getting this error when I try to deploy the grafana container image in ECS. Every other service is working.

Grafana "image": "devlake.docker.scarf.sh/apache/devlake-dashboard:v1.0.0",

**Comment by amokkapati** [comment]
@dosu 
how do I put this into an ECS Task definition

**Comment by amokkapati** [comment]
@dosu 
How do I initiate these commands in my docker configuration command settings with Fargate launch type
chown -R <personal local user> /path/to/local/volume/folder && \
chmod -R 777 /path/to/local/volume/folder

**Comment by ZhangNing10** [comment]
@amokkapati are you deploy the devlake stack in ecs via docker-compose.yml？ can i have a look at the yml content?

**Comment by ZhangNing10** [comment]
hi @amokkapati , maybe you can try below solutions to see which solution can solve your issue
1. use root user
"containerDefinitions": [
    {
        "name": "grafana",
        "image": "grafana/grafana",
        "user": "root",
        ...
    }
]

2. change the host directory permission
"volumes": [
    {
        "name": "grafana-data",
        "host": {
            "sourcePath": "/path/to/host/directory"
        }
    }
],
"containerDefinitions": [
    {
        "name": "grafana",
        "image": "grafana/grafana",
        "mountPoints": [
            {
                "sourceVolume": "grafana-data",
                "containerPath": "/var/lib/grafana"
            }
        ],
        ...
    }
]
Then ensure that the /path/to/host/directory has the correct permissions set:
sudo chown -R 472:472 /path/to/host/directory
