### ISSUE TITLE
[Bug][Dashboard] Change Failure Rate Metric Different between Dashboards

### ISSUE THREAD

**Issue by tc-jason-gregory** [apache/devlake#7971]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

On the DORA home dashboard, the Change Failure Rate shows one value. When you drill into the data and go to the "DORA Details - Change Failure Rate" page, the value is different.
![home-CFR](https://github.com/user-attachments/assets/3356ece2-18ba-4324-a0d8-e1fd755c328b)
![detail-CFR](https://github.com/user-attachments/assets/804b12d3-d0c3-4ec4-9270-8b2b8005e314)

### What do you expect to happen

I expected the values to be the same.

### How to reproduce

On the DORA home dashboard, the Change Failure Rate shows one value. When you drill into the data and go to the "DORA Details - Change Failure Rate" page, the value is different.

### Anything else

I noted the queries are different for incident counting l as follows...

1. The first query counts incidents using this logic:

`count(
  distinct case
    when i.id is not null then d.deployment_id
    else null
  end
) as has_incident`

This effectively counts the deployment if it is linked to any incident.

2. The second query simplifies it to:

`count(distinct i.id) as has_incident`

This directly counts the distinct incident IDs, which might yield different results depending on how deployments are linked to incidents.

### Version

v1.0.1-beta7@3f84bae

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@Startrekzky Please take a look.
