### ISSUE TITLE
[Feature][config-ui] usermanagement with different roles

### ISSUE THREAD

**Issue by pimperator** [apache/devlake#7982]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

For now config-ui does not provide any kind of usermanagement.
This means: basically everyone can modify every and anything on config-ui.
* Introducing different roles like 
  - admin: access to everything; probably not needed atm
  - rw: ability to add and modify blueprints
  - ro: read configuration but unable to modify anything
* map userdata from SAML

also it would be good to track changes depending on the user who did what changes (and depend api keys on that user).

### Description

introduce different roles to config-ui and use data from saml for tracking changes/creations

I am aware that there is a possibility to do [TeamConfiguration](https://devlake.apache.org/docs/v0.15/UserManuals/TeamConfiguration) but thb using data from saml is much more comfortable than creating users on the sql cli.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
try enabling these 2 environmental variables:
https://github.com/apache/incubator-devlake/blob/main/devops/releases/lake-v0.21.0/docker-compose.yml#L78C1-L79C26
