### ISSUE TITLE
[Database][DORA] : db query error: Error 1054: Unknown column 'db.dora_report' in 'where clause'

### ISSUE THREAD

**Issue by ravisanrjy** [apache/devlake#7983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am getting below error while extracting the DORA metrics

db query error: Error 1054: Unknown column 'db.dora_report' in 'where clause'

### What do you expect to happen

Because of this i could not able to see the DORA metrics, i created the connections for Jira, GitHub and Jenkins

### How to reproduce

I created the connections for Jira , GitHub and Jenkins and collect data. Jira , GitHub and Jenkins Dashboard are coming good where as when i try to access the DORA metrics , i am getting this error because of this i could not able to see the DORA metrics

### Version

v0.17.0-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ravisanrjy** [comment]
Thank you let me try

**Comment by klesh** [comment]
Please try the latest version and see if the problem gone.

**Comment by klesh** [comment]
Unable to reproduce
