### ISSUE TITLE
[Bug][config UI] removing webhook from project deletes the webhook entirely 

### ISSUE THREAD

**Issue by KyriosGN0** [apache/devlake#8001]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

i tried to remove a webhook from a project but it deleted the webhook instead 

### What do you expect to happen

webhook not being deleted 

### How to reproduce

create a webhook and assign it to a project
then remove it from a project and see that it doesn't exist it 

### Version

v1.0.1-beta7@3f84bae

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
To clarify, did you click on the following button?
![image](https://github.com/user-attachments/assets/9af38b9e-8e18-453b-93e6-6e7649d90999)

**Comment by KyriosGN0** [comment]
@klesh yes

**Comment by Startrekzky** [comment]
This fix will be included in the next tag.
