### ISSUE TITLE
[Bug][Github] GraphQL API requests will eventually fail forever collecting large repositories data

### ISSUE THREAD

**Issue by ClaudioMascaro** [apache/devlake#8028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We are facing trouble trying to collect data from a few very large repositories. This one in question has 57,425 workflow runs, with some of them having about 175 job runs. Eventually the stage fails retrying graphql api requests until token expires, without any success:
![image](https://github.com/user-attachments/assets/a220f2b0-1b34-4c61-99b5-78b66e6a2c94)

### What do you expect to happen

This is a key project for our company, and there are other projects with the same problem. We are expecting to delivery metrics for our teams. we are using API_TIMEOUT: "120s" and API_RETRY: "20", but it doesn't seem that will resolve the problem increasing more.

### How to reproduce

Adding a project for a large repository and collecting data. We run 2 pipelines at once, but when running this pipeline without concurrency, it will fails even earlier.

### Version

v0.21.0-rc1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
V0.21 is not supported anymore.
I recommend you try the latest version of v1.0.1 beta since it fixes some Github bugs and has some improvements that might help your situation.

**Comment by BhoopalanI** [comment]
I faced a similar issue in the latest version v1.0.1@e061ef2. My issue is that the pipeline shows data collected successfully. However, not all Github data is collected. I'm testing it with PRs. I tested trying to pull entire PR data using the query in the db:   
`select`  
`*`  
`from`   
`pull_requests`  
  
This is supposed to show the entire PR data. However, the data is collected only until March of 2024. I'm missing close to 400 PRs which were created before March of 2024.   
  
Below is part of the log of the pipeline:   
`time="2024-10-03 09:00:37" level=info msg=" [pipeline service] [pipeline #1] [task #2] executing subtask Collect Pull Requests" time="2024-10-03 09:00:37" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] start graphql collection" time="2024-10-03 09:00:38" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 1(not exactly)" time="2024-10-03 09:00:41" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 5(not exactly)" time="2024-10-03 09:00:45" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 9(not exactly)" time="2024-10-03 09:00:48" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 12(not exactly)" time="2024-10-03 09:00:51" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 15(not exactly)" time="2024-10-03 09:00:54" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 18(not exactly)" time="2024-10-03 09:00:58" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 21(not exactly)" time="2024-10-03 09:01:01" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 24(not exactly)" time="2024-10-03 09:01:04" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 27(not exactly)" time="2024-10-03 09:01:08" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 30(not exactly)" time="2024-10-03 09:01:11" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 33(not exactly)" time="2024-10-03 09:01:14" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 36(not exactly)" time="2024-10-03 09:01:18" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 40(not exactly)" time="2024-10-03 09:01:21" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 43(not exactly)" time="2024-10-03 09:01:26" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 46(not exactly)" time="2024-10-03 09:01:29" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 50(not exactly)" time="2024-10-03 09:01:32" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 53(not exactly)" time="2024-10-03 09:01:36" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 56(not exactly)" time="2024-10-03 09:01:39" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 59(not exactly)" time="2024-10-03 09:01:43" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 63(not exactly)" time="2024-10-03 09:01:46" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 66(not exactly)" time="2024-10-03 09:01:49" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 69(not exactly)" time="2024-10-03 09:01:52" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 72(not exactly)" time="2024-10-03 09:01:56" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 76(not exactly)" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] collector finish by parser" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] finished records: 79(not exactly)" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] ended api collection without error" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] start graphql collection" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Collect Pull Requests] ended api collection without error" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] subtask Collect Pull Requests finished in 82507 ms" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] finished step: 5 / 36" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] executing subtask Extract Pull Requests" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Extract Pull Requests] get data from _raw_github_graphql_prs where params={\"ConnectionId\":1,\"Name\":\"<org>/<repo>\"} and got 779" time="2024-10-03 09:01:59" level=info msg=" [pipeline service] [pipeline #1] [task #2] [Extract Pull Requests] finished records: 1(not exactly)" time="2024-10-03 09:02:00" level=info msg=" [pipeline service] [pipeline #1] [task #2] subtask Extract Pull Requests finished in 810 ms"`

**Comment by klesh** [comment]
@BhoopalanI I think it worked fine, the collector would stop when pipelines are out of date range specified in the Project's  Sync Policy.

**Comment by ClaudioMascaro** [comment]
@klesh We just upgraded devlake to latest version and still didn't work.

After finishing a Extract Workflow Runs with a large volume of data, the Collect Job Runs task retries until failure right after it starts, probably caused by a wrong graphql query, just like the screenshot I sent before.

Here is a new screenshot from the new version:

![devlake-issue](https://github.com/user-attachments/assets/7f620a94-3400-4528-b84b-9f3ce5d38d7c)

**Comment by ClaudioMascaro** [comment]
@abeizn

**Comment by ClaudioMascaro** [comment]
I've drafted a PR with an implementation that might be the solution for this case: https://github.com/apache/incubator-devlake/pull/8233
