### ISSUE TITLE
[Feature] Slack Notifications on Metrics Thresholds

### ISSUE THREAD

**Issue by SiliconSatchel** [apache/devlake#8029]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a developer, I want to receive notifications in Slack when certain metrics cross configurable thresholds.

### Description

DevLake provides a configuration option that lets the user specify a list of metrics, with a threshold value and a direction. When a metric crosses its threshold in the configured direction, e.g. the pipeline failure rate goes above 20%, a notification is sent to slack. When the metric crosses back to the desired side of the threshold, another notification is sent.

### Related issues

This closed feature request mentions Slack notifications: https://github.com/apache/incubator-devlake/issues/5636

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seeljugh** [comment]
A workaround for this is to use Grafana to send notifications based on metrics.
