### ISSUE TITLE
[Bug][DORA] Webhook Deployment not appearing in DORA metrics dashboard

### ISSUE THREAD

**Issue by vincentpatella** [apache/devlake#8059]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I set up a project with only a webhook as the data input and made an api call on my local machine to generate a deployment.  The API call returns a success code, and I see the deployment when I look at the lake.cicd_deployments and  lake.cicd_deployments_commits tables, but I don't see a mapping for it in the lake.cicd_scopes table, which I think is the main issue.  Because there's no mapping for lake.cicd_scopes (there are mappings for my jenkins and AzureDevOps deployment pipelines), it doesn't show up in the DORA metrics dashboard.  I followed the steps here to set it up: https://devlake.apache.org/docs/Configuration/webhook/

### What do you expect to happen

I expect the deployment to show up on the DORA metrics dashboard like it does for my Jenkins and Azure DevOps deployments.

### How to reproduce

1. Create a new project named Webhook Test
2. Create a new webhook and name it Webhook Test
3. Run Collect Data
4. Create an API key to authenticate with DevLake
5. Make the following API call (using your own url):

  curl http://localhost:4000/api/rest/plugins/webhook/9/deployments -X 'POST' -H 'Authorization: Bearer {MY_API_KEY}' -d '{
    "id": "Test 2",
    "createdDate":"2024-09-02T11:00:00+00:00",
    "startedDate":"2024-09-02T12:00:00+00:00",
    "finishedDate":"2024-09-03T13:00:00+00:00",
    "environment":"PRODUCTION",
    "result": "SUCCESS",
    "displayTitle":"optional-custom-deploy-display-title",
    "name": "Test Name",
    "deploymentCommits":[
       {
           "repoUrl":"required-repo-url",
           "refName": "optional-release-v0.17",
           "startedDate":"2024-01-01T11:00:00+00:00",
           "finishedDate":"2024-01-02T11:00:00+00:00",
           "commitSha":"c1",
           "commitMsg":"optional-msg-1",
           "result":"SUCCESS",
           "name":"Test Commit 1",
           "displayTitle":"Test Commit 1"
       },
       {
           "repoUrl":"repo-2",
           "refName": "optional-release-v0.17",
           "startedDate":"2024-01-01T11:00:00+00:00",
           "finishedDate":"2024-01-02T11:00:00+00:00",
           "commitSha":"c2",
           "commitMsg":"optional-msg-2",
           "result":"FAILURE",
           "name":"Test Commit 2",
           "displayTitle":"Test Commit 2"
       }
    ]
  }'

6. Run Collect Data
7. Check the DORA or DORA Details - Deployment Frequency dashboard

### Anything else

I have tried multiple projects and multiple webhooks, but still have this problem with each one.

### Version

v1.0.1-beta8@e195107

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vincentpatella** [comment]
Hi, I had already looked at that issue and it did not help.  The webhook is also already associated with a project and I copied the payload from the Webhook documentation for the fields before editing the data to match what a typical deployment would expect.

**Comment by Startrekzky** [comment]
Hi @vincentpatella , we'll look into this problem.

**Comment by xiaomingzhang12** [comment]
Hi @vincentpatella , I followed the steps you provided with two differences:

The URL’s IP and API key are from my own environment.
In the POST request, I updated deploymentCommits[0].startedDate and deploymentCommits[0].finishedDate to more recent dates. Other than that, everything remained the same.
After completing the steps, I checked the Deployment Frequency dashboard, and there is data, as shown in the attached screenshot. 
![img_v3_02f1_9602e126-def9-462a-8de4-b29da3f0a69g](https://github.com/user-attachments/assets/0eaac654-8b57-4797-b244-45fbfb3f3577)
![img_v3_02f1_e15e0d28-e23d-4749-94a1-25968aae4ffg](https://github.com/user-attachments/assets/021a25b3-b53a-4593-b583-f250cd1eccbd)

Could you confirm if the data in the screenshot is what you were expecting?
