### ISSUE TITLE
SonarQube Pipelines run successfully but no data in dashboard - v1.0.2-beta1

### ISSUE THREAD

**Issue by srinathsankara** [apache/devlake#8091]
Looks like SonarQube Dashboard is crashing. After successful import using pipelines, dashboard has no data.

![image](https://github.com/user-attachments/assets/2257a32d-2450-4725-a9d3-8b0648c2c24c)

**Comment by klesh** [comment]
Looks like a known issue to me. Can you confirm? @Startrekzky

**Comment by mrpaapi** [comment]
Apologies, I'm not sure what is a known issue? Does this mean that it current releases have issue with SonarQube integration and data wont work?

**Comment by mrpaapi** [comment]
I ran this but still no Luck

can you run the following scripts to change collation, then run the sonarqube bp again:
ALTER TABLE _tool_sonarqube_projects CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_issues CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_issue_code_blocks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_hotspots CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_file_metrics CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE _tool_sonarqube_accounts CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE cq_projects CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE cq_issues CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE cq_issue_code_blocks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE cq_file_metrics CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

**Comment by mrpaapi** [comment]
Any update please?

**Comment by VadimVoykin** [comment]
Hello @Startrekzky!
We managed to determine that the issue lies in the Grafana queries. In order to fix it, we changed the Data Source of each "Panel" from "Mixed" to "mysql" and changed the table in the query by appending the "lake." prefix.
<img width="578" alt="2024-10-01_09h13_18" src="https://github.com/user-attachments/assets/8418f297-9c7e-4901-8ba4-caae896709e8">
