### ISSUE TITLE
Apache DevLake - v1.0.1 - Manifest not found error - Unable to install using docker

### ISSUE THREAD

**Issue by srinathsankara** [apache/devlake#8092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/b70b71af-ee70-4b99-9259-a275226bd0d6)

### What do you expect to happen

Unable to install using docker

### How to reproduce

Unable to install using docker

### Anything else

Unable to install using docker

### Version

v1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mrpaapi** [comment]
@Dosu - I have downloaded the .env and docker-compose from the location. I see that the paths are right but still i get this error.

**Comment by mrpaapi** [comment]
using latest worked.
