### ISSUE TITLE
[Question][JIRA PLugin] JIRA Issue and commit link pattern

### ISSUE THREAD

**Issue by sanjchhoker** [apache/devlake#8096]
## Question
I am trying to setup JIRA issue and github commit remote link pattern but anything and everything I try keeps on giving me below error message
missing {namespace} (400).
I have tried both options of directly specifying pattern and using development panel but got same error.
Wondering if anyone has managed to set this up and can share a working example please ? 

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by sanjchhoker** [comment]
@dosu can you share any real example of this pattern working please.

**Comment by sanjchhoker** [comment]
@dosu both of the above doesn’t work and still says namespace not found

**Comment by kulnagar** [comment]
I think the conditions in the code are wrong.
https://github.com/apache/incubator-devlake/blob/main/backend/plugins/jira/api/scope_config_api.go#L331

**Comment by klesh** [comment]
@kulnagar Why do you say so? Would you like to elaborate?

**Comment by sanjchhoker** [comment]
@klesh I have tried this with different combination.Below code snippet expects a string which is {namepsace} not the actual value. 
If you put actual value of your github org and/or repository name the UI validation keeps on failing and complaining about missing namespace. 
However if you put hard coded string "{namespace}" which isn't correct then UI validation works but regex generation fails(as expected). 
Hence this UI validation seems incorrect where instead of actual org value it's looking for string "{namespace}".


```
if !strings.Contains(input, "{namespace}") {
		return errors.BadInput.New("missing {namespace}")
	}
```
