### ISSUE TITLE
[Bug][Refresh] Unable to delete data and collect again

### ISSUE THREAD

**Issue by pamflores-clip** [apache/devlake#8113]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have a record in the DB that is not correctly updated. 
In github, this ticket has an updated date of september:
<img width="639" alt="Screenshot 2024-09-27 at 11 34 26 a m" src="https://github.com/user-attachments/assets/6c0f6024-7c88-43ed-b809-ad2d003e2ee4">

and in the DB the updated date is in march:
<img width="930" alt="Screenshot 2024-09-27 at 10 28 40 a m" src="https://github.com/user-attachments/assets/40dd4dcd-d138-486a-b779-f3c9373f79c8">

### What do you expect to happen

I was searching for a way to delete all of the data that is in a project without deleting the actual project

### How to reproduce

I have already tried the Collect Data in Full Refresh Mode but still is not updated in DB

### Anything else

We updated our devlake version in August

### Version

v1.0.1-beta7@3f84bae

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
@pamflores-clip , thanks for reporting. We'll look at it.

**Comment by xiaomingzhang12** [comment]
Hi @pamflores-clip ,  In the database, the update_date field represents when the data itself was last updated, while the update_at field indicates when it was updated in the database. Could you check if the update_at field shows the time you were expecting?  Thank you
![image](https://github.com/user-attachments/assets/a652e8e3-e127-4f9e-9565-b56a9c28bd85)

**Comment by pamflores-clip** [comment]
hi @xiaomingzhang12 , sorry maybe I wrote this incorrectly or is misleading
the big thing is that the column status is not changing or not reflecting the Closed status (purple) that is seen in Git's UI
