### ISSUE TITLE
Azure MySQL flexible server integration with ApacheDevlake helm chart

### ISSUE THREAD

**Issue by nishasati6oct** [apache/devlake#8121]
I am using sops secret for the below values

MYSQL_USER
MYSQL_PASSWORD
MYSQL_DATABASE
DB_URL

and in the helm chart using the below section for mysql
mysql:
      # if use external mysql server, please set true
      # by default using false, chart will create a single mysql instance
      useExternal: true
      # the external mysql server address
      externalServer: xxxxxx.mysql.database.azure.com/ (we are using MySQL 8.0)
      # external mysql port
      externalPort: 3306

Error:  
panic: Error 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON.
Wraps: (2) Error 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON.
Error types: (1) *hintdetail.withDetail (2) *mysql.MySQLError

How can I mount the secret for DigiCertGlobalRootCA.crt.pem certificate path to be used in the DevLake Helm chart???

**Comment by GuillermoGarciaF** [comment]
Same issue here, we need the Apache DevLake helm chart to support mounting certificates or other secrets

**Comment by nishasati6oct** [comment]
we solved our problem with the below update in helm chart
postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: devlake-lake
            patch: |-
              - op: add
                path: /spec/template/spec/volumes
                value: []  # Creates an empty volumes array if it doesn't exist
              - op: add
                path: /spec/template/spec/volumes/-
                value: 
                  name: ca-cert
                  secret:
                    secretName: ca-cert
                    namespace: devlake
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts
                value: []  # Creates an empty volumeMounts array if it doesn't exist
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: ca-cert
                  mountPath: /usr/local/share/ca-certificates/root-ca-cert
                  readOnly: true
                  subPath: ca-cert.crt
