### ISSUE TITLE
[Bug][Module Name] JIRA Issue and commit link pattern condition incorrect

### ISSUE THREAD

**Issue by kulnagar** [apache/devlake#8128]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Input validation set in api incorrectly checks for hard coded pattern.
https://github.com/apache/incubator-devlake/blob/main/backend/plugins/jira/api/scope_config_api.go#L331
https://github.com/apache/incubator-devlake/blob/main/backend/plugins/jira/api/scope_config_api.go#L334
https://github.com/apache/incubator-devlake/blob/main/backend/plugins/jira/api/scope_config_api.go#L337

### What do you expect to happen

Condition should check if real value is provided or not.

### How to reproduce

Add any real example of a commit from github

### Version

v1.0.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Looking forward to your PR. 🌹
