### ISSUE TITLE
[Bug][Module Name] Enterprise Github Plugin Collects only X number of Data - Devlake Version:  v1.0.1@e061ef2

### ISSUE THREAD

**Issue by BhoopalanI** [apache/devlake#8131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have a github repo which has more than 1200 PRs. I'm trying to populate the data into my Devlake DB. However, Devlake collects only most recent 800 PRs. More than 400 PRs which are the oldest aren't collected. I tested this by quering the DB with the following queries:
```
select
*
from 
	_raw_github_api_pull_requests
```
```
select
*
from 
	pull_requests
```

I have also attached the log of the Github data collection. 

Version:  v1.0.1@e061ef2
[oct_3_local.zip](https://github.com/user-attachments/files/17277557/oct_3_local.zip)

### What do you expect to happen

The Github Plugin is meant to collect all the data from oldest to most recent

### How to reproduce

Please collect data from a large repository and test with the above mentioned query. The older data wouldn't be collected. 

### Version

v1.0.1@e061ef2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Please check if they were created earlier than **Time After** from your project under the Sync policy section.

**Comment by BhoopalanI** [comment]
@klesh Got it to work as expected after following your instructions. Thank you. This can be considered closed.
