### ISSUE TITLE
[Bug][DoraDashboard] Dora metrics not populating

### ISSUE THREAD

**Issue by ajayesf** [apache/devlake#8135]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have configured an project with Jira, Azure Devops and Github connects. Also configured all connection with right scope configs. Eventhought we are able to polulate the dta in all tables, none of the Dora metrcs are updating with any data.

### What do you expect to happen

We need to see all possible Dora merics based on the connection configured.
Attched the screenshot for reference

### How to reproduce

Just configure all connection and run the pipeline. and Go to dashboard and observe the the values populating
![Capture](https://github.com/user-attachments/assets/ac6f80b7-e595-4022-a29b-62e63fd4b8c9)

### Anything else

nothing

### Version

v1.0.1@e061ef2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EhteshamMohsin** [comment]
Hi team,
We are still not able to see the Dora metrics under the dashboards and we have checked all connections from Jira to Azure devops and GitHub are under place. Can you please provide further suggestions. 

Thanks,
