### ISSUE TITLE
DB Migration Failing

### ISSUE THREAD

**Issue by srinathsankara** [apache/devlake#8143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

DB Migration Failing when moving from Latest release to v1.0.2-beta2

### What do you expect to happen

After start of docker, initiation of DB migration popup and when done, it fails.

### How to reproduce

After start of docker, initiation of DB migration popup and when done, it fails.

### Version

v1.0.2-beta2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mrpaapi** [comment]
AxiosError: Request failed with status code 502

**Comment by mrpaapi** [comment]
@dosu - AxiosError: Request failed with status code 502
