### ISSUE TITLE
[Bug][Grafana] Grafana Create new Organization Failed

### ISSUE THREAD

**Issue by DevOpsAutomationCloud** [apache/devlake#8146]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Try to use Grafana organizations to manage different projects for different teams.
When create a new organization in Grafana, url keeps redirect from https://<my ip>/grafana/dashboards to https://localhost/?orgId=3
Have to manually update url to https://<my ip>/grafana/?orgId=3 in order to switch to new organization.
Then, there is no dashboard available in new organizations.
Does Grafana organizations work with DevLake? Or do we have to use the default "Main Org" only? 

### What do you expect to happen

With new Gragana organizations created, url can automatically update when switch to new organization.
Dashboards are available in new organizations.

### How to reproduce

In Grafana, Administration --> General-->Organizations, create new organization.
Then switch to new organization by click the drop list from top left of the page

### Version

1.0.1-beta9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Looks like a Gafana problem to me. Maybe take a look at the Grafana documentation?

**Comment by diwangcanada** [comment]
> Looks like a Gafana problem to me. Maybe take a look at the Grafana documentation?

I think this is more like integration with DevLake, as Grafana doesn't have it's own url, but share the same url as DevLake but use /grafana/*** at the end.

**Comment by diwangcanada** [comment]
Got this work with adding below environment variables for Grafana:
GF_SERVER_DOMAIN
GF_SERVER_ROOT_URL
It would be nice if DevLake also document it.
