### ISSUE TITLE
[Feature][Webhooks] Support for Webhook Name in Webhook Endpoints

### ISSUE THREAD

**Issue by rodrigoluizs** [apache/devlake#8195]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As an engineer, I want to integrate DevLake’s webhook API into my company’s internal infrastructure without the need to manage and persist webhook IDs (connectionId). Instead, I would like to use webhook names, which are easier to derive and manage in our systems, for actions such as creating deployments, managing issues, or retrieving webhook details.

This will allow me to streamline the integration process, reduce complexity, and avoid maintaining additional components solely for mapping webhook IDs to projects.

### Description

While integrating DevLake into our internal infrastructure, we encountered a limitation with the current Webhook API. The existing endpoints require the webhook connection ID (connectionId) to perform actions like creating deployments or managing issues. This presents a challenge, as webhook IDs are not easy to derive/template, requiring additional components to persist and map these IDs to projects, which complicates integration.

### Endpoints:

```
POST    /plugins/webhook/connections/:connectionId/deployments
POST    /plugins/webhook/:connectionId/issue/:issueKey/close
POST    /plugins/webhook/:connectionId/issues
DELETE  /plugins/webhook/connections/{connectionId}
GET     /plugins/webhook/connections/{connectionId}
PATCH   /plugins/webhook/connections/{connectionId}
```
### Proposed Enhancement

To make integration easier, I propose either extending these endpoints or creating new ones to accept webhook names as an alternative to connectionId. For example:

- Current: POST /plugins/webhook/connections/:connectionId/deployments
- Proposed: POST /plugins/webhook/connections/:connectionName/deployments

### Benefits

- Improved Usability: Webhook names are straightforward to derive, eliminating the need to maintain a mapping between webhook IDs and projects.
- Simplified Integration: Reduces the development effort by removing the requirement for additional components to manage the relationship between projects and their webhooks.

### Request for Feedback

If I missed an existing approach to achieve this, I’d appreciate your guidance. I’m new to the project but eager to learn, and if this makes sense for the project, I’d be happy to contribute to its implementation. 

Looking forward to your feedback!

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rodrigoluizs** [comment]
Thanks @klesh!

I’m already working on it. I’d like to get your input on how we should approach this, currently I'm thinking about those 2 potential solutions, each with trade-offs.

### Option 1: Add New Endpoints
We could introduce new endpoints that explicitly handle connection names, such as:
`GET /connections/by-name/:connectionName/deployments
`

This approach makes it explicit whether the API expects a connectionId or a connectionName, avoiding ambiguity. However, it introduces new endpoint paths and slightly increases the API surface area.

### Option 2: Use Existing Endpoints
We could use the existing endpoints, like:
`GET /connections/:connectionIdentifier/deployments
`

Here, we’d rename the parameter from connectionId to something more generic, like connectionIdentifier or connectionKey, to handle both numeric IDs and names. This keeps the API surface minimal but relies on clear documentation and server-side validation to distinguish between IDs and names.

I’d like to hear your thoughts on which approach aligns better with our API design principles. Let me know if you have any other suggestions or concerns.

**Comment by klesh** [comment]
Both are fine to me.
