### ISSUE TITLE
[Question][Github] Automatically add new github repositories to data scopes

### ISSUE THREAD

**Issue by nicolavolpini** [apache/devlake#8236]
## Question
We have new repositories being added or removed to our Github organization.
What would be the best way to automatically synch the Github repos to the data-scopes in DevLake?
Is there an existing script that could provide such feature?

**Comment by klesh** [comment]
There isn't a script for this purpose currently.  I suggest using the API to accomplish this.

**Comment by nicolavolpini** [comment]
Thanks klesh.

I'm analysing the API calls performed by the frontend, so I can reproduce the necessary steps.
What I see is a `PATCH` operation against the `api/blueprints/<x>` endpoint.

Do I understand correctly I need to push the entire JSON payload, containing the entire list of repos, every time I perform a change?

**Comment by klesh** [comment]
The PATCH operation only updates specific fields of a resource. To remove elements from a list, you'll need to provide a complete, updated list in the request body. You can omit unchanged fields like name if they don't require modification.

**Comment by nicolavolpini** [comment]
That was indeed the case!
I'll proceed with my experiments. Thank you for your help. I'll close this.
